### ISSUE TITLE
Getting Device ID in rule chain

### ISSUE THREAD

**Issue by nicovon24** [thingsboard/thingsboard#10114]
Hello, i am not being able to get the ID of the device when I send telemetry, I do not know why is the Originator ID node not working, it does not return anything. 
I need this to make calls to the device Swagger API. Thanks!

![Screenshot_34](https://github.com/thingsboard/thingsboard/assets/98624393/dcd7d46f-1864-409f-9379-f0ec6ec82dd1)

![Screenshot_36](https://github.com/thingsboard/thingsboard/assets/98624393/c35a8691-6645-4f9d-b150-54be28bff6a6)

**Comment by evanderbird** [comment]
Probably a BUG. I cant get id too. Your step is correct.

**Comment by ashaforost** [comment]
Hi @nicovon24 

This issue is present in the thingsboard v3.6.0. It was fixed in v3.6.1
Here's the github issue with the PR:
[Bug Rule Node Missing Entity Id](https://github.com/thingsboard/thingsboard/issues/9341)

Please upgrade to v3.6.1 at least to receive a fix. See [Upgrade Instructions](https://thingsboard.io/docs/user-guide/install/pe/upgrade-instructions/)
