### ISSUE TITLE
Sysadmin able to access tenant admin account

### ISSUE THREAD

**Issue by shashank-r25** [thingsboard/thingsboard#10207]
Hello,

When i was looking into sysadmin feature in ThingsBoard CE, i saw there feature where sysadmin can access a tenant account completely. Thingsboard docs also has this feature listed ( https://thingsboard.io/docs/user-guide/ui/tenants/#login-as-tenant-administrator ).

Is this means demo.thingsboard.io sysadmin can access its tenant account.

Please guide me through which scenarios sysadmin accessing tenant admin account is valid which scenarios its not implementable feature.

**Comment by AlexDoanTB** [comment]
@shashank-r25 yes, the sysadmin has access to all entities by design. For SaaS/PaaS, it is generic and vital because the sysadmin user provisions global configurations and policies + it must be able to check if someone actually breaches the Terms of Service or not. Distribution of malicious content, coin mining, delivering IoT services to restricted entities or countries, and other limitations are of the essence.         
With the self-hosted platform version, the local sysadmin user (the platform maintainer) has the above authority and responsibility. 
Live Demo (demo.thingsboard.io) is free PaaS for those who want to test the CE features. One can opt out or not to use the platform if disagrees with the Terms.
