### ISSUE TITLE
Application gets enlarged when viewing on Windows OS.

### ISSUE THREAD

**Issue by shashank-r25** [thingsboard/thingsboard#10213]
**Describe the bug**
The ThingsBoard application **gets enlarged up to 150%** when viewing on Windows OS unlike when viewed on Ubuntu (Linux OS) ie, with 100% . How to achieve the same normal view on Windows OS as on Ubuntu ?

**To Reproduce**
1. View [demo.thingsboard.io](https://demo.thingsboard.io/home) Dashboard on Windows OS through any web browser,  but with zoom percentage set as 100% (Make sure your device's screen resolution is set to the recommended 150%).
2. Now if you view this same dashboard on Ubuntu (Linux OS) through any web browser,  but with zoom percentage set as 100%, you will see the dashboard appears normal.  

**Expected behaviour**
Regardless of what OS the user is on and on what web browser, the application is being viewed, the view should be normal and uniform.

**Screenshots**
Ubuntu Image
![Ubuntu_Image](https://github.com/thingsboard/thingsboard/assets/103051060/d998b4ac-6e49-4d25-929a-d388cee52794)

Windows Image
<img width="959" alt="Windows_Image" src="https://github.com/thingsboard/thingsboard/assets/103051060/90f684fc-9b07-4692-9f31-f270a5af970d">

Thanks

**Comment by AndriichnekoDm** [comment]
Hi @shashank-r25!
If I have understood your question correctly.

To achieve the same normal view on Windows OS as on Ubuntu for the ThingsBoard application, you would typically need to adjust the display scaling settings in Windows. The difference in appearance is likely due to Windows' display scaling feature, which can make applications and text appear larger to improve readability, especially on high-resolution displays. Here’s how you can adjust the scaling to match the Ubuntu experience:

1. Right-click on the Desktop and select Display settings.
2. Under Scale and layout, you'll find an option that says Change the size of text, apps, and other items. Windows might have set this to something above 100% if it detects a high-resolution display.
3. Set this scaling to 100% to match the Ubuntu display settings. This should make the ThingsBoard application appear similar in size to how it does on Ubuntu.

**Comment by shashank-r25** [comment]
Hi @AndriichnekoDm 

I appreciate your efforts in the response, but I am currently looking for a solution that doesn't require the user's display settings to be changed, rather have the solution in the codebase itself for self-adaptation.

**Comment by shashank-r25** [comment]
Can we achieve the type of solution that I have mentioned?
Please guide me to the correct solution
