### ISSUE TITLE
Load module in custom widget

### ISSUE THREAD

**Issue by elpollo12** [thingsboard/thingsboard#10252]
Hi.

I need to import a library in a custom widget, but when doing so it tells me "Unable to load module from url: /api/resource/js/b4e5ad50-d1b9-11ee-b874-bb859ca7385d/download" and if I add it as a resource ( no module), no load either.

Is there any structure I must follow for the resource to be accepted as a module?

The library is: https://cdn.jsdelivr.net/npm/@equinor/esv-intersection@3.0.12/dist/index.mjs

@devaskim

**Comment by elpollo12** [comment]
Thanks @devaskim , I will try to convert that library into an Angular module.

...and yes, a buymeacoffee.com would be the least we could contribute. You are right @devdoob , @devaskim it is a reference for us in this space.

**Comment by devaskim** [comment]
> Do you know any "Buy Me a Coffee" platform to get any "thanks" from my answers considering I am not a TB support
> something in honour of what your own devs were unable to do

@devdoob Thanks for your participation to the discussion of my impact to TB community. It was a half a joke, but with a piece of truth. 

As I understand, the users of TB Pro license should or could ask in [Custom Portal](https://thingsboard-portal.atlassian.net/servicedesk/customer/portals), CE users could just hope to get the answer here, in Github Issues. It is pay for payment for a free (good!!!) product. As for me I am not who is [doing business on the TB consulting](https://thingsboard.io/partners/distributors/), I ready to just help in some local challenges, but [I am a human after all ](https://www.youtube.com/watch?v=L3wKzyIN1yk) )))

**Comment by devdoob** [comment]
Stats speaks....!!

Owners!!! 👇👇👇

![image](https://github.com/thingsboard/thingsboard/assets/1464600/548ed474-e897-42d8-b0ae-3a797b844f07)
![image](https://github.com/thingsboard/thingsboard/assets/1464600/7e3cb947-8237-43c4-8ff0-b7dd0125129b)

Our hero @devaskim 👇👇👇👇

![image](https://github.com/thingsboard/thingsboard/assets/1464600/6ff96cfe-8ac6-450a-9958-086de191ca46)

**Comment by devdoob** [comment]
Even community members mention @vvlladd28 less than @devaskim 

![image](https://github.com/thingsboard/thingsboard/assets/1464600/16f5008c-2716-4985-9442-b12d7f0f38be)

![image](https://github.com/thingsboard/thingsboard/assets/1464600/26eae064-bb9a-4f66-89af-e1417479ff31)

**Comment by AlexDoanTB** [comment]
@devdoob, please stop storming in a teacup. Apologize for this metaphor. 
Your claim is bizarre. ThingsBoard should have an army of engineers working daily on GH issues to answer various questions, sometimes odd requests, verify bugs-that-are-not-bugs, am I correct? 
Since when GH turned into a ticketing system? It is unfair to force people to answer you because you cannot do smth on your own. ThingsBoard engineers are working. They have tasks, backlogs, personal lives, and hobbies. They have ruzzia that shells Ukraine with missiles every day. And you want them to have you on this list as well, correct? Just because you decided that someone is obliged to respond to your inquiries does not mean so.  
I guess Elon Musk always replies to your Tesla-related tickets, if any... lucky you.   
GH is for community matters + periodic interaction with the product developers. We are happy to know that there are TB users who can support others, and help newbies. That is wonderful. That is what is called COMMUNITY support.  
Tickets with content and intent similar to yours will be closed without answering.   

Please forgive my wording if it may seem rude to you. 

PS: @devaskim 10Q

**Comment by devaskim** [comment]
@AlexDoanTB Yeah, it was a cry of a soul. I can understand TB team because I am developer too. But let me share with you several thoughts.

> Since when GH turned into a ticketing system?
> GH is for community matters + periodic interaction with the product developers.

It would be useful to put a reminder somewhere in GH (e.g. in issue template) about how TB team considers Github Pull Request and especially Github Issues, because the latter is a ticketing system indeed (for example, just look at [Angular Project on Github](https://github.com/angular/angular/issues))

> PS: @devaskim 10Q
What does it mean?

**Comment by AlexDoanTB** [comment]
@devaskim Yes, we must add some more clarity to the processes. Community policy will be adjusted. It is our fault that we have not come up with accurate rules, descriptions and red flags. GH issues is kinda of a ticketing system, agree. However, there is no SLA or commitment to a 100% response. `Issues` is the way to report smth, propose smth, request smth — a communication channel, not a support chat, IMHO. 

>>  PS: @devaskim 10Q

>What does it mean? 

10Q = [t'en,kju:] = "thank you"

**Comment by devdoob** [comment]
@AlexDoanTB Appologies! My intent was not to hurt anyone. I have deleted my comment. 

I admire TB and its team. Trust me, I have no grudges.

Thank you.

**Comment by devdoob** [comment]
There is an update to using custom JS modules in TB > 3.6

https://thingsboard.io/docs/user-guide/contribution/widgets-development/#thingsboard-extensions

Now much more easier to install
