### ISSUE TITLE
MQTTs over SSL configuration

### ISSUE THREAD

**Issue by mohanadsarhan** [thingsboard/thingsboard#10253]
**Component**
 * Installation

**Description**
Upon following the instructions on https://thingsboard.io/docs/pe/user-guide/mqtt-over-ssl/,
I restart the TB service and the following error appears. Any ideas on how to fix this?
2024-02-23 02:05:51,223 [main] ERROR o.s.boot.SpringApplication - Application run failed

**Environment**
 * OS:  Ubuntu
 * ThingsBoard: Professional

**Comment by Ultrazombie** [comment]
Hello @mohanadsarhan,
Please find the reason in the thingsboard.log file,
Please attach the file here, and we will look into it.
```/var/log/thingsboard/thingsboard.log```

**Comment by mohanadsarhan** [comment]
Hello @Ultrazombie,
Turns out there were permission errors on the certificates, which I resolved.

I have followed the "MQTT over SSL" instructions and would like to know the following:
1. Where do you get the _ca-root.pem_ file from to test the MQTTs connection? The _curl -f -S -o ca-root.pem https://xxx/api/device-connectivity/mqtts/certificate/download_ command returns a "File not found error".
2. The certificate generated is self-signed as per the instructions in the guide. Can Lets Encrypt be used to generate/sign it, and what are the instructions to do so? Can the same SSL certificate issued for the domain to enable HTTPS during the installation be used?

Thanks in advance.

**Comment by trikimiki** [comment]
Hi @mohanadsarhan 

1. The cert/key files are set up as a part of MQTT transport, whilst Device Connectivity uses REST. In order to provide REST with the file to return on request, you need to enable the following:
`export DEVICE_CONNECTIVITY_MQTTS_CA_ROOT_CERT=cafile.pem`
Replace `cafile.pem` with your server certificate - the same used to set up MQTT over SSL.
2. Yes to all questions.
If you have generated key using [this guide](/usr/share/tb-haproxy/letsencrypt/live), you could find files in `/usr/share/tb-haproxy/letsencrypt/live/your-domain-name` directory.
If you need to generate certificates separately, you can research how to do so by using one of [those methods](https://letsencrypt.org/docs/challenge-types/).
