### ISSUE TITLE
Upload CSV file to Thingsboard

### ISSUE THREAD

**Issue by mohanadsarhan** [thingsboard/thingsboard#10297]
**Component**

 * Generic

**Description**
Hi all,

How do you upload a CSV file to Thingsboard to be used for dashboards etc.?

Thanks

**Environment**

 * OS:  Ubuntu

**Comment by ssakharova** [comment]
Hello @mohanadsarhan,


If you want to upload a CSV file to Thingsboard in order to use this file to visualize data from the file on the widget, unfortunately, you can’t do that with the default functionality. You can only visualize data on the widget if it is stored on an entity as telemetry keys or attributes, which can then be added to the widget datasource.

If you are referring to the bulk device provisioning feature, you can use it to update devices, their telemetry, attributes, and device profiles.
Bulk provisioning in ThingsBoard enables the creation of multiple entities (devices, assets) simultaneously using a CSV file. Each line in the CSV file corresponds to one entity, allowing for easy parameterization of attributes, telemetry data, and credentials. Reserved parameters like “Name,” “Type,” and “Label” have predefined column types.
This feature streamlines the process of creating/updating numerous devices/assets in ThingsBoard.

Read more about it here - https://thingsboard.io/docs/pe/user-guide/bulk-provisioning/

Best regards,
Sofiia
