### ISSUE TITLE
Dashboard vertical scroll

### ISSUE THREAD

**Issue by vastechpro** [thingsboard/thingsboard#10304]
**Component**

 * UI

**Description**
How can I enable dashboard to scroll vertically and without the widgets resizing when height is reduced?

<img width="983" alt="Screenshot 2024-03-05 at 2 14 20 PM" src="https://github.com/thingsboard/thingsboard/assets/6180900/9046cd37-1fc1-4235-82a5-d3d7726884c2">

Right now when reduce screen height, my dashboard widgets move up and the top widget becomes too small. Also, my dashboard dow not have a vertical scrollbar. This makes the dashboard unusable.

**Environment**

 * ThingsBoard: cloud

**Comment by vastechpro** [comment]
I would appreciate help with this issue.

**Comment by d2eight** [comment]
HI @vastechpro, you need to enter to the your target dashboard state, in the edit mode click **Layouts** button, then, **Layouts settings**, and turn off **Auto fill layout height** checkbox.

**Comment by vastechpro** [comment]
Thank you @d2eight that fixed the scroll issue, however, the widgets starts to resize when I reduce the screen width. I would like fixed widgets and a horizontal scrollbar instead. Do you know how to do that?

<img width="527" alt="Screenshot 2024-03-13 at 6 56 10 PM" src="https://github.com/thingsboard/thingsboard/assets/6180900/e39b2ec5-f64b-44b9-8e8d-a72c0653a7e1">

**Comment by d2eight** [comment]
HI @vastechpro, on some screen sizes, widgets do not always adapt well. The only one possibility to fix this problem is **adding custom css** with using **media query** into your widget/dashboard. If you want to configure the only one widget, you need to enter the advanced mode of your widget, find out widget card tab and then find card style settings, where you can find **Advanced widget style**, put your css code here. If you want to configure more than one widget, you can add your custom css to the whole dashboard. In the edit mode, click on the **Settings button** of your dashboard and find here advanced settings, here you can write your css code to the multiple widgets on your dashboard.
