### ISSUE TITLE
Force number of decimals in card widgets

### ISSUE THREAD

**Issue by gcorthey** [thingsboard/thingsboard#10357]
Is it possible to force the number of decimals in card widgets (and also other widgets)? 

I noticed that even if the number of decimals is set to e.g. 2 and the number is 45.60, it shows 45.6 (doesn't show the last 0).

![image](https://github.com/thingsboard/thingsboard/assets/11965006/50e31d9e-9879-4850-9f05-e7c28d0aa1e1)

**Comment by myroslav-tb** [comment]
Hello @gcorthey , yes it is possible to change the number of decimals that are going to be shown on the widget by changing the “Decimals by default” parameter. However it is not possible to display numbers like 45.60 because of how data is processed in Thingsboard, it always cuts 0 at the end.
![image](https://github.com/thingsboard/thingsboard/assets/158559147/902bedd7-6520-484b-b0be-1938678ed62c)

**Comment by myroslav-tb** [comment]
I am closing this ticket due to inactivity.
