### ISSUE TITLE
Assets Search not working with Label Column

### ISSUE THREAD

**Issue by darioludwigswk** [thingsboard/thingsboard#10442]
**Describe the bug**
Text Search in the Assets list ist not working for Label Column. 

**Version**
Thingsboard Versions:
- v.3.6.0PE
- v.3.6.3PE

**To Reproduce**
1. Go to '/entities/assets/all'
2. Click on 'Search Assets'
3. Type some Label
4. See not what you where searching for, if it is not found in other columns like Name

**Expected behavior**
Find Assets also through Label Search similar to the Devices List.

**Comment by RajeevDash007** [comment]
can you provide the link of the page where you are facing the problem?

**Comment by darioludwigswk** [comment]
https://<YOUR_TB_DOMAIN>/entities/assets/all
![image](https://github.com/thingsboard/thingsboard/assets/155756255/5c7186fd-18d6-4afa-8abc-f61097be5aef)
![image](https://github.com/thingsboard/thingsboard/assets/155756255/e1af3f0d-2da7-4dca-9aa2-415501e16812)

**Comment by RajeevDash007** [comment]
k thanks

**Comment by darioludwigswk** [comment]
> Hi. There is no possibility to search assets by either their labels or profile. You can only filter them by their name.

Hi, thank you for looking into it!
Yes i noticed, that´s why i opend the issue. Feels more like a bug than a feature? I think assets should be searchable by labels also, similar to devices?

**Comment by mykhailokornieiev** [comment]
Hi. I meant that there is no issue or bug since this feature was designed only for devices. 
However, thank you for your suggestion; this is a valid improvement to our platform, so I've added this request to our backlog (PROD-3373) for our developers to review and decide on its implementation. There's no set timeframe for our dev reviews; however, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in subsequent releases.

**Comment by mykhailokornieiev** [comment]
Hi. I'm glad to inform you that this feature was successfully added in the latest version (3.7)
https://github.com/thingsboard/thingsboard/pull/10665
