### ISSUE TITLE
Shared Attribute not goes to Edge from Server if size is too big

### ISSUE THREAD

**Issue by bbognar1992** [thingsboard/thingsboard#10470]
**Describe the bug**
The server accept too long string for shared attribute value. It causes me problem when I wanted it to go to TB Edge.
In my case if the JSON string length was 3208 it did not go to edge. But when the  length was 233 then it went to TB Edge.

**Your Server Environment**

* own setup
  * Deployment: monolith
  * Deployment type: docker-compose
  * ThingsBoard Version: 3.6.3
  * Community
  * OS Name and Version: Linux Debian 11

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: MacOS 14.4.1
* Browser  safari
* Version: 17.4.1 (19618.1.15.11.14)

**Your Device**

* Connectivity
  * HTTP
* Device vendor and model
  * does not matter

**To Reproduce**
1. Login to ThingsBoard Server.
2. Select device XY under Entities/Devices (Important that the device should use Edge connection to communicate with the platform.)
3. On the Attribute tab  select shared attributes. 
4.  Create a test JSON attribute with length of  3208 with name 'test_sk'
5. Modify Rule Chains/Root Rule Chain: Add push to Edge action (Have a screenshot)
6. Login to Edge
7. Select device XY under Entities/Devices
8. Check the attributes/shared attributes tab if the 'test_sk' is there. 

**Expected behavior**
Server should check if the length of the attribute value is too long or not.

**Screenshots**
Modify Root Rule Chain for sharing attribute with Edge
<img width="524" alt="Képernyőfotó 2024-03-28 - 14 37 13" src="https://github.com/thingsboard/thingsboard/assets/44742549/6c439112-7b9f-4b34-a1a7-b78ad1d9c30a">

**Comment by AndriiLandiak** [comment]
Hello, @bbognar1992

Thank you for highlighting this. Currently, there's a limitation that restricts the length of time-series data and attributes messages to 1000 characters. You can find the message "Conversion to a DownlinkMsg telemetry event failed due to a size limit violation" in your log file. 

We will provide a more flexible approach that will allow users to customize this limit and send notifications in case such limit is violated. Once implemented, the only constraint on message size will be the maxInboundMessageSize, which will determine the maximum size of messages sent to Edge.
