### ISSUE TITLE
Generate Report based on Telemetry Value

### ISSUE THREAD

**Issue by AARON-HQ** [thingsboard/thingsboard#10508]
**Component**

 * Rule Engine
 

**Description**
Right now I am generating a report once per day. I would like to add a filter in the rule engine so the report is generated only if a device telemetry value on the report is greater than 0. 
Is this possible?

**Environment**

  * ThingsBoard: ThingsBoard Cloud 3.6.3.2PAAS
 * Browser: Chrome

**Comment by mykhailokornieiev** [comment]
Hi
For such a purpose, you can duplicate and modify the default Generate Report rule chain
![image](https://github.com/thingsboard/thingsboard/assets/115699895/db98e260-234a-4dd2-96c8-0bc139db8e89)
![image](https://github.com/thingsboard/thingsboard/assets/115699895/15ede92c-d64c-47f4-bfa4-4be29281ac2f)
In this case, you will be able to trigger it by POST_TELEMETRY_REQUEST event, when it meets fliter script conditions, for example 
`return msg.temeperature > 0`
If so, then there is no need in a scheduler for this purpose anymore, since it will use its own "generate report" rule chain

**Comment by AARON-HQ** [comment]
Hi Mykhailo,
Thanks for your help and sorry for the delay! I should have explained what I need a little better. I want the report to generate at 23:59 like it does now but only if the value is >0. Then there won't be empty reports when a device is not in use. I have to do this for many customers with different dashboards.  It is easy to setup the report for each customer's dashboard with the scheduler so that would be great if there is a way to control scheduler report generation from a telemetry value. If that is not possible then I guess I can create a new report rule chain for each customer. Is there an easy way to do this that I don't know about?   Thanks again, best regards. Aaron

**Comment by mykhailokornieiev** [comment]
Hi
In this case, you will need to use some mix of the logic you used earlier and the one I proposed.
Create scheduler with type "Update Attributes" for 23:59 every day. It will send attribute that can be filtered by Filter Script rule node. For example:
`return msg.check_attribute == true;`
If the condition is met, then the next part of the rule chain will be triggered, which will include the originator attribute rule node. https://thingsboard.io/docs/user-guide/rule-engine-2-0/enrichment-nodes/#originator-attributes
Then you will compare the value you need, if it fits (TRUE) - create a report in the rule chain. Otherwise (FALSE), just end the processing.

**Comment by AARON-HQ** [comment]
Ok great. I think I understand that logic. I will try it out as soon as possible. Thanks again!
