### ISSUE TITLE
Change color of legend and tooltip in timeseries chart

### ISSUE THREAD

**Issue by gcorthey** [thingsboard/thingsboard#10537]
I need to change the color or the data key label in tooltip and of the values and labels of the legend. I changed to color as shown below but still are some text in black.

![image](https://github.com/thingsboard/thingsboard/assets/11965006/5069a415-77e0-4151-85e8-ed63ebe5042e)

![image](https://github.com/thingsboard/thingsboard/assets/11965006/8f5b58c2-e466-4c2f-bd15-62848f265658)

**Comment by ssakharova** [comment]
Hello @gcorthey,

In order to change the color of the values in the legend, you need to paste these lines to the Widget CSS field under the Advanced widget style section:

![image](https://github.com/thingsboard/thingsboard/assets/98035385/0c5d841b-34db-4b6f-af2f-705c35185fbc)


```
.tb-time-series-chart-legend-value {
    color: #0047AB !important;
} 

```
Regarding the labels in the legend, their color can be configured in the Legend section in the Appearance tab. Please refer to the screenshot below:

![image](https://github.com/thingsboard/thingsboard/assets/98035385/ef2a2898-e521-4038-93f0-d6e39b79fcaf)

Unfortunately, there is no way to change the color of the data key label in the tooltip using CSS. However, as a workaround, we recommend changing the tooltip's background color for better visibility.

You can configure the background color of the tooltip in the Tooltip section, as shown in the screenshots:

![image](https://github.com/thingsboard/thingsboard/assets/98035385/f216c951-2d68-4e71-a0d1-fe23553aa53c)
![image](https://github.com/thingsboard/thingsboard/assets/98035385/a08fbb5f-cb6d-4868-8b83-302caf4b0bd4)


Best regards,
Sofiia Sakharova
