### ISSUE TITLE
How can I grant a user group permissions to only view a single dashboard group?

### ISSUE THREAD

**Issue by OzyOzk** [thingsboard/thingsboard#10585]
**Component**

 * Generic

**Description**

Hi all,

I'm using the "Entity Group Read-only User" group role to grant a user group read only access to a group of dashboards, but the users are not able to view them. There is only an option to export them.

I created an additional user group next to my Tenant Users and Tenant Admins called External Users. I then granted them the "Entity Group Read-only User" role for the specific dashboard group. I also applied the same role to the dashboard group permissions to no luck.

Generic permissions work, but this also gives external users access to all other dashboards.

**Environment**

 * OS:  linux
 * ThingsBoard: latest
 * Browser: Firefox

**Comment by myroslav-tb** [comment]
Hello @OzyOzk,comunity edition version only allows to share dashboards with a customers. You can do it by pressing manage assigned customers button.
![image](https://github.com/thingsboard/thingsboard/assets/158559147/72cc5ec3-04ee-490d-a5e0-076ef1d5476a)

You also need to share the devices. Otherwise, telemetry data would not be displayed since the customer doesn't have accesss to the device.
![image](https://github.com/thingsboard/thingsboard/assets/158559147/05e85005-b68f-4c49-b099-0a705ae8caac)

I logged in as a customer user and can see assigned dashboard and data from the devices.
![image](https://github.com/thingsboard/thingsboard/assets/158559147/03269555-4618-48f8-b00a-d44fcfb69ee8)

  <br/><br/>

If you are using a professional edition, you would need to create a dashboard group for a customer and add dashboard to it.
![image](https://github.com/thingsboard/thingsboard/assets/158559147/c750bebf-28e8-4af1-8443-2c3af879789e)
![image](https://github.com/thingsboard/thingsboard/assets/158559147/745ba138-c5bb-4175-84ec-5b13194465cd)

To add a dashboard to a group, you’ll need to open a dashboard details.
![image](https://github.com/thingsboard/thingsboard/assets/158559147/1299a9cd-409e-44b2-b4fc-32cfb2b66aa2)
Press the Manage owner and groups button and add a dashboard to the required group
![image](https://github.com/thingsboard/thingsboard/assets/158559147/284076c3-2475-43ed-acfd-7ece024a39ba)
Go to the dashboard group and open group details.
![image](https://github.com/thingsboard/thingsboard/assets/158559147/f1261d1a-1e30-4d0b-bbf8-548d9e951387)
Press Share entity group and select a customer you want to share it with and the permission you want to give them.
![image](https://github.com/thingsboard/thingsboard/assets/158559147/e8571f6e-106c-489f-96ba-1f980f61a02a)
In the permissions tab, you can change or delete the permissions 
![image](https://github.com/thingsboard/thingsboard/assets/158559147/5acca85b-9f6c-4a09-adfd-66609cce67d5)
Shared dashboards can be find in the shared tab in dashboard menu
![image](https://github.com/thingsboard/thingsboard/assets/158559147/1a8635c9-0d74-4231-9467-dd7159dda87c)

Best regards
Myroslav
