### ISSUE TITLE
Change the "next page" color

### ISSUE THREAD

**Issue by kurch00** [thingsboard/thingsboard#10627]
In my dashboard I developed a dark-mode widget. But, when the dark-mode is activated, the button "next page" in my table remains dark. How can I change the color of the button?

Here's the example:
<img width="378" alt="next-page-btn-color" src="https://github.com/thingsboard/thingsboard/assets/135682534/7083b1bc-d0ea-4285-bb8a-2252ffea0635">

**Comment by ssakharova** [comment]
Hello @kurch00,

In order to change the color of the pagination buttons, you will need to open the Widget Card settings tab, find there the card style section, and click on the drop-down element “Advanced widget style”.

In the widget CSS field, you need to put these lines of code:

```
.mat-mdc-paginator-icon{
    fill: white !important;
}
```
![image](https://github.com/thingsboard/thingsboard/assets/98035385/232d2b1f-b1f7-48ba-8abc-b7d2695cf636)

Best regards,
Sofiia

**Comment by kurch00** [comment]
tkss, it works here!!

**Comment by THANAWIT888** [comment]
if i want to changeicon color 
![image](https://github.com/thingsboard/thingsboard/assets/133348322/540240bd-ae29-4cb5-929e-4d6ddf823ec8)
how i can change it?
