### ISSUE TITLE
How can I get the username of the user executing the RPC request to the device?

### ISSUE THREAD

**Issue by hophead12** [thingsboard/thingsboard#10633]
Component

- Rule Engine

Description
I want to create a widget similar to the audit log for my users to view who, when, and how requests are sent to devices or attributes are changed. I've successfully handled the attributes in my engine rule, and with 'Attributes Updated', it's working. However, I'm encountering an issue where I can't retrieve the originatorEmail using originator fields with RPC Request to Device.

If you have any idea of a simple way please mention, thanks!

Environment

- OS: LINUX
- ThingsBoard: 3.6.2PE

**Comment by SuminDenis** [comment]
Hi @hophead12,

In order to fetch the originator's email, you need to change the originator from **Device** to the User via the **Change Originator node** and then use the **Originator Fields node** to fetch the data that you need.

Keep in mind that before changing the originator of the message from the device to a user in the rule chain, you need to create relations from **User** to **Device** with the type **Contains**.

Here is a rule chain that you can use as a hint:
[root_rule_chain.json](https://github.com/user-attachments/files/16550008/root_rule_chain.json)

**Comment by SuminDenys** [comment]
Hi @hophead12,

I am closing this issue due to inactive. Feel free to open a new issue in case you have any questions.

**Comment by AlexBBS** [comment]
It doesn't work. More precisely, it works, but only for one user. What if multiple users are connected to the device? When making an RPC request, the output of the 'Originator Fields node' returns user 'A', even though the request was made by user 'B'. Is there a way to get the username specifically from the user who made the RPC request? When updating attributes, the correct data comes in:
    "scope": "SERVER_SCOPE",
    "userEmail": "tenant@thingsboard.org",
    "userId": "9f535c60-66bc-11ef-b1fc-755232bd4956",
    "userName": "tenant@thingsboard.org"
