### ISSUE TITLE
Getting error when I am trying to run the Thingsboard IoT gateway using RPi 4

### ISSUE THREAD

**Issue by SecurityEngineers** [thingsboard/thingsboard#10677]
I am trying to make a Thingsboard IoT gateway on my **Raspberry Pi 4** with latest **Raspberry Pi OS (Bookworm)** but I am getting an error- “tb-gateway  | exec /bin/bash: exec format error”

I setup Docker and Docker Compose correctly on my system, created a new gateway in my Thingsboard account and downloaded the .yml file. Then when I try to run this code using **sudo docker compose up**, get error (It's working in my windows-wsl but not in RPi).

(I also followed this links below- 
https://thingsboard.io/docs/iot-gateway/getting-started/
https://thingsboard.io/docs/iot-gateway/install/docker-installation/)

So please someone help me to do this.

![Screenshot (2)](https://github.com/thingsboard/thingsboard/assets/168514016/3f8e04c0-c26c-419e-9db9-4b0ed237a209)

**Comment by ssakharova** [comment]
Hello @SecurityEngineers,

Since you are facing an issue with the Thingsboard IoT Gateway, consider reaching out to the GitHub community regarding thingsboard gateway issues. They may be able to provide assistance or insights that could prove valuable in addressing your specific needs.

- GitHub thingsboard gateway issues - https://github.com/thingsboard/thingsboard-gateway/issues

Best regards,
Sofiia
