### ISSUE TITLE
 Telemetry data filter

### ISSUE THREAD

**Issue by 123GHLJ** [thingsboard/thingsboard#10699]
Good afternoon. 
My device sends the following data in a single JSON packet using the DATA key.
{"VARMS":0,"VBRMS":0,"VCRMS":0,"IARMS":0,"IBRMS":0,"ICRMS":0,"VABRMS":5,"VBCRMS":1,"VCARMS":5,"VABCTRMS":3,"PA":0,"PB":0,"PC":0,"PT":0,"QA":0,"QB":0,"QC":0,"QT":0,"SA":0,"SB":0,"SC":0,"ST":0}

How can I perform filtering to use in creating alarms with duration.

Thanks.

**Comment by ashaforost** [comment]
Hi @123GHLJ 

In the thingsboard platform, it's advised to store the telemetry in key-value pairs rather than one JSON with all telemetry values. JSON fields are designed to store raw data that won't be used in data processing or visualization. So, in your case, as soon as the 'DATA' telemetry comes into the rule chain, you can transform it into the

 `msg: {"VARMS":0,"VBRMS":0,"VCRMS":0,"IARMS":0,"IBRMS":0,"ICRMS":0,"VABRMS":5,"VBCRMS":1,"VCARMS":5,"VABCTRMS":3,"PA":0,"PB":0,"PC":0,"PT":0,"QA":0,"QB":0,"QC":0,"QT":0,"SA":0,"SB":0,"SC":0,"ST":0}`   object 

instead of

`msg: {DATA: {"VARMS":0,"VBRMS":0,"VCRMS":0,"IARMS":0,"IBRMS":0,"ICRMS":0,"VABRMS":5,"VBCRMS":1,"VCARMS":5,"VABCTRMS":3,"PA":0,"PB":0,"PC":0,"PT":0,"QA":0,"QB":0,"QC":0,"QT":0,"SA":0,"SB":0,"SC":0,"ST":0}}`

After that, the device profile rule node will be able to find a necessary key in the msg object and create an alarm based on the telemetry key.

**Comment by 123GHLJ** [comment]
Thank you ashaforost.
Which Node in the rule chain can I be using, I tested some but I couldn't.
Would it be the Script node at the point as shown in the image?
![1](https://github.com/thingsboard/thingsboard/assets/168031149/02d4a18a-7831-48f7-9576-531ec34c0d3f)


My difficulty is in creating an alarm with duration. In the Key name field the only option is DATA and in the Value type field I do not have a JSON option (As shown in the image below) and I would like to use only the "ICRMS" information to create the alarm.
![2](https://github.com/thingsboard/thingsboard/assets/168031149/ab7ec3e7-9819-4662-9f5a-c718502bc182)


Thank you for your support. I'm from Brazil and I'm using a translator, maybe the explanations aren't very good.

**Comment by ashaforost** [comment]
Yes, you want to use the transformation script rule node. Here's an example:
![image](https://github.com/thingsboard/thingsboard/assets/47900737/3b23d5f8-2b90-4782-9fcb-c98f017cf779)
As for the alarm settings, when you save each JSON key as a separate telemetry, you'll be able to create an alarm based on each telemetry, e.g., `VARMS>0, QA>0`
Please note, thingsboard's device profile cannot create an alarm from the JSON telemetry.

**Comment by 123GHLJ** [comment]
Thank you very much ashaforost, for your support and taking the time to respond to me. It worked perfectly.
