### ISSUE TITLE
Rule chain Label

### ISSUE THREAD

**Issue by sirapol** [thingsboard/thingsboard#10870]
**Is your feature request related to a problem? Please describe.**
In the rule chain canvas is many node and relation line.
It very confuse for debug.
I think i should to have some memo or indicator such as label.

**Describe the solution you'd like**
Just add the label for store just textbox and can move it in canvas without relation line.
Just look link "Label A" and "Label B" in picture in attachment.

![Screenshot from 2024-05-25 18-16-11](https://github.com/thingsboard/thingsboard/assets/7825850/6df59fbd-453e-4bdd-b6e7-5f8445939ebf)

**Comment by rpcai** [comment]
I would really like this featuate as well - "Annotation" component, to allow muti-line, formatted text to be placed on the rule chain canvas.

a seperate, but related feature, would be ability to group nodes so that they move together. i.e - to avoid time-consuming 'reformatting' when adding to complex rule chains.

**Comment by ssakharova** [comment]
Hello @sirapol, @rpcai,

We already have a prod ticket in our backlog related to adding notes to the rule chain UI. 
We cannot give you an exact timeframe for implementing this improvement. 

However, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.

**Comment by mykhailokornieiev** [comment]
Hi. We've created an Idea discussion https://github.com/thingsboard/thingsboard/discussions/15024 so that we can check the community's opinion regarding this request. This is done to identify the most desirable features for the community with further analysis of this data and its transfer to developers for further review. Even if the feature request is rejected, this information will still be useful for further planning the platform's development, and the decision may be reconsidered in the future.
