### ISSUE TITLE
Logging system is unusable due to lack of documentation

### ISSUE THREAD

**Issue by burnpanck** [thingsboard/thingsboard#10889]
**Describe the bug**
The documentation describes [how to enable "certain" logs](https://thingsboard.io/docs/user-guide/troubleshooting/#enable-certain-logs), but there is zero information on what loggers would be relevant to particular topics.
I consider this a bug rather than a feature request, because it effectively prevents the resolution of actual bugs.
Take for example #9625, which was closed without a resolution because the issue could not be debugged correctly. So having at least a high-level description on how what loggers are associated with what subsystems is essential for the community to work together and actually identify bugs.

**Comment by trikimiki** [comment]
Hi!

#9625 was a "question" issue - I have provided some generic advice on how your particular problem could be investigated. One cannot simply tag their problem as a "bug" because something does not work as expected - there are many factors to consider, such as configuration, server specs, proper usage of specific components, etc. Note that Rule Engine timeouts/failures require "deep dive" investigation, and debug/trace logging is only but a small part of it.

ThingsBoard is a very flexible platform. There are more than 3000 classes in total. While I agree that "how to enable extended logging" guide could be more extensive, it is impossible to cover all use cases and what classes require additional logging in order to investigate this or that. Consider the guide as a pointer on how to enable extra logging - then, you can check the source code and find what specific Java class should be logged during your investigation.

If you think you can improve that (or any other) guide on the docs site - you are welcome to contribute to the ThingsBoard site repository: https://github.com/thingsboard/thingsboard.github.io.
