### ISSUE TITLE
Can we change event queue type on existing instance?

### ISSUE THREAD

**Issue by alenas** [thingsboard/thingsboard#10892]
**Component**
 * Installation

**Description**
Currently we have 3.6.2PE version with Cassandra and Amazon SQS, but SQS cost is a bit too much for what it delivers.
can we change to use in-memory event queue? Is it a matter of just changing TB_QUEUE_TYPE environment variable?

**Environment**
 * OS:  Ubuntu 20.05
 * ThingsBoard: 3.6.2 PE
 * Cassandra
 * Amazon SQS

**Comment by trikimiki** [comment]
hi!

yes, you can change queue type and restart TB in order to apply config.
note that you will lost all unprocessed messages that were (at the time) still in your SQS queue.

also, in-memory queue will not work if your TB is deployed in microservices mode - in that case, consider using Kafka or Amazon MSK instead
