### ISSUE TITLE
Ignore case-sensitivity for user e-mail address?

### ISSUE THREAD

**Issue by lukas-k** [thingsboard/thingsboard#10937]
**Is your feature request related to a problem? Please describe.**
We are experiencing the problem, that some users are registering multiple accounts, as they are not aware that ThingsBoard is handling user email addresses with case-sensitivity. E.g. john.doe@example.com and John.doe@example.com and john.Doe@example.com resemble separate users.

**Describe the solution you'd like**
Always cast e-mail addresses to lower-case in login / registration endpoints.

**Describe alternatives you've considered**
None - Could implement this in application-specific frontends as well, but it would be better to have this in the Backend.

**Comment by mykhailokornieiev** [comment]
Hi
By default, login is case-sensitive. The ThingsBoard allows using the same email address to different accounts when email addresses are entered in different cases.
In order to disable it, you can change the configuration parameter by updating and setting the SECURITY_USER_LOGIN_CASE_SENSITIVE env variable in the thingsboard.conf file to false:
`export SECURITY_USER_LOGIN_CASE_SENSITIVE=false`
After that, you must restart your Thingsboard service to apply the settings.
https://thingsboard.io/docs/pe/user-guide/install/config/

**Comment by mykhailokornieiev** [comment]
I closed this ticket due to inactivity. If this question is still relevant to you, feel free to open a new ticket with full description of your request

**Comment by inakigoicoleaOCB** [comment]
setting that variable works indeed

However, it must be noted that the emails of all existing users must be converted into lower-case manually. They wont work otherwise. A simple SQL command can be enough

`update tb_user set email=lower(email)`
