### ISSUE TITLE
JSON/Array  in Advanced Filters

### ISSUE THREAD

**Issue by nicovon24** [thingsboard/thingsboard#10952]
Hello, there is no JSON option in advanced filter data types a maybe an array or json.

I have a "tags" array which i need to iterate, but have no possibilities to make the filters by for example "Miami"

Thanks

![image](https://github.com/thingsboard/thingsboard/assets/98624393/c12ca6b6-7a35-4765-99d7-06671f0939df)

**Comment by devaskim** [comment]
https://github.com/thingsboard/thingsboard/issues/6473

**Comment by KashifAhmd** [comment]
> #6473

But This is different, it is for fields.

But how to make a filter for JSON type value like

![Screenshot from 2024-07-22 15-16-04](https://github.com/user-attachments/assets/18de3b08-996f-4940-8406-ff2465bfdc1b)

so how can I filter this time series data base on its "type" value, because it is json data, and there is no option to filter JSON data
![Screenshot from 2024-07-22 15-20-08](https://github.com/user-attachments/assets/13bb6367-c87e-4f71-89a1-f955edcb7f7d)


Please help me, I'll be waiting for your response.

Thank you.

**Comment by devaskim** [comment]
@KashifAhmd Not sure if it works for telemetry keys but try `String` value type and `contains` operation.

![Скриншот 22-07-2024 150040](https://github.com/user-attachments/assets/443cc0b6-a304-433a-89b2-354c7ce455d2)

**Comment by Ultrazombie** [comment]
Closed due to inactivity
