### ISSUE TITLE
API to manipulate dashboards

### ISSUE THREAD

**Issue by eykamp** [thingsboard/thingsboard#1103]
It would be very helpful to have some API access to create, alter, remove, and control the layout of controls on dashboards.  I'd like to, for example, visit all dashboards with a certain sensor and add a widget to them, or programatically add a data element to a graph.

The only way I can find to do this is to download the JSON, manipulate that directly, then re-upload.  This works, but is a very opaque way to accomplish the task.  Is there any documentation on the dashboard JSON layout?

**Comment by ashvayka** [comment]
Hi @eykamp . The structure of the widget is specific to widget type/bundle. That is why we can't provide generic API. TB UI is responsible for working with this structure and we do not have specific REST API calls to add/remove widget. This is caused by the idea that you typically create 1-2 dashboards with multiple states for single solution and do not need to execute scripts to update a lot of dashboards.
