### ISSUE TITLE
Add option for mandatory two-factor authentication at tenant and/or customer level

### ISSUE THREAD

**Issue by dm9de** [thingsboard/thingsboard#11162]
**Is your feature request related to a problem? Please describe.**
Currently, it is possible to enable two-factor authentication, but it is not possible to **require** it. That is: it is left up to a user's discretion whether or not they would like to use 2FA. This isn't sufficient for many organisations, where mandataory 2FA is a requirement of their security policy.

**Describe the solution you'd like**
It should be possible for tenant administrators (and potentially customer administrators for PE) to force the use of 2FA for all users of that tenant/customer.

**Describe alternatives you've considered**
One possible alternative is to for such organisations to use Thingsboard's OAuth2.0 support to integrate a third-party authentication provider with mandatory 2FA. However, this adds substantial complexity.

**Additional context**
A similar request has been [raised before](https://github.com/thingsboard/thingsboard/issues/7585), however that issue was been closed as 'completed', citing a currently [unmerged pull request](https://github.com/thingsboard/thingsboard/pull/7586) from November 2022.

**Comment by ssakharova** [comment]
Hello @dm9de,

I passed all the provided information to our developers and created an internal prod ticket for them to decide on its necessity and possible implementation in future versions of the ThingsBoard.
Please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.

**Comment by dm9de** [comment]
Thanks @ssakharova

**Comment by pc9de** [comment]
@ssakharova Can I ask why this issue was closed given the functionality it mentions, specifically being **required** for an organisation, is not possible?
It does not appear to be possible to enforce this with the current release and the documentation specifically states it is not possible to enforce:
“Although 2FA can be a corporate security standard, the final decision on _whether to use it or not is with a particular user_”
[Two-factor authentication](https://thingsboard.io/docs/pe/user-guide/two-factor-authentication/)

Our organisation requires it and as such we will have to seek alternative solutions if this is not implemented. I suspect we are not alone in this regard.
