### ISSUE TITLE
TrendzAnalytics Error 104 License

### ISSUE THREAD

**Issue by MarcArias-D01** [thingsboard/thingsboard#11227]
**Component**

 * Installation

**Description**
I'minstalling Trendz via Docker in the same server and when i try to wake up docker of trendz this error shows regarding license. It was working but I made a docker-compose restart it fails.

[main] ERROR o.t.license.client.TbLicenseClient - License Error: ACTIVE_INSTANCES_CAPACITY_EXCEEDED(104) - Active instances capacity exceeded!
2024-07-17 14:49:40,901 [main] ERROR o.t.license.client.TbLicenseClient - Failed to initialize ThingsBoard License Client!
2024-07-17 14:49:40,902 [main] ERROR o.t.t.s.BaseSubscriptionService - Failed to init license client

**Environment**
 * OS:  Linux
 * ThingsBoard: BE 3.6.2

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by Deesthortered** [comment]
Hi @MarcArias-D01, it is not a bug, it is the expected behavior of our license check logic. 
When you buy a subscription on the License Portal you gain the license key of the subscription that you use in the docker-compose.yml file to register your instance. However, a subscription also contains instance management - it remembers the machine where it is launched and each subscription has a limited count of machines where it can be launched (we call it "instances"). Each instance has an ID stored in the mounted data folder (that is why it is important to mount that folder). If the folder is not mounted or the license file is deleted Trendz will create a new one as a new instance. However, the subscription will recognize it as a second instance that is not allowed in the subscription and refuse its registration. In this case it will show the error ACTIVE_INSTANCES_CAPACITY_EXCEEDED. 
Solution: 
1. Be sure the folder is mounted and the data from the folder will not be removed.
2. Go to the license portal, choose your subscription, open a list of instances, and remove existing instances.
3. Run Trendz again - it must start and the new instance must appear in the license portal.

**Comment by MarcArias-D01** [comment]
Hi Anatoli,

I will do that.

Thanks for your quick response and your help.



***@***.***,2.1338315,17z/data=!3m1!4b1!4m6!3m5!1s0x12a49865191559ed:0x6a9198b1a3b74b29!8m2!3d41.3893505!4d2.1338315!16s%2Fg%2F11c5d1dxpy>

Marc Arias

Machine Learning Leader



Mail ***@***.******@***.***>

Web www.driving01.com<http://www.driving01.com/>

Address Avinguda Diagonal ***@***.***,2.1338315,17z/data=!3m1!4b1!4m6!3m5!1s0x12a49865191559ed:0x6a9198b1a3b74b29!8m2!3d41.3893505!4d2.1338315!16s%2Fg%2F11c5d1dxpy>

(Barcelona / ***@***.***,2.1338315,17z/data=!3m1!4b1!4m6!3m5!1s0x12a49865191559ed:0x6a9198b1a3b74b29!8m2!3d41.3893505!4d2.1338315!16s%2Fg%2F11c5d1dxpy>





________________________________

**Comment by Ultrazombie** [comment]
Closed due to inactivity
