### ISSUE TITLE
Map Zoom fixed

### ISSUE THREAD

**Issue by Agailh** [thingsboard/thingsboard#11258]
**Component**

 * UI

**Description**
Clear and concise details.

**Environment**

 * OS:  windows
 * ThingsBoard: community 
 * Browser: chrome 
 
 
 How to make zoom fixed ? everytime user zoom to one entity map go back to default zoom after refresh ? how to fix it ? 

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by mykhailokornieiev** [comment]
Hi
There is no way to fixate the zoom in such a way that after reloading the page, the last zoom state is opened, since by design of Thingsboard there is no way to save such data in available widgets. You will need to create some custom solution, maybe custom widget that will save zoom state as device/customer/dashboard attribute and use it for zoom state.

**Comment by Agailh** [comment]
> Hi There is no way to fixate the zoom in such a way that after reloading the page, the last zoom state is opened, since by design of Thingsboard there is no way to save such data with available widgets. You will need to create some custom solution, maybe custom widget that will save zoom state as device/customer/dashboard attribute and use it for zoom state.

thank you for the aswer
