### ISSUE TITLE
Add assignee to alarm via rule chain

### ISSUE THREAD

**Issue by warmbowski** [thingsboard/thingsboard#11279]
**Component**
 * Rule Engine

**Description**
Our use case is dynamic alarm creation via create alarm node and we want to assign a user at creation (or immediately after). The target assignee is propagated in the metadata sent to the create alarm node, but there doesn't seem to be a way to alter the alarm that is created to add the assigneeId, as the only thing we can change in the create alarm nodes is the alarm details.  Am I missing something in the create alarm node, or is there another node I can use to alter the the alarm at add an assignee?

**Environment**

 * OS:  demo.thingsboard.io
 * ThingsBoard: 3.7.0
 * Browser: Chrome Version 126.0.6478.127

**Comment by mykhailokornieiev** [comment]
Hi
The only possible solution for such case will be to use Rest API call node with https://demo.thingsboard.io/swagger-ui/index.html#/alarm-controller/assignAlarm controller after alarm creation in rule chain. 
https://thingsboard.io/docs/user-guide/rule-engine-2-0/external-nodes/#rest-api-call-node
There is no possibility to assign user simultaneously with alarm creation by design of Thingsboard.

**Comment by warmbowski** [comment]
Can we turn this issue into a feature request for adding two rule chain Action nodes that would possibly be pretty handy?
1. an Update Alarm Assignee rule chain node 
2. an Add Alarm Comment rule chain node

**Comment by warmbowski** [comment]
Yeah, after review, I don't think this rest api call is a great solution unless there is a way to create a dedicated api token that doesn't expire. As far as I understand it, your solution would mean creating a dedicated utility user in the system, then creating a Rest API node to log into the system and get a bearer token, and then another Rest API node to do the assignment. So in my case, a login and assignment would happen each time an alarm is created. I suppose a login cache could be persisted, but that would make this rule chain too cumbersome and failure prone. I will pass on doing this and figure another way, or wait for new Rule chains to be added.

Looking at the code, it might not be too difficult to find a developer to make a custom rule chain node to do the assignment without api calls, but we are planning to run on one of the hosted solutions so won't have access to customize.

**Comment by mykhailokornieiev** [comment]
Hi. At the moment, I don't see the point in creating these feature requests because alarms will be redesigned in the future (perhaps within six months to a year). If, after that, there are no necessary functionality for you, then create the corresponding feature requests, and we will consider adding them.
Till then, there is no possibility to add such features by design of Thingsboard.
