### ISSUE TITLE
[Feature Request] Rule Chain Comment Node

### ISSUE THREAD

**Issue by lucaslpmoura** [thingsboard/thingsboard#11280]
**Motivation**
Big rule chains can get really cluttered, and trying to understand what each part does, specially in chains made by other people can get annoying. Comments can help to clear things up.

**Solution**
An special "node" that is static an only features a comment. Much like node-red's approach.
![Screenshot from 2024-07-24 15-11-07](https://github.com/user-attachments/assets/449fc2dd-495e-4f2e-8a49-09ebf8e4cce2)

**Alternatives**
Node titles are a good feature, but they they can't explain the full context where the node is inserted. Also, in big chain the titles can sometimes cloud things even further.,

**Comment by mde2017** [comment]
It is already possible to define comments for Rulenodes, but this differs from node-red's approach.
I personally prefer TB's approach, since it's not neccessary to add additional nodes for the comments.

**Example in ThingsBoard:**
You can use the description field in every rulenode. When hovering over the node, the description text is displayed in a tooltip:

![image](https://github.com/user-attachments/assets/94b970de-dc33-49fc-bcf9-8321b0c2b13a)

In the given example the description is entered for the "Add Credentials" node.

**Comment by mykhailokornieiev** [comment]
Hi @lucaslpmoura 
The only possible behavior right now is the one mentioned by @mde2017. 
However, there will be rule chains UI redesign in future releases with re-build of the description / comments. 
Please follow the [Release Notes](https://thingsboard.io/docs/reference/releases/) to be notified of new updates
