### ISSUE TITLE
Issue with Secure MQTT Connection on Port 8883

### ISSUE THREAD

**Issue by Vaibhav0216** [thingsboard/thingsboard#11291]
Hi,

I am experiencing issues connecting to thingsboard.cloud using MQTT over a secure connection on port 8883.

I have successfully connected using MQTT on port 1883, but when I try to connect using the secure port 8883, I encounter the following error:
``` mosquitto_pub --cafile ca-root.pem -d -q 1 -h "thingsboard.cloud" -p 8883 \
-t "v1/devices/me/telemetry" --key deviceKey.pem --cert chain.pem -m '{"temperature":25}'
```
**Error :-** 

`
Client (null) sending CONNECT
OpenSSL Error[0]: error:0A000086:SSL routines::certificate verify failed
Error: A TLS error occurred.
`
I have followed the documentation thoroughly but still face this issue. Could you please provide guidance on how to resolve this?

Thank you.

Best regards,
Vaibhav Kshirsagar

**Comment by dealnat** [comment]
As the issue was closed by author without any comments, we decided to share some extra info related to this issue if other users will face this issue again. In the MQTT authentication with x509 certificates chain tutorial there is CA .pem certificate for the mqtt.thingsboard.cloud otherwise as the CA certificate should be used certificate mentioned in the MQTT_SSL_PEM_CERT env variable in the configuration file. Some users may be confused and choose Web server CA certificate, so this issue will reproduce
