### ISSUE TITLE
Entity Table key and value relation come in the column not in row.

### ISSUE THREAD

**Issue by Vaibhav0216** [thingsboard/thingsboard#11449]
![image](https://github.com/user-attachments/assets/ab681a22-a572-4fb8-a77f-9e1b04c505fe)

In the above table entity and value comes in the different columns.

**I want like :-** 

attributes    values 
level            6
capacity      5000

How can I achieve this.

**Comment by mykhailokornieiev** [comment]
Hi. There is no such a possibility by design of Entities Table widget. You can only display it in different columns.
For such a purpose, as workaround, you can either create some custom widget, or use HTML Value Card
![image](https://github.com/user-attachments/assets/9bf39eeb-26da-4dab-aadf-b1f59354fa5c)

**Comment by Vaibhav0216** [comment]
Thanks for your guidance. I will try it
