### ISSUE TITLE
Filters not having current device source type

### ISSUE THREAD

**Issue by nicovon24** [thingsboard/thingsboard#11474]
Hello, no current entity here?

For example a device which has a threshold of min_level and i want to show it here, i am not able to do it by now or do not know how to do it

![image](https://github.com/user-attachments/assets/9eeea35d-39f3-4e7a-add8-5d088c3c30a5)

![image](https://github.com/user-attachments/assets/571ee8c5-5be2-44db-aac7-8289adb7d536)

**Comment by ssakharova** [comment]
Hello @nicovon24,

I passed all the provided information to our developers and created an internal prod ticket for them to decide whether it is necessary and possible to implement in future versions of the ThingsBoard.

There's no set timeframe for our dev reviews. However, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.

**Comment by mykhailokornieiev** [comment]
Hi. We've created an Idea discussion https://github.com/thingsboard/thingsboard/discussions/15634 so that we can check the community's opinion regarding this request. This is done to identify the most desirable features for the community with further analysis of this data and its transfer to developers for further review. Even if the feature request is rejected, this information will still be useful for further planning the platform's development, and the decision may be reconsidered in the future.
