### ISSUE TITLE
Last changed column in Rule chains list

### ISSUE THREAD

**Issue by JimmyPedersen** [thingsboard/thingsboard#11482]
**Is your feature request related to a problem? Please describe.**
Sometimes hard to remember what rule I last made changes to (I have many many rules)

**Describe the solution you'd like**
A Last changed column in Rule chains list. Just like there is a Created column today.

**Comment by ssakharova** [comment]
Hello @JimmyPedersen,

I passed all the provided information to our developers and created an internal prod ticket for them to decide whether it is necessary and possible to implement in future versions of the ThingsBoard.
Please check our [Release Notes](https://thingsboard.io/docs/reference/releases/) for updates on future platform additions.

**Comment by mykhailokornieiev** [comment]
Hi. We've created an Idea discussion #16090 so that we can check the community's opinion regarding this request. This is done to identify the most desirable features for the community with further analysis of this data and its transfer to developers for further review. Even if the feature request is rejected, this information will still be useful for further planning the platform's development, and the decision may be reconsidered in the future.
