### ISSUE TITLE
Change text color in marker cluster on map widget dynammically

### ISSUE THREAD

**Issue by Allwhy** [thingsboard/thingsboard#11488]
In the map widget it is currently only possible to set the color of the cluster markers themselves. However, the color of the number within the markers is always static, defaulting to black. 
I would like to be able to change the color of the number within the marker dynamically to adjust to the color of the marker.
At the moment it is only possible to change the color via the advanced widget style css, but this still results in static colors.

**Comment by sumin-denys** [comment]
HI @Allwhy,

Thank you for your report! 

For now, there’s no possibility to change the text color inside the cluster marker.

I've added this request to our backlog, PROD-4502. Once the product team reviews this ticket, we’ll post an update on when this feature could be delivered if they decide to add it to the product.

Please refer to our release notes to find out more about new features and bug fixes: [Release Notes](https://thingsboard.io/docs/pe/reference/releases/)

I am closing this issue for now. If you have any further questions or require clarification, please let me know.

**Comment by mykhailokornieiev** [comment]
Hi. We've created an Idea discussion #16088 so that we can check the community's opinion regarding this request. This is done to identify the most desirable features for the community with further analysis of this data and its transfer to developers for further review. Even if the feature request is rejected, this information will still be useful for further planning the platform's development, and the decision may be reconsidered in the future.
