### ISSUE TITLE
Support of map in protobuf schema to support dynamic parameter

### ISSUE THREAD

**Issue by ukotdiya02** [thingsboard/thingsboard#11486]
**Feature Need** 
I had dynamics number of parameter for sending time series data. I want to send it using protobuf as it better for low footprint device with low bandwidth network.

**Describe the solution you'd like**
Solution is if thingsboard can support map in protobuf schema .Below is the schema I want to be supported

syntax = "proto3";
 
message TimeSeriesData {
  int64 ts = 1;
  map<string, int32> values = 2;
}
This will help me in supporting below JSON type of of Data where parameter can be added dynamically in values
{
  "ts": 0,
  "values": {
    "1.0.1.8.0.255": 550,
    "1.0.9.7.0.255": 50
  }
}
_____________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies)), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by mykhailokornieiev** [comment]
Hi. We've created an Idea discussion #16089 so that we can check the community's opinion regarding this request. This is done to identify the most desirable features for the community with further analysis of this data and its transfer to developers for further review. Even if the feature request is rejected, this information will still be useful for further planning the platform's development, and the decision may be reconsidered in the future.
