### ISSUE TITLE
Alias suggestion : Relations query from another alias

### ISSUE THREAD

**Issue by loicgillioz** [thingsboard/thingsboard#11497]
I am often trying to solve complex queries for retrieving certain assets when creating dashboards.
For example, I want to select all assets of a given _asset type_, that have a _contains_ relation to a given _device type_. So, I would like to create a first alias that selects a given _device type_. Then I would like to select _all assets of a given asset type_, that have a _contains_ relation to this first alias.

I think it would be very useful to have aliases that can make use of other aliases in dashboard.

An alternative for now is to create custom groups but it's somehow unpractical as it requires the creation of new groups each time I face this issue and it can be time consuming on the long term. It's not solving the initial issue, but it's a workaround. It needs maintenance every time there is a modification in the assets classification, which is very error prone when it comes to managing an important number of assets.

Thanks for you consideration.

**Comment by SuminDenys** [comment]
Hi @loicgillioz,

Thank you for your feature request and your valuable suggestion. We have carefully reviewed your request and understand how beneficial this feature could be.

However, after thorough consideration, we've identified that implementing this functionality could significantly impact system performance. Unfortunately, due to this potential performance issue, we won't be able to implement this feature.

We always strive to balance new features with system stability, and your feedback is a crucial part of that process. We will continue to explore possible optimization paths in the future, and we genuinely appreciate your ideas.

If you have any other suggestions or ideas, please feel free to share them with us.

Thank you once again for your understanding!
