### ISSUE TITLE
Thingsboard Realtime graph not displaying

### ISSUE THREAD

**Issue by Engineer-of-Stuff** [thingsboard/thingsboard#1149]
I've set up a device on my Thingsboard server. Data is being received from my device.

When I add a timeseries chart to the device's dashboard and set the timewindow to any value to "last" and the data aggregation function to anything but "none", nothing shows in the graph.

Any data aggregation function (besides "none") causes no data to be displayed in the graph.

Is there something I'm missing?

---
**Update:**
Even the demo site's graphs aren't working.

**Comment by vparomskiy** [comment]
1.could you pelase confirm that "count" aggregation also does not work for you?
2. Does 'historical time window works?

**Comment by Engineer-of-Stuff** [comment]
1. Count does not show data.
2. Historical does not show data when set to average.

**Comment by vparomskiy** [comment]
Thingsboard supports different data types. If you are submitting your telemetry as String, then it is saved as the string. And in this case, 'SUM' and 'AVG' functions will return empty dataset because it is not possible to calculate the sum and average value on String data. But 'MIN/MAX/COUNT' aggregation functions will work.

For example:
{"key1":"10"} - value is saved as string ("10") - SUM and AVG will not work

{"key1":10} - value is saved as integer (10) - all aggregation functions will work

You can enable debug mode in 'save telemetry' node to find original messages that are published to the Thingsboard.

**Comment by vparomskiy** [comment]
Also, here is the similar thread - [#817](https://github.com/thingsboard/thingsboard/issues/817)

**Comment by Engineer-of-Stuff** [comment]
That's the issue!! I was sending my data as strings instead of integers, never thought it would be a problem.

Thanks for the help. You should add a notice for people like me.

**Comment by vparomskiy** [comment]
We plan to automatically cast string types to numeric if it is possible. but it was not implemented yet.
