### ISSUE TITLE
Latest Telemetry not showing after publishing telemetry through MQTT

### ISSUE THREAD

**Issue by andyabcd1** [thingsboard/thingsboard#11529]
**Describe the bug**
Latest Telemetry not showing after publishing telemetry 

**Your Server Environment**
- Docker-compose following https://thingsboard.io/docs/user-guide/install/docker/
- Hosted in a VM

**Your Client Environment**

**Desktop (please complete the following information):**
MacOS

**Your Device**
* Connectivity
  * MQTT

**To Reproduce**
1. run `mosquitto_pub -d -q 1 -h 1.2.3.4 -p 1883 -t v1/devices/me/telemetry -u "T2_TEST_TOKEN" -m "{temperature:25}"`
2. Visit Entities -> Devices -> select device -> Latest Telemetry

I also try to manually create telemetry in Thingsboard Console
<img width="552" alt="Screenshot 2024-08-29 at 11 44 49 AM" src="https://github.com/user-attachments/assets/5bead518-5a8d-4388-8ee2-4e96a1e2cb81">

I saw it was created in Audit Logs, but still not showing in latest telemetry
<img width="1260" alt="Screenshot 2024-08-29 at 11 45 09 AM" src="https://github.com/user-attachments/assets/920c3cd7-9669-4835-a144-7213386978f5">

**Expected behavior**
Latest Telemetry shown here
<img width="1502" alt="Screenshot 2024-08-29 at 11 43 57 AM" src="https://github.com/user-attachments/assets/d37a311f-6c7e-4a9b-87ba-a46907c9febc">

**Comment by devdoob** [comment]
The IP address in your mosquitto command is 1.2.3.4

is this correct?

**Comment by mykhailokornieiev** [comment]
Hi @andyabcd1 
Make sure that all requirements are met:
1) You assigned device profile with either default (all) or MQTT transport selected
![image](https://github.com/user-attachments/assets/65b1bbdb-4a7f-4995-be5e-436067ed0190)
2) Check if selected rule chain of device profile has "Save Timeseries" flow in it
![image](https://github.com/user-attachments/assets/65f09364-a1b2-426a-b050-ccb09e04989b)
![image](https://github.com/user-attachments/assets/42c2ed2f-b511-4fd1-9c22-223c3dbdbafa)
![image](https://github.com/user-attachments/assets/e414f24c-57bc-4cee-801a-391565a39311)
Since you deployed your Thingsboard as docker container inside VM (as I understood it) then make sure you have either all necessary port forwarding or you use internal VM terminal with provided "Check connectivity" commands
![image](https://github.com/user-attachments/assets/1cf96215-e213-4303-8ff8-0a1a7e3fd941)
![image](https://github.com/user-attachments/assets/fb9b92d3-af42-4a21-96f4-c7049883eb23)

**Comment by andyabcd1** [comment]
Hi @mykhailokornieiev 

It doesn't work even I use default Therostat and add the telemetry manually

<img width="1073" alt="Screenshot 2024-08-30 at 9 34 58 AM" src="https://github.com/user-attachments/assets/6e4f34d5-4a6b-4550-bcbb-512c64439f10">

It shows in Audit log.
<img width="1136" alt="Screenshot 2024-08-30 at 9 35 38 AM" src="https://github.com/user-attachments/assets/c56924a1-d112-41b4-a3a7-de75b8a4d4aa">

The Root chain
<img width="321" alt="Screenshot 2024-08-30 at 9 36 36 AM" src="https://github.com/user-attachments/assets/5ba03938-08be-4721-9049-7c7167c636d7">
<img width="770" alt="Screenshot 2024-08-30 at 9 37 50 AM" src="https://github.com/user-attachments/assets/4f6d4d27-2ec4-4fe6-a790-fd23e13b4fea">
<img width="1351" alt="Screenshot 2024-08-30 at 9 39 16 AM" src="https://github.com/user-attachments/assets/71341d33-aefe-47d4-8276-9fde5bc123eb">

**Comment by andyabcd1** [comment]
Turns out it's a websocket issue because of the configuration in nginx. It's fixed now

**Comment by K-721** [comment]
Hello, @andyabcd1. May I know what to change in the configuration of nginx? Encountering the same issue right now after integrating nginx, thanks!

**Comment by chetantiw** [comment]
@peterabcd1, what is the configuration of nginx? I mean, how is it affecting the telemetric data?
