### ISSUE TITLE
thingsboard downlink to chirpstack: no body 404 Not found

### ISSUE THREAD

**Issue by NAW-KHU** [thingsboard/thingsboard#11554]
**Component**

 * UI
 * Rule Engine
 * Installation
 * Generic

**Description**
Thingsboard downlind to chirpstack : no body {404 not found}

![downlink_error_event](https://github.com/user-attachments/assets/a4323e9c-bca6-463f-9e08-c63f12a2c367)
![downlinkconverter_event](https://github.com/user-attachments/assets/898cd0dc-43db-47a7-86e4-4c1271655624)
![Chirpstack-server-log](https://github.com/user-attachments/assets/8ddb2ec2-ee05-40ab-a033-69e3536ee1f4)

**Environment**

 * OS:  window 11
 * ThingsBoard: 3.7.0 PE
 * Browser: Microsoft Edge

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by xTwigx** [comment]
Im also having an issue when using http integration from Chirpstack to Thingsboard. If anyone knows a how chirpstack should receive the message I would appreciate it.

**Comment by dealnat** [comment]
Didn't you create Thingsboard integration on chirpstack, do you? 
The 404 error may occur when you choose Thingsboard integration instead of HTTP integration.
Here is the documentation for configuring integration from the Chirpstack side [Chirpstack Integration](https://thingsboard.io/docs/user-guide/integrations/chirpstack/#configure-integration-on-your-chirpstack-application)
