### ISSUE TITLE
Is row based TTL with TimescaleDB possible?

### ISSUE THREAD

**Issue by apachler** [thingsboard/thingsboard#11581]
**Component**

 * Generic

**Description**
From the docs: Cassandra supports time-to-live(TTL) parameter for each inserted row.
Is this also possible with TimescaleDB?

**Environment**

 * OS: SLES 15 + Docker Swarm
 * ThingsBoard: 3.7

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by apachler** [comment]
Any news here?

**Comment by sumin-denys** [comment]
Hi @apachler,

**TTL** (Time-to-Live) in **Cassandra** and **TimescaleDB** are similar in concept but differ significantly in how they are implemented and used, given the architectural differences between the two databases.

**Cassandra:**
- TTL can be applied per row or column.

**TimescaleDB:**
- TTL is applied at the table level (or, more precisely, at the hyper table level, which is TimescaleDB’s special structure for time-series data).

Here is a link to the [TimescaleDB documentation](https://docs.timescale.com/use-timescale/latest/data-retention/about-data-retention/) where we can find the following: 
> Timescale data retention works on chunks, not on rows. Deleting data row-by-row, for example, with the PostgreSQL DELETE command, can be slow. But dropping data by the chunk is faster, because it deletes an entire file from disk. It doesn't need garbage collection and defragmentation.

Also, I want to mention that the ThingsBoard Team recommends using the following Hybrid setup: Postgres + Cassandra since it is more flexible in customization and architecture. You can easily create a cluster of 3 nodes for Cassandra, which compresses data to use less disk space.

The best performance for telemetry writes is achieved in Cassandra.

**Comment by apachler** [comment]
Thanks for the information!
