### ISSUE TITLE
Automate customer relation to multiple devices

### ISSUE THREAD

**Issue by anautinirea** [thingsboard/thingsboard#11621]
**Component**

 * Rule Engine

**Description**
I have a customer with multiple devices and initially manually added relations from device to customer. 
It's a bit inconvienient now and I want to automate a create relation from customer to multiple devices, during bulk provisioning or after. I would like to do this in Rule Chain. 
Can someone share how they've successfully done this? 

Note my Thingsboard version is slightly outdated (perpetually paid) so the nodes in Rule Chain is slightly different to current versions

**Environment**

 * ThingsBoard: PE 3.3.2

**Comment by mykhailokornieiev** [comment]
Hi. For such purpose your can use Create Relations rule node:
https://thingsboard.io/docs/user-guide/rule-engine-2-0/action-nodes/#create-relation-node

**Comment by anautinirea** [comment]
Thanks @mykhailokornieiev. I'm new to this, do you have a sample rule chain of what it would look like? Thanks

**Comment by mykhailokornieiev** [comment]
Hi
It will look something like this:
1. Connect your new rule chain via "Entity Created" relation type in Root Rule Chain, so it will be triggered on the Entity Created event.
![image](https://github.com/user-attachments/assets/add76df5-6e3b-434e-aef5-d3595488f5ca)
2. Create the next rule chain
![image](https://github.com/user-attachments/assets/6348c223-e69c-4a16-a3e0-cd072eb4c5d9)
The filter script rule node will filter all messages and pass only under the desired conditions.
![image](https://github.com/user-attachments/assets/9c7fc554-c127-4b51-9d68-6f1e66313178)
![image](https://github.com/user-attachments/assets/0d014c80-9454-4a88-af32-5a8dfbdb47b7)
`return metadata.entityType == "DEVICE";`
Check relations presence is optional, I've added it just for example
![image](https://github.com/user-attachments/assets/78c39e18-1c38-4af0-85e6-efeded935696)
Change Originator rule node is necessary since Create Relations can create it only using entity name, not entityId. Since we already have the device name, it will be easier to create relations from customer to device using customer as originator
![image](https://github.com/user-attachments/assets/9daee0a8-f751-4d45-9f21-dc05034fe4c5)
![image](https://github.com/user-attachments/assets/fb7987f6-aaff-4636-9a1b-48d2118498f5)
And finally, Create Relation will use already available entityName value from metadata and create the necessary relations
![image](https://github.com/user-attachments/assets/203c8063-6902-45b9-8ea0-12d72bab4921)
![image](https://github.com/user-attachments/assets/62f83333-196f-4554-b15a-64e7d2aef1ad)
This relation is a result of rule chain automated processing. I've created only device, it can be done either manually or via bulk import
![image](https://github.com/user-attachments/assets/e8e11466-f96e-40ae-86a8-2d7218e74964)

You can get familiar with this rule chain.
[create_relation.json](https://github.com/user-attachments/files/16980686/create_relation.json)
Also, here is a list of useful documentation:
https://thingsboard.io/docs/user-guide/rule-engine-2-0/filter-nodes/#script-filter-node
https://thingsboard.io/docs/user-guide/rule-engine-2-0/filter-nodes/#check-relation-filter-node
https://thingsboard.io/docs/user-guide/rule-engine-2-0/transformation-nodes/#change-originator
The Acknowledge rule node is required for those messages that you do not need
