### ISSUE TITLE
Hide duplicated rows in Timeseries table

### ISSUE THREAD

**Issue by apachler** [thingsboard/thingsboard#11658]
**Is your feature request related to a problem? Please describe.**
This is no problem at all. It is a feature request.

**Describe the solution you'd like**
Timeseries table now has the option to hide empty rows. It would also be nice to have the option to hide duplicated rows.
Something like hiding the row if the previous row has the same content.

**Describe alternatives you've considered**
Customizing the widget by myself ;)

_____________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies)), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by mykhailokornieiev** [comment]
Hi. There is no necessity in qeature request, since it can be achieved with standard functionality:
1. Add this code snippet in your datakey -> data post-processing function:
```
if (value == prevOrigValue) {
  return null;
} else {
  return value;
}
```
![image](https://github.com/user-attachments/assets/d51da8d3-17b4-4188-9b3c-301bd91aaa84)
2. Enable "Hide empty lines" option in Advanced -> Appearance -> Rows:
![image](https://github.com/user-attachments/assets/727fe4d7-3c36-433d-9e05-ff5bee4af4aa)

Before: 
![image](https://github.com/user-attachments/assets/0d00afa3-c905-48db-ba2a-3a8f56303c83)
After:
![image](https://github.com/user-attachments/assets/0a8b3886-e09f-4101-8e4d-545e680d6085)

**Comment by apachler** [comment]
Nice solution, thank you!

**Comment by apachler** [comment]
I have tried this solution but it is not satisfying because i need to compare the complete row for equality. Column based compare does not work in my case.
Do you have an idea how to solve this?
