### ISSUE TITLE
Error during installation tb-web-report

### ISSUE THREAD

**Issue by Tomi05-k** [thingsboard/thingsboard#11691]
Hello everyone,
I am using the Thingsboard_PE version and wanted to install the web report.
Unfortunately, this is not possible because there are two errors:
- the third-party libraries are no longer all available for installation 
- the googleapis noto thing does not work anymore 

first problem: 
`~# sudo apt install -yq gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
     libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
     libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 \
     libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 \
     ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils unzip wget libgbm-dev`

`Reading package lists...
Building dependency tree...
Reading state information...
Package libasound2 is a virtual package provided by:
  liboss4-salsa-asound2 4.2-build2020-1ubuntu3
  libasound2t64 1.2.11-1build2 (= 1.2.11-1build2)
E: Unable to locate package gconf-service
E: Package 'libasound2' has no installation candidate
E: Unable to locate package libgconf-2-4
E: Unable to locate package libappindicator1`

second problem:
`:~/noto# wget https://noto-website.storage.googleapis.com/pkgs/NotoSansCJKjp-hinted.zip
--2024-09-18 19:56:48--  https://noto-website.storage.googleapis.com/pkgs/NotoSansCJKjp-hinted.zip
Resolving noto-website.storage.googleapis.com (noto-website.storage.googleapis.com)... 142.250.181.219, 142.251.209.155, 172.217.16.91, ...
Connecting to noto-website.storage.googleapis.com (noto-website.storage.googleapis.com)|142.250.181.219|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-09-18 19:56:49 ERROR 404: Not Found.`

hope you can help me.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble

Best regards Tom!

**Comment by mykhailokornieiev** [comment]
Hi
As far as I know, these third-party libraries are deprecated since at least Ubuntu 23.10
You can install some of them manually:
wget http://ftp.it.debian.org/debian/pool/main/g/gconf/gconf2_3.2.6-8_amd64.deb
wget http://ftp.it.debian.org/debian/pool/main/g/gconf/libgconf-2-4_3.2.6-8_amd64.deb
https://packages.debian.org/buster/libappindicator1
https://packages.debian.org/en/sid/libasound2
As for Noto Sans, this site is currently unavailable, so as workaround, you can install it from another source 
As my practice shows, these libraries are desirable but not mandatory. As for Noto Sans CJK, this font is needed in the case of dashboard reports with Chinese, Korean and Japanese languages

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
