### ISSUE TITLE
Daily delta

### ISSUE THREAD

**Issue by realbeeit** [thingsboard/thingsboard#11719]
**Component**

 * Generic

**Description**
I want to calculate delta from my weight scale devices from first reading after midnight to current. At midnight I want to save that delta in table for each day. How I can do that? It is not delta between min and max, it is delta from first reading of the day and last.

**Environment**

 * OS:  ubuntu
 * ThingsBoard: 3.6.0
 

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by pon0marev** [comment]
You need to configure the logic using rule chains and secondary attributes. For example:
Create the attribute “first value of the day” and “last value of the day”. In the script, check if the timestamp of the current value cut to the day is greater than the timestamp of the “first value”, then it is the next day, and therefore you need to write the delta for the day to the telemetry and reset the first and last values. Otherwise, write the current delta.
For already existing data, this will be very hard to do and require the development of a custom widget/rule node.

**Comment by pon0marev** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
