### ISSUE TITLE
Scheduled Report bug

### ISSUE THREAD

**Issue by gurverm** [thingsboard/thingsboard#11745]
I have a weekly scheduling event setup to generate and email a report. The report shows a screenshot of the dashboard however, a few widgets arent displaying the data. The data looks fine on the dashboard so I am unsure why this is occurring. When i use the generate test report feature it is displaying the report as intended but the scheduled report is giving issues. I've attached the report for your reference. 

[report-2024-09-23_08_00_00.pdf](https://github.com/user-attachments/files/17137554/report-2024-09-23_08_00_00.pdf)

**Comment by xTwigx** [comment]
Hi this is happening to me as well. I has Reports all working correctly but now sometimes some of the data is not being shown but when i generate a test report a second time it shows me the data.

Also have a quick question, how did you make it give you a screen shot of the whole state. When I generate a report of a large state it cuts at a certain point and doesn't let me see the rest because its to big

**Comment by mykhailokornieiev** [comment]
Hi

Probably web-report have no enough time to draw all necessary data, so it make blank page, since this state is too heavy.
It may be able to generate full report on second attempt due to already cached data after first attempt.
In this case, you can add these parameters to /etc/tb-web-report/conf/tb-web-report.conf/
```
export LOAD_DASHBOARD_RESOURCES_TIMEOUT=180000
export DASHBOARD_IDLE_WAIT_TIME=20000
export GENERATE_REPORT_TIMEOUT=180000
```

Also, you can add the next parameter to /etc/thingsboard/conf/thingsboard.conf:
```
export SPRING_MVC_ASYNC_REQUEST_TIMEOUT=60000
```

You can also increase these parameters. After adding these parameters, remember to restart both the thingsboard and tb-web-report services.

**Comment by gurverm** [comment]
@xTwigx Heres a screenshot of my settings not entirely sure why thats the case for you. 

<img width="1512" alt="Screenshot 2024-09-26 at 11 30 44 AM" src="https://github.com/user-attachments/assets/5a4789f0-16bd-4dcb-a74e-aaf31764738e">

@mykhailokornieiev Thanks! But I dont have access to the code for the instance that i am working on. is there any alternative way to do this on the platforms ui. if not i can contact my thingsboards host provider

**Comment by mykhailokornieiev** [comment]
@xTwigx 
The ThingsBoard web report works according to the following logic: goes to full-screen mode and makes the page size 100%, and then it takes a snapshot of everything on the page.
So set up your widget in full-screen mode and page size 100%.
Unfortunately, the tb-web-report service in its current form is not perfect. The current web-report will not be fixed or improved as we are working on a new web-report service (our devs are writing it from zero) that will work correctly, but unfortunately, nobody knows when it will be released.

@gurverm if it's not demo.thingsboard.io or thingsboard.cloud, than you can ask your provider to add these parameters. For this, it's enough to have access and sudo permissions on server that running thingsboard.

**Comment by xTwigx** [comment]
@mykhailokornieiev 
Thanks for all of the help I understand how the scheduler and reports work. Looking forward to the new web report. Hopefully it has XLS export for a widget :).

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity
