### ISSUE TITLE
Unable to change dial widgets colour combinations.

### ISSUE THREAD

**Issue by harshadaVM** [thingsboard/thingsboard#11750]
We are facing issue in colour combination for dials.
We add temperature dial control with default colour combination, it looks like Image-1. But when we change blue colour to yellow(any) it looks like Image-2.
Image-1
![default](https://github.com/user-attachments/assets/bb5e030d-34b2-4559-95f2-a69938b808c7)
Image-2
![ColourChange](https://github.com/user-attachments/assets/eaee561d-c402-4939-8ce2-743663bd0531)

**Thingsboard version: 3.7.0PE**

________________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by dealnat** [comment]
Hi, this is a known bug about gauge widgets and range chart color range. The fix is already merged into the codebase, here is the pull request [Fix pull request](https://github.com/thingsboard/thingsboard/pull/11096). I can't tell you the exact timewindow for the release of the version that contains the fix, but you can observe release notes [Release notes](https://thingsboard.io/docs/reference/releases/)
