### ISSUE TITLE
Hello, I would like to ask why the msg needs to be re queued when the rule engine's relationscount > 1

### ISSUE THREAD

**Issue by lvxi0605** [thingsboard/thingsboard#11841]
**Component**
 * Rule Engine

**Description**
I deployed ThingsBoard service on a single machine, using Kafka as the messaging queue. During performance testing, I simulated 3,000 devices sending 200 data points per second, resulting in 600,000 data points per second. However, I found that Kafka was unable to process the messages due to a build-up of messages. During my analysis of the issue, I reviewed the **org.thingsboard.server.actors.ruleChain.RuleChainActorMessageProcessor.onTellNext** code and discovered that if the number of relations in the rule engine is greater than 1, the messages will be re-queued, causing Kafka to have too many messages that cannot be consumed.
~~~java  
 private void onTellNext(TbMsg msg, RuleNodeId originatorNodeId, Set<String> relationTypes, String failureMessage) {
        try {
            checkComponentStateActive(msg);
            EntityId entityId = msg.getOriginator();
            TopicPartitionInfo tpi = systemContext.resolve(ServiceType.TB_RULE_ENGINE, msg.getQueueName(), tenantId, entityId);

            List<RuleNodeRelation> ruleNodeRelations = nodeRoutes.get(originatorNodeId);
            if (ruleNodeRelations == null) { // When unchecked, this will cause NullPointerException when rule node doesn't exist anymore
                log.warn("[{}][{}][{}] No outbound relations (null). Probably rule node does not exist. Probably old message.", tenantId, entityId, msg.getId());
                ruleNodeRelations = Collections.emptyList();
            }

            List<RuleNodeRelation> relationsByTypes = ruleNodeRelations.stream()
                    .filter(r -> contains(relationTypes, r.getType()))
                    .collect(Collectors.toList());
            int relationsCount = relationsByTypes.size();
            if (relationsCount == 0) {
                log.trace("[{}][{}][{}] No outbound relations to process", tenantId, entityId, msg.getId());
                if (relationTypes.contains(TbNodeConnectionType.FAILURE)) {
                    RuleNodeCtx ruleNodeCtx = nodeActors.get(originatorNodeId);
                    if (ruleNodeCtx != null) {
                        msg.getCallback().onFailure(new RuleNodeException(failureMessage, ruleChainName, ruleNodeCtx.getSelf()));
                    } else {
                        log.debug("[{}] Failure during message processing by Rule Node [{}]. Enable and see debug events for more info", entityId, originatorNodeId.getId());
                        msg.getCallback().onFailure(new RuleEngineException("Failure during message processing by Rule Node [" + originatorNodeId.getId().toString() + "]"));
                    }
                } else {
                    msg.getCallback().onSuccess();
                }
            } else if (relationsCount == 1) {
                for (RuleNodeRelation relation : relationsByTypes) {
                    log.trace("[{}][{}][{}] Pushing message to single target: [{}]", tenantId, entityId, msg.getId(), relation.getOut());
                    pushToTarget(tpi, msg, relation.getOut(), relation.getType());
                }
            } else {
                MultipleTbQueueTbMsgCallbackWrapper callbackWrapper = new MultipleTbQueueTbMsgCallbackWrapper(relationsCount, msg.getCallback());
                log.trace("[{}][{}][{}] Pushing message to multiple targets: [{}]", tenantId, entityId, msg.getId(), relationsByTypes);
                for (RuleNodeRelation relation : relationsByTypes) {
                    EntityId target = relation.getOut();
                    putToQueue(tpi, msg, callbackWrapper, target);
                }
            }
        } catch (RuleNodeException rne) {
            msg.getCallback().onFailure(rne);
        } catch (Exception e) {
            log.warn("[" + tenantId + "]" + "[" + entityId + "]" + "[" + msg.getId() + "]" + " onTellNext failure", e);
            msg.getCallback().onFailure(new RuleEngineException("onTellNext - " + e.getMessage(), e));
        }
    }

~~~

**Environment**
 * OS:  centos7
 * ThingsBoard: 3.6
 * Browser: name and version

**Comment by ashaforost** [comment]
Hi @lvxi0605 

The main issue here is the data load, and not the rule engine design. A single thingsboard node with one kafka cannot handle 600,000 data points per second. Furthermore,  600,000 dp/s is a huge and unrealistic number that even most cluster setups cannot handle. Please see our [Performance Tests article](https://thingsboard.io/docs/reference/performance-aws-instances/) for the estimated datapoint count a given architecture can handle.

Answering your questions regarding rule engine re-queuing  messages  if there's more than one relation from the rule node, this is a design choice implemented to do the following:
When a rule node has more than one outbound relation link, the initial message is acknowledged ( removed from the queue), and instead, several new identical messages are created with new message IDs(one for each relation link) since the RC message processing is done based on the message id. Afterward, each message is routed to one of the relation links, separately from others.
While this design does generate more messages for the queue to handle, and one has to be mindful about how much message splitting one adds to a rule chain, it does not create performance issues given the right architecture was chosen for the thingsboard setup.

**Comment by lvxi0605** [comment]
Thanks for your reply.
