### ISSUE TITLE
Issues with RPC Requests in ThingsBoard: User Mismatch

### ISSUE THREAD

**Issue by AlexBBS** [thingsboard/thingsboard#11859]
I'm working with ThingsBoard and encountering an issue related to RPC requests. Currently, the system seems to only recognize one user per device. Specifically, when multiple users are connected to a device and one of them makes an RPC request, the output from the "Originator Fields node" always returns the username of user 'A', even if the request was initiated by user 'B'.

Is there a way to ensure that I receive the username of the user who actually made the RPC request, rather than the one currently associated with the device? Additionally, I’ve noticed that when updating attributes, the correct data comes through without issues.

Any insights or solutions to this problem would be greatly appreciated!

I have followed the recommended approach by using the Change Originator and Originator Fields node.

**Comment by sumin-denys** [comment]
Hi @AlexBBS,

We can fetch userId from the widget and add this value to the RPC Message body. In order to do it:

- Find the widget you use (in my case, RPC Shell) in the Widgets library.

![image-20240908-141251](https://github.com/user-attachments/assets/e65ce6a8-4031-4f7a-b7dc-e59803531b41)

- Add the following line userId: self.ctx.currentUser.userId to the sendCommandRequest object.

![image-20240908-141639](https://github.com/user-attachments/assets/30a7afec-d2fa-4e03-9ec3-443d1eb7770f)

- After that, save the new widget using the button Save in the window's top right corner.

You should see the additional value inside the RPC message with the key userId during the next RPC request. The value of this key represents the user who executes the RPC Command. You can perform some operations on this value to allow or forbid RPC Request for this user.


I believe it will help you with your issue. Please let me know if you have any questions.

**Comment by AlexBBS** [comment]
Thank you for the quick response. But if this is, for example, a Toggle button, there is no specified section of code; all that is available is written below:
self.onInit = function() {
    self.ctx.$scope.actionWidget.onInit();
}

self.typeParameters = function() {
    return {
        previewWidth: '300px',
        previewHeight: '150px',
        embedTitlePanel: true,
        overflowVisible: true,
        displayRpcMessageToast: false
    };
};


self.onDestroy = function() {
}

**Comment by sumin-denys** [comment]
Hi @AlexBBS,

Here is the other way that you can use to get the userId:
- Create an Action which will execute the code below:
```
var userID = widgetContext.currentUser.userId;
var entity = entityId;

widgetContext.attributeService.saveEntityAttributes(entity,
    'SERVER_SCOPE',
    [{
        key: "user",
        value: userID
    }]).subscribe(
    function success() {
        console.log('Success');
    },
    function error(err) {
        console.error('Error', err);
    }
);
```
- This action will save userId in the device server attribute.

The option mentioned above has the next pros:
- You can easily check the last user who executes the RPC command for the specific device.
- You can combine action with any RPC widget.

Unfortunately, there isn't any other option to get the user information via the Toggle RRC widget.
If none of these alternatives work for you, the best option is to write your own widget that perfectly meets your requirements.

This article may help you with that: [Widget Development](https://thingsboard.io/docs/user-guide/contribution/widgets-development/)
If you have additional questions about this, please let me know.

**Comment by sumin-denys** [comment]
Hi @AlexBBS 

Since there hasn’t been any activity, I’m going to close this ticket for now. If you’re still experiencing the issue or need help, please feel free to reopen it or create a new one.
