### ISSUE TITLE
Thingsboard Will message

### ISSUE THREAD

**Issue by Remington-Hunter** [thingsboard/thingsboard#11922]
How is the mqtt will message of thingsboard set up? Is there any relevant documentation? Or how does thingsboard handle the situation where the device is powered off and the network is disconnected?

**Comment by Remington-Hunter** [comment]
OK, I understand, thanks for your reply!

**Comment by mykhailokornieiev** [comment]
Hi. Thank you for the suggestion. Such a feature request was previously added to our backlog for developers. While the feature request is valid, there are no plans to implement it in the nearest releases. Due to it, we've created an Idea discussion by the [link](https://github.com/thingsboard/thingsboard/discussions/14740) so that we can check the community's opinion on the necessity of reviewing the priority of implementing this feature request.
