### ISSUE TITLE
SCADA Mode - High Performance HMI Concepts

### ISSUE THREAD

**Issue by rpcai** [thingsboard/thingsboard#11942]
**High Performance HMI Concepts**

> We currently provide 60+ SCADA symbols available out of the box, with plans to increase this number to 500+ in upcoming releases. If you need a symbol that is not available, you are encouraged to create your own using the following [guide](https://thingsboard.io/docs/user-guide/scada/scada-symbols-dev-guide/).

The release of SCADA mode in 3.8.0 is really cool - to support adoption and applicability to the industrial space  when developing additional SVG smybols, could you consider 'High Performance HMI' concepts:

In practical terms, this means focusing on developing simple schematic style symbols, with limited use of colour (except for alarm/fault conditions) 

having such a library available as part of a standard release will help elevate the product to something that can easily be use profesionally, in industrial settings. 

[https://aggregate.digital/products/scada-hmi/symbol-library.html](https://aggregate.digital/products/scada-hmi/symbol-library.html)
[https://www.realpars.com/blog/high-performance-hmi](https://www.realpars.com/blog/high-performance-hmi)
[https://www.docs.inductiveautomation.com/docs/8.1/ignition-modules/vision/common-tasks-in-vision/high-performance-hmitechniques](https://www.docs.inductiveautomation.com/docs/8.1/ignition-modules/vision/common-tasks-in-vision/high-performance-hmitechniques)

*Related*
#11447

**Comment by ashvayka** [comment]
Thank you for your valuable feedback. We will review it and take it into consideration.

**Comment by ssakharova** [comment]
Hello @rpcai,

I passed all the provided information to our developers and created an internal prod ticket for them to review. 

Please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.

**Comment by yhavrysh** [comment]
Hello @rpcai,

We appreciate your interest in "High-Performance HMI" concepts, and we're pleased to inform you that we are actively working on developing a set of simple, intuitive, schematic-style symbols that use minimal color.

We've attached some images of our current designs to give you a glimpse of our direction.

We'd love to hear your thoughts!
 
![image](https://github.com/user-attachments/assets/5bb5f614-d835-4653-9d90-7a31b2c788ff)
![image](https://github.com/user-attachments/assets/8f917078-a00e-4d85-b121-74d6c8477b5f)

**Comment by rpcai** [comment]
That sort of UI is exactly what our ustomers are looking for - is there a timeline for releasing this set of symbols?
I also have a use case for electrical single line diagram representation - very simmilar to this old issue:
#60 

Consideration should also be given to ease of creating various schematics - without having to modify widgets/SVG's every time:
 - I have been playing around with creating a simple, static line connector SVG - with the intent of resizing it (i.e stretch in one dimension without affecting it's witdth) , to create a base schematic, but this approach does not get me the result I was looking for:
 
 
![image](https://github.com/user-attachments/assets/fcc4a67c-ce1c-49ee-800f-23b02b78ab01)

**Comment by yhavrysh** [comment]
Thank you for your feedback! 

We're excited to let you know that the upcoming release will feature High-Performance SCADA with symbols. 
We plan to roll it out by the end of December.

**Comment by HernanBadillaV** [comment]
Hello. 

I am an intermediate user of the ThingsBoard dashboard. I currently have the Community Edition 3.9.0 installed on a VPS. I have been researching and testing the SCADA widgets.

In this link from the ThingsBoard documentation https://thingsboard.io/docs/user-guide/scada/, it seems possible to create dashboards that connect different SCADA widgets so that they appear as a series of continuous elements (without gaps between pipes, for example), as shown in the image I have attached.

I would like to know if creating such a dashboard is possible using the ThingsBoard dashboard editor. If so, how can the elements—such as pipes, valves, tanks, etc.—be connected?

![Image](https://github.com/user-attachments/assets/0466529a-37f6-4af1-8f6a-15784513c86f)

**Comment by 77anS** [comment]
@rpcai I have the same issue, do you have fixed that issue

**Comment by 77anS** [comment]
@rpcai  I have the same issue. Have you fixed it?

**Comment by rpcai** [comment]
I chalked it up to "Not Possible" and moved on. This was in 3.8.0, I have not checked if this got any atention in 4.xx. 
Drawing schematics, as well as responsive layouts is not easy. Big players stuggle with it too (e.g Ignition)

**Comment by yhavrysh** [comment]
@77anS You're right. Since connector resizing is not yet supported, we've implemented connectors of varying lengths. For example, you can use several connectors by selecting those that best match your required length. 

![Image](https://github.com/user-attachments/assets/e3cac922-83ed-4919-b1a6-26899cf2c8f5)  

![Image](https://github.com/user-attachments/assets/b406794a-ab9c-4352-84b8-e9bd38deac2f)

**Comment by HernanBadillaV** [comment]
> [@rpcai](https://github.com/rpcai) I have the same issue. Have you fixed it?

Hello. I'm using Thingsboard CE 3.9.0 and all is about to choose the rigth layout.

![Image](https://github.com/user-attachments/assets/44872a17-9c4c-41c7-9582-95fb8dced752)
