### ISSUE TITLE
Windows server installs trendz error

### ISSUE THREAD

**Issue by HuaPing2017** [thingsboard/thingsboard#11989]
Server I have installed thingsboard version 3.8.0, installed java17
When I installed trendz1.11.0 according to the official documentation, I installed java11.
An error occurred while executing the script install.bat
details: org.springframework.boot.loader.launch.PropertiesLauncher 时出现 LinkageError java.lang.UnsupportedClassVersionError: org/springframework/boot/loader/launch/PropertiesLauncher has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0 Trendz installation failed!

**Comment by Deesthortered** [comment]
Hi @HuaPing2017, there was a bug with packages that define requirements for Trendz installation. I know the issue was fixed in the latest builds, but we haven't published it on the portal so I will share a zip file with you. You are still needed in Java 17.
https://www.dropbox.com/scl/fi/x4clopelafujzak2zdh56/trendz-windows.zip?dl=0&e=1&rlkey=wdmkp7r9d2g3jy1e3cf594swr

The best way to install Trendz is using docker-compose file, because docker images always have the latest changes.
https://hub.docker.com/r/thingsboard/trendz/tags
https://thingsboard.io/docs/trendz/install/docker-windows/
