### ISSUE TITLE
Telemetry API request returns OS Error Connection reset by peer

### ISSUE THREAD

**Issue by seenewmax** [thingsboard/thingsboard#12028]
```
final now = DateTime.now();
final startTs = now.subtract(Duration(days: startDay)).millisecondsSinceEpoch;
final endTs = now.subtract(Duration(days: endDay)).millisecondsSinceEpoch;
const int interval = 30 * 60 * 1000;
final apiUrl = AppConfig().thingsBoardApiEndpoint;
final key = dataListToGet;
final params = 'keys=$key&startTs=$startTs&endTs=$endTs&interval=$interval&agg=AVG';

final url = Uri.parse('$apiUrl/api/plugins/telemetry/DEVICE/$deviceId/values/timeseries?$params');
final response = await http.get(
url,
headers: {'Content-Type': 'application/json', 'X-Authorization': 'Bearer $token'},
);
```

`ClientException with SocketException: Connection reset by peer (OS Error: Connection reset by peer, errno = 54)`

I'm trying to retrieve data from the past 90 days to plot a graph, but the telemetry API sometimes works and sometimes returns an error. I can't retrieve all the data at once, so I divide the time period and call the API multiple times in a loop. This worked without issues until a few weeks ago, but recently the loop stops partway through. Even with a delay between API calls, the same error occurs. I'm not sure what I'm doing wrong.

**Comment by omahurin** [comment]
Hello @seenewmax,

I have tried to recreate your setup on dart and python but had no luck recreating it. I had no issues with retrieving telemetry data with the same params and can successfully make 2-3 requests per second indefinitely.

I thought that the issue could be with set limits, so I changed rates on API on the tenant level in the tenant profile as a sysadmin user to check it, but the issue was 429 too many requests, and not like in your case. Tried to limit max web socket connection to 1 and run multiple scripts in parallel, but they work just fine, waiting before the web socket will be free.

I think that the issue can be with your TB instance, which has insufficient resources, and this is causing issues. Try increasing server resources or/and adding error handling in your code to retry the same request after some time.

I also looked online, and it seems like there can be similar issues like yours on the client side with dart/flutter https://github.com/flutter/flutter/issues/35989. Maybe try to write the same script on python or something to narrow what causes the issue.
