### ISSUE TITLE
 is it possible to customize the 'account profile' page on a customer account?

### ISSUE THREAD

**Issue by strangerCatLv** [thingsboard/thingsboard#12040]
[](url)**Description**
hi guys, I have a question.
is it possible to customize the 'account profile' page on a customer account?

**Environment**
 * ThingsBoard: version 3.8.1

_________________________________________________________
![Screenshot 2024-11-13 153330](https://github.com/user-attachments/assets/9d54b5ae-06e9-4a8d-a0dc-bc7141057a08)
__

**Comment by dealnat** [comment]
Hi,
What kind of customization do you want?

**Comment by strangerCatLv** [comment]
> Hi, What kind of customization do you want?

I want a menu to change user photos, change passwords, change usernames only.
![WhatsApp Image 2024-11-14 at 07 53 30_cde6ff02](https://github.com/user-attachments/assets/1b1128ff-eed2-46ef-8362-1aeda4d75cab)

**Comment by strangerCatLv** [comment]
wow thanks a lot dealnat! and how to add to be able to change/update profile photo? and hide 'home dashboard' menu??
![WhatsApp Image 2024-11-15 at 08 08 26_d1cc071e](https://github.com/user-attachments/assets/6fe9aa0e-5b74-467f-8562-9731be53fe37)

**Comment by dealnat** [comment]
Hi,
For now, adding a profile picture to the Thingsboard is not possible; however, the developers have a ticket in the backlog to implement this feature.
Also, hiding Home menu from custom menu isn't possible since TB 3.8.0 after Custom menu redesign, but I created a ticket for the developers to get this option back.

After the features will be delivered they will appear on the [release notes](https://thingsboard.io/docs/reference/releases/) page

**Comment by strangerCatLv** [comment]
thanks a lot dealnat!
