### ISSUE TITLE
[Question] What do use as Docker HEALTHCHECK

### ISSUE THREAD

**Issue by apachler** [thingsboard/thingsboard#12170]
**Component**

* thingsboard/tb-js-executor
* thingsboard/tb-node
* thingsboard/tb-mqtt-transport
* thingsboard/tb-http-transport
* thingsboard/tb-vc-executor
* thingsboard/tb-web-ui

**Description**

Since many supporting tools (curl, nc, wget, ..) are missing in the container image i have no idea how to implement a useful healthcheck.
Also, is there an application endpoint where some can do a solid healthcheck with? Because, checking for the running process is not suitable and does not give any hint if the application itself is working as expected.

**Environment**

* OS:  SLES 15, Docker Swarm
* Thingsboard: 3.7.0

**Comment by trikimiki** [comment]
there are no built-in means to "ping" endpoints so you need to use some workarounds, e.g. https://github.com/thingsboard/thingsboard/issues/11254, or re-builld images with `curl` installed

about endpoints - specified services (except for `js-executor`) utilize [Spring Boot Actuator](https://docs.spring.io/spring-boot/docs/2.1.7.RELEASE/reference/html/production-ready-endpoints.html) endpoints, you can use those
as for `js-executor`, a dedicated healthcheck endpoint was implemented: `/livenessProbe`
also, there are other endpoints available, see these [kubernetes liveness probes](https://github.com/search?q=repo%3Athingsboard%2Fthingsboard-ce-k8s+httpget&type=code)

**Comment by apachler** [comment]
Thanks for clarification, I will give that a try!

**Comment by apachler** [comment]
Are you sure that the Spring Boot Actuator endpoint really work?
I have tried to install curl manually in the tb-node container and executed `curl http://localhost:8080/actuator/health` and got a big HTML response but not the expected health response. Is there something i am missing?

**Comment by trikimiki** [comment]
please refer to [Spring Boot docs](https://docs.spring.io/spring-boot/docs/2.1.7.RELEASE/reference/html/production-ready-endpoints.html) - this is a native feature of this web server

for me, in order to enable "health" endpoint on monolith ThingsBoard install, I needed the following changes [here](https://github.com/thingsboard/thingsboard/blob/master/application/src/main/resources/thingsboard.yml#L1906) (or if installed - here at `/usr/share/thingsboard/conf/thingsboard.yml`):
```
# General management parameters
management:
  endpoint:                                                                     # <----------- add
    health:                                                                     # <----------- these
      enabled: "true"                                                           # <----------- ones
  endpoints:
    web:
      exposure:
        # Expose metrics endpoint (use value 'prometheus' to enable prometheus metrics).
        include: '${METRICS_ENDPOINTS_EXPOSE:info,health}'                      # <----------- here as well
  health:
    elasticsearch:
      # Enable the org.springframework.boot.actuate.elasticsearch.ElasticsearchRestClientHealthIndicator.doHealthCheck
      enabled: "false"
```
![image](https://github.com/user-attachments/assets/b874db37-867f-4b3e-9eaa-7f7fbc46850e)

transport microservices also serve spring boot, so it should be configurable there in a somewhat similar fashion
also, in case you dont want to change configuration - you can use `/actuator/info` instead as it is available by default

**Comment by apachler** [comment]
Thanks, i was able to implement all health checks!
