### ISSUE TITLE
Custom Action From Bar Chart

### ISSUE THREAD

**Issue by strangerCatLv** [thingsboard/thingsboard#12223]
**Description**
hello I have a question. is it possible to make an action on the bar chart widget, if the bar is clicked it will move the page.

**Environment**

 * OS:  docker
 * ThingsBoard: version 3.8.1 PE
![image](https://github.com/user-attachments/assets/ed7ca3ad-db61-40be-acb5-b910723f7514)

**Comment by mykhailokornieiev** [comment]
Hi. We've created an Idea discussion #15982 so that we can check the community's opinion regarding this request. This is done to identify the most desirable features for the community with further analysis of this data and its transfer to developers for further review. Even if the feature request is rejected, this information will still be useful for further planning the platform's development, and the decision may be reconsidered in the future.
