### ISSUE TITLE
i18n post-processing function in attributes card

### ISSUE THREAD

**Issue by Backdraft007** [thingsboard/thingsboard#12279]
**Is your feature request related to a problem? Please describe.**
I'm translating a dashboard. I try to translate values in the post-processing function in the Attributes card widget.
Label is no problem, but the returned value is not translated. I don't know if it is a bug or the feature isn't implemented yet.

**Describe the solution you'd like**
Custom tranlsation in the post-processing function in Attributes card widget

**Screenshots**
![Screenshot 2024-12-17 at 13-59-55](https://github.com/user-attachments/assets/7d731b32-a770-4d25-86c6-979b624e3164)
![Screenshot 2024-12-17 140238](https://github.com/user-attachments/assets/71384a50-81fb-4592-94e3-dff16d699fbb)

_____________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies)), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by mykhailokornieiev** [comment]
Hi. I was able to reproduce this issue.
However, this issue is not reproducible for the Entities Table and Timeseries Table widget:
![image](https://github.com/user-attachments/assets/102fe7c6-cb3b-4ca5-9641-42b00c288c07)
In this case, it can be used as workaround.
I've added a ticket in our backlog for developers. There's no set timeframe for this improvement; however, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions and fixes to the platform in subsequent releases.

**Comment by mykhailokornieiev** [comment]
Hi @Backdraft007 
I'm glad to inform you that this improvement was implemented in v4.3 and v4.2.1.1
