### ISSUE TITLE
related entity data node: multiple source attribute key 

### ISSUE THREAD

**Issue by ZYMCao** [thingsboard/thingsboard#12273]
**Component**

 * UI

**Description**
![image](https://github.com/user-attachments/assets/f8fa65fe-8514-4109-b778-b2182cc75aed)

Here I can fetch an attribute whose key is "maxSpeed", 
but I want to fetch all attributes whose key name begins with "max". I wonder if there is some approach more general I can try here instead of inputting them manually. 

Basically in the future I shall add more attributes whose name begins with "max", and I may forget to come back to the rule node and add them.

**Comment by devaskim** [comment]
At the moment there is no such feature

**Comment by ZYMCao** [comment]
> At the moment there is no such feature, only creating custom rule node

Understood. Thx.

**Comment by ZYMCao** [comment]
> At the moment there is no such feature, only creating custom rule node

Understood. Thx.

**Comment by omahurin** [comment]
Hi @ZYMCao,

Currently, it can't be achieved the way you described, but I have added the feature of wildcards for enrichment nodes to our backlog for developers (PROD-5253). I am closing this issue for now. If you need to update the status of the prod ticket, please feel free to comment on this issue.

Please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions and fixes to the platform in subsequent releases.

**Comment by mykhailokornieiev** [comment]
Hi. We've created an Idea discussion #15978 so that we can check the community's opinion regarding this request. This is done to identify the most desirable features for the community with further analysis of this data and its transfer to developers for further review. Even if the feature request is rejected, this information will still be useful for further planning the platform's development, and the decision may be reconsidered in the future.
