### ISSUE TITLE
Cannot use Japanese in custom menu item names

### ISSUE THREAD

**Issue by h-takado** [thingsboard/thingsboard#12271]
We use TB PE 3.8.1.

When Japanese is set for the item name of the custom menu, "???? ."

In previous versions of custom menus written in JSON format, Japanese was also available.

Please tell me how to use Japanese for menu items.

**Comment by idealissst** [comment]
Hello,
Can you provide steps to reproduce the issue?
Please refer to the template below for a detailed description of the issue.

**Describe the bug**
A clear and concise description of what the bug is.
**Your Server Environment**

* [Live Demo](https://demo.thingsboard.io/)
* [ThingsBoard Cloud](https://thingsboard.cloud/)
* own setup
  * Deployment: monolith or microservices
  * Deployment type: deb, rpm, exe, docker-compose, k8s, ami
  * ThingsBoard Version
  * Community or Professional Edition
  * OS Name and Version
**Your Client Environment**

**Desktop (please complete the following information):**
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]
**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
**Expected behavior**
A clear and concise description of what you expected to happen.
**Screenshots**
If applicable, please add screenshots to help explain your problem.
**Additional context**
Please feel free to add any other context about the problem here.

**Comment by h-takado** [comment]
Installed on cloud server by docker

ubuntu server 24.04 LTS
PE v3.8.1 PE

White labeling->custom menu, if I enter a menu item name other than English or numbers, the menu display shows ?????? The menu display becomes ???????

In the example, if the menu item name is “123あいう456”, the actual menu display will be “123???456”. The actual menu display will be “123”.

In the previous PE version, when using JSON to customize the menu, the menu is correctly displayed as “123あいう456”.
![menu_customize_bug](https://github.com/user-attachments/assets/674062f6-a453-4e5d-ad31-66b8e4764516)

**Comment by idealissst** [comment]
Thank you for your report! This issue has been confirmed. I've added this request to our backlog PROD-5316. 
I am closing this issue for now. If you need to update the status of the prod ticket, please feel free to comment on this issue.
Please refer to our release notes to find out more about new features and bug fixes: [Release Notes](https://thingsboard.io/docs/pe/reference/releases/).
If you have any further questions, please feel free to create a new issue or reopen this one.

**Comment by idealissst** [comment]
Thank you for your report! This issue has been confirmed. I've added this request to our backlog PROD-XXXX. 
I am closing this issue for now. If you need to update the status of the prod ticket, please feel free to comment on this issue.
Please refer to our release notes to find out more about new features and bug fixes: [Release Notes](https://thingsboard.io/docs/pe/reference/releases/).
If you have any further questions, please feel free to create a new issue or reopen this one.
