### ISSUE TITLE
How to delete alarm events from the log in the widget?

### ISSUE THREAD

**Issue by AndriiHavrylyak** [thingsboard/thingsboard#1261]

**Comment by macedolfm** [comment]
Looking forward for this too, tryed to delete them directly from the table "alarm" and now I a get a "java.lang.NullPointerException" when oppening the device alarms. There is a unknown relationship somewhere, I just do not know where.

**Comment by macedolfm** [comment]
OK, found the answer for doing it directly on the database:

DELETE the alarm you want to get rid on the table "alarm"

Clean up the related tables:

DELETE FROM audit_log WHERE entity_type='ALARM' AND entity_id NOT IN (SELECT id FROM alarm);

DELETE FROM relation WHERE to_type='ALARM' AND to_id NOT IN (SELECT id FROM alarm);

Not sure, but you may need to restart the thingsboard service as it holds cached data on some tables

**Comment by vparomskiy** [comment]
API for deleting alarms was added in the latest version.

**Comment by fishskinlau** [comment]
I checked AlarmController.java and I found that the delete alarm action does not call "checkAlarmId". Is it intended?

**Comment by hamburml** [comment]
@vparomskiy Any idea how a alarm can be removed via dashboard?

**Comment by mbari** [comment]
I was looking for this function too

**Comment by hamburml** [comment]
As @vparomskiy said delete API exist. The AlarmController and BaseAlarmService supports this (https://github.com/thingsboard/thingsboard/pull/1431/files).

The alarmService doesn't implement this! https://github.com/thingsboard/thingsboard/blob/master/ui/src/app/api/alarm.service.js

I found that because I used the alarmService in a widget.

Is this behavior intentional? @ashvayka

**Comment by hamburml** [comment]
I've added a PR https://github.com/thingsboard/thingsboard/pull/2266

With this change I can delete alarms via alarm widget.
