### ISSUE TITLE
Telemetry data of the same device at the same time can not be saved.

### ISSUE THREAD

**Issue by felix-ma** [thingsboard/thingsboard#1277]
I see that telemetry data is stored in the PostgreSQL database through entity_type, entity_id, key, ts as the primary key. And the exact value of TS is milliseconds.
If the same entity was collected at the same time and received multiple data at the same time, it was found that it would be wrong. Database insertion exception.
![_15429423043731](https://user-images.githubusercontent.com/30289895/48927869-b6334d80-ef14-11e8-958a-bbde35132b0b.png)
How to solve this problem?

**Comment by felix-ma** [comment]
Our database team tells us that PostgreSQL can solve the primary key insertion exception by "upset".
At present, all saving operations in source code are through the save method of JPA.

**Comment by gopirathnamt** [comment]
This is happen because they have key and ts as primary key .
i too faced this issue ,
You can solve this issue by adding datafield (bool_v,long_v,str_v,dbl_V) to primary key .
But there is another problem will arise , because when if the datafield is single field , we can easily use this method . But it has 4 field so when a data comes it stores the value in respective field and left others as null . 

so we make all 4 fields primary key , when the data comes we store the data in one field and left others as null , (**_but the problem is we cant left a primary key field as NULL_** ) .
so this method wont work . so its difficult to store the value of same ts .

**Comment by volodymyr-babak** [comment]
you should not use the same key for the logically different time-series keys.
You can easily with a help of a rule engine modify data payload and store time-series under different keys, based on your business logic.
Please consider **script** node as a starting point, with a help of this node you can change your payload in a custom way:
https://thingsboard.io/docs/user-guide/rule-engine-2-0/transformation-nodes/#script-transformation-node
