### ISSUE TITLE
What's the json format of the Additional info when add relation from Tenant？

### ISSUE THREAD

**Issue by qwyinxiang** [thingsboard/thingsboard#1284]
I want to create a relation from tenant to asset, I add the relation by click the "+" button, and there need a json format string. I fill the blank with below:
{
    "entityType":"DEVICE",
    "id":"d3ffecc0-f215-11e8-8bb7-0ff628627331"
}
The page throw an error message like below:
![image](https://user-images.githubusercontent.com/31084798/49067683-afcc0b00-f25f-11e8-9f3c-4a9db91b1486.png)

**Comment by vparomskiy** [comment]
Error is thrown because you did not specify 'To Entity' field.

There are 3 fields on this form:
1. Relation Type (you have this field configured)
2. To Entity (in your case, this field is empty)
3. Additional info 

'TO' side of the relation is not parsed from the JSON provided in 'additional info' field. You need to specify it explicitly.

**Comment by qwyinxiang** [comment]
The Tenant's ralation has no To Entity field.There is no place to fill this field.

![image](https://user-images.githubusercontent.com/31084798/49122200-64147280-f2ee-11e8-87b5-a2e3b349747f.png)
But other entities has the To Entity field. such as the CUSTOMER, ASSET, DEVICE.
![image](https://user-images.githubusercontent.com/31084798/49122032-bb661300-f2ed-11e8-94a7-2a34073ab028.png)
