### ISSUE TITLE
Setting up ssl to access UI via https

### ISSUE THREAD

**Issue by BarlowHall** [thingsboard/thingsboard#1294]
Hi,

how do I set up TB to allow users to access it via https and without having to add the 8080 port number at the end of the domain name?

I'm currently running TB 2.1.3 on AWS ubuntu 16.04 on a T2.mini instance

Thanks in advance for your assistance.

**Comment by souhaiebtar** [comment]
this is not related to project directly, you can do it by using nginx in front of thingsboard,

**Comment by vparomskiy** [comment]
you can find more details in this thread (nginx/apache2 + let's encript)
https://github.com/thingsboard/thingsboard/issues/1164

**Comment by ashvayka** [comment]
Hi @BarlowHall , yes, it is possible to do this via those changes, but usually it is easier to setup a load balancer with the HTTPS certificate, since you may still need the LB when you plan cluster deployment. See the docker compose script for cluster deployment with the HA Proxy LB for more details: https://thingsboard.io/docs/reference/msa/#deployment
