### ISSUE TITLE
Implement backpressure

### ISSUE THREAD

**Issue by janbols** [thingsboard/thingsboard#1391]
Currently there's no backpressure when ingesting iot data. This means the system is inherently unstable when overloaded. You can limit this effect by using rate limiters as is currently done, but this means you either need to set a safe lower bound or be sure the the system will not get under abnormal stress (which is pretty much impossible in practice).

**Comment by janbols** [comment]
Hi @ashvayka , thank you for the explanation. 
As you probably are well aware, there are a number of options available when it comes to implementing backpressure:
1. use one of the libraries that implement reactive streams like rxJava or akka streams
2. do it yourself by implementing some sort of feedback channel

None of the options seem easy to implement in the current thingsboard architecture so I understand that this is not a trivial task. My first guess would be to look at akka streams b/c akka is already used as a means to handle messages and akka streams has grown quite mature in offering capabilities to mix with regular akka actors.

**Comment by ashvayka** [comment]
Since we use Kafka as a streaming platform we are unsure that akka streams will be a good choice in our case. I would like to maintain one abstract layer for a queue and at least one implementation. Kafka is ok but we will add Kinesis as well once we will have some time to do this. I will add more comments here soon.

**Comment by ashvayka** [comment]
The preliminary plan is to read N messages from Kafka and push it to the rule engine. Rule engine will acknowledge processing of those N messages and once all messages are acknowledged we will read next pack of messages. We are going to implement several ack strategies:
1) ignore unprocessed messages and move forward (for instances with no SLA where issues with rule chain configuration or processing can be ignored)
2) retry (possibly with timeout and max retry count)
3) retry constantly until they are processed.
In all cases, messages are stored in Kafka and new messages are not going to be processed until the old one are processed. There might be cases when some already acknowledged messages are processed again (in case all pack is failed to process). We also plan to implement the ability to have checkpoints in processing to offload the main queue and also some ways to separate queues by tenants. 

In all cases, we plan to use a distributed persistent queue (Kafka or Kinesis) instead of single JVM solutions like RxJava.

**Comment by ashvayka** [comment]
Hi @janbols . This is a note that we are now progressing on the back-pressure implementation and it will be part of 2.5 which is planned to be released in April 2020.

**Comment by janbols** [comment]
Hi, I'm looking forward to this!
Best regards
Jan

**Comment by ashvayka** [comment]
We have released v2.5. See the following docs:
https://thingsboard.io/docs/user-guide/rule-engine-2-0/overview/#message-processing-result
https://thingsboard.io/docs/user-guide/rule-engine-2-0/overview/#rule-engine-queue
https://thingsboard.io/docs/user-guide/rule-engine-2-0/overview/#rule-engine-statistics
(the dashboard is available here: https://github.com/thingsboard/thingsboard/blob/master/application/src/main/data/json/demo/dashboards/rule_engine_statistics.json
