### ISSUE TITLE
Mail  Sending  in SpringBoot Application 

### ISSUE THREAD

**Issue by srinivasvadla** [thingsboard/thingsboard#1439]
Hello ,
I am facing this issue 
Could not connect to SMTP host: smtp.gmail.com, port: 587;  I  changed to other port also though it is not resolving 

configuration in application.properties file is .

spring.mvc.view.prefix=/pages/
spring.mvc.view.suffix=.jsp

server.port=9090

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=srinivasvadla01@gmail.com
spring.mail.password=password here 
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=false
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

Thank you,
Srinivas.

**Comment by vparomskiy** [comment]
1. What do you see in the log file? there should be an error description. Most often the reason is that security config in your Gmail account restricts connection form external services.

Did you try to use this tutorial for configuring SMTP?
https://thingsboard.io/docs/user-guide/ui/mail-settings/#step-32-gmail-configuration-example

**Comment by srinivasvadla** [comment]
Thank you so much. It's got solved.
