### ISSUE TITLE
Inactivity Timeout Alarms - Not Updating

### ISSUE THREAD

**Issue by ghost** [thingsboard/thingsboard#1454]
Hi there,

I'm trying to understand if an inactivity timeout alarm get's updated periodically once it has been raised. Looking at our experimentation, it seems they do not get updated.

We are trying to implement the following following rule:

1. Raise and inactivity alarm after defined timeout period and set alarm count to 1 (in alarm details).
2. When the inactivity alarm is updated increment the alarm count by 1
3. When the alarm count reaches 3, raise an incident in OpsGenie via the Thingsboard REST API node.

We understand that we could simply set the timeout to 3 times the real timeout value and get the same effect.

However this rule is to track when a sensor's telemetry data is lost in the LoRaWAN network, as we'd like to count the number of lost frames for each device.

Is this something we should be able to implement using the rule's engine and alarm details?

**Comment by vparomskiy** [comment]
Inactivity event triggered when there is no data from a device during last N seconds. I do not understand how you plan to connect this event with your business condition `telemetry data is lost in the LoRaWAN network` or `frame lost`. Maybe in your case, you can guarantee that device submits telemetry every X seconds, and if no data was received in X seconds, then it is a `frame lost`. Am I right?

Here is a tutorial that shows how to update alarm count in alarm details:
https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/create-clear-alarms-with-details/

Note that you need to clearly define a condition when alarm is cleared.

**Comment by enviroeye** [comment]
Yes this is correct, we expect data every 30 minutes. We can set the inactivity timer to say 35 min and trigger and alarm. However this creates a lot of noise, since its not uncommon for the LoRaWAN to lose a frame here and there.

We are instead interested if we miss three readings is a row, and this probably means the sensor is offline. We would set the timeout to 1 hour and 35 minutes and trigger and alarm then.

However we still wish to count this number of times a frame is lost (even its 1 or 2), so if we simply set the timeout to 3 times the sending interval plus 5 minutes, like a suggested before, we are not going to track the times it misses just a single frame or two, which is important as it regularly losing a single frame could be a sign of poor wireless signal etc.

I've followed the tutorial, but have not had success with getting the count working properly. I'll gather some more data and screenshots and post

**Comment by jh83** [comment]
I do not know which lorawan operator that you are using. But if we take TTN for example then they include the "frame counter" in the MQTT message. 

By using the frame counter you should be able to determine how many packages you loose during transmission.

**Comment by enviroeye** [comment]
All good, we figured out how to do it using the delay node. When the first alarm is raised after the inactivity timeout occurs, the device is considered in a 'hold-down' state. The delay is started which is 3 x the length of inactivity timeout. When the delay ends we check to see if the device has come active again, if it hasn't the alarm is moved from minor to major and we send an SMS.

**Comment by enviroeye** [comment]
The only problem is it doesn't seem like the delay node can be set using msg or metadata. As each device time has a different inactivity timeout (and hold time) we have had to add a delay node for each device type we operate and put a switch in to switch the chain to the correct delay node based on which device (and its type) has raised the alar

It would be a great feature to be able to dynamically set the length of delay based on msg or metadata

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
