### ISSUE TITLE
Use dashboard to write device parameters

### ISSUE THREAD

**Issue by abrasat** [thingsboard/thingsboard#163]
We are using the dashboard to display device process data, by connecting to a opc-ua server which controls the device. We would like to be also able to change the device settings by writing some device parameters. This does not seem possible right now. Is this a dashboard issue or a opc-ua gateway issue ? Is there any fix planned, to allow write data access over the opc-ua server ?

**Comment by ashvayka** [comment]
Hi, this feature is not available at the moment not because of technical issues. We just had no time to implement this and now working on 1.3 release which is mostly related to other items: asset and alarm management, entity relations, dashboard states. 
You are welcome to contribute this feature and if you are willing to do so we can help with implementation tips.

**Comment by abrasat** [comment]
Is this feature missing in the opc-ua gateway ? Would be possible to use GTIO widgets to set OPC-UA boolean variables ?

**Comment by awcullen** [comment]
@ashvayka Could you share your implementation tips? Thanks.

**Comment by vparomskiy** [comment]
OPC-UA integration can be used for submitting downstream messages.
