### ISSUE TITLE
Thingsboard Disconnects every 330 seconds

### ISSUE THREAD

**Issue by colognebroker** [thingsboard/thingsboard#1665]
I am using 2.3.1 CE Version
I connect devices via nodered ( mqtt ) to thingsboard via gateway-device
Every 330 seconds thingsboard disconnects the connection to nodered
so i have to connect all of my devices again ...
What ist the reason

**Comment by colognebroker** [comment]
How I connect my devices
1) I created in Thingsboard a new device of type "Gateway"
2) I did not add an extension
3) with nodered i connect devices v1/gateway/connect through the gateway Access Token in mqtt node
3) i sen telemetry via v1/gateway/telemetry

everthing works
but every 330 seconds the mqqtnode is disconnected from thingsboard
every device is disconnected

this iss a big mess

**Comment by colognebroker** [comment]
So Thingsboard is not usable if you plan to youse nodered as middleware

**Comment by colognebroker** [comment]
Solution found !
You have to change TB_TRANSPORT_SESSIONS_INACTIVITY_TIMEOUT this Parameter in thingsboard.yml and TB_TRANSPORT_SESSIONS_REPORT_TIMEOUT

I think this ist a fault in Thingsboard, because there i send enough data to the devices every second 
I did not understand this Timeout but it helps

**Comment by ChristianLutz** [comment]
@colognebroker What timeouts did you set to solve this problem?

**Comment by colognebroker** [comment]
some hours calculatetd in seconds

**Comment by ChristianLutz** [comment]
Hello @colognebroker 

the default settings are in `ms` `TB_TRANSPORT_SESSIONS_INACTIVITY_TIMEOUT` are set to 30000 and `TB_TRANSPORT_SESSIONS_REPORT_TIMEOUT` is set to 30000.

So every 30s it will be checked if a session hasn't been used the last 300s. I didn't find any code where hours will be used. Do you have any hint for me.

**Comment by colognebroker** [comment]
you have to change the second counter to 30000000000

Udo Faulhaber
Mit bestem Gruß vom Iphone

**Comment by ChristianLutz** [comment]
Hello @colognebroker (Udo)

I haven't found any issues in the code regarding wrong conversion between ms and hours. I could be wrong. With your suggested high number you -almost- disabled the session available test. I am not sure if this is what you want.

In my case I send telemetry data every three second. And the connection stays active several hours without a problem. But as I sad before, I had set the following configuration #1210. 

Kind regards

**Comment by bychenxa** [comment]
I got the same issue with v2.4.1. 
If you restart the thingsboard process, the issue dispears. But it will occur again a few days later.

**Comment by paolofrs** [comment]
I don't know if it may be of any help, but I had the same issue and this is how I check out which was the cause of disconnection. 

So, here it is. In my case, after **~5 min** in TB disconnect the device. Below the log (obtained using filters on metadata in the Rule Engine to select only `CONNECT` and `DISCONNECT`events from specific devices that uploads data via tb-gateway every 10 to 30 min):

    vps-thingsboard | 2020-05-27 13:11:23,880 [ForkJoinPool-3-worker-15] INFO  o.t.rule.engine.action.TbLogNode -
    vps-thingsboard | Incoming msgType:
    vps-thingsboard | "DISCONNECT_EVENT"
    vps-thingsboard | Incoming message:
    vps-thingsboard | {"active":false,"lastConnectTime":1590584754056,"lastActivityTime":1590584754087,"lastDisconnectTime":1590585083858,"lastInactivityAlarmTime":1590584773949,"inactivityTimeout":10000}
    vps-thingsboard | Incoming metadata:
    vps-thingsboard | {"deviceType":"IO-Controller","scope":"SERVER_SCOPE","deviceName":"LT-33222-Home"}

**NOTE** One can convert the event timestap via [this converter](https://currentmillis.com/) for example

As stated by @colognebroker :clap: this is due to the `TB_TRANSPORT_SESSIONS_INACTIVITY_TIMEOUT`set in `thingsboard.yml` file. **Indeed 300000 ms are exactly 5 min**. 

You can verify this by this equation:

    lastDisconnectTime - lastActivityTime - incativityTimeout 

The result should match `TB_TRANSPORT_SESSIONS_INACTIVITY_TIMEOUT`. Referring to the above message the result is:

         1590585083858 - 1590584773949 - 10000 = 300000

That matches the thingsboard default settings (which is my case). Changing the default to an appropriate value fixed the issue.

**Comment by peter146d** [comment]
Any update ?
