### ISSUE TITLE
Sort order for properties in widgets

### ISSUE THREAD

**Issue by danibjor** [thingsboard/thingsboard#1674]
When adding attributes (or timeseries) to show in a widget, they are shown in the order they are added. If you add scripts to attributes for post processing, it’s a pain to come in later and add a new field, if the customer wants it as the first column in the view. 
Would be nice if you could sort the properties added, either by setting a sort order on the property’s advanced tab, or by drag’n’drop on the data page when you edit a widget. 

![Skjermbilde 2019-04-30 kl  11 50 50](https://user-images.githubusercontent.com/2149381/56954143-64839480-6b3e-11e9-896c-1be9861ca30a.png)

**Comment by pgrisu** [comment]
Hello danibjor.
I inserted what you request in my github thingsboard fork. You can find my commit here https://github.com/pgrisu/thingsboard/commit/e157f76fcf055594eadd9a73d3ec5e6913a022ab
I didn't create a PR on thingsboard repo because such feature is already present in the PE edition, so PR will be rejected.
Data keys may be reordered/sorted by clicking over dataKey label, drag it and release in new position

**Comment by danibjor** [comment]
Awesome. I'll have a look at it. Thanks a lot for sharing.

**Comment by pgrisu** [comment]
Danibjor may be you can be interested also to this https://github.com/pgrisu/thingsboard/commit/76e5aa24fa80b7bf6c8dbf8508353f0002aabfd0 additional commit over the previous one.
This commit add full flexibility in dataKeys creations allowing arbitrary mixed timeseries and attributes keys that joined to the above drag-and-drop capability let you to free choose and change dataKeys order in your tables
Anyway I opened a PR https://github.com/thingsboard/thingsboard/pull/1704 on thingsboard repo hoping to see such features in next tingsboard releases....

**Comment by PovitruliaV** [comment]
Hi @danibjor,
Is this issue still relevant?
