### ISSUE TITLE
Can't login to demo NoHostAvailableException

### ISSUE THREAD

**Issue by Natsumi96** [thingsboard/thingsboard#1720]
![rrrr](https://user-images.githubusercontent.com/17880853/57797475-f658e780-7763-11e9-9694-86a6e8b2e589.PNG)

Hello there.
I can't login to my live demo account (ThingsBoard was working fine a few hours ago). When it will be fixed?

Thanks in advance.

**Comment by thriveni221** [comment]
I seem to have the same issue.  Waiting for the fix.

**Comment by Tauvic** [comment]
Servers sometimes available for some minutes an then the same problem again. Also tried REST API with same results.

**Comment by lalitjoshi86** [comment]
I am also facing the same isse.  Did you got any solution?

**Comment by lalitjoshi86** [comment]
My live server was down due to this error.  Later I had to install a fresh server.

**Comment by Karabiy** [comment]
It is so because it requires to have some downtime on upgrades for the latest versions or to apply some configurations. 
It is an okay. 
In case if such an error is related to the production server of yours, you need to go for the current tb instance of yours and check logs, so that it can be caused because of the error or the host server of those is down and then apply the troubleshooting protocol.
