### ISSUE TITLE
Grouping interval behaviour

### ISSUE THREAD

**Issue by Antyneutrinoo** [thingsboard/thingsboard#1727]
I receive cumulative energy readings of which I store differential energy readings in the database, and I have created two graphs based on that data:

- daily (Realtime - last day) power used in 1 hr grouping interval - this works well - sum of readings between say 13:00 and 14:00 is shown in form of bar starting at 13:30.

- monthly (Realtime - last 30 days) power usage in 1 day grouping interval - this is my trouble - each bar shows sum of energy recevied between 2:00 am of a day till 2:00 am of a next day, and the bar starts at 14:00 hrs of each day (so the mid point).

**My question is: can a realtime graph be controlled so that each bar shows precisely daily readings (between 0:00 hrs and 0:00 hrs)?** 

I can configure a history graph that way, as I am able to control the starting point, but end point would need to be updated each time to current moment (actually it would be good if the end point could be set to a future point of time).

**Comment by Antyneutrinoo** [comment]
Happy aniversary!

**Comment by erwinberkouwer** [comment]
I have the same issue.

**Comment by tonyuh** [comment]
Same issue here, can't seem to find a "time of day" config. I understand real-time won't probably work since changing the time won't be real-time anymore but in history tab there should be "time of day" too not just number of days. For example selecting last 7 days in history tab is the same as real-time tab if there is no time of day preset.

Right now the only way to make this sort of work is to use history tab and set it to Interval of Current Month.

**Comment by tonyuh** [comment]
> Hi I’ve previously discussed this question with our developers, and we’ve reached the conclusion that this problem is related to many factors: server location, browser’s time interpretation and the main thing is that there is no agreement (coordination) on the change to summer/winter time for such cases. You can try to change "time of day" config by setting up either different timezone in widget/dashboard settings, or timezeon of your browser/machine. However, this is a valid improvement that I’ve already added to our backlog. Once the product team reviews this ticket, we’ll post an update on when this improvement could be delivered if they decide to add it to the product. Please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.

Thanks for your answer, I could find any timezone setting on the widget/dashboard which should solve my issue for the time being. I cannot change the timezone of the browser/machine since we need the time to be correct in other applications. Could you please point me in the right direction, where is this timezone setting?
