### ISSUE TITLE
Autonomous management

### ISSUE THREAD

**Issue by e-infotech** [thingsboard/thingsboard#1734]
Hi,

I want to work on the management of the IoT network of a smart city. Does ThingsBoard provide autonomous device management such as software maintenance and update, device provisioning and authentication, device monitoring and diagnostics and performance evaluation?

**Comment by kldjaff** [comment]
After reviewing all the doc of thingsboard, I didn't find any clue of those features you mentioned. 
Device management including detection (access token pair), health check (device monitoring and diagnostics and performance evaluation), software management (upgrade, reset, debug etc), are not there. Those features are belong to some other PaaS functions like kubeedge. You may want to combine them together.

**Comment by e-infotech** [comment]
I couldn't find any either, but my intention for asking was that I considered extending it and adding these features to it, so I wanted to be sure that ThingsBoard does not offer these capabilities.

**Comment by kldjaff** [comment]
As I understand the architecture. Device provisioning is belonging to edge node IaaS services, which you might find some other data center management tools like forman or something else to do the edge node provisioning. For device software maintenance, authentication, monitoring & remediation, diagnostics etc. I consider they are belonging to the PaaS for edge part.

Think about this, if there are thousands of devices in order to prevision them, you have to build:
- image repo for pick up right images
- management database for manage all the devices meta data/configuration/ip address etc.
- remediation service to automate the remediation process
- a support team for sure.

If you want to manage their softwares, you have to have flavors for each devices and pick up the software installations accordingly. mostly likely it is an orchestration of most of the internet company is doing right now. 

Even there isn't  such amount of the devices, you have to make the flow auto.

To separate the functions of thingsboard and some IaaS or PaaS capabilities, is something I am thinking and plan to see how.

Why not to use different systems to control different purpose to make the system easily :D

I would like to work with you together on this part as well.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
