### ISSUE TITLE
Last telemetry does not match the most recent value according to timestamp

### ISSUE THREAD

**Issue by lswanderleygit** [thingsboard/thingsboard#1769]
I'm sending the following dataset through the REST API
```json
[
    { "ts": 1559673838361, "values": { "temp": 1 } },
    { "ts": 1559673902031, "values": { "temp": 2 } },
    { "ts": 1559673963942, "values": { "temp": 3 } },
    { "ts": 1559674025028, "values": { "temp": 4 } }
]
```
#### Expected behavior

Receber como telemetria mais recente <temp: 4> visto que é o valor que tem o timestamp mais recente.

#### Real behavior

Whenever I send that same dataset they are overwritten in the database, since the timestamp is the same, so far so good!

But what is not normal is that each sending the last telemetry presented is different, ie, instead of always receive as last telemetry temp = 4, sometimes I receive 4 others I receive 1, 2, 3 or 4.

Is there any way to always receive the last timestamp as the last timestamp?

### PS
I'm using ThingsBoard version 2.3.1 but this problem also ocorrence in the version 2.2.0

**Comment by ChristianLutz** [comment]
Hello @lswanderleygit 

I do experience exact same problem. But I am not sure if it is a bug or on purpose. Because last telemetry could be interpreted diverse. 
1. It could what you expect the value with the latest ts.
2. But it could also mean the telemetry last uploaded. (And this is how it behaves currently)

It is easy to reproduce. Just create two dataset, one containing just a single temp and a current timestamp. Then you create a second dataset with an old timestamp. If you query the latest telemetry you will always get the second uploaded one.

Workaround.
Instead of using the endpoint for the last telemetry use the endpoint getTelemetries. Use a timerange between 0 and current timestamp and limit your result to one. Now you will get the latest ts.

kind regards

**Comment by lswanderleygit** [comment]
Hello @ChristianLutz thanks for the help.

How would I use this solution to show the ultimate telemetry in a digital gauge?

And where do I get access to the getTelemetries endpoint?

Thanks for the help!

**Comment by ChristianLutz** [comment]
Hello @lswanderleygit 

you can't. This is only available via REST. 
See here https://cloud.thingsboard.io/swagger-ui.html#/telemetry-controller

kind regards

**Comment by lswanderleygit** [comment]
I understand, I think there should be a way to control this behavior.

**Comment by ChristianLutz** [comment]
I agree. In my opinion this is a bug. Just my 2c.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
