### ISSUE TITLE
Feature request: automatic purge of old records from Events and Audit Logs tables

### ISSUE THREAD

**Issue by albtrentadue** [thingsboard/thingsboard#1795]
As far as I know, there is no way to limit "event" and "audit log" database tables size in Thingsboard (using version 2.2.0). I experienced this using Postgres as db, but I guess this applies also when Cassandra is used.
This is somewhat related to issue #1491, but I think that "event" table is more risky because is filled under the hood. Moreover, if one leaves rules in "debug mode" in some chain (see also issue #1497), the event table gets flooded with records and the possibility to fill up the OS file system becomes significant, especially in small devices.
Of course there are ways to handle table data retention outside Thingsboard, but in general the possibility of unlimited data growth is an inherent weakness, especially when it relates to internal, non-user data tables.

**Comment by Ultrazombie** [comment]
Please use the TTL function, which is set up in the thingsboard.yml file.
https://thingsboard.io/docs/user-guide/install/config/#sql-configuration-parameters
SQL_TTL_EVENTS_EVENTS_TTL
SQL_TTL_EVENTS_DEBUG_EVENTS_TTL

 But we recommend that you use thingsboard.conf instead of editing the thingsboard.yml file,
add there in the format, e.g.:
export SQL_TTL_EVENTS_EVENTS_TTL = 0 # Value set in seconds. 0 - records are never expired.
