### ISSUE TITLE
Thingsboard on AWS logs out frequently

### ISSUE THREAD

**Issue by smsachin** [thingsboard/thingsboard#1800]
Hi,
My thingsboard AWS ec2 instance logs out frequently and I have to keep signing back in every 10 mins or so in my browser even when I am actively using it in browser. What is the issue here?
Thankyou

**Comment by mp-loki** [comment]
In your /etc/thingsboard/conf/thingsboard.yml file you can extend JWT token expiration timeout

**Comment by smsachin** [comment]
Where do I access this file? I tried myinstance_ip_address_or_url.com/etc/thingsboard/conf/thingsboard.yml
And can anyone edit those files in PE edition as it is not opensource.

**Comment by Karabiy** [comment]
you can access those easy after creating an ssh connection, those are being used for the configurations only
after you can access this on etc/thingsboard/conf/thingsboard.yml 
you can use the nano utility to apply changes 
it also can be so because of the user agent configurations of yours, please, make sure that they are an okay with the local storage and cookies for the ThingsBoard of yours
