### ISSUE TITLE
Saving shared attributes should have option to not notify the device.

### ISSUE THREAD

**Issue by fotis400** [thingsboard/thingsboard#1809]
If the device is subscribed to the attributes topic, it receives a new message each time an attribute value is changed.

However there are cases that the actual cause of the attribute write is the device itself (due to rule engine itself).

Imagine the following scenario:
1. A device sends a message to TB.
2. The rule engine processes this message, and writes a new value to a shared attribute.
3. The attribute is send back to the device.
4. Because of the "new" attribute value, the device starts processing again, sending a new message.
5. Execution goes back to step 1, running endlessly.

There should be an option in save attributes node of the rule engine, to control whether the save operation will trigger a notification towards the device or not.

If this is an actual update to the attribute, the device should be notified.
If this is a rule updating an attribute because of a device message, there is no need to send the message again.

**Comment by PavankumarTalla** [comment]
Hello, I think that happens when the shared attributes and client attributes have the same key names. Is it true?

**Comment by fjpanag** [comment]
@PavankumarTalla No this is not related.

I just need to change the shared attributes while having the option whether the device will be notified. This should be an option in save attributes node.

**Comment by ashvayka** [comment]
Hi @fotis400 . Thank you for reporting this. It took us a while to notice this issue, but we will try to fix ASAP. The original intention was that the device gets a notification about shared attributes update only when the update happens via REST API and not from the device itself. So, the idea of the fix/improvement is the following:

1) If the update of the shared attributes is originated by the user's REST API call - we push it to the device (same as before).
2) If the update arrives from the device, we will not push it back to the device by default. For this, the Device Actor will add a special metadata field to the attribute update message "notifyDevice":"false". The Rule node will look for this metadata field and will not send notification to device if it is present and set. In all other cases, for backward-compatibility, we will send notification to device. 

@YevhenBondarenko please implement this changes. (See DefaultSubscriptionManagerService.onAttributesUpdate for more details)

**Comment by fotis400** [comment]
@ashvayka Great!

I would also propose a checkbox in save attributes node to control whether the device will be notified. This will simplify things, and make it obvious that this option exists.

**Comment by YevhenBondarenko** [comment]
#3487

**Comment by falmanna** [comment]
Hi @YevhenBondarenko 

I was debugging an issue where saving shared attributes updates originated from devices are sent back to the device even if the notifyDevice box is unchecked in the `save attribute` node.

I tried to trace your PR and see what is wrong and it seems that the problem is in [this](https://github.com/thingsboard/thingsboard/blob/11d263b05e61f43966032c3963828cd17fb65cac/rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/telemetry/TbMsgAttributesNode.java#L74) line
`config.getNotifyDevice() || StringUtils.isEmpty(notifyDeviceStr) || Boolean.parseBoolean(notifyDeviceStr)`
This will always resolve to `true` unless we add `notifyDevice = false` to the message metadata, which defeat the purpose of the notify device check box in the node configs.

I am not sure about the benefit of this condition, so I can't tell exactly what the correct condition should look like.

NOTE: I am running version `2.5.6`

**Comment by YevhenBondarenko** [comment]
Hi @falmanna 

We add "notifyDevice = false" to the metadata  in the [transport layer](https://github.com/thingsboard/thingsboard/blob/11d263b05e61f43966032c3963828cd17fb65cac/common/transport/transport-api/src/main/java/org/thingsboard/server/common/transport/service/DefaultTransportService.java#L301).

**Comment by falmanna** [comment]
@YevhenBondarenko Thanks for the quick response.

Well, in my case, I am doing some post-processing on device telemetry data and if some conditions are met, I update the device shared attribute. And as you can see, there is no "notifyDevice = false" when initializing telemetry messages, so I will need to modify the message metadata in a transformation node. 

Also, even if I added that in the code or in a transformation node, I still think that the final decision should be to the node configuration value, and if we want to change that for certain messages, then we can add a "notifyDevice = true". Not sure if this makes sense as I am still going through the internal details of the system.

**Comment by falmanna** [comment]
Hi @YevhenBondarenko 
After some time investigating the transport layer, I think this condition makes sense more from a logical point of view.
We will depend on the node configuration unless it is stated otherwise in the message metadata.

`StringUtils.isEmpty(notifyDeviceStr) ? config.getNotifyDevice() : Boolean.parseBoolean(notifyDeviceStr)`

Please let me know if I missed something.

**Comment by YevhenBondarenko** [comment]
Hi @falmanna 
Your condition does not fit backward compatibility.
Maybe someone always wants to notify devices but this condition will change the behavior which was in previous versions.

**Comment by falmanna** [comment]
Hi @YevhenBondarenko 
Yeah, I didn't think about backward compatibility. 
But I guess if the `save attribute` node config is defaulted to "notify", there shouldn't be a problem since the original behavior was to always notify. Correct?

**Comment by YevhenBondarenko** [comment]
Hi @falmanna 

Yes, you are correct.
