### ISSUE TITLE
cannot connect to Thingsboard demo  server

### ISSUE THREAD

**Issue by ChristosPalisidis** [thingsboard/thingsboard#1917]
Hello people!
I was connected and capable of tranfering data few days ago.Without changing anything in my code, i am unable to connect now.I am coding in arduino IDE.

The demo server and TOKEN is being given correctly, although the tb.connect(host,token) returns false.
The only thing that changed those days, is that i was transfered in a new location with a different netwotk.Is there any issues with security policies etc and if yes, how can i overcome this?
Thank you in advance!

**Comment by Karabiy** [comment]
It can be so because you are using a ThingsBoard instance on our cloud that is intended to familiarize with its functionality and may not transmit all of the messages due to high server load.
So that I recommend you proceed with an on-premise installation in a case if the high payload and reliability are important for you on this step of studying the ThingsBoard products.

You may refer to this link regarding the ThingsBoard installation: 
https://thingsboard.io/docs/installation/
Also, make sure you have no firewall restictions for the current network you are in.
