### ISSUE TITLE
Main and sub-dashboards 

### ISSUE THREAD

**Issue by Elgaatoo** [thingsboard/thingsboard#1945]
Hello, 

is it possible to create links between dashboards (main and sub dashboards) in the community edition? For example I want to switch between three dashboards that display different information. By clicking on different sections on the main dashboard I can switch to the other sub-dashboards. And If I click on a section on one sub-dashboard I return to the main dashboard. 

Thx.

**Comment by pgrisu** [comment]
Yes, of course
You can do it using action tab in the widget settings panel
Depending of widget type, you can choose several 'action sources' (icon-buttons on widget header, row-click, html-element click...) to trigger a dashboard (or sub-dashboard) change. You can also trigger a custom function in order to execute some custom specific actions (like open dialog, show computed results, save data...)
Hope this help you. If so, please close this issue
