### ISSUE TITLE
Update 2.4.0 > 2.4.1 failed

### ISSUE THREAD

**Issue by morpheus000** [thingsboard/thingsboard#2018]
hi,
i just tried to update from 2.4.0 to 2.4.1, 
Following error occurred:
```
 sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=2.4.0
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
 ===================================================
 :: ThingsBoard ::       (v2.4.1)
 ===================================================

Error creating bean with name 'jpaTimeseriesDao': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'spring.datasource.hikari.maximumPoolSize' in value "${spring.datasource.hikari.maximumPoolSize}"
ThingsBoard upgrade failed!
```

I followed this  guide:
https://thingsboard.io/docs/user-guide/install/upgrade-instructions/#upgrading-to-241

OS: CentOS 7.6
DB: Cassandra

**Comment by Backdraft007** [comment]
Hi,
is it possible that you forget to change DB settings in the thingsboard.yml ?

**Comment by morpheus000** [comment]
Hi,
no that wasn't the problem.
The package installer didn't asked to merge the thingsboard.yml, so i had to non-merged config-files in the thingsboard directory and the update failed.
```
NOTE: Package installer will ask you to merge your thingsboard configuration. It is preferred to use merge option to make sure that all your previous parameters will not be overwritten.
Please make sure that you set database.entities.type and database.ts.type parameters values (in the file /etc/thingsboard/conf/thingsboard.yml) to “cassandra” instead of “sql” in order to upgrade your cassandra database:
```

**Comment by madper** [comment]
I was never been asked about the merge...
I have to modify the fresh installed thingsboard.yml every time.

**Comment by fjpanag** [comment]
Indeed, config merging is not working. At least for yum.

Every time, you need to manually merge the files.

**Comment by morpheus000** [comment]
Now i get this error if a user try's to login:

2019-09-23 16:08:33,074 [http-nio-0.0.0.0-8080-exec-8] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
java.lang.IllegalArgumentException: Cannot find cache named 'securitySettings' for Builder[public org.thingsboard.server.service.security.model.SecuritySettings org.thingsboard.server.service.security.system.DefaultSystemSecurityService.getSecuritySettings(org.thingsboard.server.common.data.id.TenantId)] caches=[securitySettings] | key=''securitySettings'' | keyGenerator='' | cacheManager='' | cacheResolver='' | condition='' | unless='' | sync='false'

**Comment by IoTThinks** [comment]
> I was never been asked about the merge...
> I have to modify the fresh installed thingsboard.yml every time.

I use Ubuntu version with hybrid database.
And no asking for merge, too.
I only changed TYPE to cassandra once. Then run the upgrade script. Then TB 2.4.1 is ok.

ts:
    type: "${DATABASE_TS_TYPE:cassandra}" # cassandra OR sql (for hybrid mode, only this value should be cassandra)

If I update both to cassandra. Then the website can not be up.

**Comment by SerhiiLutchenko** [comment]
During upgrade, after extracting .deb file you have to merge manually new and old thingsboard.conf and thingsboard.yml files. As I understand you didn't merge them so you had default .yml file with database postgres, that's why you get this error.

**Comment by ban2derlog** [comment]
Hi, on versions 3+ during update procedure there is ability to choose keep old or replace by new .conf file. Additionally, there is a Compare variant, but merging still needs to be done by yourself.

Thingsboard.yml file will be always replaced by new one, because all additional or overwriting defaults settings need to be done by editing **_thingsboard.conf_** file.

**Comment by Wifialarm** [comment]
Hi, I'm also failed at upgrade. 3.3.4.1 -> 3.4

:: ThingsBoard ::       (v3.4.0)
 ===================================================

Error creating bean with name 'thingsboardInstallService': Unsatisfied dependency expressed through field 'entityDatabaseSchemaService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: 
Error creating bean with name 'sqlEntityDatabaseSchemaService': Unsatisfied dependency expressed through field 'installScripts'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: 
Error creating bean with name 'installScripts': Unsatisfied dependency expressed through field 'ruleChainService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: 
Error creating bean with name 'baseRuleChainService': Unsatisfied dependency expressed through field 'ruleChainValidator'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: 
Error creating bean with name 'ruleChainDataValidator': Unsatisfied dependency expressed through field 'tenantService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: 
Error creating bean with name 'tenantServiceImpl': Unsatisfied dependency expressed through field 'customerService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: 
Error creating bean with name 'customerServiceImpl': Unsatisfied dependency expressed through field 'assetService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: 
Error creating bean with name 'baseAssetService': Unsatisfied dependency expressed through field 'assetValidator'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException:
 Error creating bean with name 'assetDataValidator': Unsatisfied dependency expressed through field 'tenantService'; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException:
 Error creating bean with name 'tenantServiceImpl': Requested bean is currently in creation: Is there an unresolvable circular reference?
ThingsBoard upgrade failed!

Assume that this is due to choosing "N" on package installer
This invisible merge option is distracting. Do we need to do that by fmerge?

By the way, how it is possible to restore TB to previous working version?

**Comment by ban2derlog** [comment]
@Wifialarm this git issue is related to version 2.4.1 which is out of date for 3 years.
please, create a new issue with this.
also these errors don't provide any info about your issue, unless if you have done changes to PostgreSQL manually before upgrade.
restoring can be proceeded only from PostgreSQL backups.
