### ISSUE TITLE
Image Map Widget - Marker not showing

### ISSUE THREAD

**Issue by mde2017** [thingsboard/thingsboard#2057]
Hello everyone,

I'm currently trying to set Marker positions in a Image Map widget:

![Unbenannt](https://user-images.githubusercontent.com/25298332/66191799-6a524880-e68f-11e9-905a-370299cafe15.PNG)

The positions for the Marker are defined by shared attributes xPos & yPos (tested Integer & Double type):

![image](https://user-images.githubusercontent.com/25298332/66191977-c9b05880-e68f-11e9-876d-ee697dd3627b.png)

But I can't still see no marker on the map. What am I doing wrong here?

(Note: ThingsBoard version 2.4.1)

Thanks in advance

**Comment by vvlladd28** [comment]
Hello, shared attributes values must be in the range 0 to 1.0

**Comment by mde2017** [comment]
Hello, 
many thanks, that worked! 
I had expected the attributes to be pixel values.

**Comment by Ccorreia08** [comment]
Hi, I am having the same problem but with server attributes instead of shared attributes. In my case the shared attributes are Latitude and Longitude for each single point I want to display  in a map. I believe these are not restrained to 0-1 values. 
Yet I still cannot see the markers in the map. Any ideas what the problem would be? Do I need create a rule chain for this? If so, any ideas on how to set it up are most appreciated. 
![thingsboard](https://user-images.githubusercontent.com/83451656/116687126-f97f2980-a9b4-11eb-85f4-762518c9a439.jpg)


Thanks,
![things2](https://user-images.githubusercontent.com/83451656/116686936-c3da4080-a9b4-11eb-800e-1532e6c39386.jpg)

**Comment by diffuzi** [comment]
Let's try it with "longitude" and "latitude" as server attribute. These do not have to be btw 0 and 1, you are right.
