### ISSUE TITLE
Certbot ACME issue

### ISSUE THREAD

**Issue by DavidMicallef86** [thingsboard/thingsboard#2080]
Hi I tried to enable HTTPs as per instructions - https://thingsboard.io/docs/user-guide/install/pe/add-haproxy-ubuntu/

In the last step certbot is failing with the following error:

root@ubuntu-ThingsBoard:~# certbot-certonly --domain dashboard.redlore.com --email dmicallef@redlore.com
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
An unexpected error occurred:
The client lacks sufficient authorization :: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports 
v2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.
Please see the logfiles in /var/log/letsencrypt for more details.

**Comment by m-krasikov** [comment]
Check your certbot version, it might be 0.31 or above.

sudo apt-get update
sudo apt-get install software-properties-common
sudo add-apt-repository universe
sudo add-apt-repository ppa:certbot/certbot
sudo apt-get update
sudo apt-get install certbot

**Comment by adminRedlore** [comment]
Thanks will try it and revert back

**Comment by coastalplain** [comment]
This issue has been killing my [AWS 2.4.2.1 BYOL AMI](https://aws.amazon.com/marketplace/pp/B07V8S6JLG) installs for the last few days (that is, while I was trying to figure out how to make it work, I kept killing my installation).

I found that I needed to do the following based on @jmorahan [suggestion](https://community.letsencrypt.org/t/update-your-acme-client/82941/9)
`sudo apt-get update
sudo apt-get full-upgrade`
I then used the [post-installation steps](https://thingsboard.io/docs/user-guide/install/pe/aws/#post-installation-steps) adding --agree-tos to the command (i.e.) and refreshing haproxy:
```
sudo certbot-certonly --domain smth.yourcompany.com --agree-tos --email support@yourcompany.com
sudo haproxy-refresh
```

**Comment by RossBlackstock** [comment]
Hi guys,

I managed to get past the "sudo certbot...." step only to be stopped by the next step: "sudo haproxy-refresh".

I get this message: 
cat: /usr/share/tb-haproxy/letsencrypt/live/README/fullchain.pem: Not a directory
cat: /usr/share/tb-haproxy/letsencrypt/live/README/privkey.pem: Not a directory
Job for haproxy.service failed because the control process exited with error code.
See "systemctl status haproxy.service" and "journalctl -xe" for details.

Anyone run into this issue?

**Comment by JasonFarque** [comment]
> Anyone run into this issue?

I have. Not found a solution yet. I wish the Thingsboard folks would comment on it and perhaps suggest a fix.

**Comment by m-krasikov** [comment]
Hi,
It becomes because of README file in /usr/share/tb-haproxy/letsencrypt/live/
Despite the fact that there is a string in haproxy-refresh script that goes through README file when creating cert for domains in HAProxy format, sometimes it happens.
I will check this script.
Now the solution is to delete README files
rm -rf /usr/share/tb-haproxy/letsencrypt/live/README*
rm -rf /usr/share/tb-haproxy/certs.d/README*

and run haproxy refresh again.

**Comment by JasonFarque** [comment]
> Now the solution is to delete README files
> and run haproxy refresh again.

I tried this after I received the message and was surprised when it did not fix the problem. I continued to get the error even after deleting the README files. I can't remember if I every tried to delete the README files before running the script. Probably not.

**Comment by ramams** [comment]
Hi,

Any update on this issue? I have the same problem with installing a Maker license on AWS EC2 instance. I tried upgrading the certbot, but got the issue mentioned in the comment above: https://github.com/thingsboard/thingsboard/issues/2080#issuecomment-580589765. Has anyone found resolution for this issue?

Thanks,
Ramamurthy

**Comment by saikumaru** [comment]
it fails for me too, I am trying to install on AWS EC2 as per steps outlined here https://thingsboard.io/docs/user-guide/install/pe/add-haproxy-ubuntu/

> sudo service haproxy restart

Fails with

>Job for haproxy.service failed because the control process exited with error code.
See "systemctl status haproxy.service" and "journalctl -xe" for details.

>journalctl -xe
parsing [/etc/haproxy/haproxy.cfg:53] : 'bind *:443' : unable to load SSL private key from PEM file '/usr/share/tb-haproxy/default.pem'


>sudo certbot-certonly --domain your_domain --email your_email
An unexpected error occurred:
Error creating new order :: Cannot issue for "12345.compute-1.amazonaws.com": The ACME server refuses to issue a certificate for this domain name, because it is forbidden by policy

**Comment by dcolley** [comment]
I had the same issue on AWS BYOL. The solution was to upgrade certbot
```
sudo apt-get upgrade certbot
sudo certbot-certonly --domain tb.domain.com --email support@domain.com
sudo haproxy-refresh
```
The server does not redirect `http` to `https`, but that's another issue

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
