### ISSUE TITLE
Defined configuration directive 'tbAnalyticsNodeAggregateLatestConfig' is not available

### ISSUE THREAD

**Issue by GrayCygnus** [thingsboard/thingsboard#2095]
I just upgraded successfully to the PE version 2.4.1 (using [this guide](https://thingsboard.io/docs/user-guide/install/pe/upgrade-instructions/)) and am trying out the Analytics Rule Nodes.

I tried adding a `AggregateLatest` but in the Dialog Window the following error/warning is shown:

![errorTB](https://user-images.githubusercontent.com/7274943/66872506-68c43280-ef63-11e9-8a52-9806d96ebfbc.png)

This confused me as, apparently, it fails to show the same Dialog options as shown in the Aggregate Node Example page: https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/aggregate-latest-data/ 

**Am I missing some steps or things here?** Any guidance is highly appreciated, and if any other detail is needed please ask and I'll gladly provide it.

**Comment by GrayCygnus** [comment]
After some days, the issue "magically" went away, and now I don't see the error and furthermore can see the GUI for configuring the Analytics node.

**Comment by johansmolinski** [comment]
For those coming to this issue by googling, I just came across a similar problem after upgrading to a new version of thingsboard. The issue seems to be that there are old cached files in the browser. Using another browser, it works fine. I suppose the cached files will "magically" disappear after their TTL for me too.
