### ISSUE TITLE
Gateway Provisionig

### ISSUE THREAD

**Issue by MirkoUgoliniDev** [thingsboard/thingsboard#2114]
Hello All,

I'm developing a home automation system and an Android App to manage the devices Provisioning. I managed to add Customers, "normal" devices, and dasboards  Using REST API.
I can't figure out how to add a Gateway type device. it's possible?

**Comment by IoTThinks** [comment]
You add Device as usual.
There is a "check" to mark a gateway.

![image](https://user-images.githubusercontent.com/29994971/68267210-37cbaf00-0084-11ea-9463-2b3734422ab3.png)

**Comment by Karabiy** [comment]
The device type is an abstraction which is being set on for the device, so that you can easily apply the filtering for those. You can set those in the data converter, in case if you are using the ThingsBoard integration feature and also on the creation of the device as it is being mentioned in the previous comment.
Please, refer for this link for the device basics documentation: https://thingsboard.io/docs/user-guide/ui/devices/

Also, for this link regarding the integration data converters: https://thingsboard.io/docs/user-guide/integrations/#data-converters
