### ISSUE TITLE
Error "Terminating application due to critical License Error ACTIVE_INSTANCES_CAPACITY_EXCEEDED(104)"

### ISSUE THREAD

**Issue by wujun** [thingsboard/thingsboard#2221]
I bought a Maker license from thingsboard and installed PE on docker(macOS v10.14.6, Docker  v19.03.4). I followed the instructions to run the professional edition but I got the error  "Terminating application due to critical License Error ACTIVE_INSTANCES_CAPACITY_EXCEEDED(104)" I DON'T know how to handle it. Here are
 my log files: tb-license.log and thingsboard.log

[thingsboard.log](https://github.com/thingsboard/thingsboard/files/3908200/thingsboard.log)
[tb-license.log](https://github.com/thingsboard/thingsboard/files/3908199/tb-license.log)

**Comment by AlexDoanTB** [comment]
Hello @wujun 
By default a single license cannot be installed on two or more instances simultaneously. The key is bound to the instance ID (physical server/VM/container/image). 
Once you had activated the key, it was tied-up. Any other attempts to re-use the key would be failed if actual instance is not deactivated.  ThingsBoard restricting any attempts to ‘mis-use’ the key.

In order to up and run your environment, please:

1. Stop TB service

2. Deactivate actual instance via the License portal (Subscriptions — Details — Manage instances — Deactivate particular instance)   

3. Delete instance-license.data file.

$ docker ps
you will get ID of your docker container, for example 09625616dba4
Connect to container console
$docker exec -it 09625616dba4 bash
You will see console bash, for example
root@09625616dba4:/#
Now run command to delete instance-license.data file
root@09625616dba4:/# rm -f /usr/share/thingsboard/bin/instance-license.data
Then deattach from  container console
root@09625616dba4:/# exit
And restart container ('mytb' is the name of your container in default installation)
$ docker stop mytb
$ docker start mytb

4. Run TB service

**Comment by wujun** [comment]
Thanks a lot! @AlexDoanTB , I corrected my license problem according to your advice. I can't find any error message in tb-license.log file now. But I got PSQLException that caused my tb service still failed. I searched thingboard.log file and found the following error message:
"Caused by: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections."
anyway, I have very appreciated for your grateful help and thanks again.
[tb-license.log](https://github.com/thingsboard/thingsboard/files/3912268/tb-license.log)
[thingsboard.log](https://github.com/thingsboard/thingsboard/files/3912272/thingsboard.log)

**Comment by Nathan-ma** [comment]
Hello and a little help here. 
I don't have docker running on my AWS, therefore I think my version of Thingsboard PE was installed for Ubuntu Server only.

I do understand all I have to do is to delete this instance-license.data file but I can't find it neither in the folder (/usr/share/thingsboard/bin/) nor by using `sudo find ./ -name "instance-license.data` in the root folder of the machine

Here is the content of my folder : 
![image](https://user-images.githubusercontent.com/11060905/86308397-7bfd5800-bbef-11ea-9d8f-221db8f0f1a6.png)

**Comment by AlexDoanTB** [comment]
Not very clear @Nathan-ma . Is this a clean installation? Were you using ThingsBoard (the license key) somewhere else?

**Comment by Nathan-ma** [comment]
I fixed it already! But thank you for the quick response! All I had to do was deactivate the license.

**Comment by CooL16** [comment]
The issue has been resolved.

**Comment by e1ke** [comment]
If you are struggling to find /usr/share/thingsboard/bin/instance-license.data, please check, if you are also as stu*id as me an overread your env-variable 
TB_LICENSE_INSTANCE_DATA_FILE: /data/license.data
in your docker-compose.yaml. This line of course changes the place of your instance data. So delete it with 
rm -f /data/license.data
and then...voila :)

P.S.
I came across multiple Errors like 
Terminating application due to critical License Error ACTIVE_INSTANCES_CAPACITY_EXCEEDED(104)
License Error: INVALID_LICENSE_CHECK_SECRET(107) - Invalid secret request sequence number!
and
License Error: INSTANCE_NOT_FOUND(105) - Instance not found!

hope this helps
