### ISSUE TITLE
ERROR o.t.s.d.s.BasicSubscriptionService - Maximum allowed devices limit reached!

### ISSUE THREAD

**Issue by andrwtse** [thingsboard/thingsboard#2256]
I only have 41 devices and purchased prototype up to 100 devices, but in the log still showing this, any help will be great: 
ERROR o.t.s.d.s.BasicSubscriptionService - Maximum allowed devices limit reached!

**Comment by AlexDoanTB** [comment]
> I only have 41 devices and purchased prototype up to 100 devices, but in the log still showing this, any help will be great:
> ERROR o.t.s.d.s.BasicSubscriptionService - Maximum allowed devices limit reached!
Hi. Please, refer this issue to TB support team (via Contact us form). How many devices do you see on UI? How many devices are persisted in your DB?

**Comment by ashvayka** [comment]
What kind of database are you using?

**Comment by andrwtse** [comment]
Postgres

**Comment by Karabiy** [comment]
Please, check your database in order to make sure that count of your devices is less than 100. You may go with the following commands:
sudo su - postgres /
\l - to check the name of database of yours. Commonly it's "thingsboard"
\c - to connect to your database
\dt - to list all the tables
select * from device;
So, it might look like
"""
sudo su - postgres
\c thingsboard
select * from device;
"""
The devices which are created under the customer and the other tenants are also included for those.
