### ISSUE TITLE
Switch control parseValue function doesn't work

### ISSUE THREAD

**Issue by mojabyte** [thingsboard/thingsboard#2313]
https://github.com/thingsboard/thingsboard/blob/92c1374a3f31a31b9492a192d65a740b67352c16/ui/src/app/widget/lib/rpc/switch.directive.js#L223

Switch control widget parseValue function doesn't work. I think if telemetry data equals 0, JavaScript takes it as false; and doesn't enter the `if` to run the parseValue function.

**Comment by wenzul** [comment]
Should already be fixed by https://github.com/thingsboard/thingsboard/pull/2958

**Comment by IvoLeal72** [comment]
It is not working again, the function gets called if the telemetry value is already a boolean, if it is a string, it doesn't get called.

**Comment by ScottJMarshall** [comment]
The routine invoking the parse value function first calls JSON.parse on the value.  If it's not a valid JSON string it won't invoke the function because the result of JSON.parse is `null`.  Something like `true` is valid JSON, but "orange" isn't.  The parse value function will get invoked If you return a value like `{"status": "on"}` instead of `on`.  Not saying it should or shouldn't work this way, but that's how it's coded up at the moment.

**Comment by sumin-denys** [comment]
Hi @mojabyte,

If I understand you correctly, this problem is related to the function below:
![image](https://github.com/user-attachments/assets/c8cabe3f-b877-4cab-8c7a-c017eb40e060)
I performed tests on the current ThingsBoard version 3.8.1, and this function works properly with the code from the screenshot and the following payload:
```
{
  "value": 1,
  "attribute2": true,
  "attribute3": 42.0,
  "attribute4": 73,
  "attribute5": {
    "someNumber": 42,
    "someArray": [1,2,3],
    "someNestedObject": {"key": "value"}
  }
}
```
I can assume that this error was resolved in one of our previous releases. Could you please confirm this on your end?

In case the function mentioned above is not the issue that you encountered, could you please add additional info about this error, such as:
1. Code of parseValue function.
2. Payload that you used when the error occurs.
3. Any additional information that may help to resolve this issue.

**Comment by sumin-denys** [comment]
Hi @mojabyte,

Since there hasn’t been any activity, I’m closing this ticket for now. 
If you’re still experiencing the issue or need help, please feel free to reopen it or create a new one.

> Please refer to our release notes to find out more about new features and bug fixes: [Release Notes](https://thingsboard.io/docs/pe/reference/releases/).
