### ISSUE TITLE
Custom Language

### ISSUE THREAD

**Issue by tpharaoh** [thingsboard/thingsboard#2514]
If I want a language not currently supported, can I just upload the JSON somewhere on my server

locale.constant-en_US.json  << renaming for my language

**Comment by Karabiy** [comment]
for now, you can only change the languages being supported, so that you can create your custom language on their base. 
you can also share the translation which is created on your side with the ThingsBoard officials via the mail, or create the pull request on your side, so that those, after the review, may become officially supported 
you may refer to this regarding the contact us the form of the ThingsBoard officials: https://thingsboard.io/docs/contact-us/
