### ISSUE TITLE
How to send custom/other message type from static widget?

### ISSUE THREAD

**Issue by IoTopenTech** [thingsboard/thingsboard#2522]
I am developing an static widget with just a button.

When the user clicks that button I want to receive a custom (or Other) message type in the Rules Chain to filter and log it.

![imagen](https://user-images.githubusercontent.com/52624907/76699897-145be500-66b2-11ea-8fee-000075a7951a.png)

Kind regards

**Comment by dajtxx** [comment]
I'd like to know this too. Or how to invoke a rules chain directly without going through the root rules chain.

**Comment by Shedaim** [comment]
Anyone has an answer to this?

**Comment by dajtxx** [comment]
I think we ended up using a widget to set a server side attribute and then catching the set attribute message in the rules chain and transforming it into an rpc call or MQTT post depending on the destination device.

The original problem we had was trying to send a message to an MQTT queue by transforming an rpc call message. The rpc widget got upset because it never received an ack for the rpc call.
