### ISSUE TITLE
How to close Export option on Dashboard List page?

### ISSUE THREAD

**Issue by yeduy** [thingsboard/thingsboard#2609]
Hello,

I want to remove export option from dashboard list page for customers as you can see in image. There couple of options in settings tab but I coulnd't find about exporting. Could you help me please?

![image](https://user-images.githubusercontent.com/59412389/79014732-2c6d3a00-7b74-11ea-9aa2-a3d0ee5550f0.png) ![image](https://user-images.githubusercontent.com/59412389/79014879-73f3c600-7b74-11ea-890d-e6de9a797bfe.png)

**Comment by ecmap** [comment]
I am also looking for this blocking feature, which should not be shown to customers. Please tell me how to block it. If there is no such feature, I hope Thingsboard can update this feature.

**Comment by LukasPeer** [comment]
Push

**Comment by kxiopl** [comment]
Agree. There should have been an option. Unless it was intentionally not considered.

**Comment by PovitruliaV** [comment]
Hi @yeduy 
If I understand you correctly, you want clients to see the dashboard. So because of this, clients will also be able to export a dashboard. For now, there doesn't exist any way to disable the export function has read permission. 

I will add your suggestion to our backlog(PROD-1127) for our developers to review this suggestion and decide on its implementation. There's no set timeframe for our dev reviews; however, please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions to the platform in the subsequent releases.

Best regards
