### ISSUE TITLE
Create a alpine version of thingsboard dockerfile?

### ISSUE THREAD

**Issue by annerajb** [thingsboard/thingsboard#261]
It seems that jre 8 is available as alpine.
Would it be possible to also create alpine tags of thingsboard?

**Comment by volodymyr-babak** [comment]
hi, at the moment we don't have plans to support this version, but you can do it for yourself if needed
You can change **_TB_RPOJECT_DIR/docker/tb/Dockerfile_** to use **openjdk:8-jre-alpine** instead of **openjdk:8-jre**
To make docker image simply execute commad: **"make build"** inside **TB_RPOJECT_DIR/docker/tb/** folder

**Comment by ashvayka** [comment]
@annerajb feel free to submit PR and we can review it. Maybe this can be an alternative container.

**Comment by ikulikov** [comment]
Closing due to an inactivity.
