### ISSUE TITLE
Is there any documents about how to work with eclipse or IDEA

### ISSUE THREAD

**Issue by lovekun** [thingsboard/thingsboard#262]
Hi:

I encounter many errors when I import thingsboard into eclipse. However, I don't know how to fix them.

The document is all about building at all kinds of platform. I want to know whether there is any documents about how to work with eclipse or IDEA

**Comment by mp-loki** [comment]
Hi @lovekun . There is no such document right now. However, it is pretty straightforward to import the project to Idea (I use the Community edition and it works fine). Did not try it with Eclipse though. 
I would recommend the following steps:
1. Checkout the thingsboard/thingsboard repository from git
2. Run mvn clean install from command line - this will ensure that all generated-sources are created and your local .m2 repository has all the dependencies in place. It takes time because the tests are heavy. Give it ~20 minutes or more.
3. Import the maven project to Intellij Idea (I guess Eclipse should work too).
4. Make sure you mark the the target/generated-sources/protobuf/java and target/generated-sources/protobuf/grpc-java as Generated Sources Root in the subprojects where these folders were created. Off top of my head you have to do it in application and extensions-core subprojects, probably somewhere else too.
(Right click on the folder -> Mark Directory As -> Generated Sources Root in idea or Build Path -> Add to build path in Eclipse).

Hope it helps.

Regards,
VS

**Comment by ashvayka** [comment]
Since no other comments I am closing this one.
