### ISSUE TITLE
getAlarms java rest api does not support optional searchStatus and status

### ISSUE THREAD

**Issue by ganzuoni** [thingsboard/thingsboard#2628]

**Comment by ganzuoni** [comment]
Still does not work in v3

**Comment by ganzuoni** [comment]
Setting all parameters, template url is wrong because of the call to:
   private String getUrlParams(TimePageLink pageLink, String startTime, String endTime) {
        String urlParams = "limit={limit}&ascOrder={ascOrder}";
        if (pageLink.getStartTime() != null) {
            urlParams += "&" + startTime + "={startTime}";
        }
        if (pageLink.getEndTime() != null) {
            urlParams += "&" + endTime + "={endTime}";
        }
        return urlParams;
    }

that adds "limit" instead of "pageSize" and "page"

**Comment by awoSYS** [comment]
I feel like this issue has been addressed in commit 91e0a77afd5d34ab324681ceee3db2c164cebd37 by @AndrewVolosytnykhThingsboard . However, this commit breaks the URL format, since it generates something like this:
`http://dedddocker03:8092/api/alarm/{entityType}/{entityId}?fetchOriginator={fetchOriginator}pageSize={pageSize}&page={page}` (mind the missing `&` before `pageSize`)
Would be great if the getAlarms() method could be fixed in the next release! Thanks for your work!
