### ISSUE TITLE
Dataconverter without Integration

### ISSUE THREAD

**Issue by david114** [thingsboard/thingsboard#2632]
Hi,

In my Project, I don't want to use the MQTT-Integration module that acts like an client to my device/application.
I want to send my device telemetry data directly to thingsboard and use a data-converter afterwards.
like this:

![Untitled Diagram (29)](https://user-images.githubusercontent.com/27721138/79543943-826b4180-808e-11ea-9785-b6e136bf6761.png)

So my question is quite simple:
 **Can I use a data-converter without a MQTT-Integration module?**

I've read [this](https://thingsboard.io/docs/user-guide/integrations/mqtt/) tutorial, and it says that a MQTT-Integration is indeed required. But i want to make sure, theres really no other way.

**Comment by Karabiy** [comment]
the data converter is being applied after the data went through the integration which it refers to, so that you can not use the data converter without the integration being created. Though, you can have the converter being tested, after pressing on edit, so that you can put the payload of yours manually and have all the tests for the data converter. 
in case if you want to have the post processing for the data which is being sent using the API, you can put those for the rule chain
in case if you want to specify the device type and the device name as it is for the data converter, it is required to use the integration. It is an okay option for those.
