### ISSUE TITLE
[Documentation] SwaggerUI missing " Bearer " in generated curl command

### ISSUE THREAD

**Issue by datenheim** [thingsboard/thingsboard#2649]
This was tested on the latest revision of thingsboard CE 2.4.3 (and it was present since 2.3).

It is also reproducible on "demo.thingsboard.io" as well as on self-hosted edition.

1. creating a API-Token as described in the documentation works
2. Authorization with Swagger-UI also works
3. using "device-controller" get /api/device/types fails with error 401 (unauthorized) despite being displayed as properly authorized when clicking the autorize button.

In the swagger UI it looks like this:
![2020-04-21 17_17_41-Swagger UI bearer bug](https://user-images.githubusercontent.com/101634/79883598-68b25d00-83f4-11ea-9845-a224c8f1d033.png)

If you copy the generated Curl command to a shell it also fails with the same error.

The only missing thing is the word "Bearer" inbetween "X-Authorization:" and the actual token.

Wrong:
`curl -X GET --header 'Accept: application/json' --header 'X-Authorization: eyJhbGciOiJIUzUxMiJ9.ey...`

Right:
`curl -X GET --header 'Accept: application/json' --header 'X-Authorization: **Bearer** eyJhbGciOiJIUzUxMiJ9.ey...`

This should be easy to fix - but I'm not quite sure where in the code-base.

I filed this new issue because it is still/again present in current release.
It is likely connected to #66

**Comment by ShvaykaD** [comment]
Hi @datenheim, probably during the authorization into the swagger UI, in the api_key prompt you forgot to add the "Bearer" keyword:

![missing_keyword](https://user-images.githubusercontent.com/16356590/81230560-6823e400-8ffa-11ea-93d6-6f0d725e8725.png)

**Comment by datenheim** [comment]
Maybe it should be written somewhere that one has to enter "Bearer " followed by the JWT (that we got with curl) into the value-field after clicking "Authorize" . Or did I overlook such instruction?

At least [REST API | Thingsboard](https://thingsboard.io/docs/reference/rest-api/) page nothing is documented about that. And it is NOT self-evident IMO.

Sounds this is a documentation flaw not a bug?

**Comment by Karabiy** [comment]
in order to proceed with ther REST API use, you need to first hold an authorize. You can have yourself being logged in the TB of yours and copy those manual from the local storage, or you should paste the "Bearer $JWT_TOKEN" for those. In order to get the $JWT_TOKEN you can use the REST API call which is being desribed in the documentation. 
It is also mentioned after the request example that the "Bearer" is being required to be entered before the $JWT_TOKEN value. You can refer to the last item of the REST API Auth topic in the documentation of the ThingsBoard REST API.
