### ISSUE TITLE
Handle all attributes through a single API call

### ISSUE THREAD

**Issue by eykamp** [thingsboard/thingsboard#277]
Currently, setting attributes requires a different API call for setting Server, Shared, and Client attributes (and retrieving such).  It might be better to create a single API call to handle them all.  

The current API calls look like this:

`    http://<<server_url>>/api/plugins/telemetry/DEVICE/<<device_id>>/values/attributes/SHARED_SCOPE
`

And takes a body that looks like this:

```
{
	"lon":-122.686507003372,
	"lat":45.5342970119868
}
```

I would propose a URL that looks like this:

`
http://<<server_url>>/api/device/<<device_id>>/attributes
`

and took/returned a body that looks like this:

```
{
  	"attributes" : {
		"server" : {
			"lon":-122.686507003372,
			"lat":45.5342970119868
		},
		"shared" : {
			"shared_attr" : 123
		},
		"client" : {
			"client_attr" : 444
		}
	}
}
```

The returned JSON could also include the Device Id:

```
	"id" : {
		"entityType" : 'DEVICE'
		"id" : '<<device_id>>'
	}
```

This syntax could be used for attaching attributes to other objects, such as Assets.

If the existing calls are left in place (but deprecated) this could be added without breaking the API.

**Comment by ashvayka** [comment]
This is a valid request and the design looks ok, except that the server side application should not impact client attributes. Let's keep them isolated. But it should be possible to push shared and server side attributes simultaneously. 

The priority of this issue seems to be low. If anyone from the community members are willing to contribute this - please go a head. Core team is too busy now.

**Comment by mohan-mu** [comment]
getting this error while Posting data 

{
    "timestamp": 1533368092508,
    "status": 405,
    "error": "Method Not Allowed",
    "exception": "org.springframework.web.HttpRequestMethodNotSupportedException",
    "message": "Request method 'POST' not supported",
    "path": "/api/plugins/telemetry/DEVICE/0200b900-7fda-11e8-90e9-653c966bc2b6/values/attributes/SHARED_SCOPE"
}

**Comment by mohan-mu** [comment]
what the API for setting attributes

**Comment by mcpicoli** [comment]
Using the "SHARED_SCOPE" trick is a hack, you're emulating the steps triggered when a user updates the attribute via GUI. It is not documented, and may be changed/removed or otherwise misbehave without prior notice. Also, it uses the JWT token, which is not convenient at all for remote devices, since it would create more credential management worries. I've been tempted a lot to use it as a workaround for the lack of capability of cliente-side updates to shared attributes, but for now, I did not use it.

I've been waiting for this feature (or something like it) since probably forever. Using PE, but getting annoyed by this kind of shortcoming.

**Comment by Ultrazombie** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
