### ISSUE TITLE
How to use Update Dashboard State feature with different key names for different entities

### ISSUE THREAD

**Issue by nmahale10** [thingsboard/thingsboard#2809]
My entities have two different keys structure given as

Device 1 :- key1 and key2
Device 2 :- key3 and key4

I have one table in the dashboard in which I need to update data as per Entity(Device selected)
for which I am using Update Dashboard State action.

So in that, if I select Device1 it should show key1 and key2 data on the table.
and if I select Device2 it should show key3 and key 4 data.

Like in thingboardCloud demo, in DemoMeter dashboard keys are the same which are water and energy but in my case keys are different, so how can I achieve the same functionality.

Thanking you all.

**Comment by ashvayka** [comment]
It is not possible to show different keys in different rows. You should add a rule in rule engine to calculate and save something like "values" key where all values will be present (as a JSON). Than, you can use the "Data Key Configuration" and define the "data post-processing function" to visualize fields that you need. Let's assume you have combined all keys to JSON:

```json
{"key1": "v1", "key3": "v3"}
```

The post-processing function:
```javascript
var label = "";
var json = JSON.parse(value)
if(json.key1){
    label += json.key1;
}
if(json.key2){
    label += json.key2;
}
if(json.key3){
    label += json.key3;
}
if(json.key4){
    label += json.key4;
}
return label;
```

**Comment by nmahale10** [comment]
I have tried adding  rule in rule engine to calculate and save something like "values" . But while saving it to Telemtry using "Save Telemetry" rule .It was giving me error .So not able to save it in telemtry.
Shared a screenshot of my script.

![values](https://user-images.githubusercontent.com/22172258/84694114-46f1d400-af66-11ea-85e0-d40be9670919.png)

**Comment by BarlowHall** [comment]
Hello!

I did some tests. I am assuming that the error that the "Save Telemetry" node was giving was
`Can't parse value: {"key1":"value1","key2":"value2"}`. If not, then I will need to know what the error was.

It is because the "values" key is a JSON, which is not a valid value for a time series entry. You can use `JSON.stringify()` to cast it to a string in the rule node, then later in the post processing function you using `JSON.parse()` to change it back to a JSON.

Hope this helps!
