### ISSUE TITLE
REST API node Authorization

### ISSUE THREAD

**Issue by blackprincess88** [thingsboard/thingsboard#2913]
**Component**

 * Rule Engine

**Description**
Hi there! I am using a REST API node where I have to set the proper Authorization as Header. For testing, I already have used the X-Authorization token and it worked, but as you may know it expires after a login or a short time...I tried setting "Authorization" as Header and "${credentials}" as value...Of course, I have included an enrichment node as a previous node (in particular tenant/customer attributes) in order to get the credentials as metadata (I set "source field" as well as "Target attribute" to "credentials"- I already tried "username" and "password")...Unfortunately, I am not able to get this target field and I always have the same 401 Authorization error as REST API node output...

Any suggestions?I think that what is missing is the correct name of the source/target attributes to be used in the enrichment node...I did not find help in documentation! 

Thanks in advance for your help! 

PS: I also have tried "None" as value for the Authorization in the REST API node.

**Environment**

 * OS:  Linux
 * ThingsBoard: previous version (not updated yet after the 18 may updates)
 * Browser: Chrome 83.0.4103.61

**Comment by Karabiy** [comment]
For those reasons it is required to setup the next schema
First the authorization request being invoked, so that the jwt_token being received is valid and afters the requests to the API using the "Bearer jwt_token" as fot the x authorization being included to the headers for the next request to be invoked
It is also recommended to have a separate users whos credentials will be used fot the rule chain development
