### ISSUE TITLE
json telemetry for device in dashboard

### ISSUE THREAD

**Issue by Jalili-73** [thingsboard/thingsboard#2920]
devices send json to thingsboard like this:
{
       "id":1,  //id of device
        "cell_volt":[4500,3600,4000,3900,4100], //battery cell volt
        "loc":[38703298,52350148,273,0,0,38,678]  //lat_gps, lng_gps, heading, lat_gsm, lng_gsm, prec_gps, prec_gsm
}

how can i show each element of this array in widget.
for example show long and lat on map widget and cell volt on last telemetry chart in thingsboard 2.5 ce that support json array format.
in previous version i separate array like this:
{
       "id":1,
       "cell_volt1":4500,
       "cell_volt2":3600,
       "cell_volt3":4000,
       "cell_volt4":3900,
       "cell_volt5":4100,
       "long":38703298,
       "lat":52350148
}
and show in widget.
in version 2.5 we can save json array in database but how can i separate array element telemetry and show in widget, for example for showing latitude use object.loc[2]?

**Comment by Karabiy** [comment]
those can be achieved with two options 
1) Using the custom widget option. This link can be useful in this case: https://thingsboard.io/docs/user-guide/contribution/widgets-development/
2) Using the integration option (ThingsBoard Professional Edition only) you can have the data converter being configured in a way so that those telemetries will be parsed in a way you have described. You can refer to this link regarding those: https://thingsboard.io/docs/user-guide/integrations/#data-converters
3) It is also possible to have those being configured using ThingsBoard IoT gateway. You will need to have some customizations for the data converter of the Gateway itself. You can refer to this link regarding those: https://thingsboard.io/docs/iot-gateway/custom/#custom-converter-methods-reference

**Comment by dostuffthatmatters** [comment]
In case anyone stumbles on this issue, here is a solution: https://github.com/thingsboard/thingsboard/issues/7675#issuecomment-1327612849
