### ISSUE TITLE
[Bug] Cannot upgrade TB from 2.4.3 to 2.5.0 . Failed to execute query: DROP TABLE ts_kv_old; due to: ERROR: cannot drop table ts_kv_old because other objects depend on it

### ISSUE THREAD

**Issue by GokulSNarayan** [thingsboard/thingsboard#2993]
**Describe the bug**
When we were trying to upgrade from version 2.4.3 to 2.50 we are facing this error at this command
`sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=2.4.3`
**Failed to execute query: DROP TABLE ts_kv_old; due to: ERROR: cannot drop table ts_kv_old because other objects depend on it**

We followed the hint which said to do **Drop CASCADE ts_kv_old** 
`DROP TABLE if exists ts_kv_old cascade;`

After this we are getting new error
                                                .....install.log.....
`PL/pgSQL function create_partition_ts_kv_table() line 13 at SQL statement
2020-06-23 13:21:56,730 [main] ERROR o.t.s.i.ThingsboardInstallService - Unexpected error during ThingsBoard installation!
java.lang.RuntimeException: Failed to execute query:call create_partition_ts_kv_table() due to:`
**Your Server Environment**

* own setup
  * AWS EC2 instance t2.small; 2gb ram
  * ThingsBoard Version 2.4.3
  * Ubuntu 18.04.4 LTS Bionic

**Comment by ShvaykaD** [comment]
Hi, @GokulSNarayan could you let me know if you did the database backup before executing the upgrade script?

If so, do you have the ability to provide the backup via mail or share it on google drive with me: dshvaika@thingsboard.io in order to investigate the issue.

Or, maybe you can share the ssh credentials for your server to investigate the issue on your ec2 instance?

**Comment by GokulSNarayan** [comment]
> Hi, @GokulSNarayan could you let me know if you did the database backup before executing the upgrade script?
> 
> If so, do you have the ability to provide the backup via mail or share it on google drive with me: [dshvaika@thingsboard.io](mailto:dshvaika@thingsboard.io) in order to investigate the issue.
> 
> Or, maybe you can share the ssh credentials for your server to investigate the issue directly on your instance?

I will sent you the backup link ,do you happen to have telegram.

**Comment by GokulSNarayan** [comment]
upgrade failed from 2.5.2 to 3.0

$/var/log/thingsboard$ sudo /usr/share/thingsboard/bin/install/upgrade.sh --fromVersion=2.5.2

===================================================

:: ThingsBoard Professional Edition ::       (v3.0.0PE)

===================================================

 

Starting ThingsBoard Upgrade from version 2.5.2 ...

Unexpected error during ThingsBoard installation!

java.lang.RuntimeException: Unable to upgrade ThingsBoard, unsupported fromVersion: 2.5.2

        at org.thingsboard.server.install.ThingsboardInstallService.performInstall(ThingsboardInstallService.java:189)

        at org.thingsboard.server.ThingsboardInstallApplication.main(ThingsboardInstallApplication.java:60)

        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

        at java.lang.reflect.Method.invoke(Method.java:498)

        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)

        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)

        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)

        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:597)

Unexpected error during ThingsBoard installation!

ThingsBoard upgrade failed!`

**Comment by ShvaykaD** [comment]
Hi @GokulSNarayan 

- Regarding the upgrade to 2.5 from 2.4.3:

The issue that occurred in your database is abnormal because the ts_kv table didn't depend on any other objects. It doesn't have any foreign keys that can be a reason for the issue that happened in your TB instance. Probably the ts_kv table was manually changed before the upgrade. 

- Regarding the upgrade to 3.0:

the reason for the issue for the upgrade to 3.0 was: unsupported 2.5.2 version in the --fromVersion flag. For the upgrading from 2.5.2 version the flag should be set to "--fromVersion=2.5.0". For more details please check our official documentation page regarding the upgrade instructions to version 3.0:

https://thingsboard.io/docs/user-guide/install/pe/upgrade-instructions/#upgrading-to-30pe

**Comment by trypzz** [comment]
Hello, @GokulSNarayan 

Tell me, please, your problem is actual or not?
