### ISSUE TITLE
Alarm Rule chain

### ISSUE THREAD

**Issue by e60newbie** [thingsboard/thingsboard#3006]
**Component**

 * Rule Engine

**Description**
Hy Folks,
I search for a solution to create an Alarm trough the Rule Chain.
I Send over Mqtt a value with a number (Error word).
In the rule Chain i parse these value binary with a script to get if a bit is set or not.
My idea was to Add telemetry data like:
if ((error & 0x1)===0x1)
{errortext ='error 1'}
else if ((error & 0x2)===0x2)
{errortext ='error 2'}
and so on.

but i have no idea how handle these than with the creation Alarm node. Exist a possibility to use the message data? may someone have an example how the message data should looks like?

the idea behind is to have one creation node / erase node and I can add the error text in the script. i need to show about 50 errors, if I create for everey his own node, I never finish.

Greetings from Italy

**Environment**

 * OS:  Windows Server
 * ThingsBoard: V3.0.1 PE

**Comment by Backdraft007** [comment]
Have a look here:
https://thingsboard.io/docs/user-guide/rule-engine-2-0/tutorials/create-clear-alarms/#configure-device-and-dashboard
You can read your telemetry data and filter them and give it to the other nodes.

**Comment by e60newbie** [comment]
![errorchain](https://user-images.githubusercontent.com/55992097/85851993-0db03400-b7b0-11ea-8607-a6baf6732691.JPG)
The link you provided I followed but wont help in my case. There is no description how handle the creation node with "use message alarm data" in the example provided is a simple true or false request, in my case is bit parsing how can set 2 bits at the same time, so simple true or false return wont work.
see the rule chain idea attached.

**Comment by Karabiy** [comment]
you can have the alarm creation being handled on the side of the script node. For those reasons the alarm "Use message alarm data" can be applied. Refer to the below 
In such a case, the "Create Alarm" node does accept an Alarm object. So as an example the next message data is needed to be sent for the input of an alarm node:
{
    "tenantId": {
        "entityType": "TENANT",
        "id": "3ca3ef30-f17e-11e8-b197-b3b9a2a7f897"
    },
    "type": "General Alarm",
    "originator": {
        "entityType": "DEVICE",
        "id": "60b94110-d952-11e9-8ee3-bdfc65c3ae4d"
    },
    "severity": "CRITICAL",
    "status": "ACTIVE_UNACK",
    "startTs": 1580391775816,
    "endTs": 1580391775816,
    "ackTs": 0,
    "clearTs": 0,
    "details": {},
    "propagate": false,
    "propagateRelationTypes": [],
    "id": {
        "entityType": "ALARM",
        "id": "6b8a4390-4366-11ea-be3b-9d7f1c9b90f0"
    },
    "createdTime": 1580391775817,
    "name": "General Alarm"
}
 
Where tenantId, type, originator, severity, status, startTs - required
You may inspect more about it if you need to customize it
If you need to get more examples of how to go with a "Use message alarm data", you may go test different alarm types, setups on yourself and getting more information about possible alarm objects for you to create. In order to make those you can use the generator node to generate specific messages types which are required 

so that using those you will have a flexible possibilities for the alarm creation and those can be handled most on the scripts sides based on the requirements of yours with the single create alarm node being used
