### ISSUE TITLE
Automatically acknowledge a cleared alarm

### ISSUE THREAD

**Issue by lmax25** [thingsboard/thingsboard#3012]
Hello !
Please tell me how can I automatically acknowledge a cleared alarm.
Thank You !

Environment
OS: Win 7 x64
ThingsBoard: 2.5.2
Browser: Chrome

**Comment by Karabiy** [comment]
Hello,

For those reasons, you can use the create alarm rule node. So that you will update the existing alarm.
The feature to be used in those case is the  "Use message alarm data"
 
In such a case, the "Create Alarm" node does accept an Alarm object. So as an example the next message data is needed to be sent for the input of an alarm node:
{
    "tenantId": {
        "entityType": "TENANT",
        "id": "3ca3ef30-f17e-11e8-b197-b3b9a2a7f897"
    },
    "type": "General Alarm",
    "originator": {
        "entityType": "DEVICE",
        "id": "60b94110-d952-11e9-8ee3-bdfc65c3ae4d"
    },
    "severity": "CRITICAL",
    "status": "ACTIVE_UNACK",
    "startTs": 1580391775816,
    "endTs": 1580391775816,
    "ackTs": 0,
    "clearTs": 0,
    "details": {},
    "propagate": false,
    "propagateRelationTypes": [],
    "id": {
        "entityType": "ALARM",
        "id": "6b8a4390-4366-11ea-be3b-9d7f1c9b90f0"
    },
    "createdTime": 1580391775817,
    "name": "General Alarm"
}
 
Where tenantId, type, originator, severity, status, startTs - required
You may inspect more about it if you need to customize it
If you need to get more examples of how to go with a "Use message alarm data", you may go test different alarm types, setups on yourself and getting more information about possible alarm objects for you to create. 
for the use case of an automatic acknowledgement you can first setup the create alarm rule node for the alarm creation and afters apply the filtering logic based on which the alarm will become acknowledged as it is cleared.

**Comment by lmax25** [comment]
Hello again and thanks for your answer !

Unfortunately  I couldn't achieve my goal to Automatically acknowledge a cleared alarm using your sample message...

I think I made my new message exactly like yours but it doesn't work. The Create Alarm node is creating a new GENERAL ALARM with CRITICAL Severity status.

Please provide me a full working sample or please give me the API command to do this !

Thank You and Best Regards !

**Comment by Karabiy** [comment]
make sure that you are running the latest version and there are have not missed somewhere for the configurations on your side. also, I highly recommend you to check our documentation: https://thingsboard.io/docs/

**Comment by lmax25** [comment]
Hello !
Today I spent about another 5-6 hours to try to solve the problem, but I couldn't !
I tried a lot of actions, but without any success !
Please provide me a full working sample or please give me the API command to do this !

Thank You and Best Regards !
