### ISSUE TITLE
Count Number of Devices under Asset type

### ISSUE THREAD

**Issue by GauravChoube** [thingsboard/thingsboard#3073]
Hi Guys,
i want to count the number of device fall under same asset type and can show on  individual dashboard of each device.
i also want to know number of active devices active on that time of same asset type and show on each dashboard.

How can i do this ?
any way or scripts.
please help me out.

I am using demo version of thingsboard

**Comment by Karabiy** [comment]
you can have those being related with an asset which is being set for an active with a relation, and delete this relation in case if the device is inactive. It requires the rule chain to be created. 
You may refer to this link for the rule engine docs, which will be useful for your case: https://thingsboard.io/docs/user-guide/rule-engine-2-0/overview/
So that more complex structure may be created and different approaches on those can be taken, though, it will be quite easy to make modifications
you can also use the REST API calls and have those being counted using the request queries, though, it would not be that easy to modify 
you can refer on this link to the ThingsBoard REST API docs: https://thingsboard.io/docs/reference/rest-api/

**Comment by lmax25** [comment]
Can you be more specific and give an example about how to count all the devices that are related to every asset ?
How can I pass the total number of the devices for every asset to an attribute ?
Thank You !
