### ISSUE TITLE
[Feature Request] add Join Node to rule engine to create a single message from separate streams of messages

### ISSUE THREAD

**Issue by t0mmyz7** [thingsboard/thingsboard#3081]
If you are familiar with the [Join Node](https://cookbook.nodered.org/basic/join-streams) in Node-red, similar would be very helpful in the rule engine.

Many nodes in the rule engine, like originator attributes, aggregate latest, output each attribute queried, or value calculated, into a separate output message. So it is impossible to use the Script node to calculate base on multiple values.

For example, I grab more than 1 attribute with Originator attribute, Att-A, Att-B, Att-C, and I want to perform a calculation based on them in Script node, like Att-A + Att-B + Att-C.  At the moment each attribute, although grabbed at the same time, by the same node, it output as a separate message.

There are many other uses cases that require Join Node, you can review the link about for an example from Node-red.

Is there a way to currently do this in TB 3 that I am missing?

Cheers

**Comment by Karabiy** [comment]
you can have those being applied in case if you proceed with one of the sequential strategies being applied and saving the data as the attribute, like key1,2,3 and the flag to proceed further with the processing, so that you will drop 2 messages and enrich the third one with the first and second, so that those can be proceeded further as a separate one message with two previous being aggregated

**Comment by t0mmyz7** [comment]
@Karabiy thanks for taking the time to reply and for your suggestion. 

Any chance you can draw this method in the rule engine and post an image or json export here? Not entirely sure how to accomplish this.

Is your suggestion  to save the calculated value a,b as attributeA and attributeB and set AttributeC as a flag. Then setup another rule to filter for attribute type C, and enrich it with attribute A,B?

Does attribute enrichment node outputs all variables in one message?

Thanks in advance

**Comment by Karabiy** [comment]
The schema of those is being attached 
you can also refer to the screenshot 
I also want to note that this is just the schema, so that it requires enrichments and proper configuration for the use case that may be applied based those schema
N - is the count of messages you want to have as max
![Screenshot from 2020-07-14 17-47-12](https://user-images.githubusercontent.com/31805736/87441248-9249e180-c5fb-11ea-9362-689b275c2f23.png)
and the rule chain to import to get better view on the titles of the rule node, which refers on how those may be used

[join_chain.json.txt](https://github.com/thingsboard/thingsboard/files/4919510/join_chain.json.txt)

**Comment by t0mmyz7** [comment]
Thanks @Karabiy 

I am going through your example and learning your approach here.

I would still encourage the team to add a simple Join node like the one implemented in node-red.

**Comment by Delapouite** [comment]
> Many nodes in the rule engine, like **originator attributes**, [...] output each attribute queried, or value calculated, into a separate output message.

@t0mmyz7  Is that always the case? I've did some test with an `originator attributes` node, configuring it to add the server attributes `address`, `city` and `telephone` of a device, and I only got 1 message with these 3 attributes inside, not 3 distinct messages.

Could this behavior be tied to a specific version of Thingsboard?

**Comment by Karabiy** [comment]
@Delapouite this is the expected behavior. It is an okay. In case if you want those to be set for the separate messages, you can use script nodes. 
The next structure can be used:
![ThingsBoard-PE-Cloud-Rule-chain](https://user-images.githubusercontent.com/31805736/93203325-ea68a580-f75c-11ea-91c0-dc3e20537796.png)
