### ISSUE TITLE
[Question] What is the meaning of latest in "latest telemetry"?

### ISSUE THREAD

**Issue by helguson** [thingsboard/thingsboard#3119]
**Component**

 * UI / Generic

**Description**
We transmit telemetry data (including timestamps for measurements) in non chronological order (e. g. when transmitting batches of data). We observed that a widget which shows the "latest telemetry" value shows rather the most recently received data than the most recently measured data. That's why we do not show the most current state available in widgets that show the "latest" data.

1. Do we access the situation correctly that right now the "latest telemetry" represents the telemetry value of the most recent transmission?
2. Is it intended to work like this? (or is it a bug?)
3. Is it currently possible to modify this behavior, e.g., in the thingsboard settings? Or to access the data of the most current measurement? (We see use cases for both options.)
4. Would it be better to refer with "latest" to the time of most current measurement?

**Environment**

- We use an [official docker image consisting of Thingsboard CE 2.4.0 and cassandra](https://hub.docker.com/r/thingsboard/tb-cassandra). 
- We use the [MQTT-gateway API](https://thingsboard.io/docs/reference/gateway-mqtt-api/#telemetry-upload-api) to upload data.

**References**
- #1769 is a related open issue.

**Comment by ismaeil-shajar** [comment]
That true latest telemetry  is the most recently received data 
I don't know if it bug but from tb 2.0 it's like this 
But latest value is shown in entities view but when work with widget it use websockets which is call API with your current time and get most recent value even if it old received .
The widget what I'm talking about is time series widget because it get value from ts_kv table .
Latest value was saved in another table I think called latest_ts_kv . 
You can work with api or websockets and you will receive your right orders of data just reject what latest value shown you

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
