### ISSUE TITLE
Send widget value to node-red

### ISSUE THREAD

**Issue by Ataraxiall** [thingsboard/thingsboard#3129]
**Component**

 * UI

**Description**
Good morning,

I am getting into thingsboard to see if it is feasible to apply it to a system I have.
The system is based on node network, and I have been able to do basic things (send data via http to the dashboard, connect via websocket, etc ...) what I cannot do after a thousand laps is to be able to send change values ​​to node network . For example, I have a knob controller on node red, which I use to raise or lower amps.
I wish that the thingboard knob controller widget could send the values ​​to the node red for it to apply.
Can someone guide me?
thank you!

**Environment**
google translate
 * OS:  cloud.thingsboard.io (demo)

**Comment by Karabiy** [comment]
The knob controller does invoke an RPC call request processing to be handled on the rule engine side, so that for the use case of yours, you need to handle the rule engine all the processing logic, and the knob controller will trigger the rule chain. The trigger can be achieved different ways (API Call, Control widgets, etc.). 
You can refer to this link regarding the rule engine: https://thingsboard.io/docs/user-guide/rule-engine-2-0/overview/
And the external rule node can be used to have the connection for different services you are using

**Comment by amizer12** [comment]
I used to have the same use case.
RPC is an option but it sucks as it heavily relies on your devices being online all the time, what i endup using is creating a widget ( knob or whatever ) that will read and save the temperature data as device attribute, on atribute update the attribute service will send the updates via mqtt to node-red device that will process the change further, the same way the other way around - when i change something on node red device it is sending new attribute value to thingsboard.
