### ISSUE TITLE
ide

### ISSUE THREAD

**Issue by stormwrym** [thingsboard/thingsboard#313]
What IDE does this project need,I want to  change some things.

**Comment by stormwrym** [comment]
What development environment does this project need

**Comment by ssmaurya** [comment]
We use IntelliJ and Eclipse.

**Comment by stormwrym** [comment]
How many projects can I import into eclipse ,compiler error message

**Comment by mp-loki** [comment]
Hi @stormwrym 
Do you follow the [Contribution guide](https://thingsboard.io/docs/user-guide/contribution/how-to-contribute/)?

Briefly, you have to:

1) Check out the source code from Git
2) Build it with maven from command line `mvn clean install`
3) Import the project to Eclipse - File -> Import -> Maven Project, then select the root pom file.
It should automatically import all maven modules

**Comment by eykamp** [comment]
I had huge problems getting Eclipse configured.  I've currently got things working with NetBeans which seems to have a more transparent way of working with maven projects.  Now that that is working, I may go back and see if I can get Eclipse, as at least some of my problems turned out to be node dependency issues that are independent of IDE.

**Comment by mp-loki** [comment]
After the project is imported in Eclipse, I recommend you to disable the Maven Project Builder on **ui** module. This will avoid Eclipse from hanging while digging in node_modules directory.
To do this, right-click on **ui** module, go to Properties -> Builders and then uncheck Maven Project Builder checkbox

**Comment by ashvayka** [comment]
Closing this issue since we don't officially support contribution guide via eclipse
