### ISSUE TITLE
[Bug] Alarm Table Widget Shows Alarms For Only One Device Per Table

### ISSUE THREAD

**Issue by arianofaoms** [thingsboard/thingsboard#3195]
**Describe the bug**

**Your Server Environment**

- [ ] demo.thingsboard.io
- [ ] cloud.thingsboard.io
- [x] own setup
  * cloud or local infrastructure or docker deployment: MS Azure - BYOL Image
  * ThingsBoard Version: PE 2.2.49.2
  * OS Name and Version: Linux (ubuntu 18.04)

**Your Client Environment**

**Desktop:**

* OS: MacOS
* Browser:
* Version:

**Your Device**

* Connectivity
- [ ] MQTT
-  [x] HTTP
- [ ] CoAP
- [ ] Gateway
- [ ] Integration: (Specify name) 

**To Reproduce**
1. Create 2 Devices on Thingsboard
2. Create a create alarm rule chain for the two devices
3. Trigger the alarm by sending fake data via HTTP to each device
4. Create a dashboard and use the Alarm Widget to view the alarms. Define an entity alias for the alarms table with the following settings:
![image](https://user-images.githubusercontent.com/52330044/88824092-e45e3b80-d193-11ea-87d7-b265e012b621.png)

**Expected behavior**
I would expect that both alarms (for device 1 and device 2) are shown. But only the alarms originated by one of the two devices are shown at all times:

![image](https://user-images.githubusercontent.com/52330044/88824542-79613480-d194-11ea-813d-dc63eb76e6ef.png)

### I have tried defining different types of aliases (example below), but none seemed to work.

![image](https://user-images.githubusercontent.com/52330044/88824247-1bcce800-d194-11ea-9c70-5f7bda17afd6.png)

### As a work-around, I had to create multiple tables with single entity aliases like so:

![image](https://user-images.githubusercontent.com/52330044/88824405-4c148680-d194-11ea-8ecd-b5c353bfdbd9.png)

### And made two individual tables instead.
![image](https://user-images.githubusercontent.com/52330044/88824949-f4c2e600-d194-11ea-8636-84b6c21e778b.png)

**Additional context**
Please let me know if this is not a bug and there is a solution for this.

**Comment by RondoRonaldo** [comment]
For now, when you assign a group of devices to an alarm widget, only one of them will be processed, and the "Resolve as multiple entities" button won't work too.
So If you want to show alarms from several entities, this can be circumvented by creating an auxiliary entity (asset for the example) that will have relations to all the entities(devices for the example) with alarms and setting “propagate alarms” in the “create alarm” node to true. This way all the alarms being generated afters will be available on the asset.
I will provide you with an example of two devices connected to an asset so you may refer to the screenshots below.

The “Create alarm“ node transforms the telemetry object into the string to be visualized easily on the dashboard “Alarm widget” and set “alarm type” to the device name, so that it won’t create a new alarm object but update the one with the same alarm type.
![image](https://user-images.githubusercontent.com/43723966/88902795-58afe200-d25b-11ea-9b96-5a921a654f62.png)
![image](https://user-images.githubusercontent.com/43723966/88902809-5baad280-d25b-11ea-8d87-017ac1775d05.png)
![image](https://user-images.githubusercontent.com/43723966/88902817-5fd6f000-d25b-11ea-9e80-c61ef5eeccaf.png)
![image](https://user-images.githubusercontent.com/43723966/88902826-62394a00-d25b-11ea-933e-eb6e415a46e5.png)
