### ISSUE TITLE
[Bug] Rule Engine JS Invoke Stats: requests [9977] responses [60] failures [68]

### ISSUE THREAD

**Issue by dgood-tech** [thingsboard/thingsboard#3227]
In version v2.5.2, when the rule chain runs for a certain period of time, it will become stuck and will not be displayed in the running log 2020-08-03 18:11:46,249 [TB-Scheduling-2] INFO  o.t.server.actors.ActorSystemContext - Rule Engine JS Invoke Stats: requests [9977] responses [60] failures [68]
2020-08-03 18:11:46,249 [TB-Scheduling-3] INFO  rpc - Nashorn JS Invoke Stats: pushed [100] received [60] invoke [60] eval [0] failed [0] timedOut [68]
This is not an issue in version 2.4.3

**Comment by Karabiy** [comment]
please, set the rule engine statistics dashboard and check those for failures 
you can refer to this link for the rule engine statistics: https://raw.githubusercontent.com/thingsboard/thingsboard/master/application/src/main/data/json/demo/dashboards/rule_engine_statistics.json
and for this link for the docs for the rule engine statistics: https://thingsboard.io/docs/user-guide/rule-engine-2-0/overview/#rule-engine-statistics
as for the timeout  to be increased, the script is blacklisted when its execution is longer than 100 ms can occur.
The main solution involves changing thingsboard.yml parameter:changing js.local.max_cpu_time in the thingsboard.yml to a value more than 100 in order to increase the time before the script is blacklisted by the rule engine.
