### ISSUE TITLE
Running Apache server with thingsboard

### ISSUE THREAD

**Issue by GauravChoube** [thingsboard/thingsboard#3231]
I am running thingsboard on vps which has ubantu linux.
i using thingsboard community and i want to run Apache along thingsboard.

Please suggest me how to achieve it.

**Comment by Karabiy** [comment]
for those reasons you should set the port for the ThingsBoard or the Apach in a way to prevent the "Port already bound"
in order to prevent those, for the ThingsBoard you can change the ports being used
Please, set those in the thingsboard.conf file and refer to the thingsboard.yml file only to get the environmental variables. It is the same logic as for the license key, so, for example, in case if you would have want to change the MQTT enabled ( the MQTT API to stop ) to the disabled, for the thingsboard.conf file you would have added the next row: 
export MQTT_ENABLED=false

After all the changes will be applied, it is required to have the thingsboard restart, to have the changes to be applied. 

The thingsboard.yml file is located in the same directory as the thingsboard.conf. The path for the directory is /etc/thingsboard/conf/
