### ISSUE TITLE
[Question] How to post telemetry data to thingsboard IoT gateway via HTTP

### ISSUE THREAD

**Issue by Nadou14** [thingsboard/thingsboard#3234]
**Description**
I've already configured the distribution of **HTTP** on my server to push data to my **thingsboard** instance, but now I want to use **ThingsBoard IoT gateway** so I can have only one route for data transfer. However I found in TB doc that the gateway uses MQTT connection. So I wonder if I can still publish my data via HTTP by using Rest connector that I found in this link https://thingsboard.io/docs/iot-gateway/config/rest/ or I should use MQTT protocol instead. 

**Environment**

 * ThingsBoard: version 3.0.1

**Comment by zbeacon** [comment]
Hi @Nadou14 ,

Thank you for your interest in ThingsBoard IoT gateway. The gateway uses MQTT to communicate with ThingsBoard, but you are able to use any connector in the gateway to pass data to the gateway. In you case you can configure REST connector and send data to created endpoint (Then the gateway will convert it to MQTT message and send to ThingsBoard) instead of publishing to ThingsBoard instance
