### ISSUE TITLE
TCP integration error

### ISSUE THREAD

**Issue by anhdv1979** [thingsboard/thingsboard#3250]
I successfully install TCP integration with my TB PE however it could not work. Pls help me check!
Many thanks!
[tb-tcp-udp-integration.log](https://github.com/thingsboard/thingsboard/files/5033542/tb-tcp-udp-integration.log)

**Comment by Karabiy** [comment]
those is a known issue for 3.0.1, those will be fixed for the version 3.1, though, can not comment you at exact time on those to be released
you also can have use the next Rest API call:

curl --location --request POST 'https://cloud.thingsboard.io/api/integration' \
--header 'Connection: keep-alive' \
--header 'Accept: application/json, text/plain, */*' \
--header 'X-Authorization: value' \
--header 'Content-Type: application/json' \
--header 'Origin: https://cloud.thingsboard.io' \
--header 'Sec-Fetch-Site: same-origin' \
--header 'Sec-Fetch-Mode: cors' \
--header 'Referer: https://cloud.thingsboard.io/integrations' \
--data-raw '{"name":"name","type":"TCP","enabled":true,"debugMode":null,"defaultConverterId":{"entityType":"CONVERTER","id":"c0949f80-c1d2-11ea-8c1f-47625adf437a"},"downlinkConverterId":null,"remote":true,"routingKey":"9525219c-1027-5ee2-1e3e-a1664390d9df","secret":"wz5g6hyejupp3fxxjodu","configuration":{"clientConfiguration":{"port":10560,"soBacklogOption":128,"soRcvBuf":64,"soSndBuf":64,"soKeepaliveOption":false,"tcpNoDelay":true,"handlerConfiguration":{"handlerType":"BINARY","byteOrder":"LITTLE_ENDIAN","maxFrameLength":128,"lengthFieldOffset":0,"lengthFieldLength":2,"lengthAdjustment":0,"initialBytesToStrip":0}},"metadata":{}},"additionalInfo":{"description":""}}'

based on the values of yours, so that those will send the correct message and the integration should work an okay with those

**Comment by anhdv1979** [comment]
I do as you told and successfully connect TB-Integration with TB PE . However tcp client send data (as your sample in your website) but it seems that TB-Integration get error and no telemetry for device in TB. Pls help me check!
[tb-tcp-udp-integration (2).log](https://github.com/thingsboard/thingsboard/files/5038988/tb-tcp-udp-integration.2.log)

**Comment by Karabiy** [comment]
which system do you run integration on?

**Comment by Karabiy** [comment]
does the issue persists?
