### ISSUE TITLE
Update or change asset Server attributes using rules chain

### ISSUE THREAD

**Issue by GauravChoube** [thingsboard/thingsboard#3294]
hi,
I am using demo version of thingsboard where i want to change the value of server attribute of asset whenever particular message received from device.
I want to changed to value using rules chain.
I configured the  one asset which has 3 device relation with.
now problem is whenever i stored server attribute to create and changed in device server attributes but i want to changed asset one.
please tell how can i change it.

**Comment by ChantsovaEkaterina** [comment]
Hello,
You can use the _Change originator_ rule node to achieve what you need.

**Comment by GauravChoube** [comment]
Hi ChantsovaEkaterina,
thanks for reply.
can you tell me how to use change originator.

**Comment by ChantsovaEkaterina** [comment]
@GauravChoube You could find needed information here:
https://thingsboard.io/docs/user-guide/rule-engine-2-0/transformation-nodes/#change-originator
If something remains unclear fill free to ask any questions.

**Comment by GauravChoube** [comment]
Thank for your suggestions and successful updated the asset attributes.

**Comment by Karabiy** [comment]
glad to hear

**Comment by HachemGaharbi** [comment]
hi @GauravChoube can you please tell me how did you update the asset attributes.

**Comment by astijon95** [comment]
hi @GauravChoube  I have a similar problem.  My device is pussing telemetry and with the change originator node the originator of the message is change to the related asset. The problem is that I want the activity/inactivity atributtes from the device going into the asset attributes, but this is not happening.

I attached my rule chain
![Rule_chain](https://user-images.githubusercontent.com/85154397/124909883-4271e080-dfeb-11eb-8f26-8d20d984193b.png)

Thank you in advance

**Comment by escalanterj** [comment]
Hi Guys, How do you add attributes like perimeter?
