### ISSUE TITLE
Install Thingsboard PE with Docker

### ISSUE THREAD

**Issue by Kampi** [thingsboard/thingsboard#3295]
**Component**
 * Installation

**Description**
I want to use the Thingsboard PE version (the smallest one) to test the capabilities of Thingsboard before buying the big version. So I set up a virtual machine with Ubuntu 18.04 and install Thingsboard with [this](https://thingsboard.io/docs/user-guide/install/pe/docker/) guide. After logging in into docker hub and executing `docker-compose pull` I got the error message

```
ERROR: pull access denied for store/thingsboard/tb-pe, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

It seems that the version isn´t available on the Docker hub. So how can I install my PE version?

**Environment**
 * OS:  Ubuntu 18.04.4 LTS

**Comment by ashvayka** [comment]
Hi @Kampi ,

in order to pull the image you need to open https://hub.docker.com/_/thingsboard-pe and click "Proceed to Checkout". Once you do this you will be prompted to accept the license agreement (similar to when you install the deb package). Once you accept the agreement, you need to do a "docker login" on your Ubuntu instance with the same credentials you have used to checkout image on docker hub. Then everything will work :-)

**Comment by Kampi** [comment]
> 
> 
> Hi @Kampi ,
> 
> in order to pull the image you need to open https://hub.docker.com/_/thingsboard-pe and click "Proceed to Checkout". Once you do this you will be prompted to accept the license agreement (similar to when you install the deb package). Once you accept the agreement, you need to do a "docker login" on your Ubuntu instance with the same credentials you have used to checkout image on docker hub. Then everything will work :-)

Hi @ashvayka,

thank you for your quick response. It is working now.
