### ISSUE TITLE
 License Error: INSTANCE_NOT_FOUND(105) - Instance not found!

### ISSUE THREAD

**Issue by arjentraas** [thingsboard/thingsboard#3312]
I have upgraded my TB PE instance from 2.4.3 to the most recent 3.1.0 version, in multiple steps. 

The Linux VM that is hosting ThingsBoard is restarted, but now I cannot start my TB instance. It displays the following error: `License Error: INSTANCE_NOT_FOUND(105) - Instance not found!`

It doesn't create a new instance when I restart the Thingsboard service. The license portal shows my license, but no instances. 

The [YouTube video](https://www.youtube.com/watch?v=2khu3RP0TGE&feature=youtu.be) addressing these problems does not address this issue.

**Comment by fanrong1993** [comment]
How do you solve this problem

**Comment by sandeepv10494** [comment]
how to solve this issue ?

**Comment by jason-hulkman** [comment]
Mine is PE version, I upgrade the plan, and delete the instance, and restart the TB service, and service status logs find the error message:

Aug 31 12:19:46 instanceIDXXXXXXXXX thingsboard.jar[1780]: [ERROR] License Error: INSTANCE_NOT_FOUND(105) - Instance not found!
Aug 31 12:19:46 instanceIDXXXXXXXXX thingsboard.jar[1780]:  [ERROR] Failed to initialize ThingsBoard License Client!
Aug 31 12:19:46 instanceIDXXXXXXXXX thingsboard.jar[1780]:  [ERROR] Failed to init license client
Aug 31 12:19:46 instanceIDXXXXXXXXX thingsboard.jar[1780]:  Terminating application due to critical License Error INSTANCE_NOT_FOUND(105), ex>
Aug 31 12:19:52 instanceIDXXXXXXXXX thingsboard.jar[1780]: WARNING: An illegal reflective access operation has occurred
Aug 31 12:19:52 instanceIDXXXXXXXXX thingsboard.jar[1780]: WARNING: Illegal reflective access by org.nustaq.serialization.FSTClazzInfo (jar:f>
Aug 31 12:19:52 instanceIDXXXXXXXXX thingsboard.jar[1780]: WARNING: Please consider reporting this to the maintainers of org.nustaq.serializa>
Aug 31 12:19:52 instanceIDXXXXXXXXX thingsboard.jar[1780]: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflectiv>
Aug 31 12:19:52 instanceIDXXXXXXXXX thingsboard.jar[1780]: WARNING: All illegal access operations will be denied in a future release
Aug 31 12:19:57 instanceIDXXXXXXXXX thingsboard.jar[1780]: Warning: Nashorn engine is planned to be removed from a future JDK release

follow this article: https://ashespia.tistory.com/64

rm -rf /usr/share/thingsboard/bin/instance-license.data

Done!
