### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by shanevanj** [thingsboard/thingsboard#3364]
**Describe the bug**
After installing a new instance of PE and activating the server using license manager - no new devices can be added

**Your Server Environment**
* own setup
  * local infrastructure
  * ThingsBoard Version  - thingsboard-3.1pe
  * OS Name and Version ubuntu 20.04 LTE

**Your Client Environment**
**Desktop (please complete the following information):**
* OS: [e.g. iOS] MACOS
* Browser [e.g. chrome, safari] Safari
* Version [e.g. 22] 13.1.2

**Your Device**
* Connectivity
  * MQTT

**To Reproduce**
1. Create new Ubuntu server
2. Install PE as per https://thingsboard.io/docs/user-guide/install/pe/ubuntu/
2. Open license manager https://license.thingsboard.io/subscriptions
3. Deactivate and delete previous server instance in use 
4. Copy license secret and insert in /etc/thingsboard/conf/thingsboard.conf
5. Restart server
6. Login to PE and configure SMTP etc
7. Create new tenant and tenant admin
8. Log in as new tenant admin and create new customer group and then new customer
9. Open customer and then device groups "All"
10. Add new device (1st device) 
11. Error: Limit reached 

**Expected behavior**
1. System should allow 10 new devices to be created on the pay-as-you-go license

**Screenshots**
![image](https://user-images.githubusercontent.com/11026875/91163196-798a1c80-e6cd-11ea-906d-f583cd3b18fe.png)

**Additional context**
Bought a paid for a new (uneeded subscription) added new license key to server - restart TB - same issue

**Comment by Karabiy** [comment]
Those seem to be related to the count of the devices. Please, make sure that you have less than the 10 devices in the ThingsBoard according to the subscription of yours so that you can have one more being added. To investigate the device count for the current ThingsBoard version of yours, you can proceed with the instructions below. 
The devices of yours can be set under the customer entities/other tenant entities

sudo su - postgres /
\l - to check the name of the database of yours. Commonly it's "thingsboard"
\c - to connect to your database
\dt - to list all the tables
select * from device;
So, it might look like
"""
sudo su - postgres
\c thingsboard
select * from device;
"""

**Comment by shanevanj** [comment]
Thanks for the response - it was a simple issue that was not obvious at the time ….. When I installed TB I installed it with demo data and that demo data already has 9 devices provisioned for the demo scripts - I deleted the demo tenant and all is working as it should be.


 
Shane van Jaarsveldt
Tel: +27 11 469 4750  Cel: +27 82 601 0499  Fax: +27 11 469 3370
