### ISSUE TITLE
[Bug] Tcp-udp-integration service doesn't process message with initial # 

### ISSUE THREAD

**Issue by anhdv1979** [thingsboard/thingsboard#3419]
**Describe the bug**
it seems that your tcp-udp-integration could not process message with # initial (text payload)
Let me describe:
1. I do exactly as your document guides except for device name: #SN-001 
2. - Use netcat #SN-001,default,temperature,25.7\n\rSN-001,default,humidity,69 || nc -q0 127.0.0.1 10560  -> no telemetry
    - Use netcat '#SN-001,default,temperature,25.7\n\rSN-001,default,humidity,69' || nc -q0 127.0.0.1 10560 -> telemetry 
    - Use netcat SN-001,default,temperature,25.7\n\rSN-001,default,humidity,69 || nc -q0 127.0.0.1 10560 -> telemetry found (if I change device name into SN-001)
-> I think your service stop processing message with # intial
Pls. do not ask me to provide configuration because I posted in yesterday. #3402
Pls help me fix as soon as possible because I have to integrate our customer's gps devices!
Many thanks
**Your Server Environment**

  * ThingsBoard Version: 3.1.1PE
  * OS Name and Version: Ubuntu 20.04

**Comment by Karabiy** [comment]
make sure to use the quotes for the body of the payload, so that those should work okay

**Comment by anhdv1979** [comment]
The device send without quote. pls kindly help me check your code. 
P.S: I could not ask vendor to
change firmware.

**Comment by Karabiy** [comment]
The integration is okay with the "#" on the beginning of the raw. The issue occurred because the "#" was used for the comments, so that the body for the echo command was not recognized, in case if those is being specified on the start of the body of the message, so that the message requires to have the quotes to be applied, so that there is no issue with the "#" in the beginning. 
For example, the next command is valid: 
echo -e '#SN-001,default,temperature,25.7' | nc -q0 127.0.0.1 10560
Because the message body is being allocated with the quotes, so that those is being correctly recognized by the echo command
And the next command:
echo -e #SN-001,default,temperature,25.7 | nc -q0 127.0.0.1 10560
Would not be correct because the "#" symbol just comments all the other part of the command, so that the recognized command is 
echo -e 
Also, those would work for the case when there are symbols being specified before the #, so that the body is being recognized correctly. So that the next command would work:
echo -e Symbols#SN-001,default,temperature,25.7 | nc -q0 127.0.0.1 10560

**Comment by anhdv1979** [comment]
I could not ask customer to replace their firmware.  Frankly speaking, this is not suitable answer

**Comment by Karabiy** [comment]
Those does not relate to the particular firmware. the processing for those should be an okay with the usage of the integration. above refers to the bash scripting, so that the '#' for the bash relates to the single quote comment.
