### ISSUE TITLE
[Feature Request] Cant use external Cassandra with Datastax

### ISSUE THREAD

**Issue by JoniSanchez** [thingsboard/thingsboard#3420]
Hello,

We need to connect thingsboard with an external Datastax with SSL connection. At least, the certificate of the server needs to be provided.

Currently, this is the code in the thingsboard/cassandra class "CassandraDriverOptions": 

```
@Value("${cassandra.ssl}")
private Boolean ssl;
@PostConstruct    
public void initLoader() {        
     ProgrammaticDriverConfigLoaderBuilder driverConfigBuilder =  DriverConfigLoader.programmaticBuilder();
         if (this.ssl) {            
             driverConfigBuilder.withString(DefaultDriverOption.SSL_ENGINE_FACTORY_CLASS, "DefaultSslEngineFactory");        
         }
``` 
From my understanding, we need to integrate this further configuration.

```
@Value("${cassandra.ssl}")
private Boolean ssl;
@Value("${cassandra.trustStoreLocation}")
private String trustStoreLocation;
@Value("${cassandra.trustStorePassword}")
private String trustStorePassword;
@PostConstruct    
public void initLoader() {        
     ProgrammaticDriverConfigLoaderBuilder driverConfigBuilder =  DriverConfigLoader.programmaticBuilder();
         if (this.ssl) {            
             driverConfigBuilder.withString(DefaultDriverOption.SSL_ENGINE_FACTORY_CLASS, "DefaultSslEngineFactory") 
                 .withString(DefaultDriverOption.SSL_TRUSTSTORE_PATH, this.trustStoreLocation)                    
                 .withString(DefaultDriverOption.SSL_TRUSTSTORE_PASSWORD, this.trustStorePassword); 
         }
```
It would be also nice that the keystore could be also set in the input config file.

**Comment by TrevorMuraro** [comment]
Being able to set the Cassandra keystore and truststore in thingsboard.yml would definitely be preferable to the current method, but you can use Cassandra SSL with the current setup.

If the DataStax java driver isn't provided a keystore, keystore password, truststore or truststore password, it uses the JSSE system properties. That means that you can add this to thingsboard.conf:

```
export JAVA_OPTS="$JAVA_OPTS -Djavax.net.ssl.trustStore=/etc/thingsboard/conf/thingsboard_trust.p12 -Djavax.net.ssl.trustStoreType=pkcs12 -Djavax.net.ssl.trustStorePassword=the_password"
export JAVA_OPTS="$JAVA_OPTS -Djavax.net.ssl.keyStore=/etc/thingsboard/conf/thingsboard_cassandra_client.p12 -Djavax.net.ssl.keyStoreType=pkcs12 -Djavax.net.ssl.keyStorePassword=the_password"
```

Note that this will override the default JSSE truststore, which is your Java's default cacerts. Since ThingsBoard HTTPS (using Tomcat) uses the JSSE truststore to verify its certificate, in order to not break HTTPS you will need to copy cacerts, import your Cassandra certificate into it, and make that your JSSE truststore.

You may be able to set the used cipher suites with
```
export JAVA_OPTS="$JAVA_OPTS -Djdk.tls.client.cipherSuites=SUITE_1,SUITE_2"
```
but I don't know for certain that that works. DataStax's description of the DefaultSslEngineFactory cipher-suites parameter is "This property is optional. If it is not present, the driver won't explicitly enable cipher suites on the engine, which according to the JDK documentations results in 'a minimum quality of service'."

The one Cassandra SSL parameter you definitely won't be able to change is hostname validation. It's enabled by default, and without explicitly setting it you won't be able to disable it.

**Comment by JoniSanchez** [comment]
Work done!! 
We used the following command:

```
keytool -importcert -trustcacerts -keystore /docker-java-home/jre/lib/security/cacerts -storepass <password> -noprompt -alias cassandra-cert -file <path_cert>
keytool -importcert -trustcacerts -keystore /docker-java-home/jre/lib/security/cacerts -storepass <password> -noprompt -alias cassandra-ca -file <path_ca>
```
In the config/thingboard.conf:
```
export JAVA_OPTS="$JAVA_OPTS -Djavax.net.ssl.keyStore=/tmp/certificate/identity.jks -Djavax.net.ssl.keyStoreType=jks -Djavax.net.ssl.keyStorePassword=<password>"
export JAVA_OPTS="$JAVA_OPTS -Djavax.net.ssl.trustStore=/docker-java-home/jre/lib/security/cacerts -Djavax.net.ssl.trustStoreType=jks -Djavax.net.ssl.trustStorePassword=<password>"
  ```
But now, we have other problem. The user to our Datastax it isnt admin. And we have this error:
 ```
java.lang.IllegalStateException: java.util.concurrent.ExecutionException: com.datastax.oss.driver.api.core.servererrors.UnauthorizedException: User thingsboarduser has no CREATE permission on <all keyspaces> or any of its parents
```
Is it not possible launch thingboard with user that not super-user?
Is it possible to create the different tables in the same keyspace, because of the same problem with the permissions/priviledges?

**Comment by TrevorMuraro** [comment]
You can use thingsboard with a non-super-user Cassandra role, I'm doing it in my own setup. However, manually-installed Cassandra lets non-super-user roles create keyspaces by default (I should probably change that.)

[It looks](https://github.com/JanusGraph/janusgraph/issues/933#issuecomment-374377380) like you might need to explicitly `GRANT CREATE ON ALL KEYSPACES TO thingsboarduser`, or create the thingsboard keyspace yourself and then GRANT thingsboarduser all permissions on that keyspace.
