### ISSUE TITLE
Latest Telemetry values Not Appearing using HTTP Integration on TB 3.1.1 PE running on GCP

### ISSUE THREAD

**Issue by FreddyHunter** [thingsboard/thingsboard#3461]
Hi guys, I am new on TB world, and starting to set up my production environment.

The issue I am facing is: I already setup a HTTP integration receiving a json payload from my device, and I am receving the message properly without returning error. I also created a data converter which is generating output message and metada accordingly without any error as well. The device and device type are being created automatically by HTTP integration without any problem, too. But, I am not seeing the Latest Telemetry on my device details, it is still empty. Is there something I am missing or doing wrong? Because watching the videos and reading the guides it seems to be ok. Is anybody facing the same issue? Can anybody help me?

I am running the standard installation of TB 3.1.1 PE with PostgreSQL on Google Cloud Platform.

Thanks in advance Folks!

**Comment by Karabiy** [comment]
The issue of yours seems to be related to the rule chain configurations. Please, make sure that the rule chain of yours is configured for processing in a way you want it to be.

For those reasons, please, use the debug mode for the rule nodes to be set, so that you can check the debug logs in the events tab of the rule node, so that you can get additional information regarding the processing.

You also may refer to this link regarding the debugging: https://thingsboard.io/docs/user-guide/rule-engine-2-0/overview/#debugging

Also you can check the integration "Events" the "Debug" event type, to make sure whether the messages of yours does arrive

**Comment by FreddyHunter** [comment]
Thanks.

**Comment by Karabiy** [comment]
Does the issue persists?

**Comment by FreddyHunter** [comment]
Thanks Vlad, I already solved it. I forgot to close the issue.
