### ISSUE TITLE
[Bug] Cannot select telemetry beyond `Items per page` limit

### ISSUE THREAD

**Issue by ghost** [thingsboard/thingsboard#3479]
**Describe the bug**

Cannot select telemetry beyond `Items per page` limit
for example, I want to select 35 telemetry items in `Device` tab to display on a dashboard, but the `Items per page` limit is at most 30. 

**Your Server Environment**

  * cloud or local infrastructure or docker deployment
  * ThingsBoard Version 3.1.1
  * OS Name and Version Ubuntu 18.04 LTS

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: win10 64bit
* Browser chrome
* Version  83.0.4103.116

**Your Device**

* Connectivity
  * Gateway
* Device vendor and model
Thermo fisher i48/i42 instrument

**To Reproduce**
1. device-> telemetry
2. select some telemetry attributes
3. change `Items per page`  to 30
4. click next page 

**Expected behavior**
I can keep selected telemetry attributes from last page. And add more than 30 telemetry attributes to a gadget in dashboard.

**Screenshots**
![image](https://user-images.githubusercontent.com/10754664/93418211-735a1b00-f8dc-11ea-8635-7b6361d21c98.png)

**Additional context**

**Comment by Delapouite** [comment]
I would say that the issue is broader than only telemetries. It can be applied to many other use cases, for example when you want to select all the devices of a device group but there are more than 30 of them.

So I agree with this request, in the UI there should be a way to select all "things" listed independently of the pagination. Some operations need to be performed massively and the way to do them 30 by 30 is both time consuming and error prone.

**Comment by pon0marev** [comment]
You can increase the amount of data per page in the settings, or disable pagination: 
![image](https://github.com/user-attachments/assets/6d2a7b49-ae42-4c5d-8a9d-e3d4c0629740)
However, with a large number of rows, this setting will affect performance

Another way is to specify the number of rows per page in the request.
https://DOMAIN_NAME/entities/devices/groups/54d9ca40-36af-11ee-93a3-d9f7b0df3bbc?pageSize=200
