### ISSUE TITLE
Perform mathematical function on the entirety of two or more telemetry values

### ISSUE THREAD

**Issue by WillNilges** [thingsboard/thingsboard#3494]
**Component**

 * Rule Engine

**Description**
I am trying to create a rule chain in which a device can request a totaling of several telemetry values. I have a device which reports power1, power2, and power3. I have an algorithm which would take in the entirety of that telemetry (From, say, March 2018 to March 2020) as JSON, perform some calculations, and spit out a single integer value. The originator telemetry rule node doesn't allow for more than 1000 entries, and we have W A Y more than that. Is there any other way to do this?

**Environment**

 * OS:  Linux
 * ThingsBoard: 2.4
 * Browser: Firefox 80

**Comment by Karabiy** [comment]
in case if you have no data, for now, and those will be only created, you can have the data of yours to be also duplicated as the attribute value
for example, you can have those to be stored as a string, or as a json, and append the new keys each time to use the originator attributes and get the data which is required 
you can also have a use of the ThingsBoard Rest API: https://thingsboard.io/docs/reference/rest-api/
so that you can use the getTimeseries request setting the limit the count of the telemetry datapoints at max as you are being expecting
also, you will need to use the "Rest API Call" Rule node for those purposes.

So that the next flow is required to be built: 

The message will process to a certain filtering, afters it is required to have all the enrichment and message preparation for the "REST API call" rule node, which will authorize to the ThingsBoard (making a request to receive the jwt token) and afters those jwt token can be used to be put in the headers of the request of the request of yours using the ThingsBoard "REST API call" rule node. 

Please, refer to this link regarding the external "REST API call" rule node: https://thingsboard.io/docs/user-guide/rule-engine-2-0/external-nodes/#rest-api-call-node

It is also recommended to create a separate user which credentials will be used for the REST API Call requests, for the security reasons.
