### ISSUE TITLE
[Question] how to connect to mqtt server

### ISSUE THREAD

**Issue by finyyu** [thingsboard/thingsboard#3527]
I want to check mqtt message in thingsboards，how can i connect to mqtt server?

backgroup info:  

 * Generic

**Description**
I publish some data to thingsboard by post telemetry, and these data haven't be saven to database. 

**Environment**

 * OS:  centos7.6
 * ThingsBoard: 3.1.1
 * Browser: name and version

**Comment by Karabiy** [comment]
It can be related to the misconfigured processing in the rule chains.
The issue of yours seems to be related to the rule chain configurations. Please, make sure that the rule chain of yours is configured for processing in a way you want it to be. Make sure that you have the "save timeseries" rule node to be set in the rule chains of yours. 

For those reasons, use the debug mode for the rule nodes to be set, so that you can check the debug logs in the events tab of the rule node, so that you can get additional information regarding the processing.

You also may refer to this link regarding the debugging: https://thingsboard.io/docs/user-guide/rule-engine-2-0/overview/#debugging

And to this link regarding the Rule Engine documentation: https://thingsboard.io/docs/user-guide/rule-engine-2-0/re-getting-started/

Regarding the MQTT API of the ThingsBoard to be used for the device connectivity and data transmitting purposes, you can refer for this link https://thingsboard.io/docs/reference/mqtt-api/

So that after the device creation and when you will get the access key of the device, you can use the mosquitto client for testing purposes, and use the next command to send the telemetry with this: 
mosquitto_pub -d -h "127.0.0.1" -t "v1/devices/me/telemetry" -u "$ACCESS_TOKEN" -f "telemetry-data-as-object.json"
where 
telemetry-data-as-object.json includes the next:
{   "stringKey": "value1",   "booleanKey": true,   "doubleKey": 42.0,   "longKey": 73,   "jsonKey": {     "someNumber": 42,     "someArray": [1,2,3],     "someNestedObject": {"key": "value"}   } }
--

**Comment by finyyu** [comment]
thanks at first!

The background of the question: There were about 5k devices connect to the TB Server, and 1 telemetry message per 1 device per 1s，i found that some debug info of [save timeseries] can‘t show timely, also i don't know the speed of progressing. Currently I can only check whether it is finished by stop posting telemetry continuously. 

If have one ui page to show the count of message processed, like rabbitmq admin page, it will be convenient.

**Comment by Karabiy** [comment]
Starting from the 2.5 version there is also available the dashboard with the rule chain metrics and errors to be logged. Please, refer for this link regarding those: https://thingsboard.io/docs/user-guide/rule-engine-2-0/overview/#rule-engine-statistics

Please, refer for this link for the rule engine statistics dashboard: https://raw.githubusercontent.com/thingsboard/thingsboard/master/application/src/main/data/json/demo/dashboards/rule_engine_statistics.json
