### ISSUE TITLE
Import timeseries from csv

### ISSUE THREAD

**Issue by thomas-tu1** [thingsboard/thingsboard#3558]
Hello everyone,

I would like to import a given timeseries to thingsboard from a CSV.
Afterwards I want to compare  the imported timeseries to new data.

Is there any way to import data (from CSV)?

Thank you in advance.
Thomas

**Comment by Karabiy** [comment]
for those reasons you can have a use of the ThingsBoard REST Clients in order to populate data via the ThingsBoard REST API
ThingsBoard REST API: https://thingsboard.io/docs/reference/rest-api/
Java ThingsBoard Rest Client: https://thingsboard.io/docs/reference/rest-client/
Python Rest Client: https://thingsboard.io/docs/reference/python-rest-client/
So that those data will be populated to the ThingsBoard. In case if you want your data to have the rule engine processing to be applied, you can have a use of the Integration feature (PE only) in order to populate your data. 
Please, refer to this link regarding the integration feature overview: https://thingsboard.io/docs/user-guide/integrations/
You also can refer to this link regarding how to HTTP integration particularly: https://thingsboard.io/docs/user-guide/integrations/http/
