### ISSUE TITLE
Thingsboard Startup failed

### ISSUE THREAD

**Issue by shiyazt** [thingsboard/thingsboard#3578]
**Component** 
Generic

**Environment**
Version : Thingsboard 2.2.1 PE
OS : CentOS Linux 7
Linux Kernel : 3.10
Database : Apache Cassandra 3.0

**Description**
Since we are using Thingsboard Professional Edition v2.2.1 and we have two instances one for Thingsboard Platform and another instance for Cassandra database. 

we came across with this error from browser:
![image](https://user-images.githubusercontent.com/39874957/95816328-73fb9b00-0d3c-11eb-800a-8b898779fb93.png)

We inspect the diskspace of Database instance it seems to be look like it utilized high data usage
![image](https://user-images.githubusercontent.com/39874957/95816361-88d82e80-0d3c-11eb-80d2-6bc04c10d6b1.png)

Thereafter we restarted the two instances.

**_Platform Instance restarted successfully but database instance didnt restarted successfully. Database instance state is in down state._**

**Database Instance Log:**
![image](https://user-images.githubusercontent.com/39874957/95816384-97264a80-0d3c-11eb-8a8e-861f6b15ecfc.png)

**Thingsboard Instance Error :**
Error starting Tomcatcontext.Exception:org.springframework.beans.factory.UnsatisfiedDependencyException
![image](https://user-images.githubusercontent.com/39874957/95816402-a4433980-0d3c-11eb-86b0-0da503d52eb0.png)

Any help would be much appreciated.

Thanks in advance.

**Comment by CooL16** [comment]
Please provide us with the screenshots in 1080p so we can be able to read the error message

**Comment by Karabiy** [comment]
it seems that there is an issue related to the cassandra, please, try to proceed with the Cassandra nodetool compact and the nodetool repair, so that it should be an okay after those would be applied. 
We also recommend to have an upgrade for the latest version of the ThingsBoard and migrate to the hybrid mode, so that you will also have all the bug fixes and new features of the ThingsBoard product. You can refer to the ThingsBoard release notes via this link: https://thingsboard.io/docs/reference/releases/
And also for this link regarding the on how to proceed with an upgrade: https://thingsboard.io/docs/user-guide/install/pe/upgrade-instructions/

**Comment by trypzz** [comment]
closed due to inactivity
