### ISSUE TITLE
Stop Drawing Line When No Data Received

### ISSUE THREAD

**Issue by sandonet13** [thingsboard/thingsboard#358]
Hello, i'm just recently using Thingsboard, is it possible to stop drawing line in timeseries chart if there is no data received, this is the example

![Image of Sensor](https://imgur.com/download/ErOtnsP)

That line is supposed to be cutted line until i started the data stream again, but it still there.
How can i achieve this requirement ? thank you.

**Comment by ashaforost** [comment]
To achieve this effect you can go to the advanced tab of the line chart settings and uncheck the hover individual points option.

**Comment by muhakmalfadh** [comment]
I can't see the '[Hover Individual Points](https://thingsboard.io/docs/pe/user-guide/widgets/#:~:text=Tooltip%20settings-,Hover%20individual%20points,-.%20When%20the%20box)' option. @ashaforost, has it been removed? I need this option because I'm encountering the same issue as @sandonet13.

![Image](https://github.com/user-attachments/assets/7ef8d613-898c-4192-91f6-8341ed9c7359)
