### ISSUE TITLE
Migration from AWS ec2 to Google Cloud Platform

### ISSUE THREAD

**Issue by destr1ke** [thingsboard/thingsboard#3611]
Hi there! Please tell me how to properly migrate Thingsbord from **AWS ec2** to **Google CLoud Platform** with saving data and platform configuration. I will be grateful for any advice , Thanks!

**Comment by Karabiy** [comment]
Hello 
For those reasons you need to back up the databases of yours for the current ThingsBoard you are running and then move those to the server, you want the ThingsBoard to run on. 
You can refer to this link for on how to proceed with the backup: https://thingsboard.io/docs/user-guide/install/pe/upgrade-instructions/#prepare-for-upgrading-thingsboard-centos-ubuntu
And then it is required to unpack the backup on the new server. 
After those, please, proceed with the installation of the same version of the ThingsBoard which you have to run on for the AWS ec2 and in case if you are running the ThingsBoard Professional Edition it is also required to deactivate ( NOT TO DELETE ) the instance, so that you will be able to start the ThingsBoard on the instance you migrated to

**Comment by ashvayka** [comment]
Also, one should backup contents of the /etc/thingsboard/conf folder and move them to new server as well. You should move them only after you have installed the same thingsboard version on the second server. So, the flow is like this:
1) Install same ThingsBoard version on the second server.
2) Move the database(s)
3) Copy the configuration files from /etc/thingsboard/conf

**Comment by joelwembo** [comment]
This was helpful to me as I was migrating some my company data from AWS EC 2 to google cloud
