### ISSUE TITLE
how can i create my own table in thingsboard  postgres DB and  query that in rule chain?

### ISSUE THREAD

**Issue by mohsenzare9485** [thingsboard/thingsboard#3614]
**hello every body**
how can i create my own table in thingsboard  postgres DB and  query that in rule chain?
for example create table named "customTable " in postgres DB and define fields and rows manually and 
in rule chain :
1. get data with a query like: select * from customTable where ...  
2. and then use this data for filter scrip in rule chain .

thanx a lot 

* Rule Engine

**Comment by mohsenzare9485** [comment]
any help?

**Comment by Karabiy** [comment]
for those reasons you will need to have the additional development. The custom rule node can be created, as an enrichment rule node like, in order to get the data from the table and the action rule node can be created for the save reasons.
you can refer to this link for the custom rule node option: https://thingsboard.io/docs/user-guide/contribution/rule-node-development/

**Comment by mohsenzare9485** [comment]
tanx a lot

**Comment by scadaway** [comment]
> tanx a lot 

Hello, were you able to communicate with the custom table?
