### ISSUE TITLE
Filter in thingsboard dashboard

### ISSUE THREAD

**Issue by sonychoudhary** [thingsboard/thingsboard#3622]
**Component**

 * Generic

**Description**
 I want to filter my data based on the values in the field. Suppose I have 3 entity timeseries data which contains building name, temperature and sensor data.So it may happen that in some packets only the temperature will come and not the sensor data and sometimes both will come together so I want to display only those rows which has both the data . I m looking for any document on how to use this filter?

**Environment**
 * OS:  ubuntu
 * ThingsBoard: 3.1.2
 * Browser: chrome
image link: https://i.stack.imgur.com/ZK8rC.png
https://i.stack.imgur.com/htrqE.png

**Comment by Delapouite** [comment]
Hello. You can find a bit of information in this video from last month: https://www.youtube.com/watch?v=yTAhUpZiFkM&t=181s

**Comment by sonychoudhary** [comment]
I want to know to to set filter to only display rows where name is defined and don't show the undefined rows in the table and as show in the video i tried filtering data based on battery level i.e; value less than 67 but it shows battery level 100 after filtering is applied.
![Capture](https://user-images.githubusercontent.com/42209904/97083335-e7e74e80-162c-11eb-8d05-bcfdf6ffaa1c.PNG)
![batt](https://user-images.githubusercontent.com/42209904/97083396-47455e80-162d-11eb-92ac-360092bbabe5.PNG)
![cap2](https://user-images.githubusercontent.com/42209904/97083397-47ddf500-162d-11eb-9cef-3a2ff3b6506f.PNG)

**Comment by aicastianhai** [comment]
I have the same problem using the filters on Entity Timeseries Table (Thingsboard 3.2.0). It seems this issue is closed, @sonychoudhary, could you please so kind to tell me the solution?

**Comment by jinsu-radata** [comment]
@aicastianhai, Could you please tell me the solution?

**Comment by GrayCygnus** [comment]
Posting here (and [here](https://github.com/thingsboard/thingsboard/issues/5455)) with the hopes that this helps somebody. I contacted TB support (we pay professional edition at my work) and they confirmed that this is not possible. Quoting:

> Overall, the behavior you request cannot be implemented via thingsboard’s default functionalities, as it contradicts the initial design of the platform

and

> By ThingsBoard design, the widget’s historic timeseries cannot be filtered based on the timeseries values. Filters can only be applied to the latest timeseries, attributes, and entity fields.

I have a partial workaround: on the Advanced Settings of the widget, on the Row Style, you should return {display: 'None'}; on the rows that match your filtering condition.

I said partial because this successfully hides the rows one wants to filter, but (1) the row count at the bottom of the widget still displays the total number of rows (including the ones hidden) and (2) when you export to csv or similar the hidden rows are downloaded along the rows that are not hidden.

In case you only wish to hide them visually, then I think this workaround will suffice.

**Comment by devdoob** [comment]
Intelligent.

> [GrayCygnus](/GrayCygnus)
