### ISSUE TITLE
How to Backup From All thingsboard Data

### ISSUE THREAD

**Issue by mohsenzare9485** [thingsboard/thingsboard#3641]
Hello
I'm using thingsboard 2.4.3 and postgres Databse 
How can i Backup from all thingsboard Data include devices,dashboard,Assets ,time Series Data and other data?
i back up from postgres database and restore it on other system but thingsbaord doesn't work properly
thanx a lot

**Comment by Karabiy** [comment]
Hello
For those reasons you need to back up the databases of yours for the current ThingsBoard you are running and then move those to the server, you want the ThingsBoard to run on.
You can refer to this link for on how to proceed with the backup: https://thingsboard.io/docs/user-guide/install/pe/upgrade-instructions/#prepare-for-upgrading-thingsboard-centos-ubuntu
And then it is required to unpack the backup on the new server.
After those, please, proceed with the installation of the same version of the ThingsBoard which you have to run on for the current host of yours and in case if you are running the ThingsBoard Professional Edition it is also required to deactivate ( NOT TO DELETE ) the instance, so that you will be able to start the ThingsBoard on the instance you migrated to

Also, one should backup contents of the /etc/thingsboard/conf folder and move them to new server as well. You should move them only after you have installed the same thingsboard version on the second server. So, the flow is like this:

Install same ThingsBoard version on the second server.
Move the database(s)
Copy the configuration files from /etc/thingsboard/conf

**Comment by dip-devlopement** [comment]
you are using a containerised thingsboard?
