### ISSUE TITLE
[Question] Import custom dashboard and rules chains automatically

### ISSUE THREAD

**Issue by Stimaleger** [thingsboard/thingsboard#3654]
**Component**

 * Generic

**Description**
Today I use thingsboard with doker and I was wondering:
 - is it possible to make thingsboard load my custom dashboard / decoder and rules chains at startup by specifying a folder containing our developpement ? or something like that ?

In other word how should I manage the versioning of our thingsboard development ? In order to tag and deploy my solution quickly  ? An do not load my development manually as I am currently doing.

**Environment**

 * OS:  ubuntu 18.04 LTS
 * ThingsBoard: 2.4.3

**Comment by Karabiy** [comment]
The dashboard same as the rule chains are being set within the database. For the deployment automation purposes, you can have the default database to be set up and move those along with the thingsboard service. 
One more option, in order to prevent the new deployments requirement is to have a use of the multitenancy feature: https://thingsboard.io/docs/user-guide/ui/tenants/

**Comment by Stimaleger** [comment]
@Karabiy thx for the support.
Well, I thing using postgresql init script I can automatically load my thingsboard developpment
