### ISSUE TITLE
Static widget size

### ISSUE THREAD

**Issue by fotis400** [thingsboard/thingsboard#377]
Sometimes I need to use static widgets in the dashboards. Inside these widgets I add HTML and/or javascript code.

The size of this widget changes according to the window size (in case of mobile, or very small screen etc..). The content within this widget has also to change and adapt to the actual size (i.e. images or fonts resize etc).

How can the code running in this widget know the dimensions of the widget itself? How can the size of this widget get locked, so it cannot change? Or at least specify a minimum and/or maximum dimension?

**Comment by vparomskiy** [comment]
we are using gridster for the widget scaling. You can use it to determine current widget dimensions

**Comment by hjlopezr** [comment]
Hi @vparomskiy  how to access to gridster?
I'm working with bootstrap 4 cards, i need to adjust the widget height, as of number of cards.
Regards!

**Comment by bskrt** [comment]
I'm also pretty interested in this.
In general the grid system is great, but it would be very welcome to have a way to disable the automatic height resizing.

I tried setting a fixed height in de widget style, but then the automatic repositioning screws things over.

**Comment by bskrt** [comment]
**Found a hacky way to do this.**

In your widgets javascript, all gridster options are available through:
`self.ctx.dashboard.gridsterOpts`

You can do a console.log() of those options to see how they are set by Thingsboard.
For references [here](https://github.com/ManifestWebDesign/angular-gridster/blob/master/README.md)'s a list of all available options.

So to fix my current height issue, I set the `self.ctx.dashboard.gridsterOpts.rowHeight = 60;` to a specific value in the `self.onResize`function. *You only need to set this in one of your widgets.*

**warning:** Because we set options onResize they will also trigger on mobile, so the `mobile row height` setting in the dashboard setting will also get overwritten.

_note:_ I initially changed the gridsterOpts in the `self.onInit`function, but noticed that this gave issues whenever the window was resized to mobile width and back.
This is very likely related to the fact that on mobile, the row height gets set to a fixed height already, and gets reset to default when resizing to desktop width again.

**Comment by hjlopezr** [comment]
Thanks @bskrt i will test this.
Regards!

**Comment by Karabiy** [comment]
> **Found a hacky way to do this.**
> 
> In your widgets javascript, all gridster options are available through:
> `self.ctx.dashboard.gridsterOpts`
> 
> You can do a console.log() of those options to see how they are set by Thingsboard.
> For references [here](https://github.com/ManifestWebDesign/angular-gridster/blob/master/README.md)'s a list of all available options.
> 
> So to fix my current height issue, I set the `self.ctx.dashboard.gridsterOpts.rowHeight = 60;` to a specific value in the `self.onResize`function. _You only need to set this in one of your widgets._
> 
> _note:_ I initially changed the gridsterOpts in the `self.onInit`function, but noticed that this gave issues whenever the window was resized to mobile width and back.
> This is very likely related to the fact that on mobile, the row height gets set to a fixed height already, and gets reset to default when resizing to desktop width again.
you may refer to this regarding the solution for the reasons of yours

**Comment by yogamuliawan** [comment]
I've found a tricky way to do it by changing the height via xpath address

Use the below function to get the Element and set the height using `style.property = value`

```
getElementByXpath = function(xpathfullpath) {
  return document.evaluate(xpathfullpath, document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;
}

```
Goodluck Guys! 😊
