### ISSUE TITLE
[Question] [Community Edition] Change xaxis to group by actual day and not by time

### ISSUE THREAD

**Issue by AnnieBts** [thingsboard/thingsboard#3822]
**Component**
 * Generic

**Description**

I want to change bar chart so that it would get the actual date on x Axis. It currently grouping by time so if you change it to days, it's grouping every 24 hours. So if it's currently 3 o'clock, the last day would start from 3 o'clock yesterday. This messes with my data. Is there any way to change it?

**Environment**
 * ThingsBoard: community edition

**Comment by garageeks** [comment]
@ikulikov we have the same issue. Grouping functions "Last 7 days" and "Last 30 days" shouldn't affected by the time of the day. They should start at midnight of the selected device timezone.
Because of this, the total value calculated by the timeseries graph is messed up, because our counter is reset at midnight.
I had a look at the source code, looks like the UI is calculating the time interval in milliseconds, that it is passed to the backend. Therefore it appears to be only a UI code change, it would be great if you could add this option in the Advanced settings.

**Comment by ashvayka** [comment]
Hi @AnnieBts ,
Since version 3.2.2, it is possible to use predefined intervals (Current Day, Previous Day, Previous Month, etc.) in addition to last X minutes/hours/days. Note that the Current day interval means 24 hours (12 am at night to 12 am the next night), whereas the Current day so far means from 12 am at night until the time when the time window was updated. All other intervals are distinguished in the same way.
Version 3.2.2 introduces time zone configurations. By default, dashboard uses the time zone provided by the browser. Now it is possible to set the time of your browser or a specific country. To quickly find the needed time zone, start typing its name in the time zone bar.

See more info here: https://thingsboard.io/docs/user-guide/dashboards/#time-window
