### ISSUE TITLE
no generated the class file?

### ISSUE THREAD

**Issue by zth390872451** [thingsboard/thingsboard#3876]
env:
tb-3.2.0-release 
jdk 1.8

![20201221174650](https://user-images.githubusercontent.com/13637039/102763400-8d603980-43b4-11eb-8dc7-914c90736131.png)

why the queue.proto file can not generate the class file ?
but when I delete the message UsageStatsKVProto and ToUsageStatsServiceMsg,it can generated the class file successfully.

**Comment by agtokty** [comment]
Hi @zth390872451 , this is a common issue because of IntelliJ IDEA. The generated java file size bigger than max size evaluated by IDE, so you need to increase related settings values.

Add the following settings to you idea.properties file. To open this file on IntelliJ , go to **Help** -> **Edit Custom Properties**.

`idea.max.content.load.filesize=3000`
`idea.max.intellisense.filesize=3000`

Hope that helps you.

**Comment by ashvayka** [comment]
@agtokty is correct!

**Comment by codeHui** [comment]
how to generate Java files? any one help?
now I can not run my project because there are no java file of the Proto file
why they don't commit the Proto  java file, this way would be easiyer
