### ISSUE TITLE
[Bug] E-Mail settings: can't save password

### ISSUE THREAD

**Issue by jonrot1906** [thingsboard/thingsboard#3892]
**Describe the bug**
Can't insert an email password into the Admin mail settings. When inserted and Test mail is clicked, everything is working out fine. When pressing "save" the mail password just vanishes and the new settings are not applied.

**Your Server Environment**
* own setup
  * docker deployment
  * ThingsBoard Version: 3.2.0 CE
  * OS Name and Version: Ubuntu 20.04

**Expected behavior**
I'd expect to still be able to edit my mail server password settings.

**Comment by ashvayka** [comment]
Hi @jonrot1906 . This is a painful usability bug, but the actual password is saved. The issue here is that this is how we implemented the requirement to hide the password once it is saved. So, when you hit "test" or "save" the password is sent to the server and then the field is cleared. So, to save the password you need to copy-paste or type it into the form and click save. If you hit "Test" you will need to input the password again. I understand that this is not really usable and we will improve it in 3.2.1 or 3.3.

**Comment by jonrot1906** [comment]
> Hi @jonrot1906 . This is a painful usability bug, but the actual password is saved. The issue here is that this is how we implemented the requirement to hide the password once it is saved. So, when you hit "test" or "save" the password is sent to the server and then the field is cleared. So, to save the password you need to copy-paste or type it into the form and click save. If you hit "Test" you will need to input the password again. I understand that this is not really usable and we will improve it in 3.2.1 or 3.3.

Thanks for coming back to this issue, I can confirm that the password is saved when trying out other features (like password reset). As this is more a convenience issue and not a functional one, I'll close this request. Thanks again!

**Comment by Manusisko** [comment]
This is not the case on TB3.2PE. The password might be saved on the database in the admin_settings table, key=mail, json_value reads through the REST Api as
![image](https://user-images.githubusercontent.com/39056975/104337878-b451ed00-54d4-11eb-8a19-39d228d4c969.png)

We cannot leave this issue hanging, what is a workaround for this?

**Comment by JacksonBowe** [comment]
This issue is not closed. The password is not getting saved, it is being discarded. 

I can paste a password in and hit "Send Test mail" and it works. If i click "Save" and then again hit "Send Test Mail" it errors.
Error Code: "unable to send mail 535 5.7.3 Authentication Unsuccessful" 

What I think is happening? When clicking "Save", it empties the Password field and then sends the empty string to the server, updating the password to "".

This is a huge issue. Mail servers are not functional until this is resolved. I can't send activation emails to my customers.

For reference, I am using TB PE 3.1.1.
