### ISSUE TITLE
cannot get web UI started

### ISSUE THREAD

**Issue by DanwithArduino** [thingsboard/thingsboard#39]
After following directions at https://thingsboard.io/docs/user-guide/install/linux/, including Oracle JDK8, i am not getting a response on the web side. Additionally, i am getting the following errors:

> 2017-01-26 03:49:35,344 [main] ERROR o.s.boot.SpringApplication - Application startup failed
> 2017-01-26 03:59:19,767 [main] ERROR o.s.boot.SpringApplication - Application startup failed
> 2017-01-26 04:04:08,063 [Thingsboard Cluster-reconnection-0] ERROR c.d.driver.core.ControlConnection - [Control connection] Cannot connect to any host, scheduling retry in 1000 milliseconds
> 2017-01-26 04:04:09,064 [Thingsboard Cluster-reconnection-0] ERROR c.d.driver.core.ControlConnection - [Control connection] Cannot connect to any host, scheduling retry in 2000 milliseconds
> 2017-01-26 04:04:11,875 [main] ERROR o.s.boot.SpringApplication - Application startup failed

Any help would be greatly appreciated. Moving on from the digital ocean "phant" server, looking forward to having a more capable and better supported system up and running. 

Additionally, i was not able to install any of the database schema / initial data. Not sure if these issues are related... 

thanks
dan

**Comment by ashvayka** [comment]
Please make sure that you have 
1) installed cassandra, 
2) it is working (try cqlsh tool or similar)
3) you have imported schema and data [from the installation step](https://thingsboard.io/docs/user-guide/install/linux/#provision-database-schema-and-initial-data)

If you will have other installation issues, ping us on [gitter](gitter.im/thingsboard/chat) and we will try to help. 

Closing this because this is definately installation issue.
