### ISSUE TITLE
[Question] How can I have remote access to Cassandra db through the [thingsboard/tb-cassandra] docker instance?

### ISSUE THREAD

**Issue by Hamed-Hasibi** [thingsboard/thingsboard#3905]
**Component**

 * Generic

**Description**
I want to have remote access to Cassandra time series DB so I do the followings:

1. Running docker container from thingsboard/tb-cassandra image file with exposing port 9042:9042 for remote access.
2. Having local access to Cassandra with the following command: docker exec -it [container id] bash
3. Then using cqlsh to connect to DB successfully and seeing time-series data through container
4. Pinging container from a remote host leads to successful
5. **But** using cqlsh tool on remote host (and even host which running container): cqlsh [container IP] => result: connection refused

Is there any specific username/password for Cassandra DB? or any other problem?

**Environment**

 * OS:  Docker Engine - Community Version: 20.10.1 on Ubuntu
 * ThingsBoard: thingsboard/tb-cassandra:3.2.0
 * Browser: Google Chrome Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by ashvayka** [comment]
Please attach your docker file. I suspect that the issue is with the Cassandra listen-address which is localhost and thus your cassandra will not be available. You can build your own docker image or go to the container file system and change this setting. In any case, this is not recommended and you should just use docker-compose setup and separate Cassandra and ThingsBoard. The thingsboard/tb-cassandra image is created to simplify the getting started process.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
