### ISSUE TITLE
Fix JWT Token

### ISSUE THREAD

**Issue by nmahale10** [thingsboard/thingsboard#3986]
Is it possible to fix the JWT Token without expiration.

 How can we get JWT Token in Rule Engine

**Comment by ashvayka** [comment]
Hi @nmahale10 , it is possible to fix it by increasing the JWT token expiration time to 100 years, for example. See "Security parameters" in https://thingsboard.io/docs/user-guide/install/config/.

There is no way to get the JWT Token in the Rule Engine, since JWT Token is related to user requests and not to the backend processing logic.

**Comment by nmahale10** [comment]
Tahnks a lot @ashvayka .
