### ISSUE TITLE
How to enable again Custom Menu after disabling it through disabledMenuItems

### ISSUE THREAD

**Issue by FreddyHunter** [thingsboard/thingsboard#4098]
**Component**

 * UI

**Description**
I was disabling custom_translation menu, but wrongly typed custom_menu as a customer administrator account. As system administrator I still seeing it full menu, but not when accessing this specific customer account. How can I re-enable custom menu again for this account? Thanks

**Environment**
 * OS:  Ubuntu 18.04
 * ThingsBoard: 3.2.1
 * Browser: Chrome

**Comment by vvlladd28** [comment]
You need to the login of tenant account and find this customer. Open customer details and find Server attributes: `customMenu`. Edit or delete it.

**Comment by FreddyHunter** [comment]
Thanks for your reply.

**Comment by FreddyHunter** [comment]
Hi Vladyslav, I was able to return custom menu of my system administrator user at tenant portal, but how can I return it when I disable it for a customer administrator user? I tried to search the custom menu attribute for the customer administrator group and user, but it wasn't there like on the Tenant portal for the System Admin. Any tip?

**Comment by vvlladd28** [comment]
Hi @FreddyHunter,
Maybe your resolve ploblem, opening page custom menu for link `/settings/customMenu`

**Comment by jlhulbert** [comment]
I have to say this is a horrible workaround.  This means if you want to hide the default menus from your customer admins, they could use this workaround to enable them again.  There should be a way for the Tenant Admin to modify the menu for all customer accounts without having to do it as the Customer Admin.  Or I suppose you could keep the Customer Admin account a secret and only allow the Tenant Admins that information.  However, there should be a better way to manage menus.  If you know if a way, please share, otherwise please look into a better solution for future versions.

**Comment by Ultrazombie** [comment]
closed due to inactive
