### ISSUE TITLE
[Bug] TB 2.5.6. Rule chain node triples messages

### ISSUE THREAD

**Issue by IoTopenTech** [thingsboard/thingsboard#4106]
**Describe the bug**
In a rule chain, a node that only receives 1 message triples it processing it 3 times.
There is nothing special in these script nodes.

**Your Server Environment**

* own setup
  * cloud deployment
  * ThingsBoard Version 2.5.6
  * OS Name and Version Ubuntu
![imagen](https://user-images.githubusercontent.com/52624907/107963113-0ab8bc80-6fa8-11eb-8e8f-6e6f97dc6109.png)

**Comment by ashvayka** [comment]
What is your message rate? There might be a case that not all messages are logged in debug (due to rate limits). This can explain the issue. 

The difference between the messages arrive at the first node and the second one is few seconds. The other possible explanation is that you have a "retry policy" and your message is not processed correctly. I may guess that the output of the first node has multiple "Success" relations. In this case, the original message is acknowledged, and new message is created. If the new message is not processed correctly in the further rule nodes, rule engine may try to reprocess it (depends on the [processing strategy](https://thingsboard.io/docs/user-guide/rule-engine-2-0/overview/#queue-processing-strategy) configured for your rule engine).

**Comment by IoTopenTech** [comment]
Thank you very much @ashvayka 
I am not sure whether I understand the queue processing strategy after reading the documentation.
If I enter the sequentialByOriginator queue and downstream there is a timeout (for example an smtp timeout), the rule engine will reprocess the message?
![imagen](https://user-images.githubusercontent.com/52624907/107984400-29c74680-6fc8-11eb-894e-2c9560b7048f.png)

**Comment by ashvayka** [comment]
Yes, if there is a timeout or failure, the rule engine will try to reprocess the message 3 times for SequentialByOriginator queue. But SMTP rule node is in a different "path", so it should not cause this reprocessing. It ay cause reprocessing only for the message that goes through that path. Maybe you have a timeout or failure on "change originator" rule node that is just after "pre.. accounting" node.  Please enable debug on the rule nodes and check what happens there.
