### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by zth390872451** [thingsboard/thingsboard#4151]
**_When I used the following code to test proto protocol:GetAttributeRequestMsg , I found a problem!_**

> TransportProtos.GetAttributeRequestMsg msg = TransportProtos.GetAttributeRequestMsg
                .newBuilder()
                .addAllSharedAttributeNames(CollUtil.newArrayList("loc_freq","dev_info"))
                .addAllClientAttributeNames(CollUtil.newArrayList("dev","dev_info2"))
                .build();
        client.setCallback(new CustomTbMqttCallback());
        client.publish(DEVICE_ATTRIBUTES_REQUEST_TOPIC_PREFIX+1,msg.toByteArray(),1,false);

### **So I looked at the code and found that data conversion is different from other places：**

> public static TransportProtos.GetAttributeRequestMsg convertToGetAttributeRequestMessage(byte[] bytes, int requestId) throws InvalidProtocolBufferException, RuntimeException {
         TransportApiProtos.AttributesRequest proto = TransportApiProtos.AttributesRequest.parseFrom(bytes);
        TransportProtos.GetAttributeRequestMsg.Builder result = TransportProtos.GetAttributeRequestMsg.newBuilder();
        result.setRequestId(requestId);
        String clientKeys = proto.getClientKeys();
        String sharedKeys = proto.getSharedKeys();
        if (!StringUtils.isEmpty(clientKeys)) {
            List<String> clientKeysList = Arrays.asList(clientKeys.split(","));
            result.addAllClientAttributeNames(clientKeysList);
        }
        if (!StringUtils.isEmpty(sharedKeys)) {
            List<String> sharedKeysList = Arrays.asList(sharedKeys.split(","));
            result.addAllSharedAttributeNames(sharedKeysList);
        }
        return result.build();
    }

**### So I modified my code, tested it, and it worked，here is my code updated:**

> public static TransportProtos.GetAttributeRequestMsg convertToGetAttributeRequestMessage(byte[] bytes, int requestId) throws InvalidProtocolBufferException, RuntimeException {
        TransportProtos.GetAttributeRequestMsg requestMsg = TransportProtos.GetAttributeRequestMsg.newBuilder().mergeFrom(bytes).build();
        return requestMsg;
}
I wonder why I use this code. My modification is right

> TransportApiProtos.AttributesRequest proto = TransportApiProtos.AttributesRequest.parseFrom(bytes);

**Comment by zth390872451** [comment]
and here it still use json?
@Override
    public TransportProtos.PostTelemetryMsg convertToPostTelemetry(MqttDeviceAwareSessionContext ctx, MqttPublishMessage inbound) throws AdaptorException {
        DeviceSessionCtx deviceSessionCtx = (DeviceSessionCtx) ctx;
        byte[] bytes = toBytes(inbound.payload());
        Descriptors.Descriptor telemetryDynamicMsgDescriptor = getDescriptor(deviceSessionCtx.getTelemetryDynamicMsgDescriptor());
        try {
     //                  return TransportProtos.PostTelemetryMsg.parseFrom(bytes);
 return JsonConverter.convertToTelemetryProto(new JsonParser().parse(dynamicMsgToJson(bytes, telemetryDynamicMsgDescriptor)));
        } catch (Exception e) {
            throw new AdaptorException(e);
        }
    }

**Comment by ShvaykaD** [comment]
> **_When I used the following code to test proto protocol:GetAttributeRequestMsg , I found a problem!_**
> 
> > TransportProtos.GetAttributeRequestMsg msg = TransportProtos.GetAttributeRequestMsg
> > .newBuilder()
> > .addAllSharedAttributeNames(CollUtil.newArrayList("loc_freq","dev_info"))
> > .addAllClientAttributeNames(CollUtil.newArrayList("dev","dev_info2"))
> > .build();
> > client.setCallback(new CustomTbMqttCallback());
> > client.publish(DEVICE_ATTRIBUTES_REQUEST_TOPIC_PREFIX+1,msg.toByteArray(),1,false);
> 
> ### **It doesn't get me the right data I want。**
> ### **So I looked at the code and found that data conversion is different from other places：**
> > public static TransportProtos.GetAttributeRequestMsg convertToGetAttributeRequestMessage(byte[] bytes, int requestId) throws InvalidProtocolBufferException, RuntimeException {
> > TransportApiProtos.AttributesRequest proto = TransportApiProtos.AttributesRequest.parseFrom(bytes);
> > TransportProtos.GetAttributeRequestMsg.Builder result = TransportProtos.GetAttributeRequestMsg.newBuilder();
> > result.setRequestId(requestId);
> > String clientKeys = proto.getClientKeys();
> > String sharedKeys = proto.getSharedKeys();
> > if (!StringUtils.isEmpty(clientKeys)) {
> > List clientKeysList = Arrays.asList(clientKeys.split(","));
> > result.addAllClientAttributeNames(clientKeysList);
> > }
> > if (!StringUtils.isEmpty(sharedKeys)) {
> > List sharedKeysList = Arrays.asList(sharedKeys.split(","));
> > result.addAllSharedAttributeNames(sharedKeysList);
> > }
> > return result.build();
> > }
> 
> **### So I modified my code, tested it, and it worked，here is my code updated:**
> 
> > public static TransportProtos.GetAttributeRequestMsg convertToGetAttributeRequestMessage(byte[] bytes, int requestId) throws InvalidProtocolBufferException, RuntimeException {
> > TransportProtos.GetAttributeRequestMsg requestMsg = TransportProtos.GetAttributeRequestMsg.newBuilder().mergeFrom(bytes).build();
> > return requestMsg;
> > }
> > I wonder why I use this code. My modification is right
> 
> > TransportApiProtos.AttributesRequest proto = TransportApiProtos.AttributesRequest.parseFrom(bytes);

Hi, 

Seems like your test is not valid, because, in order to request attributes from the server with Proto transport payload type enabled for your device, we use another proto message as MQTT message payload for publishing request on the next topic: "v1/devices/me/attributes/request/$request_id".

where $request_id is your integer request identifier.

GetAttributeRequestMsg used internally only to convert incoming data from the device over MQTT transport and it unrelatable to incoming payload type JSON or Protobuf. In the JSON type enabled, we are converting incoming payload from JSON to GetAttributeRequestMsg. In the Proto type enabled, we are converting  incoming payload from
TransportApiProtos.AttributesRequest to  TransportProtos.GetAttributeRequestMsg

So in order to receive attributes from the server, you need to send a valid attributes request that will use the TransportApiProtos message 
as MQTT message payload:

message AttributesRequest {
  string clientKeys = 1;
  string sharedKeys = 2;
}

, where clientKeys and sharedKeys are comma-separated lists of attribute names, that also used when you publish data using JSON transport payload type.

**Comment by ShvaykaD** [comment]
Hi @zth390872451 

> and here it still use json?
> @override
> public TransportProtos.PostTelemetryMsg convertToPostTelemetry(MqttDeviceAwareSessionContext ctx, MqttPublishMessage inbound) throws AdaptorException {
> DeviceSessionCtx deviceSessionCtx = (DeviceSessionCtx) ctx;
> byte[] bytes = toBytes(inbound.payload());
> Descriptors.Descriptor telemetryDynamicMsgDescriptor = getDescriptor(deviceSessionCtx.getTelemetryDynamicMsgDescriptor());
> try {
> // return TransportProtos.PostTelemetryMsg.parseFrom(bytes);
> return JsonConverter.convertToTelemetryProto(new JsonParser().parse(dynamicMsgToJson(bytes, telemetryDynamicMsgDescriptor)));
> } catch (Exception e) {
> throw new AdaptorException(e);
> }
> }

Hi @zth390872451,

No, for telemetry and attributes upload over MQTT with Proto payload enabled you to have the ability to set up the proto schemas for each publishes type in the device profile transport configuration:

![image](https://user-images.githubusercontent.com/16356590/108990401-7cc38c80-769f-11eb-822d-d29df7c12808.png)

For each schema, we create DynamicMessage descriptors in order to parse incoming MqttPublishMessage to DynamicMessage that after that we convert to TransportProtos.PostTelemetryMsg and TransportProtos.PostAttributeMsg in accordance.

**Comment by zth390872451** [comment]
ok，thankyou!
