### ISSUE TITLE
attributeUpdates via (plain) MQTT

### ISSUE THREAD

**Issue by iw2lsi** [thingsboard/thingsboard#4182]
Hi,

   does anybody know if [attribute updates](https://thingsboard.io/docs/iot-gateway/config/mqtt/?MqttConverterTypeConfig=custom) is available also when using the gateway with a custom converter (CustomMqttUplinkConverter ) ?
I'm trying to setup a plain-text (ie non json-based) mqtt converter and everything seems to work except for the attribute section in mqtt.json... 

  "attributeUpdates": [
    {
      "deviceNameFilter": "SmartMeter.*",
      "attributeFilter": "uploadFrequency",
      "topicExpression": "sensor/${deviceName}/${attributeKey}",
      "valueExpression": "{\"${attributeKey}\":\"${attributeValue}\"}"
    }
  ]

frankly I do not understand what each key is representing here... my attribute/topics are in plain-text and looks like:

mosquitto_pub -q 1 -h my.broker.com -p "1883" -t "tele/ME99/211df8/version" -m "x.y.z"
mosquitto_pub -q 1 -h my.broker.com -p "1883" -t "tele/ME99/211df8/protocol" -m "1.0"

etc etc

    any hints ?

             Giampaolo

**Comment by ssakharova** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
Please re-create a new ticket in GitHub thingsboard gateway issues (https://github.com/thingsboard/thingsboard-gateway/issues) with detailed steps to reproduce if this problem still exists.
