### ISSUE TITLE
Dashboard state : Open in separate dialog using custom action

### ISSUE THREAD

**Issue by innoagg** [thingsboard/thingsboard#4292]
I am re-posting this issue as I was not clear enough in the previous post : [#4223](https://github.com/thingsboard/thingsboard/issues/4283)

How does one "Navigate to new dashboard state" using a widget custom action AND "Open in separate dialog"?

I am trying to do this in a custom action script using the IStateController. Is there a modified call to "updateState" to have the state appear as separate dialog?

`var params = widgetContext.stateController.getStateParams();
params.timeIndex = additionalParams[0];
stateId = "intellivms_viewer";
widgetContext.stateController.updateState(stateId, params, true);`

The docs don't seem to address the added feature to open state in separate dialog using code.

Environment:
ThingsBoard: 3.2.1

**Comment by vvlladd28** [comment]
Hi @innoagg,
At this time, the Open in separate dialog feature cannot be used by your custom action.

**Comment by agyllang** [comment]
Hi, if/when will "open in separate dialog using custom action" be available?

**Comment by dhaval2017** [comment]
I think this option is available in thingsboard PE

**Comment by FrancescoMenga** [comment]
Hi @ashvayka,
Since I needed this function for a project of ours, i developed it for our platform (TB 3.2.2), it might work on your too:
To create a custom dialog you have to create an action from your widget, and select "Custom action with HTML template".
When the environment is set up you have to insert this code:
`<form style="min-width:{{dialogWidthCalc}}px; min-height:{{dialogHeightCalc}}px; background-color:#0A1739">
    <mat-toolbar fxLayout="row" color="primary" style="height: 60px">
        <h2></h2>
        <span fxFlex></span>
        <button mat-icon-button (click)="cancel()" type="button">
            <mat-icon class="material-icons">close</mat-icon>
        </button>
    </mat-toolbar>
    <mat-progress-bar color="warn" mode="indeterminate" *ngIf="isLoading$ | async">
    </mat-progress-bar>
    <embed src="DASHBOARD_SOURCE"
               style="height:100%; width:100%; min-height:{{embedHeight}}px"/>
</form>`

^^ HTML Code

`let $injector = widgetContext.$scope.$injector;
let customDialog = $injector.get(widgetContext.servicesMap.get('customDialog'));
openEditEntityDialog();

function openEditEntityDialog() {
    url = "/dashboard/da0083b0-4df0-11ed-8bf1-d3df0f3458d1"
    htmlTemplate = htmlTemplate.replace("DASHBOARD_SOURCE", url)
    customDialog.customDialog(htmlTemplate, EditEntityDialogController).subscribe();
}

function EditEntityDialogController(instance) {
    let vm = instance;
    
    let widthPerc = 80
    let heightPerc = 80
    
    //Dialog dimension calc
    if(widgetContext.isMobile){
        vm.dialogWidthCalc  =  window.innerWidth
        vm.dialogHeightCalc =  window.innerHeight
        vm.embedHeight = window.innerHeight - 60
    }
    else{
        vm.dialogWidthCalc  =  window.innerWidth * (widthPerc/100)
        vm.dialogHeightCalc =  window.innerHeight * (heightPerc/100)
        vm.embedHeight = window.innerHeight * (heightPerc/100)
    }
    
    vm.cancel = function() {
        vm.dialogRef.close(null);
    };
}`

^^JS Code

By using this code you have access to change dialog viewport width and height (widthPerc and heightPerc).
I tested it both on desktop and mobile and seems to be working.

Please note that DASHBOARD_SOURCE is being used since setting url from vm.url doesn't work.

Then, if you want to use "set entity from widget" option you have to set url this way:
`url = "/dashboard/da0083b0-4df0-11ed-8bf1-d3df0f3458d1?state="+state`

"state" is a variable that you have to set by encoding in Base64 entity. To do this please check #2693 closed issue.

Hope it works for you 👍

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.

**Comment by Adw1284** [comment]
https://github.com/thingsboard/thingsboard/issues/10949

**Comment by xiaofeifeii** [comment]
> ```
> widgetContext.actionsApi.openDashboardStateInSeparateDialog("update_devices", {}, "Update Devices", true);
> ```
> 
> `update_devices`是仪表板状态的状态 ID
> 
> #10949



> ```
> widgetContext.actionsApi.openDashboardStateInSeparateDialog("update_devices", {}, "Update Devices", true);
> ```
> 
> `update_devices`是仪表板状态的状态 ID
> 
> #10949

Hahaha, thank you so much, finally succeeded and solved the problem that has been bothering me for a long time, I wish you all the best in your work!
