### ISSUE TITLE
[Feature Request]Is there a way to add Unit column in ts_kv_dictionary so that each parameter of a device can have its units(eg.Voltage,Ampere) specified as a column

### ISSUE THREAD

**Issue by GokulSNarayan** [thingsboard/thingsboard#4450]
**Is your feature request related to a problem? Please describe.**
We need to get the Unit details of a parameter and as per my understanding the best way is to have a column in ts_kv_dictionary table called units or something which can give the Si unit or any other of the parameters that is being monitored.(eg.Volt, Ampere, kWh)

**Describe the solution you'd like**
Provide  an option to add unit for a parameter of a device during its creation and have its mapped in ts_kv_dictionary

**Comment by pon0marev** [comment]
This request cannot be implemented because, in the current Thingsboard architecture, different entities can reuse keys.  For example, one device sends a key with the value of “Wh”, and another sends a key with the value of “kWh”. This can lead to conflicts between values and keys.
To specify units, use the “Units” section on the widget settings:
![image](https://github.com/user-attachments/assets/168781c7-05ae-4fee-a689-7f157af6484a)
