### ISSUE TITLE
how to do Java Compilation on Thingsboard

### ISSUE THREAD

**Issue by srimathselva** [thingsboard/thingsboard#462]
hi,
      After builded Things-board source.  I have modified one java file from thingsboard/dao/.java dir but it is not affected any things. Whether I need to compile particular java file or compile whole Java file and how to compile the java file on thingsboard.  please coordinate me on this. Thanks

**Comment by mp-loki** [comment]
hi @srimathselva ! You need to compile whole project using maven. Compilong only DAO module is not sufficient because it will not be reflected when you run the application. Please see our [Contribution Guide](https://thingsboard.io/docs/user-guide/contribution/how-to-contribute/) for the guidelines on building from source

**Comment by srimathselva** [comment]
hi @mp-loki, 
                      Its worked thanks. I have question here, I’m modifying the user level data’s like adding one more fields in user profile. So where I need to handle the adding, fetching data and set/get data in database ?. how the Java side reading the data and returning the data to user. what are the file I need to use?. Where the file is appear in thingsboard folder?. 
Thanks.

**Comment by mp-loki** [comment]
see **dao** module. Note that there is an implementation for sql and for Cassandra (nosql).
