### ISSUE TITLE
ThingsBoard not connecting with MQTTLens

### ISSUE THREAD

**Issue by PauloSantosAction** [thingsboard/thingsboard#464]
Hi All, 

I've already tested some platforms with MQTTLens, although for thingsboard i'm not able to connect.
I'm using demo.thingsboard.io on port 1883 and using the device token as username and leaving the password blank...

Any ideas?

Thanks

**Comment by minhsiangli** [comment]
I have the same issue, too. 
It's seems like MQTTLens doesn't include fixed header to `MqttTransportHandler`. 
I'm try to use null exception to catch related code such as `msg.fixedHeader()`, and pass the connection to `processConnect` method.
But it still not working...
How do i fix it?

Thanks a lot!

**Comment by Karabiy** [comment]
you can refer to this link regarding on how to proceed with the MQTT API of the ThingsBoard: https://thingsboard.io/docs/reference/mqtt-api/
in case if this does not fulfill your needs, you can refer to the ThingsBoard Professional Edition MQTT integration functionality, so that you can use any kind of the third-party MQTT broker, to have those being configured. you can use this link for the feature-investigation reasons: https://thingsboard.io/docs/user-guide/integrations/mqtt/
