### ISSUE TITLE
How can I show combination of incoming metrics on the dashboard

### ISSUE THREAD

**Issue by RenCisco** [thingsboard/thingsboard#4694]
OS: centos 7.0
ThingsBoard:commumity Edition 3.2

I don't understand  your solution. I tried the 'change originator node', but it didn't work!

i collect data of Device A throught the thingsboard-gateway, The Device A has  five last telemetry (pressure,temperature,humidity,voltage,electricity).
I created two virtual devices:  B and C.
### before change：
一、device list img：
![image](https://user-images.githubusercontent.com/21196303/120420190-74fa3f00-c396-11eb-8e3b-887859772366.png)
二、device profile list img：
![image](https://user-images.githubusercontent.com/21196303/120420260-a115c000-c396-11eb-85a6-6f3844fd1d2b.png)
![image](https://user-images.githubusercontent.com/21196303/120420324-be4a8e80-c396-11eb-8f6d-6528be4f9b8b.png)
三、rule chain list img：
![image](https://user-images.githubusercontent.com/21196303/120420391-df12e400-c396-11eb-8e37-f89356dc6e21.png)
![image](https://user-images.githubusercontent.com/21196303/120420454-f356e100-c396-11eb-9d45-1607e011cf17.png)

Script Transformation Node configuration：
![image](https://user-images.githubusercontent.com/21196303/120420704-724c1980-c397-11eb-85a1-496bddd219d3.png)
B.Rulechain and C.Rulechain:
![image](https://user-images.githubusercontent.com/21196303/120420780-9d366d80-c397-11eb-841f-aaf3dfca2de0.png)

result:  deviceB or DeviceC dosen't any data in the last telemetry,But there is data in the rule chain and the OUT status is SUCCESS
![image](https://user-images.githubusercontent.com/21196303/120421432-da4f2f80-c398-11eb-8969-326e59bce44d.png)

### Issue:
How to do it ? -- device b has data in the last telemetry list

_Originally posted by @RenCisco in https://github.com/thingsboard/thingsboard/issues/4640#issuecomment-852697375_

**Comment by LeoMorgan113** [comment]
Hi @RenCisco,

Your device doesn't get telemetry, because you have the wrong logic.
If I understand clearly, Device A is a gateway and you want to send telemetry on Device B and Device C.
In your request, you need to set the device name on which you want to send telemetry, no need in rule chain.
So you can refer to this article: https://thingsboard.io/docs/reference/gateway-mqtt-api/#attributes-api

Also, I'd like to tell you that your rule chain won't work correctly.
When you create rule chain and assign it to profile, it will work for all devices with this profile.
So if you want to save telemetry you don't need to add few nodes "save timeseries".
Your data will be saved to that device, on which you put data.
