### ISSUE TITLE
[Question] Buttons that move to a new dashboard state

### ISSUE THREAD

**Issue by snir99** [thingsboard/thingsboard#4764]
**Component**
 * UI

**Description**
How can I create button that will move to a different dashboard state according an entity alias?
I created a button that like described [here](https://github.com/thingsboard/thingsboard/issues/3920). Now I want this button to move to a dashboard state according to a data that I will attach to the button. The thing is that I cant attach data to a static widget. Is there a way to create a button and attach to it a data? 

**Environment**
 * OS:  Ubuntu 20.04
 * ThingsBoard 3.2 CE

**Comment by JacksonBowe** [comment]
Instead of using the Static Widget, use the Timeseries > New HTML Value Widget
![image](https://user-images.githubusercontent.com/26427343/122691510-7de28000-d273-11eb-834b-4d3def9c3eb0.png)

You can add timeseries/attributes
![image](https://user-images.githubusercontent.com/26427343/122691539-acf8f180-d273-11eb-9b4e-c2024eb905bd.png)

Then do standard HTML stuff similar to the other issue you linked to.

However, when you add widget action select the Custom Action option. The following line controls dashboard state navigation:

`widgetContext.stateController.updateState(stateId, params, false);`

Where **stateId** is the id of the state you want to navigate to. I suggest printing out widgetContext and using that to evaluate what state you want to go to.
For example following from previous images, in the widgetContext object you can navigate to
![image](https://user-images.githubusercontent.com/26427343/122692133-c5b6d680-d276-11eb-8694-44f74ff5b5fc.png)

Then based on the value (eg **rain gauge**) you can determine what state to navigate to.

There is actually a youtube video the covers exactly what you are trying to do on the Thingsboard channel: https://www.youtube.com/c/ThingsBoard/videos 

It's somewhere in there, can't recall which one (maybe CRUD operations?). Either way I suggest watching all of them as lots of the information in these videos isn't actually found in their written documentation.

**Comment by snir99** [comment]
@JacksonBowe thanks, it solved the problem for me.
What I used was is the following widget: **Card > Latest Value > HTML Value Card**
**HTML Value Card** is the one that _JacksonBowe_ showed up above.
In the **HTML Value Card** under **Advance** I did what is suggested [here](https://github.com/thingsboard/thingsboard/issues/4362) with the image that I wanted to display.
