### ISSUE TITLE
Unable to set Kafka topic key using Kafka Node

### ISSUE THREAD

**Issue by thirstyfish** [thingsboard/thingsboard#4865]
**Describe the bug**
The Kafka Node doesn't seem to have any way to define the keys for the messages produced.
The topic key is a very important aspect in kafka that influences message ordering etc. and it seems like the related field is just set to null in the producer's publish method:

https://github.com/thingsboard/thingsboard/blob/36855446f095625fbacd4b17308efb71df98a0d3/rule-engine/rule-engine-components/src/main/java/org/thingsboard/rule/engine/kafka/TbKafkaNode.java#L132

**Your Server Environment**
TB 3.2.1 and TB 3.2.2

**Expected behavior**
The Kafka node should provide a property that allows the user to set one of the message or metadata attribute values as the key for the produced message.

E.g., this is how a kafka connect transform achieves the same result:

```
"transforms": "ExtractField",
"transforms.ExtractField.type":"org.apache.kafka.connect.transforms.ExtractField$Key",
"transforms.ExtractField.field":"id"
```

For the Kafka TB node, only an extra field would be required where the user could set the attribute name that should be parsed as the key by the publisher method.

**Comment by sblendorio** [comment]
Is this bug still present? I'm using Thingsboard v2.5.6 and I need to set the topic key using Kafka Node

**Comment by sumin-denys** [comment]
Hi @thirstyfish,

Thank you for your report! 
I am happy to let you know that Kafka Node since ThingsBoard 3.4.2 provides the option to set the Kafka topic key from message or metadata.
I am closing this issue.
Please refer to our release notes to find out more about new features and bug fixes: [Release Notes](https://thingsboard.io/docs/pe/reference/releases/)
