### ISSUE TITLE
[Bug] OAuth2 providers bug. with OAuth 2.0 using WSO2 Identity Server ,The back-office service reported the error malicious String ";"

### ISSUE THREAD

**Issue by flystreet** [thingsboard/thingsboard#4916]
**Describe the bug**

OAuth2 providers bug. with OAuth 2.0 using WSO2 Identity Server ,The back-office service reported the error. like this:
  `ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL contained a potentially malicious String ";"
	at org.springframework.security.web.firewall.StrictHttpFirewall.rejectedBlacklistedUrls(StrictHttpFirewall.java:369)
	at org.springframework.security.web.firewall.StrictHttpFirewall.getFirewalledRequest(StrictHttpFirewall.java:336)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:194)`

**Your Server Environment**

* own setup
  * ThingsBoard Version:3.3
  * OS Name and Version:windows 2019

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: windows 2019
* Browser [ chrome]
* Version chrome 90

**Screenshots**

![1](https://user-images.githubusercontent.com/392213/125879701-41663200-3f53-4fec-92ba-103b98157d96.jpg)
![2](https://user-images.githubusercontent.com/392213/125879704-e9e81f46-7254-4ea2-898a-e44de9636b95.jpg)
![3](https://user-images.githubusercontent.com/392213/125879703-01a16ab0-5ba1-4842-9537-7638ca941b53.jpg)
![4](https://user-images.githubusercontent.com/392213/125879702-b78684db-9e5b-48b0-9aa6-1faa93d6fc60.jpg)
![5](https://user-images.githubusercontent.com/392213/125879706-25eb7377-a79c-4ff7-b8cd-ca7b11c15938.jpg)

**Comment by flystreet** [comment]
additional .I'm sorry! English proficiency is limited

![6](https://user-images.githubusercontent.com/392213/125880405-f99b1d39-5206-47d6-80ac-7f49b193f0ad.jpg)
![7](https://user-images.githubusercontent.com/392213/125880411-9d09e575-146a-4daf-abca-c98817cda592.jpg)

**Comment by ban2derlog** [comment]
Hi, you had wrong configuration for redirect URI which you received from WSO2.
![image](https://user-images.githubusercontent.com/33271053/184671727-58845a14-0694-4676-9399-49e485bae635.png)
Redirect URI in your OAuth2 service must be like this one:
![image](https://user-images.githubusercontent.com/33271053/184671587-f96ef038-b272-4dd5-b045-d5382dc4fcc4.png)
Because this endpoint will use token that will be generated from your OAuth2 system to precede login.
Check Callback URI in WSO2 that it don't have any symbols at end and uncheck box - Support PKCE'Plain Transform Algorithm.
