### ISSUE TITLE
Led indicator RPC control issue

### ISSUE THREAD

**Issue by toponsky** [thingsboard/thingsboard#503]
Hey there, 

I am trying to work out RPC in thingsboard. 

First, I got Raspberry PI GPIO Demo Dashboard worked on my PI.  

I am trying to use tb-gateway and KURA plugin to do the same thing. 
Here are some things confuse to me.
The gpio.py script connected to the thingsboard straightway, In this case, the thingsboard plays three roles, publisher, subscriber and broker. Since I want to use tb-gateway, so I don't want thingsboard plays broker role. I want thingsboard publish MQTT message to a broker which tb-gateway connected. Is thingsboard enable to do it?

**Comment by BIT-masterpy** [comment]
I have the same idea. Have you solved it?

**Comment by AbCthings** [comment]
Yes, _you can use tb-gateway to issue commands to edge devices_.

The information flow is:
Thingsboard server (cluster) **->** Internal Thingsboard MQTT broker (let's call it "BROKER_1") **->** tb-gateway **->** generic MQTT broker ("BROKER_2") which enables communication between tb-gateway and the edge device(s).

The reverse flow will happen for sending the response (feedback of control) from edge device(s) to ThingsBoard server.

You need to map the tb-gateway to define communication topics used in the "BROKER_2" MQTT broker, so that you can implement a consistent logic in your edge device. In any case the communication via "BROKER_1" between ThingsBoard server and ThingsBoard gateway is "invisible" to you.

**Comment by Karabiy** [comment]
you can use the external node "MQTT" for those reasons
you can refer to this link regarding those: https://thingsboard.io/docs/user-guide/rule-engine-2-0/external-nodes/#mqtt-node

**Comment by samiullah02** [comment]
Hello,Can any help me in external led indicator to blink in arduino code
