### ISSUE TITLE
[Bug] alarm-controller POST request 400 error

### ISSUE THREAD

**Issue by Trysar** [thingsboard/thingsboard#5033]
Creating a new alarm via HTTP POST request to thingsboard /api/alarm endpoint result in a 400 error.
The returned message states that "Alarm originator should be specified!" yet the request payload satisfy the specifications laid out in [swagger](https://demo.thingsboard.io/swagger-ui.html#!/alarm-controller/saveAlarmUsingPOST).

**To reproduce:**
1. Create an alarm object (here in python)
```
alarmObj = 
    {"alarm":
        {
          "details": "some details",
          "name": "alarm name",
          "originator": {
              "entityType": "DEVICE",
              "id": "%existingDeviceId%"
            },
          "propagate": False,
          "propagateRelationTypes": [],
          "severity": "MINOR",
          "type": "alarm type"
    }
```
2. send the request (here using python requests, headers are already populated with valid token)
`response = requests.post(url, json=alarm, headers=headers)`

3. returned response:
`'status': 400, 'message': 'Alarm originator should be specified!', 'errorCode': 31`

**Expected behavior**
The correct response should be a 200 status, and the alarm should be created and associated to the specified device

**Notes**
Seems like the endpoint won't correctly recognize the "originator" parameter, or maybe the documentation is lacking

**Comment by LeoMorgan113** [comment]
Hi @Trysar,

I've tested your code, and it is really not working.
Maybe because you forget to write - "status": "ACTIVE_UNACK",
Please try the next:
`{
  "details": "some_details",
  "name": "ALARM",
  "originator": {
    "entityType": "DEVICE",
    "id": "ID"
  },
  "severity": "CRITICAL",
  "status": "ACTIVE_UNACK",
  "type": "CRITICAL TEMP"
}`
![image](https://user-images.githubusercontent.com/56256429/130224173-c790ee86-dd72-4b3c-b235-1f21b826f26c.png)
![2021-08-20_14-03](https://user-images.githubusercontent.com/56256429/130224192-d5e23d9e-8145-4f47-9076-a62c24704973.png)

**Comment by Trysar** [comment]
Thank you, that solved the issue!
Adding the "status" key worked, and now the alarm gets correctly registered.
I was assuming that a newly created alarm would automatically get a "ACTIVE_UNACK" status, turns out that's not the case.

Still, the error message is quite misleading.
