### ISSUE TITLE
[Question] How to restrict Tenant Users from accessing other dashboards?

### ISSUE THREAD

**Issue by EES-IoT** [thingsboard/thingsboard#5083]
![GitHub TB2](https://user-images.githubusercontent.com/88802414/129377966-c9682161-d0a5-495a-8e46-6770242dea9d.jpg)

![GitHub TB1](https://user-images.githubusercontent.com/88802414/129251578-89d50284-3ac6-4b96-b838-f88dd5faec2a.png)

 * UI
 * Generic

Hi there, 
I have added one tenant user. this user has all read only permission by default. I added all alarm permission in added action option. I added one home dashboard and provisioned it with full screen mode. I was trying to restrict this tenant user to this assigned dashboard only. I do not want this user to have access to other dashboards. I tried to find the solution for this specifically from documentation, but it did not help. 
Any potential solution will be appreciated. 

Note: I provisioned this user under tenant user section, but it is showing as tenant admin after logging in (in the top right corner of window). I am wondering if it is a bug or not? 

**Environment**
 * OS:  Windows10
 * ThingsBoard: v.3.2.1PE
 * Browser: Google Chrome (Latest)

**Comment by JacksonBowe** [comment]
Well since the Tenant User Role has read permissions to ALL you will not be able to restrict them in the way you want. What you should do is make a new **generic** role, Tenant User Restricted (or something similar) and give them read permissions to everything **excluding** dashboards. 

Then make a **group** role called **Group Read Only** with permissions **Read, Read Attributes, Read Telemetry**. 

Next, create a dashboard group called **Shared Dashboards** and put the dashboard you are trying to share in there.

Next create a User Group for the new role, **Restricted Tenant Users**. Put your user in this group, and **give the user group** the permissions of **Tenant User Restricted**, and **Group Read Only**. When trying to apply the Group Read Only role select dashboard group > shared dashboards.

That should work to give your desired functionality.

This form of solution should really try to make use of the Customer hierarchy instead of operating on the Tenant level.

**Comment by EES-IoT** [comment]
![GitHub TB3](https://user-images.githubusercontent.com/88802414/129786499-06bd4818-791f-45ae-b0d0-3d6118aad4ba.JPG)
@JacksonBowe There is no "Read" resource available in role creation panel. It has "ALL", where "read" is a option. So it is not offering any solution to my issue. Thank you for the suggestion.


I am looking forward to have a  workable solution.

**Comment by JacksonBowe** [comment]
@EES-IoT Do the following for every option **excluding dashboards and dashboard groups**
![image](https://user-images.githubusercontent.com/26427343/129803973-cc881793-a567-4d54-833d-187687e395bd.png)

Then This
![image](https://user-images.githubusercontent.com/26427343/129804206-0946f9bf-848f-4273-9ebc-80b832e02af1.png)

Now this user can only see the 3 dashboards I've allocated to them (3 out of 20 or so).
![image](https://user-images.githubusercontent.com/26427343/129804317-b2b7ceaa-d0c4-49b3-af5a-41a0968c894b.png)


I've just tested this and it works exactly how you want.

**Comment by EES-IoT** [comment]
Thank you @JacksonBowe

**Comment by ashvayka** [comment]
Thanks to @JacksonBowe I believe we have great instruction and now can close this issue.
