### ISSUE TITLE
missing documentation: configruation options: dynamic_page_link

### ISSUE THREAD

**Issue by t0mZ4** [thingsboard/thingsboard#5133]
Hello

I cannot find any reference to the following configuration options in thingsboard.yml

`    dynamic_page_link:
      refresh_interval: "${TB_SERVER_WS_DYNAMIC_PAGE_LINK_REFRESH_INTERVAL_SEC:50}"
      refresh_pool_size: "${TB_SERVER_WS_DYNAMIC_PAGE_LINK_REFRESH_POOL_SIZE:1}"
      max_per_user: "${TB_SERVER_WS_DYNAMIC_PAGE_LINK_MAX_PER_USER:10}"
`

**Comment by ashvayka** [comment]
Since ThingsBoard 3.1 we support filters for entities. For example, you may use this to show "All devices on the map where battery level is less than 20" in the entity table widget. The entity table widget displays the first 10 (20, 75) records on the page, sorted by some field (created time desc by default). Obviously, the devices charge and discharge. So, the list and the visible results of the first page may change over time and is dynamic. That is why we call this page link to be dynamic. We manage such page links on the back-end. So, the "refresh_interval" is responsible for the invalidation of the page link. The refresh_pool_size is a thread pool size to execute the invalidations and the max_per_user is a number of dynamic page links that the user may create (typically in the scope of his WebSocket session, since UI uses one WebSocket session per browser).

**Comment by ashvayka** [comment]
Leaving open to add this to documentation.

**Comment by t0mmyz7** [comment]
Thanks for the explanation Andrew.


Is there a configuration to set the refresh time of the dashboard as far as
how often new time series data shows in the widgets and graphs in Realtime
view?

**Comment by xalt7x** [comment]
Parameters were added by #9362  and now available in the [documentation](https://thingsboard.io/docs/user-guide/install/config/).
