### ISSUE TITLE
[Bug] alarmConditionDuration values do not make sense

### ISSUE THREAD

**Issue by t0mZ4** [thingsboard/thingsboard#5173]
Hello

we are very happy to see alarmConditionDuration added in release 3.3.0

but the values we are getting do not make any sense.

for example, an alert just created has the value of: 900014

`{
    "alarmConditionDuration": "900014",
    "isNewAlarm": "true",
    "scope": "SERVER_SCOPE",
    "temperature": "14.22",
    "userId": "9343e550-c992-11ea-8098-b37af6066e1f",
    "userName": "xxx@xxxx.com"
}`

here is the alert detail screenshot:

![image](https://user-images.githubusercontent.com/31729091/131507100-0a7cf75b-79d6-499a-b02f-2938586ebea4.png)

created time to end time is 5min, the alarmConditionDuration

Alarm duration in Profile is set dynamically by device attribute to 1min

Alarm clear duration in Profile is set fixed to 15 min

any idea what's going on here?

**Comment by trikimiki** [comment]
According to release notes:
“alarmConditionRepeats” and “alarmConditionDuration” metadata fields of alarms _**generated via alarm rules**_;
Can you please provide your alarm rule?

**Comment by t0mmyz7** [comment]
@trikimiki  hi, alarm rule is nothing special, we are listening to alarm type messages in the system, and we see such values in alarmConditionDuration that don't make sense.

**Comment by t0mmyz7** [comment]
@trikimiki any idea?

**Comment by SuminDenis** [comment]
Hi @[t0mZ4](https://github.com/t0mZ4), 

I suppose this value refers to the “Alarm Clear Duration”  = 15 minutes, because if you try to convert 900014 from milliseconds to minutes, you will get exactly 15 min.This value you set up manually via Device Profile when creating Alarm Rule.

![Screenshot from 2024-06-27 15-54-19](https://github.com/thingsboard/thingsboard/assets/63262257/64747af7-5037-4f41-b600-0b5471b863a9)

Code example below represents this value in the current ThingsBoard version.


![Screenshot from 2024-06-27 15-52-31](https://github.com/thingsboard/thingsboard/assets/63262257/e73fed18-ac00-4b84-aab1-57df20375a98)

**Comment by ashaforost** [comment]
I'm closing this issue, since the "alarmConditionDuration" parameter is not in the latest thingsboard version.
