### ISSUE TITLE
demo.thingsboard.io is down

### ISSUE THREAD

**Issue by kulbhushans** [thingsboard/thingsboard#52]
demo.thingsboard.io is down since last few hours.

**Comment by ashvayka** [comment]
This is fixed now, sorry for delays.

13 лют. 2017 р. 6:22 дп "kulbhushans" <notifications@github.com> пише:

demo.thingsboard.io is down since last few hours.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/thingsboard/thingsboard/issues/52>, or mute the thread

**Comment by kulbhushans** [comment]
Thanks

**Comment by tardisfromtornspace** [comment]
Will have to reopen again, it's down for my entire student development team as well.
