### ISSUE TITLE
widget font color problem

### ISSUE THREAD

**Issue by jasonlee9900** [thingsboard/thingsboard#5217]
For many widgets font color setting are only available for head font modification, if background is white that's ok, but if we need black background or silver background theme, then those fonts besides chart are not visable, e.g. radar chart, bars chart etc. because it's font color same as background color, and that font color are not changeable. 
For a tendor may both have black theme project and white theme project.

**Comment by LeoMorgan113** [comment]
Hi @jasonlee9900,

I'll add your appeal to our backlog and hope it will be taken into account in the new release.

**Comment by albtrentadue** [comment]
Hi
As this is reacognized as a bug, and a feature limiting one, I suggest to indicate a target release for fixing, rather than just hoping "it will be taken into account in the new release".
If the bugfix will not fit into the development sprint, then at least the fact will be tracked here and a new target will be set.
