### ISSUE TITLE
[Bug] SMTP password is not encrypted in "send email node" and can be accessed when exporting rule chain as json.

### ISSUE THREAD

**Issue by artturimW** [thingsboard/thingsboard#5229]
**Describe the bug**
SMTP password is not encrypted in "send email node" and can be accessed when exporting rule chain as json.
Also when switching to system SMTP settings but leaving password configuration to email node, password stays in json file.

**Your Server Environment**
* own setup
* docker deployment
* ThingsBoard Version 3.3.1

**To Reproduce**
1. Make Rule Chain with "send email node" and use manual SMTP settings
2. Go to Rule Chains and export your SMTP rule chain.
3. Open your .json rule chain file and your SMTP password can been seen as plain text.
 

**Expected behavior**
Password would been encrypted somewhere. Although you need tenant admin privileges to do this.

**Comment by jonrot1906** [comment]
Depending on your SMTP provider, you could also use app passwords (i.e. gmail, mailcow,... offer that). That way your clear text password never shows up anywhere and you can specify passwords for different apps/use cases. Otherwise, if you use your own setup, why not use system SMTP settings?
I can very much recommend using mailcow-dockerized if you want to host your own mail server.

**Comment by artturimW** [comment]
Yes, for now on I am going to use system SMTP settings. 
Also if you have already configured the node in non-system SMTP settings and change it afterwards, password stays in the json file.

**Comment by SuminDenis** [comment]
Hi @artturimW,

This is valid feature request.
It’s on our roadmap, however, it’s low priority so it wont be implementer in the near releases

Thank you!
