### ISSUE TITLE
[Question] Filters 

### ISSUE THREAD

**Issue by AbrahamSalvi** [thingsboard/thingsboard#5237]
**Component**

 * Generic

**Description**

![image](https://user-images.githubusercontent.com/78015483/133062761-da813d23-a5ce-4281-92a7-568ceed8c1d3.png)

I use a filter in this widget, but I would like to be able to see everything without a filter. How can I see all the devices without removing the filter from the widget?

**Environment**

 * OS:  windows 10
 * ThingsBoard: Smartec v.3.2.2PE
 * Browser: google chrome

**Comment by JacksonBowe** [comment]
Try using a User Attribute. With Filters you can set them to use a _dynamic_ value. It's hard to give any more detailed answer because there's not a whole lot of description of what you're trying to achieve. But yeah I'd start there.

**Comment by AbrahamSalvi** [comment]
Hi @JacksonBowe, I have already created the dynamic filters, but in this case they have 2 states online or offline but I would like to have an option to deactivate the filters to put all the devices, because only if I remove the filter in the widget I can see everything without filtering.

Thanks for the reply.

![image](https://user-images.githubusercontent.com/78015483/135247515-3b82e635-4c00-4639-8682-78d4ef83a180.png)

**Comment by JacksonBowe** [comment]
@AbrahamSalvi seems to me like you are trying to use a Boolean (2 states) to control something with 3 states. Maybe you can just use a String instead. 

Instead of having a variable called **on** that can be **True/False**, have a variable called **state**, that can be **on/off**.
From there you can have multiple approaches. For example, your user attribute could determine what to hide, eg userAttr **toHide** = **on**.
Then in your filter, you search for all devices where **state!=toHide**.
If you want to show **on** devices, you set **toHide=off**(this will hide all **off** devices), and visa versa. To show everything you set **toHide=none**.
Something like that would work.

**Comment by AbrahamSalvi** [comment]
@JacksonBowe thanks so much for your reply, i will try.
