### ISSUE TITLE
[Question] Grouping by monthly calendar interval

### ISSUE THREAD

**Issue by qwykx** [thingsboard/thingsboard#5296]
**Component**

 * Generic

**Description**
As a dashboard end user I want the ability to do a comparison of my energy consumption based on an actual calendar month instead of a 30 day interval.

**Question/Feature Request/Contribution tips**
Is this already possible and we are maybe missing something? How could we achieve this if we had to develop it ourselves, like a starting point where to look at.

**Comment by JacksonBowe** [comment]
Hi @qwykx 

I have done something similar to this myself two seperate ways. Both are difficult. 
The first way I did it was in a **massive** rule chain. It's not an elegant solution but I'll give you a rundown. This approach assumes that the device posts energy consumption since last post. Eg, posts once per hour, with the amount of energy consumed in that hour. We'll be using the attributes **month**, and **mtd**(month-to-date). 

Pseudo: 
- Device posts 
- Check if the current month is stored in attributes (use the _originator attributes_ rule node to get the stored value)
 If not save the current month ```var d = new Date(parseInt(metadata.ts)) >>> d.getMonth()```
- Check if stored month is the same as stored
- If it is, pull the attributes **mtd** and add the latest reading to it
- If current and stored months are different, pull the attribute **mtd**, write it's value into a new field **monthly_usage**, and now set the latest reading to overwrite mtd. 
- Save **monlthy_usage** into timeseries (you will want to change the metadata.ts value to not be at the end of the month)
- Save the overwriten **mtd** into attributes
- Update the **month** attribute

^ Yuck right?

Alternatively, create a custom widget that just reads the timestamps associated with each telemetry reading, and sum them using months as cutoffs.

Solution 1 lets you use your new values with any existing widget
Solution 2 will make you lose less hair, but you will only have a single widget, and the values wont be stored in the DB

I haven't used TB3.3.1 much though, so there may be a calendar month option available in there.

**Comment by sparvalarva** [comment]
I've been scratching my head to try and get this working. Found this post just now.
Can this be real? Theres no way to group by calendar month? 
No answer from 
I'd say its a very basic thing for an IoT-Platform to be able to visualize by calendar month, week, day of week, etc.

@ashvayka any answer regarding this would be much appreciated. Is there a way to do this? If not, why not?

**Comment by mykhailokornieiev** [comment]
Hi
Such a feature was available starting from 3.6.3
![image](https://github.com/thingsboard/thingsboard/assets/115699895/6f52fd52-f78e-46c6-8a90-b00a5e51d7b7)
https://github.com/thingsboard/thingsboard/releases/tag/v3.6.3
In this case, I will close this ticket
