### ISSUE TITLE
[Bug] Thingboard not showing Received Data / not receiving it

### ISSUE THREAD

**Issue by yayaLy** [thingsboard/thingsboard#5306]
**Describe the bug**
Hi!
I have Thingboard Cloud Prototype.

It's been a month since I have noticed that after some time, my thingsboard does not receive any data.
I have a MQTT integration and if I go on the event tab, I don't see any eventhough my brocker is still publishing data on the topic the integration is subscribed on.

Is it related to a limit of the number of packet I can receive on dayly basis or... monthly basis. 
When I look on API usage everything seams correct. 

And when I touch the integration configuration and leave it as it was data begin to show up.

Thank you for your help

**Your Server Environment**
* cloud.thingsboard.io PROTOTYPE
* own setup
  * cloud deployment
  * ThingsBoard Version

**Your Client Environment**
**Desktop (please complete the following information):**

* OS: [Windows]
* Browser [chrome,]
* Version [e.g. 22]

**Your Device**

* Connectivity
  * MQTT
  * Integration: (Specify name) 

**To Reproduce**
I don't know exactly how to reprduce it

**Expected behavior**

**Comment by JacksonBowe** [comment]
Sounds to me like your integration is getting blacklisted. 

When an integration gets 3 errors in a row it gets blacklisted, because it is clearly not working so why bother running it.

When you edit the integration/data converter it removes the blacklisted status. But it can happen again if you don't resolve the issue.

I'd enable debugging and just see if you can find out what might be causing the errors.

**Comment by yayaLy** [comment]
Hello @JacksonBowe 
you are right, It has been backlisted because of errors. 
Thank you for your reply, It did help
