### ISSUE TITLE
[Question] Change client id or username/password of MQTT node dynamically.

### ISSUE THREAD

**Issue by FacelookHK** [thingsboard/thingsboard#5315]
**Component**

 * Rule Engine

**Description**
Can the cliend id or username/password of the MQTT node be changed dynamically (based on the data in the msg) in rule engine?

**Comment by ashaforost** [comment]
Hi there,

The credentials fields cannot be dynamically set due to their configuration. As a workaround, you can try adding a switch rule node to create a unique link, using which message type switch rule node will route the message to the MQTT node with the corresponding set of credentials.
Here's a link to the switch rule node example usage:
[Filter Nodes Article](https://thingsboard.io/docs/user-guide/rule-engine-2-0/filter-nodes/#switch-node)

**Comment by FacelookHK** [comment]
One reason I want to change the client id or username/password on-the-fly is that I want to forward the message to different devices via MQTT, which require a different client id or username/password. Using a switch node will not work in this case because I do not know the number of devices beforehand or there may be hundreds of devices.

**Comment by ashvayka** [comment]
The MQTT node is designed to send data from multiple devices to the same (external) MQTT Broker vias single MQTT connection. It is not designed for your use case and we don't plan to change this. It is very resource-consuming to create a lot of connections from one rule node and maintain them. This turns the ThingsBoard rule engine into the gateway. You may use the REST API call node and forward data to your own (micro)services that will do this job.
