### ISSUE TITLE
[Bug] Although entities are public, they cannot be viewed by customer users. 

### ISSUE THREAD

**Issue by gohm-tech** [thingsboard/thingsboard#5403]
Hi,

The thingsboard screen is accessed with the Teanant administrator.
A new asset is added from the Asset screen.
These added assets are made public as client assignment.
In this way, it is aimed to display the public assets for the users under the customer.
Afterward, it requests to make asset public with thingsboard rest api.
After performing these operations, the asset that has been modified is displayed in the public tenant administrator to which it belongs.
However, this public asset cannot be viewed by users under other customers.

I have implemented the following two scenarios, but the users belonging to the customer cannot view the public assets.

Scenario1

    Added a new asset to the assets section. Afterwards, the entity pcustomer is assigned as public via the dashboard. After this assignment, the customer was assigned as public again with the rest-api method. The problem persisted.

Scenario2

    A new asset has been added to the assets section with rest-api. Afterwards, the customer is assigned to the entity as public via the dashboard. After this assignment, the customer was assigned as public again with the rest-api method. But the problem persisted.

You can see the attached images.Please can you help with this

 

Best Regards,
GOHM Team

** Server Environment**

* own setup
  * docker deployment

  * OS:  Linux(Ubuntu 20.04) 

** Client  Environment**

* OS:  Linux(Ubuntu)
* Browser : Chrome, Firefox
* Version  Ubuntu Version 20.04

![Selection_101](https://user-images.githubusercontent.com/91528436/138039904-20d5111a-ff5f-4738-a640-2c69dfb5f712.png)
![Selection_102](https://user-images.githubusercontent.com/91528436/138039912-c0e75859-b00b-4713-97f8-ed73656ef7f9.png)
![Selection_104](https://user-images.githubusercontent.com/91528436/138039916-c77d09d8-1028-4345-bff5-4c282639a6cd.png)
![Selection_105](https://user-images.githubusercontent.com/91528436/138039917-760c4614-c20e-4c19-9edd-dc597a85d780.png)
![Selection_107](https://user-images.githubusercontent.com/91528436/138040506-daee71b3-e20e-4308-b5b2-018d9d363bfb.png)

**Comment by gohm-tech** [comment]
Hi @vortexalex 

Can you please reply?
Is there anything you wonder about our system?

Best Regards,
Gohm Team

**Comment by vortexalex** [comment]
Hello,

as I said before, public entities doesn't mean that thery are visible to all your customers. They are meant to be accessed by anonymous (unauthenticated) users.
The `customerId` you see in the body response of your `POST api/customer/public/asset/{assetId}` is the Public customer's customerId, which is created lazily if not yet exists. 

In the screenshot below you can see the method from `DeviceController `class, which implements the REST endpoint to make a device public (same logic applied for assets)
I highlighted the service method that, as its name says, `findOrCreatePublicCustomer`. If you go through it you'll find that if the Public Customer doesn't exist, it wille be created on demand, with a time-based UUID `customerId`.

![image](https://user-images.githubusercontent.com/5671229/142426649-d48e0d9d-4d9f-4cd5-9664-e8809704bba1.png)

**Comment by gohm-tech** [comment]
Hi @vortexalex 

So how do I arrange an asset that I created on thingsboard so that it can be seen by all users? According to your advice, I can continue after editing the java code and compiling it again. Isn't there a new endpoint or other solution for this bug instead?

**Comment by vortexalex** [comment]
I don't know why you're saying this is a bug, it is not a bug.

The Thingsboard CE security model is designed so that you can assign a given asset or device to only one customer, so with Thingsboard CE then the only possible way to assign assets/devices to multiple customers requires customizing source code.
Thingsboard PE >= 2.3 has a new RBAC that allows you to do what you want.

For further details read [here](https://thingsboard.io/docs/pe/user-guide/rbac/).

**Comment by gohm-tech** [comment]
Hi @vortexalex,

Thanks for your reply. We understood the topic.

Best Regards,
**Gohm Team**

**Comment by fargiolas** [comment]
@vortexalex sorry if I hijack this bug, I'm having a slightly related issue.

I'm writing a simple script to download data using python `tb_rest_client`. As far as I can tell I cannot use the REST API without logging in first, or maybe I cannot do this from the python wrapper, not sure.
So let's say I want to download public data from a public device, I have to login first and I have to login from a tenant admin user, because a simple customer won't be able to query public devices (with e.g. `get_customer_devices`), am I correct?
So I have no way to anonymously download public data using the rest api as far as I can tell.

The only workaround I found so fare is to create a "guest" customer and assign all public devices to him instead making them public, but I'm losing the ability to access the dashboard and devices without loggin in first.

**Comment by vortexalex** [comment]
Hi @fargiolas , 

try to do a public login:
`POST /api/auth/login/public`

with a request body like the following: 
`{"publicId": "<your_public_customer_id"}`

To get your public customer id, you can log into your desired tenant as tenant admin and navigate through the Customers panel, then click on the Public customer row:
![image](https://user-images.githubusercontent.com/5671229/147562407-ecb90081-356c-4ea0-a7c3-2332fa25bf8f.png)

a popup will appear, finally you can copy the public customer's id to use in the above public login API:
![image](https://user-images.githubusercontent.com/5671229/147562506-40e81908-b69f-4d53-bcdf-89d336148f63.png)


After getting the access token in the API response, you can use it in Telemetry APIs to fetch data from public devices.

Cheers

**Comment by fargiolas** [comment]
> try to do a public login: `POST /api/auth/login/public`

@vortexalex thank you! that actually works very well! it's not implemented apparently in tb_rest_client, will open an issue there to see if there's any interest
