### ISSUE TITLE
[Bug] filter on Timeseries - Widget Timeseries table

### ISSUE THREAD

**Issue by nowherex** [thingsboard/thingsboard#5455]
Bug or..., I'm trying to put a filter on the widget imeseries table, I have the following key value: "testA": 2,
and created a filter with the following parameters:
Key Type: Timeseries, key Name: testA, Value Type: String,

Operation: Contains, Ignore Case: true, Value: 2,

But it doesn't show the values, I've already tried to change the Operation, send a string in the testA key, etc, can anyone give me what I can do wrong? I have several dashboards with filters working with Key Type Attributtes, only now I needed to use a Timeseries ..

### Key Filter
![key filter](https://i.ibb.co/P9z1kLC/Captura-de-tela-de-2021-10-28-02-25-29.png)

### Widget Timeseries table
![Widget Timeseries table](https://i.ibb.co/k8RnQWv/Captura-de-tela-de-2021-10-28-02-17-44.png)

### Widget Timeseries table with filter (value: 2)
![Widget Timeseries table](https://i.ibb.co/XF3m6wY/Captura-de-tela-de-2021-10-28-02-18-30.png)

### Widget Timeseries table with filter (value: nothing)
![Widget Timeseries table](https://i.ibb.co/S3yJF49/Captura-de-tela-de-2021-10-28-02-18-05.png)

Environment

OS: Ubuntu 20.04 (64 Bit)
ThingsBoard: Thingsboard PE V3.2.2
Browser: Google Chrome

**Comment by GrayCygnus** [comment]
Writing here in case it helps anyone. I contacted TB support (we pay professional edition at my work) and they confirmed that this is not possible. Quoting: 

>Overall, the behavior you request cannot be implemented via thingsboard’s default functionalities, as it contradicts the initial design of the platform

and 

>By ThingsBoard design,  the widget’s historic timeseries cannot be filtered based on the timeseries values. Filters can only be applied to the latest timeseries, attributes, and entity fields. 

I have a partial workaround: *on the Advanced Settings of the widget, on the Row Style, you should return {display: 'None'}; on the rows that match your filtering condition*.

I said partial because this successfully hides the rows one wants to filter, but (1) the row count at the bottom of the widget still displays the total number of rows (including the ones hidden) and (2) when you export to csv or similar the hidden rows are downloaded along the rows that are not hidden.

In case you only wish to hide them visually, then I think this workaround will suffice.
