### ISSUE TITLE
[Question] CUSTOM MENU setAccessToken

### ISSUE THREAD

**Issue by evanderbird** [thingsboard/thingsboard#5499]
Hi, what is setAccessToken use in custom menu?
` "name": "My Custom Menu 2",
      "iconUrl": null,
      "materialIcon": "menu",
      "iframeUrl": "https://thingsboard.io",
      "setAccessToken": false,`

i try set it true or false, but nothing seems diferent?

**Comment by ashvayka** [comment]
If 'iframeUrl' is specified and the 'setAccessToken' is true, the access token of the current user will be passed to the iframe as an 'accessToken' query parameter. So, if you want to open a dashboard or other UI component in the iframe, you will remain logged in. You may also use dashboardId instead of an iFrameUrl. Then you don't need to set access token to the URL params
