### ISSUE TITLE
[Question] Subscribe all topics without device's ACCES_TOKEN

### ISSUE THREAD

**Issue by gohm-tech** [thingsboard/thingsboard#5502]
Hi,

We want to get all incoming MQTT messages of TB.

If you want to listen to incoming MQTT messages from a specific device. You have to use this script like this paper.
https://thingsboard.io/docs/reference/mqtt-api/#protocol-customization

`mosquitto_sub -d -h "thingsboard.cloud" -t "v1/devices/me/attributes" -u "$ACCESS_TOKEN"`

We want to subscribe to MQTT messages sent by all devices and send MQTT messages to all devices. How can we do that using mosquitto_sub?

Best Regards,
Gohm Team

** Server Environment**

own setup

docker deployment

OS: Linux(Ubuntu 20.04)
** Client Environment**

OS: Linux(Ubuntu)
Browser: Chrome, Firefox
Version Ubuntu Version 20.04

**Comment by mde2017** [comment]
Hi @gohm-tech,

you could use the MQTT Gateway API, where only one ACCESS_TOKEN is needed (for the Gateway itself):
https://thingsboard.io/docs/reference/gateway-mqtt-api/#:~:text=The%20Gateway%20is%20a%20special%20type%20of%20device,devices%20and%20the%20platform%20using%20single%20MQTT%20connection.

If you are using ThingsBoard PE, another option would be the use of the MQTT Integration in order to fetch data from external MQTT Brokers:
https://thingsboard.io/docs/user-guide/integrations/mqtt/

**Comment by gohm-tech** [comment]
Hi @mde2017,

Thank you.

Best Regards,
**Gohm Team**
