### ISSUE TITLE
Device Profile Alarm Rule - alarm severity cannot be change from Critical to Major

### ISSUE THREAD

**Issue by sunyong-mwi** [thingsboard/thingsboard#5508]
Consider the following device profile alarm rule:
creation condition 1: if device temperature > 4, create High Temperature alarm with Critical severity
creation condition 2: if device temperature > 0 and temperature <=4, create High Temperature alarm with Major severity
clear condition: if device temperature < 0

Test result:
1. device temperature = 2, new alarm with Major severity is created => OK
2. device temperature = 5, alarm is updated with Critical Severity => OK
3. device temperature = 2 again, no update to alarm severity => NOT OK
4. device temperature = -1, alarm is cleared => OK

Question: in step 3,  should the alarm be updated with severity set to Major?

**Comment by ashvayka** [comment]
It is currently implemented the way you described. For us, it seems logical and expected behavior. We assume the person who is configuring the rule is interested to know about the alarm caused by the "maximum" temperature. For example, if this is a fridge with something that can't be stored with temperature > 0. Then, if the temperature is -2 it is Major alarm, but if the temperature was +1, it is definitely critical, even if then, the temperature is back to -2.

**Comment by sunyong-mwi** [comment]
Thanks for the explanation. I understood the logic behind now.
