### ISSUE TITLE
Dashboard time series table column width

### ISSUE THREAD

**Issue by sunyong-mwi** [thingsboard/thingsboard#5514]
In dashboard time series table, there is no option to set the column width like alarm table. How to set the column width for time series table?

**Comment by mykhailokornieiev** [comment]
Hello sunyong-mwi
Please let me know if your issue is still relevant. Perhaps you have already found a solution?
You can change the width of your columns in your dashboard settings, in data --> select the display timewindow--> set the period for which to display the data. You can also resize the widget itself.
Best regards,
Mykhailo

**Comment by mykhailokornieiev** [comment]
Hello again
Yes, you are right, there is really no way to set the column width in the data key settings for the timeseries widget. But, you can use the timewindow change in the settings of the widget itself as shown in the screenshot. Also you can change the shape of your widget, this will also affect the width of the column. Unfortunately, there is no more options to change column width in timeseries bar widget, so that two different data keys have different widths.
Best regards,
Mykhailo

![Screenshot from 2022-11-04 17-39-08](https://user-images.githubusercontent.com/115699895/200331445-83609d6e-e0f5-46d1-bafd-db1dba45f49f.png)
![Screenshot from 2022-11-04 17-39-22](https://user-images.githubusercontent.com/115699895/200331453-5c738566-6dc3-4118-91b1-7c1f1bbb94d5.png)
![Screenshot from 2022-11-04 17-39-39](https://user-images.githubusercontent.com/115699895/200331454-7d097cfd-17ab-483f-a422-cde7c3add2ae.png)
![Screenshot from 2022-11-04 17-39-54](https://user-images.githubusercontent.com/115699895/200331456-85b60075-d81b-4489-b839-593dcad8edb3.png)

**Comment by mykhailokornieiev** [comment]
Hello

If your request is still valid, I found out how to change the width of the bar chart
You can increase the width of a bar chart only for non-aggregated data. 
To do this, you need to change the data aggregation function to "None" in the timewindow settings.
![image](https://github.com/thingsboard/thingsboard/assets/115699895/0525a520-4959-4a5d-9c38-d140d33fa4e0)
Then you can increase the width of bar chart in Settings → Advanced → Default bar width for non-aggregated data 
![image](https://github.com/thingsboard/thingsboard/assets/115699895/f9c6474d-61b5-4e50-bc0d-3f8b4462a01e)
![image](https://github.com/thingsboard/thingsboard/assets/115699895/395c6172-ea69-4570-88d9-74bd8deb7c8c)
![image](https://github.com/thingsboard/thingsboard/assets/115699895/1ebf6e2b-6891-4062-8056-8b8d2a0149df)

Best regards,
Mykhailo

**Comment by sunyong-mwi** [comment]
Hi, I'm talking about the Time Series table, not Time Series bar chart. There is no way to configure the column width in the Time Series table.

**Comment by mykhailokornieiev** [comment]
Hi. Sorry for the delay in response. Unfortunately, I've missed your message and was reminded about it in a similar ticket. Indeed, there is no possibility to set the column width in Timeseries Table widget.  Such a feature request was previously added to our backlog for developers. Please follow our [Release Notes](https://thingsboard.io/docs/reference/releases/) to see all new additions and fixes to the platform in subsequent releases.

**Comment by mykhailokornieiev** [comment]
Hi. We've created an Idea discussion https://github.com/thingsboard/thingsboard/discussions/15391 so that we can check the community's opinion regarding this request. This is done to identify the most desirable features for the community with further analysis of this data and its transfer to developers for further review. Even if the feature request is rejected, this information will still be useful for further planning the platform's development, and the decision may be reconsidered in the future.
