### ISSUE TITLE
How to use current device's attribute in key filter

### ISSUE THREAD

**Issue by sunyong-mwi** [thingsboard/thingsboard#5541]
I want to add a filter like "device's temperature > device's threshold attribute". However, in the Key Filter setting, there is no option to select the current device's attribute. How should I do it?

![2021-11-12 09_52_53-Window](https://user-images.githubusercontent.com/17080208/141395525-5f70c3b0-cf0b-41dd-bec0-590a94dd9c2a.png)

**Comment by mykhailokornieiev** [comment]
Hi. Not sure if this request is still relevant for you, but this feature was available in Thingsboard from at least 3.5.
![image](https://github.com/thingsboard/thingsboard/assets/115699895/1aa3cdf4-e03d-490f-9e40-cc4568ee7f47)
In this case I close ticket.

**Comment by Rapatas** [comment]
Hello @mykhailokornieiev, I'm using v3.5.1 and I do not see the "Current device" option, only "Current user". 

I have 4 gateway devices managing a lot of IoT devices. The goal is to have a "home" `Entities table` widget with all the Gateways, and have an action that opens a new dashboard state that shows a "list" `Entities table` with all the devices managed by that gateway. For the "home" I setup entity aliases "gateways" that is `Devices of type <gateway>` and for "list" `Devices of type <IoT>`. The IoT devices have an attribute `gateway.name` that is the gateway that manages them. The home table has `Set entity from widget ` on the action. 

I need a filter for the "list" table to match the selected gateway name to the attribute of the IoT devices

**Comment by mykhailokornieiev** [comment]
Hi. We've created an Idea discussion https://github.com/thingsboard/thingsboard/discussions/15634 so that we can check the community's opinion regarding this request. This is done to identify the most desirable features for the community with further analysis of this data and its transfer to developers for further review. Even if the feature request is rejected, this information will still be useful for further planning the platform's development, and the decision may be reconsidered in the future.
