### ISSUE TITLE
[QUESTION] NaN on chart aggregation returned on post-processing function

### ISSUE THREAD

**Issue by seikosantana** [thingsboard/thingsboard#5593]
**Timeseries - Flot**

 * UI

**Description**
I'm trying to create a chart based on the telemetry, so I am going with post-processing function in a datasource.

```js
var change;
if (prevOrigValue)
    change = (value - prevOrigValue) / prevOrigValue * 100;
return change;
```

also tried
```js
if (prevOrigValue)
    return (value - prevOrigValue) / prevOrigValue * 100;
```

Both code results in a NaN on the chart aggregation.
![image](https://user-images.githubusercontent.com/35630407/142713970-b4a651ab-965b-4272-8c67-78f9fab5c679.png)

What is the correct way to not produce a telemetry point when prevOrigValue is not present (on the very beginning of the chart)?

**Environment**

 * OS:  Ubuntu Server 18.04 ARM64 on Raspberry Pi 4
 * ThingsBoard: 3.1.1
 * Browser: Microsoft Edge version 95.0.1020.53

**Comment by JacksonBowe** [comment]
Well the reason that the aggregation is showing as NaN seems to be because sometimes your post-processing functions don't return numbers.
```
var change;
if (prevOrigValue)
    change = (value - prevOrigValue) / prevOrigValue * 100;
return change;
```
This will return and array like this for example: `[undefined, 10, 15, 12, 14, ...]` Basically an array of whatever numbers you're trying to aggregate with an undefined in the first position. But  I think you already guessed that based on your last line.

Using just the post-processing function I don't know of any easy way to not show the first value. Can you get away with hardcoding it to a reasonable value, maybe 1 or 0 or something?

**Comment by seikosantana** [comment]
I ended up harcoding it to 0, but i hope we have a way to do this.

**Comment by Ultrazombie** [comment]
Closed due to inactivity
