### ISSUE TITLE
[Bug] TB3.3.2 new Widget Settings issue with Mozilla Firefox 94.0.1

### ISSUE THREAD

**Issue by JacksonBowe** [thingsboard/thingsboard#5596]
Minor issue:
In Widget Style section the custom css expandable tab is outside of display.
Browser: Mozilla Firefox 94.0.1

![image](https://user-images.githubusercontent.com/26427343/142782985-ee62c816-d75b-4f52-afa7-f247a09ebd77.png)

This issue is not present with Chrome.

Workaround:
You can still click the top of the text, and then just open in fullscreen.

**Comment by mykhailokornieiev** [comment]
Hello JacksonBowe
Please let me know if your issue is still relevant. Perhaps you have already found a solution?
We are not able to reproduce your problem with 3.4.1 PE & Firefox 106. Please clarify which version of TB you use + do you see this problem on latest versions of Firefox?
Best regards,
Mykhailo

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
