### ISSUE TITLE
[Bug] MQTT gateway attributes API doesn't seem to work

### ISSUE THREAD

**Issue by martinjaeger** [thingsboard/thingsboard#5632]
**Describe the bug**
It's not possible to receive device attributes via the MQTT gateway API.
Request/response method as well as subscribing to `v1/gateway/attributes` to receive attribute updates doesn't seem to work.

**Your Server Environment**
* Own setup
  * Docker deployment
  * ThingsBoard Version v3.2.2
  * Manjaro Linux

**Your Client Environment**
`mosquitto_pub` and `mosquitto_sub` (version 2.0.13)

**Your Device**

* Connectivity
  * MQTT
  * Gateway

**To Reproduce**
1. Create a **gateway** device named "dev" in the Web UI and get its access token
2. Publish client attribute: `mosquitto_pub -d -q 1 -h "localhost" -t "v1/gateway/attributes" -u "token" -m '{"dev":{"client-attr":1234}}'`
2. Run `mosquitto_sub -d -q 1 -h "localhost" -t "v1/gateway/attributes/response" -u "token"` in separate window
3. Run `mosquitto_pub -d -q 1 -h "localhost" -t "v1/gateway/attributes/request" -u "token" -m '{"id": 123456, "device": "dev", "client": true, "key": "client-attr"}'
4. Realize that no response is received by the subscribing

These steps closely follow [the documentation](https://thingsboard.io/docs/reference/gateway-mqtt-api/).

The MQTT connection is working in general. If I use the device API instead of the gateway API, I can read the attributes.

**Expected behavior**
I would expect to receive the message with the client attribute in the subscribing window.

In order to investigate the issue, I have logged the communication with Wireshark, see below screenshot.

It looks like immediately after the publication to `v1/gateway/attributes/request` is received, ThingsBoard closes the TCP connection with the subscribing client, see FIN packet highlighted in blue. The FIN packet goes from ThingsBoard (port 1883) to the client (port 57408). Afterwards, the `mosquitto_sub` immediately establishes a new connection (now using port 57422). However, the expected MQTT PUBLISH packet is not sent from ThingsBoard to the new connection.

I have reproduced this behaviour multiple times. I don't understand why ThingsBoard drops the TCP connection to the subscribed client. Is there anything wrong in my steps or the usage of the API?

**Screenshots**

![image](https://user-images.githubusercontent.com/17674105/143764462-edba7076-7e22-4cf2-a0af-dd5651f9893b.png)

**Additional context**

Also when subscribing to `v1/gateway/attributes` no changed **shared** attributes (this time updated via the UI) are sent out via MQTT. I guess these issues are related. If not, I can do another Wireshark analysis for this one aswell.

**Comment by ashvayka** [comment]
Greetings, @martinjaeger. The documentation assumes that the request for attributes and subscription is made in the same MQTT session (within the same mqtt connection). The [device API](https://thingsboard.io/docs/reference/mqtt-api/#request-attribute-values-from-the-server) has a special note about this "Pure command-line examples are not available because subscribe and publish need to happen in the same mqtt session.". If you plan to use Gateway API, you should create a single MQTT connection and use it for all subscribe and publish commands. The creation of separate connections per each command is redundant from CPU, battery, and traffic usage. See the following script for your convenience:

```javascript
var mqtt = require('mqtt')
var host = 'localhost'
var accessToken = "GW_TEST_TOKEN"
var client  = mqtt.connect('mqtt://'+ host,{
    username: accessToken
})
client.on('connect', function () {
    console.log('connected')
    var msg = '{"dev":{"serialNumber": 42}}';
    client.publish('v1/gateway/attributes', msg);
    client.subscribe('v1/gateway/attributes/response')
    client.publish('v1/gateway/attributes/request', '{"id": 1, "device": "dev", "client": true, "key": "serialNumber"}')
})
client.on('message', function (topic, message) {
    console.log('response.topic: ' + topic)
    console.log('response.body: ' + message.toString())
    client.end()
})


```

**Comment by martinjaeger** [comment]
Thanks for the quick answer @ashvayka. It makes sense. In the real application I would of course use the same session, but didn't realize that testing via the command line doesn't work in this case.

However, as mentioned, also the `v1/gateway/attributes` does not seem to work. Do we need any special circumstances for this one aswell? I guess not, as there is no request that has to be matched to a response.

Process here:
1. `mosquitto_sub -d -q 1 -h "localhost" -t "v1/gateway/attributes" -u "gateway-token"`
2. Change a shared attribute of a **device** that was created by publishing telemetry data via the gateway API in the dashboard.

I would expect to receive the update via MQTT, but I don't. Here is another Wireshark packet log. You can see that HTTP requests go to the backend, but no message follows afterwards.

![image](https://user-images.githubusercontent.com/17674105/143835601-55642f85-dc95-48a9-839f-a9f885ec35c5.png)

I'm also wondering if / how ThingsBoard keeps track of which devices are behind which gateway. Or would above command receive updates of all devices of that user or tenant and would have to ignore messages that are not connected to itself?

I would be very happy about any further hints.

**Comment by ashvayka** [comment]
Yes, there is a special requirement for this call as well. When the gateway connects, it needs to tell ThingsBoard that it has some "real " devices connected to it. In other words, ThingsBoard does not know that this gateway is expecting to receive attribute updates for the device "dev" ( or any other device). In order to do this, you should do one of the following:
1) Publish a special message to "connect" the topic. See [doc](https://thingsboard.io/docs/reference/gateway-mqtt-api/#device-connect-api).
2) Publish telemetry or attribute on behalf of such device.
(You may choose one of the options, but they should happen within the same MQTT session).

For more info, you can always browse code of TB IoT gateway which is written in python.

**Comment by martinjaeger** [comment]
Ok, got it, thanks a lot for your explanations, really appreciated!

I'll close this issue, as I was following the wrong process and it's not a bug.
