### ISSUE TITLE
[Question] Alarm Node repeatedly creates alarm message

### ISSUE THREAD

**Issue by biggiao** [thingsboard/thingsboard#5652]
**Component**

 * Rule Engine

**Description**
The device uploads data every 5 seconds , At the same event time , alarm node  sometimes creates the  'Created' message twice for two messages at an interval of the same device. This affects subsequent nodes，how can i solve it?

**Environment**

 
 * ThingsBoard: 3.2.2CE

**Comment by ashaforost** [comment]
Hi @biggiao,

Due to the platform's design, where the alarm creation operation is concurrent and not transactional, sometimes duplicate alarms can be created. This feature was implemented as a tradeoff between availability and consistency, as it's better to create two identical alarms in periods of high load rather than miss out on some crucial alarm if the message processing slowed down for some reason.

In order to avoid this issue, you can use the checkpoint rule node to change the queue to Sequential By Originator, so messages are processed one by one, eliminating the situation where two alarms can be created simultaneously.
