### ISSUE TITLE
Is it possible to have multiple dashboard states and fix a part of it once you are inside one of them?

### ISSUE THREAD

**Issue by lucasKapf** [thingsboard/thingsboard#5653]
Hello, I'm new to Thingsboard and I try to do this : 
I have a customer which has contain relations of several customers.
Each of those customers has contain relations of several assets.
I have created entity aliases and dashboard states to navigate between those customers.
When I'm in the dashboard state of one customer, I can see only the assets related to this customer, which is what I want.
I have an action on row click on the asset list which update the dashboard state.
The problem is that when I click on a row of this asset list, the assets disappear and I have an empty widget.
It's because the customer selected and the asset selected are both entity aliases of the kind : Entity taken from dashboard state parameters. Is it possible to have a "dashboard state of a dashboard state " ?
 
In fact, I would like to keep the customer infos in a widget when I'm inside his state and see the informations of the selected asset in another widget in the same dashboard state.

Kindly regards,

Lucas

**Comment by ashvayka** [comment]
Yes, it is actually pretty easy. You should create two aliases with different state entity names. "Selected customer" and "Selected asset". When you create an alias, make sure you have selected: 

![image](https://user-images.githubusercontent.com/5016373/144210915-4f36d737-16e2-49d5-ac4d-4fd2b7de4615.png)

Also, don't forget to specify the same state entity parameter names in the field below the "Set entity from widget" checkbox in the widget action:
![image](https://user-images.githubusercontent.com/5016373/144210241-15c0b04f-003d-4fa0-bf62-32f53b6ab8a0.png)

I hope the description is clear. let me know otherwise.

**Comment by lucasKapf** [comment]
Hello, thank for your quick answer, it is clear. It works now.
