### ISSUE TITLE
Is there a documentation about $injector ?

### ISSUE THREAD

**Issue by lucasKapf** [thingsboard/thingsboard#5677]
Hello,

I would like to know if a documentation exists about the $injector in the $scope of a widgetContext ? 

Best regards,

Lucas

**Comment by dhaval2017** [comment]
I believe no document exist for it
But What you want to know about $injector?
I might can help

**Comment by lucasKapf** [comment]
Hello @dhaval2017 , thank you for your quick answer. In fact I don't know precisely what I search, but I found [this example](https://stackoverflow.com/questions/54651930/thingsboard-navigate-to-new-dashboard-state-widget-custom-action-javascript-code) on stackoverflow and he uses $injector.
What I try to do is this : 
When I click on an asset marker on a map, it updates the current dashboard state. But I have an entities Table containing my table of asset too. I would like that the row of this table changes color when an asset is selected on the map. I don't know if I have to use the row style function of the entities table widget, or somewhere else to put my code, and this code is executed everytime the dashboard state changes.
I don't know if this is clear, or  if this has anything to do with the injector

**Comment by ashvayka** [comment]
Since version 3.3.2, there is rich documentation about the available parameters for each function, including custom widgets. if you are using the old version, you may browse the raw doc files here: https://github.com/thingsboard/thingsboard-ui-help/tree/master/help/en_US/widget

P.S. generic functionality of angular injector is described here: https://angular.io/api/core/Injector

**Comment by lucasKapf** [comment]
@ashvayka thank for your answer, I didn't know injector was a class in angular.
