### ISSUE TITLE
[Docs] Please update docs for IoT Gateway REST connector

### ISSUE THREAD

**Issue by greg-mcnamara** [thingsboard/thingsboard#5791]
**Component**
 * Generic

**Description**
The docs for [REST Connector](https://thingsboard.io/docs/iot-gateway/config/rest/) appear to be out of date. For example:
- general section:
-- shows a single setting for host, but a separate port setting is required
-- shows a setting SSLVerify which no longer exists
-- missing required SSL setting (docs and the sample config)
-- if SSL is true, it looks like another security settings group is required (also not documented).

Also, it would be great if someone could add an example POST json payload based on the example configuration to clarify the converter settings.

**Comment by ssakharova** [comment]
Hello @greg-mcnamara,

Since you are facing an issue with the IoT Gateway, you might consider reaching out to the GitHub community regarding thingsboard gateway issues. They can provide assistance or insights that could prove valuable in addressing your specific needs.

GitHub thingsboard gateway issues - https://github.com/thingsboard/thingsboard-gateway/issues
