### ISSUE TITLE
[Question] Rename telemetry

### ISSUE THREAD

**Issue by payablez** [thingsboard/thingsboard#5803]
**Telemetry**
 * Generic

**Description**
Hi,

I want to rename the telemetry.
The only way I see to do it is through a script that fetches all telemetry, device per device, pushes again with the name and erases the original telemetry.

Anybody knows a better way to do it?
Any help appreciated.

Thank you,

**Environment**
 * OS:  Ubuntu 20.04
 * ThingsBoard: PE 3.2.1

**Comment by epalchenko** [comment]
Hello @payablez,
There is no such default feature by design of Thingsboard. However, there are two workarounds:

Develop a script that will connect to the database, copy the old telemetry from the old key to the new key, and then delete the old telemetry. Since the ""key"" is a primary key in the Cassandra database and cannot be changed.

Create a rule chain that will get the old telemetry via rest API https://thingsboard.cloud/swagger-ui/#/telemetry-controller/getTimeseriesUsingGET, post it with the old timestamp and the new key https://thingsboard.cloud/swagger-ui/#/telemetry-controller/saveEntityTelemetryUsingPOST , and then delete the old telemetry https://thingsboard.cloud/swagger-ui/#/telemetry-controller/deleteEntityTimeseriesUsingDELETE.
