### ISSUE TITLE
[Bug] Queue strategy is being ignored when sending an array of messages to rpcCallRequest node

### ISSUE THREAD

**Issue by NN01010101** [thingsboard/thingsboard#5848]
**bug**
Queue strategy is being ignored when sending an array of messages to rpcCallRequest node.

**Server Environment**
* own setup
  * docker deployment
  * ThingsBoard 3.2.2CE/PE

**Client Environment**
* OS: OSX, node app

* Connectivity
  * MQTT
  * Gateway

**To Reproduce**
1. generator node with array of numbers
2. pass the message to checkpoint node (SequentialByOriginator)
2. connect this not to script node that loops over the array and create message objects which are passed as array to rpcCallRequest node

**Expected behavior**
Messages incoming on client in incremental order.
Messages incoming one at a time, next message arrives only if client published response with requested

**Actuall behavior**
Messages incoming on client in random order.
Messages incoming all at once regardless of whether client published response with requested or not

**Screenshots**
![rule-engine](https://user-images.githubusercontent.com/10622794/148848631-132bd805-cac4-48e9-8eab-4c19111afaba.png)

![script](https://user-images.githubusercontent.com/10622794/148848599-6ec0d65b-f5f4-422f-9c82-33cd97997eb8.png)

**Additional context**
The idea is to send multiple chunks to the device via gateway since the throughput between the gateway and the device does not allow to send large packages. Throwing chunks onto the sequential queue should result in messages being sent in the same order as they were in the array, one by one, only after the previous rpc call was confirmed by the gateway. Unfortunately the opposite is the case, the order is random, and if no confirmation on topic v1/devices/me/rpc/response/requestId happened all messages are still sent out.

Maybe there is another way how to put multiple messages on a queue at one go, the one way that I've found (send array) seems to ignore strategy. Am I doing something wrong or is it a bug?
Thanks!

**Comment by SuminDenis** [comment]
Hi @NN01010101,

Explanation of how does ThingsBoard know about delivered RPC you can find by the following link:[Server RPC](https://thingsboard.io/docs/reference/mqtt-api/#rpc-api)

For your purposes, you need to use _Persistent RPC_. You can read about light RPC and persistent RPC by the following link:[RPC Guide](https://thingsboard.io/docs/user-guide/rpc/).

Also, here is the configuration for the ThingsBoard IoT Gateway MQTT Connector: [RPC Commands Configuration](https://thingsboard.io/docs/iot-gateway/config/mqtt/#server-side-rpc-commands)

When you read all the documentation mentioned above, you should be able to achieve the expected behavior!

We will close this ticket due to the long inactive time. You can open a new one if you need more help on this.
