### ISSUE TITLE
[Question] Whether the External-REST API Call Node supports sending post requests whose body is in raw/xml format?

### ISSUE THREAD

**Issue by silence-yin** [thingsboard/thingsboard#5898]
**Component**
 * Rule Engine
 
**Description**
 * Question: Whether the External-REST API Call Node supports sending post requests whose body is in raw/xml format?
 * Detail: I try to send Post Request whose request body is raw/xml format by External-REST API Call Node in thingsboard Professional Edition.  according to official Documentation, File Storage has a feature to send a single file as request body but i didn't find any entry to upload file. the only way to store file is using generate report node, file type is only  PDF | PNG | JPEG. 
so whether the External-REST API Call Node supports sending post requests whose body is in raw/xml format ? or if there is other way to send post request which body is in raw/xml format?
![node_cap](https://user-images.githubusercontent.com/40138208/149606543-41296fe4-8eb7-4acf-9552-f7ca7658c0ed.png)

**Environment**
 * OS:  Thingsboard.cloud
 * ThingsBoard version: Thingsboard v3.3.3PAAS-RC1

**Comment by volodymyr-babak** [comment]
hi @silence-yin 

REST-API call node is not able to send XML requests on the [TB cloud](https://thingsboard.cloud). 
ThingsBoard platform is not designed as file storage, and that's why upload file functionality is not available on the [TB cloud](https://thingsboard.cloud).

One of the possible options to consider is to have a PE edition that is managed by you or the ThingsBoard support team, where you'll be able to add custom rule node components.
You'll be able to develop a custom rule node component, that based on your business requirement will generate XML files and store them in the platform. Once this file is stored, you'll be able to use it in the REST API Call node.
Here are more details on Java custom rule node development:
https://thingsboard.io/docs/user-guide/contribution/rule-node-development/

**Comment by silence-yin** [comment]
Hi @volodymyr-babak 

I get it now
Thank you for your prompt reply.
