### ISSUE TITLE
Multiple "All" device groups

### ISSUE THREAD

**Issue by Kevinowitsch** [thingsboard/thingsboard#5918]
![all](https://user-images.githubusercontent.com/83923282/149981459-54e4bda6-da21-485f-9bce-be3cc14a5539.PNG)
**Component**

 * Generic

**Description**
I have multiple (3 to be exact) instances of "All" in the device groups. 
One contains the majority of our devices. The second contains 45 devices and the third cotained 1 device, wich I deleted to see if the group disappears. It didn't.
Whats the issue with that and how can I fix that?

**Environment**

 * OS:  Win10
 * ThingsBoard: PE 3.3.2
 * Browser: Firefox

**Comment by volodymyr-babak** [comment]
hi @Kevinowitsch.
This is not possible on the database level if you are using PE 3.3.2 and PostgreSQL as database.
Here is the entity_group CONSTRAINT: 
**CONSTRAINT group_name_per_owner_unq_key UNIQUE (owner_id, owner_type, type, name)**
As you can see the name is used in the UNIQUE key for this table and it's not possible to create multiple 'All' groups for the same owner and type.

So most probably this issue is related to some errors during migration from Cassandra or maybe something else, but it's hard to provide an answer without deep knowledge of your setup.
Please provide as many details of your environment as possible, as well please additionally specify the history of your environment - when and from what database you migrated, etc. 

Having details in place probably we can provide you some feedback on what is wrong at the moment with your environment.

**Comment by Kevinowitsch** [comment]
So we just recently mirgrated to PE 3.3.2. Before we were on PE 2.4.2 and at the very beginning we had an even older version (PE 2.2 ?). I connot say when this problem occured first, but when I started working with TB, there were already multiple "ALL" device groups.

All versions were using PostgreSQL.

The two earlier versions were installed as AWS Marketplace all in one package on a single server. Data bank backup was transfered manually as descriped in guide at that time. (update data to the same version as new TB version and then transfer to new TB).

So the issue must have probably occured during the first update process.

PE 3.3.2 now runs on AWS EKS.

**Comment by volodymyr-babak** [comment]
@Kevinowitsch 
There must be done particular manipulations on the database side to attach devices to a single 'All' group and remove duplicate groups.
If you are using the PE version you should have access to the TB customer portal. 
Please create a ticket for this problem on the customer portal - https://thingsboard-portal.atlassian.net/servicedesk/customer/portals.
TB support team will be able to help you on this topic, once you'll provide credentials to the platform.

**Comment by Kevinowitsch** [comment]
I found the source of that problem. 2 customers had in their "All" device group permission given to us as tenant. therefore this group appeared in our tenant device groups.
