### ISSUE TITLE
How to group the Interval in Thingsboard Dashboard > Chart Widget > New time series Bar Chart > Realtime filter?

### ISSUE THREAD

**Issue by suncodetb** [thingsboard/thingsboard#5994]
Hi, 

This question is wrt the Thingsboard Dashboard > Chart Widget > New time series Bar Chart.

When i select the Realtime / History Filter feature i noticed that i cannot enter any time interval:

Steps that i followed:

Step 1: Updated the Realtime filter to view the readings for last 1 hour on my dashboard ('Last' drop-down set to 'Last 1 hour')

Step 2: Select any 'Data aggregation function' e.g.'Max' or any other value except 'None' to enable the 'Grouping Interval' filter.

Step 3: In 'Grouping Interval' enable the 'Advanced' button. I wanted to group the interval to 10 minutes but when i enter 10 min and move outside, the value is defaulted to 8 Min 34 seconds automatically.

similarly i tried for 'Last 1 minutes' and 'Group interval' is now defaulted to 8 seconds.

Question 1: Can you please help in understanding why thingsboard has put this restriction ? It would be helpful to know the business reason for putting this logic ?

Question 2: Is there a way i can override the above default logic and group the interval by any random interval more than default value?

Screenshot :https://i.stack.imgur.com/Y9jZs.png

Thanks a lot ! Sun

**Comment by kalutkaz** [comment]
Hi @suncodetb, 

You have this problem because 'Grouping Interval' function has a limit on the minimum and a maximum number of values. In your case with 'last 1 hour' timewindow Thingsboard calculated that interval 10 minutes can`t create a minimum necessary number of values and automatically changed the interval to 8 minutes 34 seconds. 

Also, you can more read about 'Grouping Interval' here: https://github.com/thingsboard/thingsboard/issues/5863

**Comment by suncodetb** [comment]
@kalutkaz Thank you, this is helpful !
