### ISSUE TITLE
[Bug] Remove User broken

### ISSUE THREAD

**Issue by janvl1234** [thingsboard/thingsboard#6007]
The system will give the following error when trying to remove a user: "could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet"

* own setup
  * cloud infrastructure
  * ThingsBoard Version v3.3.3
  * Ubuntu 20.04.3 LTS 

**To Reproduce**
1. Create a user
2. Delete a user
3. See error. 
"could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet"

https://www.janvanloenen.com:9091/share.cgi?ssid=28658c7ce4b6470fa962a25494513f63&ep=&fid=28658c7ce4b6470fa962a25494513f63&open=normal

**Comment by volodymyr-babak** [comment]
@janvl1234 
most probably you have an incorrect database schema.
Please make sure that you had installed properly ThingsBoard according to the official documentation website.
In case of the upgrade - please make sure that you did all the steps in the upgrade guide.

If after verification that you did everything correctly you'll still see problems - please attach your thingsboard.log file to the ticket.
We'll be able to provide you exact reason from the stack trace.

But removing user functionality works totally fine and is covered by different integration tests.
The issue is exactly with your environment, and not because of the bug.

**Comment by Ultrazombie** [comment]
Hello @janvl1234, Did this happen after the upgrade or with a clean TB installation?

**Comment by janvl1234** [comment]
@Ultrazombie 
This happened with an upgrade from v3.3.2 to v3.3.3

**Comment by Ultrazombie** [comment]
@janvl1234 Please try running the upgrade scripts again, I have checked several times, I have a clean install, and from 3.3.2 to 3.3.3, all works fine

**Comment by janvl1234** [comment]
@Ultrazombie 
Running the upgrade script a 2nd time seem to fix the issue.
