### ISSUE TITLE
Need support in establishing communication with Thingsboard Gateway via MQTT & OPC-UA protocols[Question] your title here

### ISSUE THREAD

**Issue by bhimashankarP** [thingsboard/thingsboard#6038]
**Component**

- Thingsboard Cloud (PasS Instance) v3.3.3
- Docker Desktop v.4.4.4
- Node-Red v2.2.0

**Description**

1. Installed Thingsboard Gateway container in the Docker Desktop
2. We have configured two Gateways in Thingsboard at Tenant level [ attached tb_gateway.yaml file for MQTT & OPC-UA]

> 3. MQTT_Gateway (For MQTT ) - attached "mqtt.json" file
> 4. OPC-UA Gateway (For OPC-UA) - attached "opcua.json" file

5. We are running a Gateway container with connectors configured for MQTT & OPC-UA individually in “tb_gateway.yaml” file. We tried each connector once at a time.
6. We are using Node-Red to publish data to MQTT Broker & TB Gateway will subscribe to it. [attached exported JSON file]
7. For OPC-UA server, we have used free opc-ua server python script to publish data. Attached "opcua_server.py" file.

Issue is Irrespective of protocols  [MQTT/OPC-UA]  used, Thingsboard board Gateways establishes the connection successfully but not creating the respective devices and not updating the telemetry data of existing devices. We are not getting any error messages so far from any of the log files.

Your support would be very much appreciated.

Kind Regards,
Bhimashankar 
![mqtt_json](https://user-images.githubusercontent.com/38416893/152683360-e5ca83af-fbca-41ba-9268-160ef5f8cb4d.png)
![Node-Red MQTT Boker Screenshot](https://user-images.githubusercontent.com/38416893/152683366-e6479631-1bf3-41d3-b6fa-e2f16fac8801.png)
![Node-Red Publish Data Flow Screenshot](https://user-images.githubusercontent.com/38416893/152683367-8b4208e6-882d-4a09-b8c8-f5463c159342.png)
![opcua_json](https://user-images.githubusercontent.com/38416893/152683368-1864ddb1-fa2c-407f-9857-cf56aa79a482.png)
![tb_gateway_yaml](https://user-images.githubusercontent.com/38416893/152683371-e04cc95a-5a13-4112-a2cc-a2b5dcc1613d.png)

**Comment by ashvayka** [comment]
@zbeacon , please check and provide accurate steps to collect gateway logs. I assume gateway is not connected to the cloud but we need to confirm this.

**Comment by zbeacon** [comment]
Hi @bhimashankarP,

In order to understand the reason of the described behavior please follow the next steps and give us information after getting results:
1. Please check "active" server attribute of the gateway device - is it true?
2. Please try to use IP address instead of "host.docker.internal" for "host" parameters in configuration and restart the gateway.
If steps above don't help you please provide us the gateway logs. In order to enable debug logging you can follow the next steps:
1. open logs.conf file in your config folder.
2. Replace all "INFO" to "DEBUG"
3. Restart the gateway
4. You can find logs in your mounted logs folder (Usually ~/.tb-gateway/logs in Linux-based systems or C://Users/YOUR_USER/tb-gateway/logs in Windows)
