### ISSUE TITLE
Thingsboard mapping - splitting telemetry data correctly into attributes and timeseries

### ISSUE THREAD

**Issue by m-menon** [thingsboard/thingsboard#605]
Whenever I post the telemetry data from sensors ( through thingsboard gateway ), I am also adding the time (unix time as well as datetime in ISO8601 format) to json data. For example

    {"MAC": "00-14-22-01-23-45","UNIX_TIME": 1519404687,"ISO8601_DATETIME": "2018-
    02-23T16:52:38+00:00","VOLTAGE": 3.452}

I was just curious - If we were to split the above data into attributes and timeseries, would it be correct ( in a strict sense ) to split it like this

Attributes: **MAC**
Timeseries: **UNIX_TIME**, **ISO8601** and **VOLTAGE**

Or would the UNIX_TIME and ISO8601 go under attributes? Because (logically and technically speaking) they are attributes of the  posted data? I am no expert in deciding that so It would be great to hear from others. I want to use these in the mapping and want to make sure that I start off right. Thanks

**Comment by aderusha** [comment]
Read up on the following two documents which might clear things up for you: https://thingsboard.io/docs/user-guide/entities-and-relations/
https://thingsboard.io/docs/user-guide/attributes/

In your specific case, I'm left to wonder why you would bother recording two different time stamps - or even one - because all time series data entries (like VOLTAGE) will be timestamped in the database already.  I would argue that you wouldn't want to keep either UNIX_TIME or ISO8601, but if you need them for some reason I suspect that they would be probably best saved as time series data.

**Comment by m-menon** [comment]
@aderusha thanks. The reason I needed timestamp was because the tb gateway devices are mobile and there might be connectivity issues sometimes preventing the data from reaching the thingboard server immediately, and hence the timestamp to let me know when the data was logged. Thanks for the links, I understood most of it but didn't see an example that had datetime in it, and I wasn't too sure cos I felt it could fit into either. But as you said perhaps its makes sense to have them under time series data. :+1:
