### ISSUE TITLE
Ability to set State Entity for Default/Home Dashboard

### ISSUE THREAD

**Issue by igloodan** [thingsboard/thingsboard#6052]
**Is your feature request related to a problem? Please describe.**
I have a lot of users who have access to only one device which uses a dedicated dashboard, if I could set the state entity in their user settings then I could avoid the need for an initial dashboard state which they (in 99% of cases) choose a device from a list of 1, which is pointless.

**Describe the solution you'd like**
Add another box on the user settings form to choose a state/state-entity for the default/home dashbaord.

**Describe alternatives you've considered**
I have considered either developing or paying for the development of an entity table widget which automatically carries out a "Row Click" action if there's only one item in the list but this will look a bit strange to the users when they see a page load, then instantly be replaced.

**Comment by epalchenko** [comment]
Hello @igloodan,
You can implement your request by developing a custom widget. Please familiarise yourself with Widget Development Guide: https://thingsboard.io/docs/pe/user-guide/contribution/widgets-development/
Since the community hasn't helped you in two years, I'm closing this ticket as inactive.
