### ISSUE TITLE
[Question] Rule Chain is taking too much time

### ISSUE THREAD

**Issue by hector-gerard-protectline** [thingsboard/thingsboard#6060]
**Component**

 * Rule Engine

**Description**
Hello, 

Our processes need to be fast with a consistent duration. But we find it very slow sometimes.
When we add debug mode to trace a message from the begging to the end of a rule chain, we find out that there can be up to 5 seconds between two nodes or even few seconds between IN/OUT for a script filter node that only do an "if". 
For example, one of our process need to be 30 seconds, so when it is faster: we add a delay, but most of the time it is slower and goes to 50 seconds.

So, my question is, is it normal for a rule chain node to take sometime more than a second to respond and that the message is taking time to be processed by the next node? 

Thank you.

**Environment**

 * ThingsBoard: TB 3.2.2
 * Browser: Chrome 97.0.4692.99

**Comment by volodymyr-babak** [comment]
@hector-gerard-protectline 
that depends on many factors. 
As a starting point I would recommend getting familiar with the Rule Engine Queue concept:
https://thingsboard.io/docs/user-guide/rule-engine-2-0/overview/#rule-engine-queue

Next step - taking a look at the Rule Engine Statistics dashboard:
![image](https://user-images.githubusercontent.com/3466101/153184281-ff852d7b-3296-4759-8b1e-2f1ec973bcc2.png)
You can navigate to it from the 'Api Usage' menu.
You'll be able to see possible errors in your environment or the number of timeout messages.

In your case, most probably the reason is a lot of JS executions are happening in the rule engine, and the JS engine is not able to effectively process these JS requests. You'll be able to identify this from the Rule Engine Statistics dashboard.
If your rule engine is not shared between multiple users and you control who is changing the rule chains, I would recommend starting by disabling the sandbox feature of the rule engine - this should speed up your JS engine.
You can disable it by setting env **USE_LOCAL_JS_SANDBOX** variable to **false**:
https://thingsboard.io/docs/user-guide/install/config/#javascript-evaluator-parameters

p.s. Here are more details on what is a sandbox https://github.com/javadelight/delight-nashorn-sandbox.

And additionally, you can enable debug log level for a special java class, and once you'll do this - you'll be able to see in the logs rule nodes that are taking the most time to process, and probably this will give you glue on what is happening in your environment:
https://thingsboard.io/docs/user-guide/troubleshooting/#message-pack-processing-log

Please do the investigation based on these tips. If this will not help identify the root cause, please provide as many details on your investigation in the ticket, so we'll be able to suggest you next steps.

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
