### ISSUE TITLE
[Bug] Use Chrome version 97.0.4692.99 (official version) (x86_64) to access the add dashboard function, does not support drag and drop images

### ISSUE THREAD

**Issue by 15168316096** [thingsboard/thingsboard#6081]
**Describe the bug**

**Your Server Environment**

* demo.thingsboard.io
* cloud.thingsboard.io
* own setup
  * cloud or local infrastructure or docker deployment
  * ThingsBoard Version
  * OS Name and Version

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

**Smartphone (please complete the following information):**
* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Your Device**

* Connectivity
  * MQTT
  * HTTP
  * CoAP
  * Gateway
  * Integration: (Specify name) 
* Device vendor and model

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by mykhailokornieiev** [comment]
Hi 15168316096
Please let me know if your issue is still relevant. Perhaps you have already found a solution? If it's still relevant, please clarify your desktop and server environment, ThingsBoard version and is it works similar on other browsers?
Best regards,
Mykhailo Kornieiev,
TechOps Engineer at Thingsboard

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
