### ISSUE TITLE
[Question] How to write the mqtt mapper/converter for an input json payload with an array of device data in IoT Gateway configuration file?

### ISSUE THREAD

**Issue by FacelookHK** [thingsboard/thingsboard#6094]
**Component**

 * IoT Gateway

**Description**
I have a BLE gateway that scans nearby BLE beacons and aggregates the data into an array and sends it to MQTT broker. I would like to know how to write the IoT Gateway mqtt mapper/converter in the mqtt configuration file?

The incoming json payload from the MQTT broker has something like this:

[{
    "deviceName": "0001"
 }, {
    "RSSI": -70
}, {
    "RSSI": -54
}]

**Environment**

 * OS:  Ubuntu 20.04
 * ThingsBoard: 3.3.3
 * Browser: Any

**Comment by ssakharova** [comment]
Hello @FacelookHK,

Since you are facing an issue with the IoT Gateway, you might consider reaching out to the GitHub community regarding thingsboard gateway issues. They can provide assistance or insights that could prove valuable in addressing your specific needs.

- GitHub thingsboard gateway issues - https://github.com/thingsboard/thingsboard-gateway/issues

Best regards,
Sofiia
