### ISSUE TITLE
[Bug] refresh token gives 401 error

### ISSUE THREAD

**Issue by znnspace** [thingsboard/thingsboard#6144]
**Your Server Environment**
v3.2.1

**Screenshots**
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/25051018/155125032-673df74a-0f21-42ed-b368-e02d12fbdad8.png">

**Comment by ashaforost** [comment]
Hi @znnspace 

The 401 Unothorizer error usually points to invalid credentials, the user under these credentials is not active or the user password expired.
Please check your request and let me know if the issue is still present. If so, please provide the example of your request and the full text of the error.
