### ISSUE TITLE
Can't export dashboard - Connection refused: localhost/127.0.0.1:8383

### ISSUE THREAD

**Issue by anonim8080** [thingsboard/thingsboard#6218]
**Component**

 * UI

**Description**
I am getting the following error "Connection refused: localhost/[127.0.0.1:8383](http://127.0.0.1:8383/)" when I try to export a dashboard or generate a report through Scheduler.

**Environment**

 * OS:  Debian 10
 * ThingsBoard: 3.3.3PE-1
 * Browser: Firefox 97.0.1

**Comment by mykhailokornieiev** [comment]
Hello anonim8080
Please let me know if your issue is still relevant. Perhaps you have already found a solution?
If not, please clarify in what format did you try to export the dashboard? Where exactly is the error observed (at the stage of export or import)? Also you can give us thingsboard.log file to check what causes the problem.
Best regards,
Mykhailo

**Comment by anonim8080** [comment]
Hello,

issue resolved.

Thanks

**Comment by GlanThorian** [comment]
Hi, 

I have the same error. Would you please tell me what was the solution for this problem?

BR,

**Comment by milkmeslow** [comment]
The solution is to install the web component (step 9 here - https://thingsboard.io/docs/user-guide/install/pe/ubuntu/).

**Comment by GlanThorian** [comment]
Thanks, that must be it. I will check whether the component has been installed or not (but I guess not).

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
