### ISSUE TITLE
[Bug] Entities Hierarchy widget doesn't work properly when using a filter.

### ISSUE THREAD

**Issue by lucasKapf** [thingsboard/thingsboard#6227]
**Describe the bug**
When using a custom filter, the entities hierarchy widget doesn't show the related entities in the widget
**Your Server Environment**

* cloud.thingsboard.io

**Your Client Environment**

**Desktop (please complete the following information):**

* OS:  Windows 10
* Browser Chrome

**To Reproduce**
1. Create an entities hierarchy widget based on clients
2. Provide a custom filter that would check if a boolean attribute of the client is true
3. See that only the clients are displayed and not their related entities

**Expected behavior**
I would expect that my filter filters the client, but then displayed all their related entities. I think that in fact my filter is applied on the related entities too : the attribute tested in my filter doesn't exists on the related entities so they are not displayed. I would expect that my filter is applied only on the datasource (the clients) on the root level of the hierarchy and not on their related entities.

**Comment by stevmei** [comment]
I can confirm this is still the case.

**Comment by SuminDenis** [comment]
Hi @lucasKapf,

You cannot apply a filter only on the root level of the hierarchy via the **Entities Hierarchy Widget** because of the ThingsBoard design. However, you are free to develop your custom widget with the feature mentioned above.

As a hint, here is the list of articles regarding custom development capabilities on top of out-of-the-box features:
[Widget Development](https://thingsboard.io/docs/pe/user-guide/contribution/widgets-development/)
[Custom Action](https://thingsboard.io/docs/user-guide/ui/widget-actions/#custom-action)
