### ISSUE TITLE
Bridging NodeRed to ThingsBoard

### ISSUE THREAD

**Issue by AvishekHardin** [thingsboard/thingsboard#623]
Hello Team,

Good day, grateful if you could extend your help. I have my sensors connected to NodeRed hosted locally, sensors are publishing data to NodeRed via MQTT. 

My aim is to send all my sensor data from NodeRed to ThingsBoard via any MQTT. Attached is the picture. I have checked the bridge option, but unfortunately its not working can you please guide me the proper way in doing so.

Thanks for your help.
Best Regards,
![nodered to thingsboard](https://user-images.githubusercontent.com/7479253/36900096-4bee6e82-1e3b-11e8-839f-b4b315d42eb8.png)

**Comment by Javierete** [comment]
Hello,

You can use the device API to publish from node-red to thingsboard via mqtt
(adding an mqtt output node pointing to thingsboard server) another option
is a post request.

Excuse my brevity I'm replying from mobile


El 2 mar. 2018 14:02, "AvishekHardin" <notifications@github.com> escribió:

Hello Team,

Good day, grateful if you could extend your help. I have my sensors
connected to NodeRed hosted locally, sensors are publishing data to NodeRed
via MQTT.

My aim is to send all my sensor data from NodeRed to ThingsBoard via any
MQTT. Attached is the picture. I have checked the bridge option, but
unfortunately its not working can you please guide me the proper way in
doing so.

Thanks for your help.
Best Regards,
[image: nodered to thingsboard]
<https://user-images.githubusercontent.com/7479253/36900096-4bee6e82-1e3b-11e8-839f-b4b315d42eb8.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/thingsboard/thingsboard/issues/623>, or mute the thread

**Comment by AvishekHardin** [comment]
Hello Javierete,

Thanks for your swift response.
I tried just like you mentioned above, However, am getting data for only one of my sensors. 
I used the Access-Token as username in NodeRed MQTT out, however I noticed that the Access-Token is static when adding new MQTT OUT node in NodeRed. Means the same access token is replicated for any new nodes am actually adding. additionally if i change the UserName (Access-Token) for anyone of the MQTT OUT node, the rest of the MQTT OUT node are having the same Access-Token. 

Is this the correct way of doing this? Can you please advise how to do this. 

NOTE: am actually pusblishing data to the following topic "v1/devices/me/telemetry" using Access-Token as username.

Many thanks for your help.
Best Regards,

**Comment by Javierete** [comment]
Hello @AvishekHardin you are correct. 
As far as I know Node-red mqtt node doesn't permit change of username dinamically, so two options here:

1. Make many node-red brokers as devices you have. (a little bit messy if you want to post many devices)
2. Use http request instead, here you can define an HTTP POST to a dynamic URL simply by setting URL string.

**Comment by AvishekHardin** [comment]
Hello Javierete,

Gosshhhh... ok i will try above. many thanks for your help.

Best Regards,

**Comment by armyjam** [comment]
> Hello Javierete,
> 
> Gosshhhh... ok i will try above. many thanks for your help.
> 
> Best Regards,

Can I have your setting on node red please?

**Comment by hanno1234** [comment]
i am having trouble with sending mqtt from node red to thingsboard. In node red mqtt out: topic:v1/devices/me/telemetry
 server: http://demo.thingsboard.io
username: device token 
it shows conected in node red but never shows in latest telemetry in TB

**Comment by armyjam** [comment]
> i am having trouble with sending mqtt from node red to thingsboard. In node red mqtt out: topic:v1/devices/me/telemetry
> server: http://demo.thingsboard.io
> username: device token
> it shows conected in node red but never shows in latest telemetry in TB

Did you send by JSON format?

**Comment by MsalahBibars** [comment]
Hello team,
my data were connected successfully between NR and TB, but now with the same setting, I can't get NR Connect with TB.
can somebody help me to solve this issue?

thanks

**Comment by claib** [comment]
Hello everybody
got exactly the same troubles as described above. NR is sending mqqt messages correctly to another free mqtt broker, but not to Thingsboard. NR finds TB is connected ( green ), but  when sending a message, it  gets red....
![image](https://user-images.githubusercontent.com/8424229/67359316-403fc800-f563-11e9-97f4-99903725a273.png)
.... And telemetry data field in TB stays empty.
an advice ?
best, Christoph

**Comment by simonbuehler** [comment]
hi @claib 

i have the same issue, how did you fix it?

**Comment by AvishekHardin** [comment]
Hi Everyone,

**Comment by AvishekHardin** [comment]
Hi Everyone,

you can use settings as per the attached snapshot.
I hope it helps you.

![setting](https://user-images.githubusercontent.com/7479253/80700167-4902ef00-8aee-11ea-937c-aa4e03aa5f4f.png)

Thanks,

**Comment by simonbuehler** [comment]
thanks, the solution was to send proper json formatted data using a template node

**Comment by martin9115** [comment]
Hi, i did the same settings, but cant upload any data. Any help?
