### ISSUE TITLE
503 http error after a while loading data with http calls

### ISSUE THREAD

**Issue by stefanolissa** [thingsboard/thingsboard#626]
Hi, after sometime the server is up I start getting this response to http calls to inject data:

`<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Mon Mar 05 08:25:38 CET 2018</div><div>There was an unexpected error (type=Service Unavailable, status=503).</div><div>No message available</div></body></html>`

I'm using the latest version. 

I cannot find an error log which explains where the problem is, any idea on how to debug it?

Thank you, Stefano.

**Comment by vparomskiy** [comment]
In case if there is no useful information in the Thingsboard log file, you can always enable debug logging level in Thignsboard configuration for more detailed logging.

**Comment by stefanolissa** [comment]
Yes, thank you very much, it was a bad written condition in an alarm... should those kind of error block the data acquisition?

Thank you, Stefano.

**Comment by vparomskiy** [comment]
Thingsboard should guarantee message delivery. With the current rule engine architecture, the only way to guarantee this is to wait till all rule chains will be finished, otherwise throw an error.
We are working on a new rule engine that will have more sophisticated algorithms for message delivery and it will not be a problem in the future if

**Comment by stefanolissa** [comment]
Thank you very much, Stefano!
