### ISSUE TITLE
some doubts about profile function

### ISSUE THREAD

**Issue by john1337** [thingsboard/thingsboard#6275]
**Component**

 * Generic

**Description**
i am considering update thingsboard version to 3.3.4, i found there are many profile functions compared to thingsboard 3.1 version,i am wondering the considerations for adding profile funtions such as device profile?

**Environment**

 * OS:  ubuntu20.04
 * ThingsBoard: 3.3.4

**Comment by mde2017** [comment]
Hi @john1337,

the functionality of device profiles is described here:
https://thingsboard.io/docs/user-guide/device-profiles/

It can be quite useful e.g. for defining Alarm rules easier (without development of rulechains) or to have separate rulechains for device data processing instead of the Root rulechain. But you don't have to use this functionality if it doesn't fit to your usecases. Then you can treat the device profiles just as device types.

Hint: If you perform the upgrade process, keep in mind to update iteratively from one version to next release, step-by-step.
In your case first upgrade from 3.1 to 3.1.1, then from 3.1.1 to 3.2, ...
https://thingsboard.io/docs/user-guide/install/upgrade-instructions/

**Comment by john1337** [comment]
thanks
