### ISSUE TITLE
Upgrade newversion

### ISSUE THREAD

**Issue by epneo-banuprakash** [thingsboard/thingsboard#6385]
**Component**
 
 * Installation nd upgradation 
 
**Description**
Can we upgrade ThingsBoard version from 3.2.1 to 3.3.4.1 (Latest) directly in ubuntu linux system 

**Environment**
Ubuntu-LTS
Production

**Comment by Backdraft007** [comment]
No,
3.2.1 -> 3.2.2
3.2.2 -> 3.3.
3.3 -> 3.3.1
3.3.1 -> 3.3.2
3.3.2 -> 3.3.3
3.3.3 -> 3.3.4
3.3.4 -> 3.3.4.1

And since 3.2.2 Java 11 is used:
https://thingsboard.io/docs/user-guide/install/ubuntu/#step-1-install-java-11-openjdk

CE:
https://thingsboard.io/docs/user-guide/install/upgrade-instructions/#upgrading-to-322

PE:
https://thingsboard.io/docs/user-guide/install/pe/upgrade-instructions/#upgrading-to-322pe
