### ISSUE TITLE
[Bug] Post to api/dashboard with id resets created_time

### ISSUE THREAD

**Issue by eykamp** [thingsboard/thingsboard#6427]
**Describe the bug**
Calling the api/dashboard endpoint, specifying an id, resets the dashboard created_time field to 0.

Packet being sent:
{
  "id": {
    "id": "784f394c-42b6-435a-983c-b7beff2784f9",
    "entityType": "DASHBOARD"
  },
  "title": "Dash",
  "configuration": { ... }
}

Update seems to work otherwise.

**Your Server Environment**

* own setup
  * cloud 
  * ThingsBoard Version 3.3.3, Postgres
  
cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Comment by sumin-denys** [comment]
Hi @eykamp,

I am glad to inform you that this issue was resolved in the current ThingsBoard version. 

Please refer to our release notes to find out more about new features and bug fixes: [Release Notes](https://thingsboard.io/docs/reference/releases/)
Thank you for your request. I am closing this issue since the bug was resolved.

If you have any further questions, please feel free to create a new issue or reopen this one.
