### ISSUE TITLE
[Feature Request] dotted and dashed line representation in Timeseries Line Chart 

### ISSUE THREAD

**Issue by ThomasBaumgartner** [thingsboard/thingsboard#6440]
**Describe the solution you'd like**
It would be great to have the possibility to choose the line pattern in timeseries line chart. Someone should be able to choose whether a line is solid, dashed or dotted.

**Comment by mde2017** [comment]
Hi @ThomasBaumgartner,

you may take a look at **Data Key configuration** --> **Advanced**:

![image](https://user-images.githubusercontent.com/25298332/164026128-0f095cb5-4caf-40c0-9081-d66ba96c66f1.png)

![image](https://user-images.githubusercontent.com/25298332/164025698-75764d58-633a-408f-a4a2-51deb16a3237.png)

There you can already change options like e.g. display points instead of lines.
But indeed dotted lines aren't currently supported, yet.
