### ISSUE TITLE
[Question] Load data over http instead of websockets in a dashboard?

### ISSUE THREAD

**Issue by ChristofferHolmesland** [thingsboard/thingsboard#6460]
**Dashboard**

 * UI

**Description**
Some of our customers are using firewalls that block websocket traffic. When they open the dashboards we create for them they are able to see the dashboard, but data never loads because the traffic is blocked. Is it possible to configure dashboards and the included widgets to load data over http instead of websockets?

**Comment by qwykx** [comment]
Hello @ChristofferHolmesland 

Using HTTP instead of websockets isn't possible in the current implementation.

The problem with using HTTP is that it isn't meant to be bi-directional even though there are certain workarounds for that e.g. _Long Polling_. Have a look at [Long Polling vs. Websockets](https://ably.com/blog/websockets-vs-long-polling#:~:text=Generally%2C%20WebSockets%20will%20be%20the,hops%20between%20servers%20and%20devices.) to see why to use latter.

I don't see any problem with allowing WebSockets for Websites on a company firewall.

Cheers

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
