### ISSUE TITLE
Removing telemetry data

### ISSUE THREAD

**Issue by marciopamplona** [thingsboard/thingsboard#647]
How to correctly remove some telemetry data from a device (a time window of data) in a running system?

**Comment by Tangerino** [comment]
And what is the data persistency policy? I'd like to purge temperature data from 30 days but retain energy consumption data for about a year. Is that possible?

**Comment by DIYGuy01** [comment]
I think yes. I constantly remove not correct data sent during the development directly from database. You can write the query and remove particular data like temp_from_sensor1. Tables structure is flat, have not seen any impact. Just in your case you need to work with Unix Timestamp type date field because each record is in this format when it arrives.
values table "ts_kv", "sensor0" is my sensor.

![image](https://user-images.githubusercontent.com/37554013/37616573-0d56ce18-2bb9-11e8-9e00-dc046ab531d9.png)

**Comment by marciopamplona** [comment]
Hi @DIYGuy01 , you can post your query ?

**Comment by fotis400** [comment]
I am in need of this feature as well.

Can we see such an option in the Web UI?

**Comment by eduardonatan** [comment]
@DIYGuy01 hello! any idea about how to do it with cassandra?
@Tangerino Did you find something? I'm trying to do the same

**Comment by untilbit** [comment]
I'm also interested in this for Cassandra or directly from Thingsboard.

**Comment by eduardonatan** [comment]
Hi @untilbit 
This is what I'm doing with Cassandra right now, probably is not the best approach but is working:

The thingsboard does not allow database management through its UI, so, we need to connect directly with the thingsboard DB.

**Query a specific value from a specific device:**

The ts_kv_cf table stores all the telemetry data of all devices and sensors.

entity_id = device id (can be found in thingsboard device UI)
key = name of the data


`SELECT * FROM thingsboard.ts_kv_cf WHERE entity_id = f35bcef0-3ef5-11e8-8fd0-cb746776d0c2 and key = 'temperature' ALLOW FILTERING;`



**Creating functions to get date/time intervals in cassandra:**

Cassandra does not support arithmetics operations (version 3.11), so it is impossible to do something like “SELECT * FROM thingsboard.ts_kv_cf WHERE ts <= now() - 7d”, to be able to get for example the last 7 days, we need to create a UDF function in Cassandra, using Java. For that:

First, you have to turn on enable_user_defined_functions: true in the conf/cassandra.yaml file.

then create the function:

```
CREATE FUNCTION IF NOT EXISTS thingsboard.timeAgoMinsOrDaysOrMonths(minutes int, days int, months int) 
  CALLED ON NULL INPUT 
  RETURNS timestamp
  LANGUAGE java AS '
    long now = System.currentTimeMillis();

    if (minutes != null)
	  return new Date(now - (minutes.intValue() * 60 * 1000));
    else if (days != null)
	  return new Date(now - (days.intValue() * 86400000));
    else if (days != null)
	  return new Date(now - (months.intValue() * 2629746000L));
    else
	 return new Date(now);
    
  ';

  ';
```
[check this](https://stackoverflow.com/questions/46135576/how-to-do-arithmetics-with-datetimes-in-cql?rq=1)

Note: The function has 3 parameters, you need to decide if you want to use an interval in minutes, days or months, once you decided the other parameters should be passed as null values.  

timeAgoMinsOrDaysOrMonths(minutes,days,months)

**This query returns the last 7 days of temperature data from a device:**

`SELECT * FROM thingsboard.ts_kv_cf WHERE entity_id = f35bcef0-3ef5-11e8-8fd0-cb746776d0c2 and key = 'temperature' and ts >= timeAgoMinsOrDaysOrMonths(null,7,null) ALLOW FILTERING;`

**The same query, but it returns the last 1 month of temperature data from a device:**

`SELECT * FROM thingsboard.ts_kv_cf WHERE entity_id = f35bcef0-3ef5-11e8-8fd0-cb746776d0c2 and key = 'temperature' and ts >= timeAgoMinsOrDaysOrMonths(null,null,1) ALLOW FILTERING;`

**The same query, but it returns the last 10 minutes of temperature data from a device:**

`SELECT * FROM thingsboard.ts_kv_cf WHERE entity_id = f35bcef0-3ef5-11e8-8fd0-cb746776d0c2 and key = 'temperature' and ts >= timeAgoMinsOrDaysOrMonths(10,null,null) ALLOW FILTERING;`

**This new function allow us to execute clean routines in the database, for instance, if we want to erase the last seven days of data, we can execute:**

`DELETE FROM thingsboard.ts_kv_cf WHERE entity_id = f35bcef0-3ef5-11e8-8fd0-cb746776d0c2 and key = 'temperature' and partition IN (1525132800000, 1522540800000, 1525132800000) and entity_type = 'DEVICE' and ts >= timeAgoMinsOrDaysOrMonths(null,7,null);`

**if we want to keep just the last 7 days of data and erase everything else:**

`DELETE FROM thingsboard.ts_kv_cf WHERE entity_id = f35bcef0-3ef5-11e8-8fd0-cb746776d0c2 and key = 'temperature' and partition IN (1525132800000, 1522540800000, 1525132800000) and entity_type = 'DEVICE' and ts <= timeAgoMinsOrDaysOrMonths(null,7,null);
`
obs: the partition and the entity_type must be used to delete actions on Cassandra (because they form the primary key of the entity). To see all the partitions and be able to use them in the IN clause, you need to query the ts_kv_partitions_cf table.

Hope that helps

**Comment by mcpicoli** [comment]
**IMPORTANT!!!**

_Please note the function posted above is wrong (has a typo) and will have DISASTROUS results if used to expunge old data measured in months:_ (but will work fine for minutes and days)

Where it reads:
```

    else if (days != null)
	  return new Date(now - (months.intValue() * 2629746000L));
```

It should read:

```
    else if (months != null)
	  return new Date(now - (months.intValue() * 2629746000L));
```

So that the full code should be:

```
CREATE FUNCTION IF NOT EXISTS thingsboard.timeAgoMinsOrDaysOrMonths(minutes int, days int, months int) 
  CALLED ON NULL INPUT 
  RETURNS timestamp
  LANGUAGE java AS '
    long now = System.currentTimeMillis();

    if (minutes != null)
	  return new Date(now - (minutes.intValue() * 60 * 1000));
    else if (days != null)
	  return new Date(now - (days.intValue() * 86400000));
    else if (months != null)
	  return new Date(now - (months.intValue() * 2629746000L));
    else
	 return new Date(now);
    
  ';
```

Example run with the bugged function (2019-06-12):

```
cqlsh> select thingsboard.timeagominsordaysormonths(null, null, 3) from system.local;

 thingsboard.timeagominsordaysormonths(NULL, NULL, 3)
------------------------------------------------------
                      2019-06-12 19:01:35.627000+0000
```

Example run with the corrected function (2019-06-12):

```
cqlsh> select thingsboard.timeagominsordaysormonths(null, null, 3) from system.local;

 thingsboard.timeagominsordaysormonths(NULL, NULL, 3)
------------------------------------------------------
                      2019-03-13 11:36:22.034000+0000

```

Also, one should note that the multiplier for the month duration is approximate, and while perfectly usable in many cases, if greater accuracy is needed, other functions should be used.

**Comment by luixal** [comment]
Wow. I'm totally surprised this can't be done through the UI. A simple CRUD for telemetry seems like one of the first things you would implement in this kind of platform.

**Comment by rkertesz** [comment]
You can use the REST API to remove telemetry data. There is no button or GUI wrapped around this but you could feasibly add a separate management webapp to do using the API if it really needs to have a UI
https://demo.thingsboard.io/swagger-ui.html#!/telemetry-controller/deleteEntityTimeseriesUsingDELETE

**Comment by mcpicoli** [comment]
I disagree completely on using the API and having to develop a separate management webapp for something so basic and useful as functionality for deleting a device's telemetry.

_It definitely should be a standard feature._

Of course, as far as developer resources are concerned, the priorities are very likely to be different.

As an aside, let me note that I've faced serious trouble trying to expunge old data from the Cassandra DB. Cassandra does not like to deal with large deletes for devices containing a few hundred thousand telemetry records. Be it via API or direct database access. It times out, and afterwards causes trouble in other unrelated operations because of the large amount of tombstones created.

Yes, it can be worked around by several means, but it is far from simple.

Using PE 2.5, trying to upgrade to 3.x (and this is where the serious trouble began...)

**Comment by rkertesz** [comment]
@mcpicoli I see. If you are paying customer then I'd recommend having a conversation with the project developers to prioritize this feature (note that I am in no way affiliated with the company). They probably should also help you through the migration process if you are a paying customer. 

I was also surprised not to see it either but then again this is one of the few freely accessible Open Source platforms with otherwise deep functionality. If you aren't a paying customer then since this is a community repo, you may want to either:
* contribute back to the community by building or designing the functionality (especially if you are using the open source version for commercial purposes)
* consider providing a bounty for someone else to build the feature. You have a good user story. With some detailed acceptance criteria and the right amount of money, I would be surprised if this isn't taken up.  I'm not sure how popular this feature would be but if enough people are on-board you can crowdfund this.

I'm sorry if that isn't what you are looking for.

**Comment by AdrienAdB** [comment]
Hi all, I was also in the need of deleting timeseries and didn't want to let our team doing manual postgres queries, it's a way too unsafe. Thingsboard API has all needed and is much safer.

We developed a quick tool in our website: https://acte.ltd/iot/client/login
- fill your TB instance domain and log as a **tenant** (not as customer as it won't work)
- select device
- select and wipeout all timeseries data

Coming soon:
- delete older than rather than all entries.
- delete attributes

Note it should work on any Thingsboard instance with SSL enabled.
Yes it would be much better to do it directly via Thingsboard, we are thinking about developing a widget for that...

**Comment by EmbeddedDevver** [comment]
> way

awesome work! Anyway to place the source of this online so I can host it myself?

**Comment by AdrienAdB** [comment]
I published npm package here (work in progress...): 
- https://www.npmjs.com/package/thingsboard-js-sdk
- https://github.com/acte-solutions/thingsboard-js-sdk

Regarding database size, please look at Thingsboard blog. Postgres will keep deleted row until you run VACUUM.
- https://blog.thingsboard.io/2020/09/deleting-timeseries-of-deleted.html?m=0

I now run a cronjob every night, and before backing up. Be careful !!! It can put Thingsboard down for a while, depending on your database.
- https://gitlab.acte.solutions/snippets/9

**Comment by EmbeddedDevver** [comment]
Thanks for letting me know. Indeed I did a VACUUM, but I just read that a FULL VACUUM including ANALYZE is required to reclaim the drive space. As I have a VPS with low disk space, FULL VACUUM is currently not possible as the entire database size will first be duplicated in terms of size before it will compact the used space.

But by just using VACUUM, the database file size does not grow until all empty spaces in the database are used again. So that can be fine too.

**Comment by varun-mahajan** [comment]
Recent version of thingsboard has come up with Tenant profile that has some settings around TTL. Can anyone explain if we can use combinations of that to get the purge functionality of older timeseries data out of box?

**Comment by DG-Wangtao** [comment]
1. https://thingsboard.io/docs/user-guide/telemetry/#data-retention
> **Data durability**
The device that sends message with time-series data to ThingsBoard will receive confirmation once the message is successfully stored into the Rule Engine Queue that is configured for particular device profile.
As a tenant administrator, you may configure processing strategy for the queue. You may configure the queue either to reprocess or ignore the failures of the message processing. This allows granular control on the level of durability for the time-series data and all other messages processed by the rule engine.

2. https://thingsboard.io/docs/user-guide/install/config/

> **Common SQL database parameters**

| name | env | default value | description|
| ------ | ----|--------------|-----------|
|ql.ttl.ts.enabled | SQL_TTL_TS_ENABLED | true | The parameter to specify whether to use TTL (Time To Live) for timeseries records.
|sql.ttl.ts.execution_interval_ms | SQL_TTL_TS_EXECUTION_INTERVAL | 86400000 | The parameter to specify the period of execution TTL task for timeseries records. Value set in milliseconds. Default value corresponds to one day.
| sql.ttl.ts.ts_key_value_ttl | SQL_TTL_TS_TS_KEY_VALUE_TTL | 0 | The parameter to specify system TTL(Time To Live) value for timeseries records. Value set in seconds. 0 - records are never expired. System TTL value can be overwritten for a particular Tenant, or parent Customer entity by setting the server-side attribute TTL to the corresponding Tenant or parent Customer entity. Please, note that the value should be set as long value, otherwise the TTL will be used from the higher level(Tenant or System).
| sql.ttl.events.enabled | SQL_TTL_EVENTS_ENABLED | true | The parameter to specify whether to use TTL (Time To Live) for events records.
| sql.ttl.events.execution_interval_ms | SQL_TTL_EVENTS_EXECUTION_INTERVAL | 86400000 | The parameter to specify the period of execution TTL task for events records. Value set in milliseconds. Default value corresponds to one day.
sql.ttl.events.events_ttl | SQL_TTL_EVENTS_EVENTS_TTL | 0 | The parameter to specify TTL(Time To Live) value for Events(LC_EVENT, STATS) records. Value set in seconds. 0 - records are never expired

**Comment by luixal** [comment]
Hi,

One thing I'm doing is copying timeseries data from devices to assets so I can just look at the asset and get all the relevant info; it also helps when replacing some sensor.

Thing is, using this won't help out in that scenario, will it?

Thanks!

**Comment by hasankarainfo** [comment]
[https://github.com/hasankarainfo/ThingsBoard.git](url) maybe it can be useful

**Comment by Ultrazombie** [comment]
Hello @marciopamplona,
To delete data from the device you can use swagger API.
https://thingsboard.io/docs/reference/rest-api/

**Comment by Vasilis-Dim** [comment]
> Hi @untilbit This is what I'm doing with Cassandra right now, probably is not the best approach but is working:
> 
> The thingsboard does not allow database management through its UI, so, we need to connect directly with the thingsboard DB.
> 
> **Query a specific value from a specific device:**
> 
> The ts_kv_cf table stores all the telemetry data of all devices and sensors.
> 
> entity_id = device id (can be found in thingsboard device UI) key = name of the data
> 
> `SELECT * FROM thingsboard.ts_kv_cf WHERE entity_id = f35bcef0-3ef5-11e8-8fd0-cb746776d0c2 and key = 'temperature' ALLOW FILTERING;`
> 
> **Creating functions to get date/time intervals in cassandra:**
> 
> Cassandra does not support arithmetics operations (version 3.11), so it is impossible to do something like “SELECT * FROM thingsboard.ts_kv_cf WHERE ts <= now() - 7d”, to be able to get for example the last 7 days, we need to create a UDF function in Cassandra, using Java. For that:
> 
> First, you have to turn on enable_user_defined_functions: true in the conf/cassandra.yaml file.
> 
> then create the function:
> 
> ```
> CREATE FUNCTION IF NOT EXISTS thingsboard.timeAgoMinsOrDaysOrMonths(minutes int, days int, months int) 
>   CALLED ON NULL INPUT 
>   RETURNS timestamp
>   LANGUAGE java AS '
>     long now = System.currentTimeMillis();
> 
>     if (minutes != null)
> 	  return new Date(now - (minutes.intValue() * 60 * 1000));
>     else if (days != null)
> 	  return new Date(now - (days.intValue() * 86400000));
>     else if (days != null)
> 	  return new Date(now - (months.intValue() * 2629746000L));
>     else
> 	 return new Date(now);
>     
>   ';
> 
>   ';
> ```
> 
> [check this](https://stackoverflow.com/questions/46135576/how-to-do-arithmetics-with-datetimes-in-cql?rq=1)
> 
> Note: The function has 3 parameters, you need to decide if you want to use an interval in minutes, days or months, once you decided the other parameters should be passed as null values.
> 
> timeAgoMinsOrDaysOrMonths(minutes,days,months)
> 
> **This query returns the last 7 days of temperature data from a device:**
> 
> `SELECT * FROM thingsboard.ts_kv_cf WHERE entity_id = f35bcef0-3ef5-11e8-8fd0-cb746776d0c2 and key = 'temperature' and ts >= timeAgoMinsOrDaysOrMonths(null,7,null) ALLOW FILTERING;`
> 
> **The same query, but it returns the last 1 month of temperature data from a device:**
> 
> `SELECT * FROM thingsboard.ts_kv_cf WHERE entity_id = f35bcef0-3ef5-11e8-8fd0-cb746776d0c2 and key = 'temperature' and ts >= timeAgoMinsOrDaysOrMonths(null,null,1) ALLOW FILTERING;`
> 
> **The same query, but it returns the last 10 minutes of temperature data from a device:**
> 
> `SELECT * FROM thingsboard.ts_kv_cf WHERE entity_id = f35bcef0-3ef5-11e8-8fd0-cb746776d0c2 and key = 'temperature' and ts >= timeAgoMinsOrDaysOrMonths(10,null,null) ALLOW FILTERING;`
> 
> **This new function allow us to execute clean routines in the database, for instance, if we want to erase the last seven days of data, we can execute:**
> 
> `DELETE FROM thingsboard.ts_kv_cf WHERE entity_id = f35bcef0-3ef5-11e8-8fd0-cb746776d0c2 and key = 'temperature' and partition IN (1525132800000, 1522540800000, 1525132800000) and entity_type = 'DEVICE' and ts >= timeAgoMinsOrDaysOrMonths(null,7,null);`
> 
> **if we want to keep just the last 7 days of data and erase everything else:**
> 
> `DELETE FROM thingsboard.ts_kv_cf WHERE entity_id = f35bcef0-3ef5-11e8-8fd0-cb746776d0c2 and key = 'temperature' and partition IN (1525132800000, 1522540800000, 1525132800000) and entity_type = 'DEVICE' and ts <= timeAgoMinsOrDaysOrMonths(null,7,null); ` obs: the partition and the entity_type must be used to delete actions on Cassandra (because they form the primary key of the entity). To see all the partitions and be able to use them in the IN clause, you need to query the ts_kv_partitions_cf table.
> 
> Hope that helps

Hello and thank you. That helps a lot. Any idea how to insert data from cassandra and display them in ui? I tried insert into thingsboard.ts_kv_cf but i only see the data in cassandra (cqlsh) and not in the UI.

**Comment by GrayCygnus** [comment]
My two cents:

I see that in case of Postgres, ThingsBoard uses [partitions](https://www.postgresql.org/docs/current/ddl-partitioning.html) on some of their tables (TS_KV one of them).

You can DROP the partitions (they are done by month) that you no longer want (perhaps old months). This can be done via PGAdmin GUI or as always with a good 'ol query DROPping the partition(s) you want.

I've done this a couple of times now, even on a running system, without issues (mileage may vary).

**Comment by rancor187** [comment]
Hello,

I'm also having issues removing older date (data before I set a TTL in the **Root-Rule-Chain**) from the cassandra db. **Thingsboard Version 3.6.2.**

In Cassandra one can't just use
`DELETE FROM thingsboard.ts_kv_cf WHERE partition <= 1730419200000;`
even if you know the **"entity_type", "entity_id" and "key"** it would't work:
`DELETE FROM thingsboard.ts_kv_cf WHERE entity_type = 'DEVICE' AND entity_id = 8566d180-eb93-11eb-936c-05495382bfe7 AND key = 'RPS_121_LOW_LIMITS';`
Cassandra throws this **error**: 
_Error from server: code=2200 [Invalid query] message="Partition key parts: entity_type, entity_id, key must be restricted as other parts are"_
This is because of the PRIMARY KEY = ((entity_type, entity_id, key, partition), ts)

However, this will work:
`DELETE FROM thingsboard.ts_kv_cf WHERE entity_type = 'DEVICE' AND entity_id = 8566d180-eb93-11eb-936c-05495382bfe7 AND key = 'RPS_121_LOW_LIMITS' AND partition = 1740787200000;`
This statement deletes all key-value-pair entries for that device for that partition.

So to run a **DELETE** you need the unique combination of entity_type, entity_id, key and partition.  
I wrote a bash script, that'll automate the process for me. I found that I will get the unique combinations from the **ts_kv_partitions_cf** table.

I transferred the contents of this table into a file. However I fount that the key _"scannerstatistik.db_sc.scanner.5.reading.AwaitBarcode"_ was **not listed** in the file/table.
I know that the key must exist in the DB because I can see it in here: 
Thingsboard_URL/entities/devices -> click on device -> click on "Newest (or Latest) Telemetrie" Tab:

![Image](https://github.com/user-attachments/assets/98fe1360-b5e5-4796-b023-03abc8e64a9d)

I've got 1000s of entries (key-value-pairs) without TTL from at least 20 devices dated back to September 24 that needs to be removed.
Real example in "Newest (or Latest) Telemetrie" Tab:
`DATE: 2024-09-03 14:28:26; Key: scannerstatistik.db_sc.scanner.5.reading.AwaitBarcode; Value: false
`
Also I find it strange that the oldest partition in the ts_kv_partitions_cf table is 1740787200000 (=2025-03-01 00:00:00 UTC); which is the partition for the current month.
**So not all unique combinations are in there, or I have something totally wrong.** 

My next idea was, that I could get all the **unique combinations from the ts_kv_cf table instead**, using:
`SELECT DISTINCT entity_type, entity_id, key, partition FROM thingsboard.ts_kv_cf`

Knowing that this would stress the database I decided to run this **SELECT** in batches by using token-based paging.
It ran for a few batches until cassandra throw an **error**: 
_<stdin>:1:ReadFailure: Error from server: code=1300 [Replica(s) failed to execute read] message="Operation failed - received 0 responses and 1 failures: READ_TOO_MANY_TOMBSTONES from localhost/127.0.0.1:7000" info={'consistency': 'ONE', 'required
_responses': 1, 'received_responses': 0, 'failures': 1, 'error_code_map': {'127.0.0.1': '0x0001'}}_

Even after a **manual compaction** (nodetool compact thingsboard ts_kv_cf) I run into the same error.
Now I am thinking of temporary increasing the **"tombstone_failure_threshold"** in the config file and run the script again.

There must be a solution to this. 
Any ideas?

Thank you
