### ISSUE TITLE
[Bug] "Save Timeseries" rule node  affect kafka rule node 

### ISSUE THREAD

**Issue by freebooterish** [thingsboard/thingsboard#6505]
Describe the bug:
      Please look attached pictures, I output  "Post Telemetry" to two rule nodes: "Save timeseries" and "Kafka" in default rule chains. I sent 1000 messages with interval 10ms,  I found about 120 messages are saved successfully and found lot of timeoutMsgs in thingsboard.log, meanwhile，the "Kafka" rule node only received about 160 msgs, and in thingsboard.log found Kafka rule node Timeout.
      However, when I remove "post telemetry" to "Save telemetry" rule node, 1000 msgs are received successfully in "Kafka" rule node. Why does the timeout of "Save Telemetru"  result in the timeout of "Kafka"?  Two rule nodes from "Post Telemetry" is  parallel OR serial processing?
      Thanks.

Your Server Environment
[thingsboard.log](https://github.com/thingsboard/thingsboard/files/8588832/thingsboard.log)

own setup
<img width="815" alt="pic2" src="https://user-images.githubusercontent.com/1250352/165896866-247efbdd-dd18-44d2-9274-5ecac89949fc.png">
<img width="762" alt="pic1" src="https://user-images.githubusercontent.com/1250352/165896872-cdc642e3-c41d-4a23-b2d8-55c2f72d04ef.png">

cloud infrastructure
3.3.3
ubuntu 20.04
Your Device

Connectivity
MQTT

**Comment by sumin-denys** [comment]
Hi @freebooterish,

Thank you for your request. I am glad to inform you that this issue was resolved in the current ThingsBoard version. 

Please refer to our release notes to find out more about new features and bug fixes: [Release Notes](https://thingsboard.io/docs/reference/releases/).

I am closing this issue. If you have any further questions, please feel free to create a new issue or reopen this one.
