### ISSUE TITLE
[Bug] The API auth  (password flow) doesn't conform to the RFC 6749

### ISSUE THREAD

**Issue by magodo** [thingsboard/thingsboard#6525]
**Describe the bug**

Per the RFC 6749: https://datatracker.ietf.org/doc/html/rfc6749#section-4.3.2, the password flow should use content type of `application/x-www-form-urlencoded`. While currently, thingsboard API only accepts `application/json`.

**Your Server Environment**

* own setup
  * The latest docker image: thingsboard/tb-postgres (id: e6b071a2debd60bf184ca1317650654b6e4d6d7984f89c17307160c878c0aca)

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: Linux Chrome

**Comment by SuminDenys** [comment]
Hi @magodo,

There is a list of reasons why we use `application/json` such as:

Our authentication process involves validating JWT, so we should use `application/json` to handle the structured data and tokens involved in these processes.
- Many modern authentication protocols, like OAuth2, use JSON format for transmitting tokens and credentials. Most APIs expect authentication requests to be in JSON format.
- JSON has become the de facto standard for data exchange in REST APIs, including for authentication endpoints.
- Most modern front-end frameworks and libraries (e.g., React, Angular) work seamlessly with JSON when handling authentication requests.
- Back-end frameworks also commonly expect JSON payloads for authentication, and handling JSON data is straightforward in most server environments.
- Our company policy prevents us from changing our API due to backward compatibility.

What is the problem you're looking to solve?

**Comment by magodo** [comment]
Hi @SuminDenys, thank you for the response! I believe I was trying to use `terraform` (an infrastructure as code tool) to build the TB dashboard, where I encountered this issue when using some Golang native oauth2 package. I can't remember the details though. But I have a blog telling how this is done: https://magodo.github.io/thingsboard-via-terraform/. 

Feel free to close this issue if you'd like.

**Comment by SuminDenys** [comment]
Hi @magodo,

I am closing this issue. 
Feel free to open a new one if you have questions about ThingsBoard.

Have a great day!
