### ISSUE TITLE
Timeout to process message but rule node is null

### ISSUE THREAD

**Issue by xiddjp** [thingsboard/thingsboard#6568]
I often encounter this problem, timeout to process message,  but ruleChainId and ruleNodeId is null.
Even 'Last Rule Node' is null. My server cpu and memory usage is normal.
How to Analyze this problem? Log is as below:

Timeout to process message: TbMsg(queueName=Main, id=d54d9ae1-5148-42c7-ac44-f367625e1937, ts=1652872828613, type=POST_TELEMETRY_REQUEST, originator=b5f60ca0-d19b-11ec-a468-a73b0ea8dc33, customerId=a2c80370-0fbf-11ec-9efb-3f378fd48a51, metaData=TbMsgMetaData(data={deviceType=cs, deviceName=cs0001, ts=1652872754438}), dataType=JSON, data={"txv":"12.6"}, ruleChainId=null, ruleNodeId=null, ctx=org.thingsboard.server.common.msg.TbMsgProcessingCtx@7709b92a, callback=org.thingsboard.server.common.msg.queue.TbMsgCallback$1@7125cc1b), Last Rule Node: null

**Comment by devaskim** [comment]
Maybe [this guide](https://thingsboard.io/docs/user-guide/troubleshooting/?scenario=growing-latency#possible-performance-issues) helps you.

**Comment by xiddjp** [comment]
I've tried all the method in your link, but it doesn't seem to help at present.

**Comment by devaskim** [comment]
What message queue are you using?
[Here](https://thingsboard.io/docs/user-guide/install/config/#queue-parameters) is various configuration parameters for queue.

**Comment by xiddjp** [comment]
I use Kafka as message queue.

**Comment by xiddjp** [comment]
> What message queue are you using? [Here](https://thingsboard.io/docs/user-guide/install/config/#queue-parameters) is various configuration parameters for queue.

Why ruleNodeId and ruleChainId is null?  I think all msg must processed by root rule chain and device profile rule node at least.

**Comment by xiddjp** [comment]
I think may be device profile node cost too much time cause timeout.
Sometimes device profile need to create a lots alarms,  but tb has low performance in dealing with alarms, especially when the number of alarms reaches millions.

**Comment by gpanasco** [comment]
I am experiencing this problem as well. In my case, logs are very similar to @xiddjp, however I must add that in my case no packets are processed after the problem starts occuring. Only restarting thingsboard solves the issue. Server RAM and CPU usage are normal.

**Comment by alexcorvis84** [comment]
Hello, I'm experiencing this problem as well. 

I've tried to restart the services as commented by @gpanasco but issue still persists.

Below attached the logs from tb-rule-engine:

![imagen](https://github.com/thingsboard/thingsboard/assets/44984326/cf661a63-7b4e-487e-83d1-9fd19a92bbf5)

What could be the root issue? Any help @smatvienko-tb @ashvayka ? 

Thanks in advance.

**Comment by smatvienko-tb** [comment]
> Hello, I'm experiencing this problem as well.
> 
> I've tried to restart the services as commented by @gpanasco but issue still persists.
> 
> Below attached the logs from tb-rule-engine:
> 
> ![imagen](https://user-images.githubusercontent.com/44984326/255578947-cf661a63-7b4e-487e-83d1-9fd19a92bbf5.png)
> 
> What could be the root issue? Any help @smatvienko-tb @ashvayka ?
> 
> Thanks in advance.

Hi, @alexcorvis84 

You have a **timeout** on the **save attribute node**.
It relays on **Postgresql performance**.

You might be writing too much for your Postgresql performance capabilities.

Please, check the SQL queues responsible for batch writing to Postgresql.

```
kubectl logs tb-rule-engine-0 -f --since 10m | grep SqlBl
```
The healthy state is to have **around zero queue size**.

![image](https://github.com/thingsboard/thingsboard/assets/79898499/f29a33a4-a7db-4b93-8140-2cadb6154a14)

General advice - avoid excessive attributes write. Write only attributes only if changed (any custom logic for now)

**Comment by alexcorvis84** [comment]
> > Hello, I'm experiencing this problem as well.
> > I've tried to restart the services as commented by @gpanasco but issue still persists.
> > Below attached the logs from tb-rule-engine:
> > ![imagen](https://user-images.githubusercontent.com/44984326/255578947-cf661a63-7b4e-487e-83d1-9fd19a92bbf5.png)
> > What could be the root issue? Any help @smatvienko-tb @ashvayka ?
> > Thanks in advance.
> 
> Hi, @alexcorvis84
> 
> You have a **timeout** on the **save attribute node**. It relays on **Postgresql performance**.
> 
> You might be writing too much for your Postgresql performance capabilities.
> 
> Please, check the SQL queues responsible for batch writing to Postgresql.
> 
> ```
> kubectl logs tb-rule-engine-0 -f --since 10m | grep SqlBl
> ```
> 
> The healthy state is to have **around zero queue size**.
> 
> ![image](https://user-images.githubusercontent.com/79898499/255608421-f29a33a4-a7db-4b93-8140-2cadb6154a14.png)
> 
> General advice - avoid excessive attributes write. Write only attributes only if changed (any custom logic for now)

Hi @smatvienko-tb,

Thanks a lot for your your quick feedback and support!

I've just checked the SQL queues and healthy state seems OK as **it shows 0 queue size.**

![imagen](https://github.com/thingsboard/thingsboard/assets/44984326/8cf09925-1581-4e32-acfa-96a8936997ce)

What is strange to me, is that I can't see any INFO regarding **[Attributes]** related... There's no entry for that in my case as you can check in the pic attached :(

Also, I tried to push again and new write attribute and always is stuck at the IN event **but I can't see the OUT event** registered on the Save Attributes node.

![imagen](https://github.com/thingsboard/thingsboard/assets/44984326/779ad0e6-ab90-40e9-a5c7-4f34d5551401)

Then in the Lifecycle, on of the servers is STOPPED

![imagen](https://github.com/thingsboard/thingsboard/assets/44984326/f76b390a-1133-4a01-b181-e09f56ab3762)

I've tried to check for Attributes in my recent logs and this is the output for the command `docker-compose logs -f tb-rule-engine1 tb-rule-engine2 | grep Attributes` :

![imagen](https://github.com/thingsboard/thingsboard/assets/44984326/9a0da5a6-d630-4d1d-95fa-cfb7c32522bd)

Not sure what's causing this behavior, Could you please give me any feedback what could I check further in order to try to fix it?

Many thanks in advance!

**Comment by pon0marev** [comment]
`SqlBl` doesn't include the attribute queue, so we can't say that everything is fine here. 
![image](https://github.com/thingsboard/thingsboard/assets/44898346/3f6298a4-fdb9-4577-afce-b8cb12544bd4)
Another screenshot shows that the attribute queue polling was interrupted

The issue with attribute saving may be related to the Redis cache, as it is constantly mentioned before saving attributes; normally, this should not be the case. Check that your Redis container is up and running and make sure there are no errors in the Redis logs.

If your devices send attributes on a timer rather than after a change, you should upgrade to a newer version like 3.6.4 or 3.7.0 and enable the "Save attributes only if the value changes" option. This will reduce the load on the database and reduce the number of timeouts. To make this feature work correctly, make sure that your redisplay has the policy is  `allkeys-lru`, `allkeys-lfu` or `allkeys-random`
```
redis-cli config get maxmemory-policy
```
