### ISSUE TITLE
[Question] Get username from database

### ISSUE THREAD

**Issue by nunovivas** [thingsboard/thingsboard#6599]
**Component**

  * Generic

**Description**
I currently have one device that returns UserId, CurrentVelocity, every minute.
I would like to know the best approach, either by doing it in the dashboard section, or something else, to get the UserName based on the stored Id. Is this possible?
I'm currently re-reading the Aliases documentation but don't seem to be able to solve this issue that seems quite simple. 

**Environment**

 * OS:  Ubuntu Server
 * ThingsBoard: 3.3.4.1PE
 * Browser: Firefox/Chrome

**Comment by ashaforost** [comment]
Hi @nunovivas 

If you prefer to fetch the username by user id from a dashboard, you need to develop a custom widget because thingsboard default widgets don't support this behavior.
However, you can also fetch the username in the rule chain processing stage. When a device posts telemetry in the rule chain, you can check whether the telemetry contains the userId key and use the rest API call rule node to fetch the user info by user id, to later save the username to the device's telemetry. See the following request in the swagger UI:
[getUserById](https://thingsboard.cloud/swagger-ui/#/user-controller/getUserByIdUsingGET)
