### ISSUE TITLE
Closed but not fixed: 'Write Users cannot acknowledge or clear alarms [Bug]'

### ISSUE THREAD

**Issue by daanstevenson** [thingsboard/thingsboard#6837]
Still seeing this issue as of today:

1. Create device
2. Add device to device group
3. Create user
4. Add user to user group
5. assign user group 'write user' role for device group
6. Generate device alarm
7. Use Alarm Widget to clear or acknowledge alarm
8. Get permission error

![image](https://user-images.githubusercontent.com/26634522/175425205-a5294056-74c5-40dc-b900-f8898d03a09d.png)

Customer user group has 'Entity Group Write User' Role for the Device Group that the device is in, and 'Generic Alarm Resource All' Role (as well as for Assets and Devices, none seem to help).

![image](https://user-images.githubusercontent.com/26634522/175425054-4f0a682b-9ae7-418a-9333-1befde414ecc.png)

If Device Ownership is transferred to Customer, alarms generated after transfer can be cleared and acknowledged by Customer.
Thanks!

_Originally posted by @daanstevenson in https://github.com/thingsboard/thingsboard/issues/6370#issuecomment-1164972937_

**Comment by ivojanalik** [comment]
We're having the same problem in thingsboard.cloud. We have Device 1 under Customer 1. We propagate the alarm from this Device 1: 
- use checkbox "propagate alarm to related entities" in Device profiles - Alarm rules - Advanced settings  
- set Device 1 - Relations direction To with Contains type Customer to target Customer 2 

New alarm propagated. Customer 2 see alarm in Alarm widget on Current customer alias on Dashboard. 
But can not acknowledge or clear its.

Next we:
- set Group all role (for All permissions) 
- set Device groups (with Device 1) in Permissions to target Customer 2 for target Customer is setting   
Customer can not still ack or clear this alarm.
We tried acknowledge API /api/alarm/{alarmId}/ack with auth user Customer 2, server response Forbidden message:

`"message": "You don't have permission to perform 'WRITE' operation with ALARM 'boxAlarm'!"`

Where do we have to set WRITE ?
Thanks.

**Comment by Civilduino** [comment]
I am having the same issue.
I as a Tenant own the devices and share them with my Costumers (e.g. device leasing). I share the Device Group using reading and writing roles. However, my costumer cannot acknowledge or clear the alarms, only I can do it. 

It seems that the Device ownership is a problem, could ownership be shared somehow, representing a leasing case?
The device alarm can only be acknowledged and cleared under the device owners hierarchy, unfortunately.

I hope they come around with a solution because this do not work for our application.

**Comment by ivojanalik** [comment]
Hello, our use case is a central dispatch of alarms for selected devices of its owners. The owner wants to see these alarms, but Ack and Clear is done by the central dispatcher.

**Comment by ivojanalik** [comment]
I analzyed source alarm-table-comfig.ts. Buttons for Ack or Clear shows only when **user is not CUSTOMER_USER (is TENANT admin) or user is comes from owner customer device**:

![Screenshot_2022-10-11_08-34-18](https://user-images.githubusercontent.com/56821237/195013778-c37d2838-a242-4792-8631-1bedeb230b14.png)

The same problem is in API (unfortunatelly source TB PE is not public):

![Screenshot_2022-10-11_08-41-44](https://user-images.githubusercontent.com/56821237/195015359-9ba3a9b7-1315-409f-9d38-4c6a527afea0.png)

**Please, we want set permission from RBAC for Alarm operation Ack and Clear**. When I have permission for setting Attributs and other Write settings the entity, why I can not do Alarm Ack and Clear ?  

@ashvayka We want buy Thingsboard PE Perpetual Fallback License for our project. But this problem is blocking it.

**Comment by netbc** [comment]
We are having the same issue. Using latest v3.4.1PE. The Customer cannot acknowledge or clear alarms originating of it's sub-customer devices. When trying gets permission denied. The customer has generic read/write permissions for alarm resources. Is there any workaround for this?

**Comment by sunyong-mwi** [comment]
We also need the solution as our customer need their admin staff to acknowledge the alarm of all the department (sub-customer) sensors. Please help to solve it.

**Comment by GrayCygnus** [comment]
Seems that this is indeed solved or possible. Check the mentioning thread, I posted an comment there with a solution: 

https://github.com/thingsboard/thingsboard/issues/6370#issuecomment-2111300551

**Comment by mykhailokornieiev** [comment]
Closed due to inactivity

**Comment by AndreSensaway** [comment]
I'm running thingsboard 3.9 PE and still have this problem:
a user from parent customer with write/read permissions for Alarms, cannot clear/acknowledge alarms that were propagated from a device of a child customer.

Anyone found a solution for this?
