### ISSUE TITLE
[Question] Can we use a real datasource inside the custom widet builder instead of a function?

### ISSUE THREAD

**Issue by OzyOzk** [thingsboard/thingsboard#6947]
**Component**

 * UI

**Description**
Is it possible to use a real datasource in the widget builder instead of a function? I need a data source that has at least a months worth of values.

**Environment**

 * OS:  Windows
 * ThingsBoard: ThingsBoard Cloud
 * Browser: FireFox

**Comment by ssakharova** [comment]
Hello @OzyOzk,

Currently, there is no possibility to use a real datasource in the widget builder instead of a function. However, the prod ticket is already in the backlog for our developers to decide on its necessity and possible implementation in future versions of the ThingsBoard.
Please check our [Release Notes](https://thingsboard.io/docs/reference/releases/) for updates on future platform additions.
