### ISSUE TITLE
[Question] Does server delete timeseries and attributes when user deletes device or asset?

### ISSUE THREAD

**Issue by devaskim** [thingsboard/thingsboard#6989]
**Component**
 * Generic

**Description**
Does server delete timeseries and attributes when user delete device or asset?

**Environment**

 * ThingsBoard: 3.4

**Comment by trikimiki** [comment]
After you delete a device, you are unable to access the telemetry/attributes, but it is not deleted from the database:

My device is deleted:
```
curl -X 'GET'   'http://localhost:8080/api/device/a13b4ef0-14b8-11ed-ac1a-cda7fc0ae93f' < . . . >
```
`{"status":404,"message":"Device with id [a13b4ef0-14b8-11ed-ac1a-cda7fc0ae93f] is not found", < . . . >`

Data is inaccessible (as it requires entity ID in order to get):
```
curl -X 'GET'   'http://localhost:8080/api/plugins/telemetry/DEVICE/a13b4ef0-14b8-11ed-ac1a-cda7fc0ae93f/values/attributes?keys=this_attribute_exists' < . . . >
```
`Device with requested id wasn't found!`
```
curl -X 'GET'   'http://localhost:8080/api/plugins/telemetry/DEVICE/a13b4ef0-14b8-11ed-ac1a-cda7fc0ae93f/values/timeseries?keys=this_ts_exists&startTs=0&endTs=9999999999999' < . . . >
```

`Device with requested id wasn't found!`

Still, I am able to see it in the DB:
```
thingsboard4=# select * from attribute_kv where entity_id='a13b4ef0-14b8-11ed-ac1a-cda7fc0ae93f';
 entity_type |              entity_id               | attribute_type |     attribute_key     | bool_v | str_v | long_v | dbl_v | json_v | last_update_ts 
-------------+--------------------------------------+----------------+-----------------------+--------+-------+--------+-------+--------+----------------
 DEVICE      | a13b4ef0-14b8-11ed-ac1a-cda7fc0ae93f | SERVER_SCOPE   | active                | f      |       |        |       |        |  1659701873122
 DEVICE      | a13b4ef0-14b8-11ed-ac1a-cda7fc0ae93f | SERVER_SCOPE   | this_attribute_exists | t      |       |        |       |        |  1659702053060
(2 rows)

thingsboard4=# select * from ts_kv where entity_id='a13b4ef0-14b8-11ed-ac1a-cda7fc0ae93f';
              entity_id               | key |      ts       | bool_v | str_v | long_v | dbl_v | json_v 
--------------------------------------+-----+---------------+--------+-------+--------+-------+--------
 a13b4ef0-14b8-11ed-ac1a-cda7fc0ae93f |  82 | 1659701987929 | t      |       |        |       | 
(1 row)
```

**Comment by devaskim** [comment]
@trikimiki Thanks for detailed response. Do you know why such data has been left?

**Comment by ashvayka** [comment]
The records in `ts_kv` are left intentionally, because 
1) For PostgreSQL we clean up the telemetry partitions based on TTL. It is an efficient way of deleting the telemetry. You may have millions of telemetry records per device and we don't want to block REST API and DB to perform the deletion of telemetry in an inefficient way.
2) For Cassandra the TTL is built-in into the DB structure and records are automatically deleted as well after some time. 

The records in the `attribute_kv` are left non intentionally. We have an internal to-do for deletion of those records but did not get time to implement it yet.

**Comment by devaskim** [comment]
TTL for PosgreSQL is [disabled by default](https://github.com/thingsboard/thingsboard/blob/master/application/src/main/resources/thingsboard.yml#L286). It means that data are left forever (in case absence of tenant and customer level limiters), right @ashvayka ?

**Comment by trikimiki** [comment]
Correct. In Postgres, by default, TTL for telemetry is set to 0, which is indefinite.
