### ISSUE TITLE
Why does PE deployment in Intranet stop automatically

### ISSUE THREAD

**Issue by DaXian459** [thingsboard/thingsboard#7022]
**Component**

 * Installation

**Description**
Deploying PE in the internal network will automatically stop every few days, and it needs to be connected to the Internet and restarted

**Environment**

 * OS:  Centos8
 * ThingsBoard: 3.34PE
 * Browser: Edge

**Comment by trikimiki** [comment]
PE requires internet access in order to check the license key once in a while. While there is no internet connection, ThingsBoard gives a "grace period" for the license check in case of supposed network issues or issues with the License Server itself.

You can find more info here: https://thingsboard.io/products/license-server/#architecture

So, it is impossible to use ThingsBoard without internet access. As a solution, you can set up a proxy server with internet access and then add this line to the `/etc/thingsboard/conf/thingsboard.conf` file:
`export JAVA_OPTS="$JAVA_OPTS -Dtb.proxy.system=true -Dhttp.proxyHost=<proxy_host> -Dhttp.proxyPort=<proxy_port> -Dhttps.proxyHost=<proxy_host> -Dhttps.proxyPort=<proxy_port>"`
