### ISSUE TITLE
After docker container reset I can't access thingsboard in web browser

### ISSUE THREAD

**Issue by b-kolodziej** [thingsboard/thingsboard#707]
I followed this instruction https://thingsboard.io/docs/user-guide/install/docker/ to deploy Thingsboard (open source IOT platform) on my VPS. Everything was working ok for 2.5 months, but after restart container I'm getting this error in web browser:
"This site can’t be reached 54.37.232.178 refused to connect."
Container is running, ports are listening. I don't have idea what's the reason for that behaviour. Can anyone suggest me solution for this? Thanks in advance! I can post whatever is needed.

docker ps - https://pastebin.com/VvhCVTHh
Docker Inspect - https://pastebin.com/Dd8u2hwQ
netstat -atun - https://pastebin.com/rb9N8FFg

**Comment by wolfen351-diligent** [comment]
Could you solve this? I'm seeing the same problem now too

**Comment by Karabiy** [comment]
the cause of such an issue can be that the hard drive of yours is full. those means that there was no more disk space to write the temporary files which are required to be created by all the services so that the services will fail also, the issue may persist to the docker itself. we recommend using our official images which can be found on the site of ours, 
in addition to this, make sure that there was not the latest tag for the images being specified, because in case if the database schema was upgraded, you will need to run an upgrade script on the latest version first, and then start the containers which will use the latest version. you can refer to this link on how to upgrade in case of the docker being used: https://thingsboard.io/docs/user-guide/install/docker/
