### ISSUE TITLE
[Question] Text dynamic to zoom on mobile

### ISSUE THREAD

**Issue by rungg12** [thingsboard/thingsboard#7070]
Hello everyone,
I have an Imagemap with different values on it. 
I disabled zoom, but in mobile you can still zoom in, so far so good. 
The Problem is, that if i zoom into the picture, the marker's title isn´t in the right size. Would it be possible to scale the text on the imagemap on base of the zoom level?
Thanks in advance

**Comment by ssakharova** [comment]
As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.

Please re-create a new ticket in GitHub with respect to the product you are using if you still need help:
- https://github.com/thingsboard/flutter_thingsboard_app/issues
- https://github.com/thingsboard/flutter_thingsboard_pe_app/issues

Please describe all the details of your case there, and then you will increase the probability that the GitHub community will be able to help you.
