### ISSUE TITLE
Thingsboard login white labelling

### ISSUE THREAD

**Issue by mubashirp** [thingsboard/thingsboard#7075]
Can anyone help me to do login white labelling of my thingsboard tenant and user accounts. They are asking for domain name and base url. As i am not having knowledge on websites, domains and all, I am very confused on how to do that.

**Comment by devaskim** [comment]
I think [this doc](https://thingsboard.io/docs/pe/user-guide/white-labeling/) will help you.

**Comment by mubashirp** [comment]
Should we need create a fresh website( without any contents) for the login
white labelling page.

**Comment by mubashirp** [comment]
anybody, please tell what to be done from the website end

**Comment by ashaforost** [comment]
Hi @mubashirp 

To configure a separate domain for a customer (e.g. customer1.yourRegisteredDomain.com), you can create a subdomain within your DNS provider and input the corresponding CNAME record to use the new domain. Once done, you will need to white label the customer's login page with said domain.
Base URL: Specify the URL here if you don't want to use a general URL for requests, for example, to generate a link to reset the password. Otherwise, duplicate the Domain Name.
Checkbox: Prohibit to use hostname from the client request headers: must be active so that you can reset the password only using the above Base URL.

**Comment by mubashirp** [comment]
thank you very much. I am able to create white labelled login page. 
I have one problem too. When ever i create a new user, the activation link is redirecting to the white labelled login page instead of set password page. Also i am not getting any option to set password for my newly created user account. I have checked the last option in white labelling, pohibit the use of hostname, as i need my users to only see my url.

**Comment by ashaforost** [comment]
If you experience issues with activation link it may be due to several factors:
- Incorrect base url set 
- Checkbox _Prohibit to use hostname from the client request headers_  is disabled
- Incorrect LoadBalancer Setup 
- Old ThingsBoard Version (upgrade to latest https://thingsboard.io/docs/user-guide/install/pe/upgrade-instructions/ )
