### ISSUE TITLE
Calculate Storage based on Data Point 

### ISSUE THREAD

**Issue by portalteknik** [thingsboard/thingsboard#7079]
Hello everyone. Where can I calculate the total amount of storage I use? (for example, in MB, GB, or KB)? Because in the API usage, there are only storage data points in units of Million (M), not MB GB or KB

How to measure or convert data point size in MB, GB or KB

Thanks all.

**Comment by epalchenko** [comment]
Hello @portalteknik,
The ThingsBoard Platform does not have this functionality, because ThingsBoard does not have a built-in database. Here you need to look in postgres (or cassandra if you are using the hybrid) and write a query that will calculate this for you. We can only suggest you to use TTL (TimeToLive) to avoid eternal data and volumetric growth (if you need it, of course).
