### ISSUE TITLE
[Bug] java.lang.RuntimeException: Unable to upgrade ThingsBoard, unsupported fromVersion: 3.3.4.1

### ISSUE THREAD

**Issue by t0mZ4** [thingsboard/thingsboard#7139]
trying to upgrade to thingsboard 3.4.x from 3.3.41 is failing with this error
'java.lang.RuntimeException: Unable to upgrade ThingsBoard, unsupported fromVersion: 3.3.4.1'

if i change the upgrade command to upgrade.sh --fromVersion=3.3.4 then it works

regards

**Comment by Backdraft007** [comment]
I don't find any documentation where is written "--fromVersion=3.3.4.1".
It is written "--fromVersion=3.3.4". So, it is no bug.

**Comment by t0mZ4** [comment]
well, latest TB version was 3.3.4.1

so it's counter-intutive no?



<https://iot-experts.net/>

Tom Zamir

Owner

***@***.***

+972-55-660-1239 <+972556601239>

Pardes Hanna, Israel

iot-experts.net

<https://www.linkedin.com/r/tomzamir>

**Comment by trikimiki** [comment]
As Chris specified, there is no option for 3.3.4.1 in the upgrade script: https://thingsboard.io/docs/user-guide/install/upgrade-instructions/#upgrading-to-34.

This is because 3.3.4.1 was a hotfix version, which only fixed a specific issue: https://thingsboard.io/docs/reference/releases/#v3341-march-22-2022. There is no need to change the Postgres schema for this version, so the upgrade from 3.3.4.1 to 3.4.0 is the same as from 3.3.4 to 3.4.0
