### ISSUE TITLE
[Question] Thingsboard stop receiving data and ts_latest type is not correct.

### ISSUE THREAD

**Issue by Vasilis-Dim** [thingsboard/thingsboard#7218]
Hello Everyone. 
We have the following problem : 

We are using thingsboard for almost a year now and from the first days we have this problem that thingsboard loses connection to the mqtt broker and stops receiving  data (the mqtt service does not stop). After restarting all the services (thingsboard-cassandra-postgresql)everything is  active again. When this happens (at least once a week) we don't lose any data.

I was looking around to see what is happening and i saw that we have not changed the the ts_latest type from sql to cassandra inside thingsboard.yml file. (ts type has set to cassandra from the first day). As a result all data was/is being saved in postgresql.

The Questions are : 
1. Does the ts type have anything to do with the problem we have? 
2. Can i change the ts_latest type to cassandra without any problems or we need to create the table then move the data from postgres and then change the value in yml? 
 

 * OS:  ubuntu
 * ThingsBoard: version 3.2.2 (PE)

**Comment by pon0marev** [comment]
Ts most likely do not related to your issue of losing connection to the mqtt broker.
To change ts_latest to cassandra you will need to add a new table to cassandra: [schema-ts-latest.cql](https://github.com/thingsboard/thingsboard/blob/master/dao/src/main/resources/cassandra/schema-ts-latest.cql)
However, this is an outdated approach and it is best to store ts-latest in a postgres database, since the read write operation for ts-latest is much faster in a postgres database than for cassandra.
