### ISSUE TITLE
[Question] Combine exported pages in one new dashboard, unique IDs?

### ISSUE THREAD

**Issue by KenSense** [thingsboard/thingsboard#7283]
* UI

**Description**
I want to combine two dashboards (pages) in one new dashboard by editing the json file so I don't have to do all the work again.

In the json file there are a lot of ID numbers,  do I need to change them?
"id": "bfca0f00-c159-937b-4e6b-4f3d393b5d78"
(I don't want widgets to be changed if the other dashboard changes)

I assume when you import something it creates new ID's?
(I also import the same dashboards so I don't have to start from nothing for a new one.)

**Environment**
 * OS:  Ubuntu
 * ThingsBoard: PE 3.3.3

**Comment by pon0marev** [comment]
If you imported a dashboard that you already have and changed it, this change will not happen in another dashboard. Because the new dashboard was created with a different id.
But if you want to combine 2 dashboards into one, you need unique widget id inside one dashboard. Also the state coordinates of the widget must not overlap.
