### ISSUE TITLE
[Question] Adding details to alarms created in the Device Profile using Alarm Rules "not working"?

### ISSUE THREAD

**Issue by Civilduino** [thingsboard/thingsboard#7284]
**Component**

 * UI
 * Rule Engine

**Description**

Currently I am trying to add the `entityLabel` as additional information in my alarm rule in order to use it in the alarm table widget, instead of the `originator` column. I can see the `details.data` but the entity label is not fetched.
I could use the entity label from the current dashboard as a key in the alarm table widget. However, I need this because I want to show the device label higher up in the hierarchy as I propagate the alarm to its related assets and other dashboards.

1) Is this a bug or how should I define the details query?
![image](https://user-images.githubusercontent.com/27728926/190363535-66b8b600-1b15-4302-b507-f73956416ca7.png)
![image](https://user-images.githubusercontent.com/27728926/190364763-a39375e6-16f6-4b14-b03f-847d557c29a5.png)

I added the `details.data` key in the alarm table widget following this issue #3457.
![image](https://user-images.githubusercontent.com/27728926/190365411-1bfc3c9f-2bfe-48c5-b06c-32a7f238cdc6.png)

But you can see that the device label is not being fetched.
![image](https://user-images.githubusercontent.com/27728926/190365630-0a0fcef9-87ad-4e98-a677-64279848dc46.png)

2) How do you define the details query to add multiple key/value pairs in addition to the `data:value` pair? I cannot find any information on how to do this.

Thank you for any help!!

**Environment**

 * OS:  macOS
 * ThingsBoard: 3.4.1 PAAS 
 * Browser: Chrome and Firefox

**Comment by Civilduino** [comment]
Note that I tried to add an additional key filter with of the `Attribute` type trying to fetch the label, but there is not `label` attribute, and I can only select the server side attributes.

What is the proper name of the `label` attribute of the device in order to fetch it?

![image](https://user-images.githubusercontent.com/27728926/190383518-e3d41328-8ee1-40e2-8618-b94df635455c.png)

![image](https://user-images.githubusercontent.com/27728926/190383776-fd5f95b0-9aa9-4c44-92bc-d474afcca3cb.png)

**Comment by HaydenBurrows** [comment]
Hi, I have approached this a slightly different way.  I use label attribute from device as below.  Then in the alarms table, chose label (E)
For this to work, I had to choose my entity alias to include the device.  Here the 'Sensors' alias includes device 1909003.  Otherwise you may not be able to choose 'label'. 

![image](https://user-images.githubusercontent.com/69659611/190562298-13022db0-e99f-41ff-a02b-41e21a1ae649.png)
![image](https://user-images.githubusercontent.com/69659611/190562438-acbcd765-9666-4b4b-8ca6-e30dc4f531db.png)

![image](https://user-images.githubusercontent.com/69659611/190562571-4e0b23ce-a038-49f1-bce6-18d38f0098b1.png)


This way you don't need to add anything in the Details section of the alarm.
I also found that I could only get server side attributes.  So had to add one in the device which is not too hard.

![image](https://user-images.githubusercontent.com/69659611/190563768-83e06981-13b9-46e7-92d6-bdecba448e93.png)

**Comment by Civilduino** [comment]
Hello @HaydenBurrows and thanks for your answer.

As per your first suggestion, I did the same for the dashboard where I see my sensors (as I wrote "I could use the entity label from the current dashboard as a key in the alarm table widget").
However, I have other alarm tables in other dashboards (based on my Assets hierarchy) and I cannot select the label in those dashboards unless I create specific Aliases.

As per your second suggestion, I did not want to repeat the information that is already available in the device entity, but I think I will have to do it anyway.

**Comment by Civilduino** [comment]
Just to update my previous comment, any key that you want to use in the details part of the Alarm profile needs to be included in the filter of the alarm, as the key is then added to the message to be processed in the background.

<img width="680" alt="image" src="https://user-images.githubusercontent.com/27728926/213684233-67c0d4f6-2efb-431c-98dd-13f1802eb3a3.png">

Then the details is just a String variable where you can include the keys or text you want, with the format you want.

<img width="783" alt="image" src="https://user-images.githubusercontent.com/27728926/213684647-bd57ae6b-a776-4b5e-bbf7-e8fce0e8115b.png">
