### ISSUE TITLE
[Question] Use list to consult attributes values

### ISSUE THREAD

**Issue by DjFoxzi** [thingsboard/thingsboard#7327]
**Component**

 * Rule Engine
 
I want to use a list that contains the recently updated attributes to only request the value of those attributes and send them as a response to the device, but I don't know how to pass it to the originator attributes node and have it recognize them, I attach example images

the list is msg.result and the rest of the values is an attempt to make a loop of nodes that did not work for me

and the list depends on how many attributes the user changed from the platform since the device queried every x time

**Environment**

![Captura de pantalla de 2022-09-23 11-47-02](https://user-images.githubusercontent.com/50997052/192011595-98500478-645c-4014-8ecf-e9f9847cb107.png)
![Captura de pantalla de 2022-09-23 11-47-08](https://user-images.githubusercontent.com/50997052/192011600-28875a78-8d69-4d4d-bdad-2043cd0d09d9.png)

 * ThingsBoard: 3.4.1

**Comment by devaskim** [comment]
With the help of *Transformation node* you can convert *result* array to array of messages where each message will contain only one value from the *result*-array (see [this link](https://github.com/thingsboard/thingsboard/issues/6594#issuecomment-1141037479) for more details). So ` msg: { result: ['value1', value2'] }` will be transformed to `[ { msg: { 'attr_name': 'value1'} }, { msg: { 'attr_name': 'value2' }} ]`. With data formatted in this way you can use `$[attr_name]` to read attribute name from `msg` instead of hardcoding it in node configuration.

**Comment by DjFoxzi** [comment]
Excellent with the suggestions implemented, I was able to correctly generate the list of attributes, when I looked for a similar situation the appointment did not appear, so sorry for the inconvenience, and thank you very much for your attention
