### ISSUE TITLE
active attribute is not get updated

### ISSUE THREAD

**Issue by kanellopoulos** [thingsboard/thingsboard#7330]
**Component**
Rule Engine

**Description**
Hello, i would like to update the ss_active attribute but even through i pass data between two rule chains and change originator correctly the active attribute is not get updated.
The attribute get updated only if i publish data through mqtt directly to the related device.
There are no failures and the rules works perfectly but the device status(ss_active) staying always false.
Any ideas?

My related device rule chain :

![image](https://user-images.githubusercontent.com/83007224/192114743-5ea306fc-4ce5-442e-a21d-ae35b2f8ac57.png)

**Comment by mykhailokornieiev** [comment]
Hi. I'm not sure if your problem is still relevant for your, but it's highly not recommended to edit activity attributes since it can break activity management. In your case it looks like active attribute didn't upgrade since there were no save attribute rule node (maybe it is somewhere outside of your screenshot, but who knows).

**Comment by mykhailokornieiev** [comment]
I close this ticket due to inactivity. Feel free to comment on it, and I will re-open it.
