### ISSUE TITLE
issues with GUI MQTT Extention guide

### ISSUE THREAD

**Issue by t0mZ4** [thingsboard/thingsboard#737]
Hi

I am trying to follow the guide found here:

https://thingsboard.io/docs/iot-gateway/getting-started/#step-82-mqtt-broker-gui-configuration

First of all, currently there is inconsistent information between the section iot-gateway/getting-started which contains the latest information, and the configuration section in iot-gateway/configuration which contains older information regarding MQTT.

Secondly, I am unable to complete the guide successfully, when I import the sample  mqtt-gui-extension-configuration.json it is missing the required fields, Device type json expression, and filter expression

![image](https://user-images.githubusercontent.com/31729091/39230702-21386896-4870-11e8-8c7d-d562a8ab7b6f.png)

**Comment by davygraham** [comment]
Same issue here. Does anyone have sample files of the following that they have working with MQTT I can get a look at the configuration on

tb-gateway.yml
mqtt-config.json

**Comment by aderusha** [comment]
We're nearly a year out from the opening of this issue.  The documentation and examples provided have not been functional for editing in this time.  Is there any expectation that a working example might be provided some day?

**Comment by mp-loki** [comment]
Hi @aderusha! I am sorry for the tutorial being inaccurate.
In fact, the **Filter Expression** should not be required in the GUI configuration. Filter Expression is a JSONPath expression to capture a part of the input data. The default setting in file-based configuration is an empty string (no filter). Since GUI does not allow you to leave it blank, as a workaround you can set it to '$' (without quotes) which is effectively the same thing as 'no filter'.
For the **Device Type json expression**  - it can be either a JSONPath or a String. So if you don't want to extract the device type from your input message, you can set an arbitrary String value like 'default' - and it will set it to the type field of the newly-created device.

Please let me know if this helps. Meanwhile, I will try to fix the tutorial
