### ISSUE TITLE
Thingsboard bar chart

### ISSUE THREAD

**Issue by mubashirp** [thingsboard/thingsboard#7416]
may i know the reason why the bars in the  bar graph of  thingsboard is starting halfway  after the x axis data date point. For eq, if the data is for october 11, it will be represented halfway after october 11 and the bar ends in halfway after october 12, instead of starting from october 11 and ending just before october 12.
the function is average, and grouping interval is given as 1 day, as i need the value at each day represented.
![image](https://user-images.githubusercontent.com/49026279/195523948-3ce40cfc-5759-4ba0-b82f-016f321b6a54.png)

**Comment by ssakharova** [comment]
Hello @mubashirp,

Since you have enabled the average data aggregation function and set the grouping interval to 1 day in the timewindow, the chart will show bars with a slight offset.

By the Thingsboard design, the aggregation works by summarizing all the values of the telemetry key within each hour/day and dividing them by their count to calculate the average value. 


In order to see the data every day without offset, you need to update the timewindow to Realtime mode and set the data aggregation function to 'None'. 

Best regards,
Sofiia
