### ISSUE TITLE
How to create gateway devices automatically via MQTT and how to connect multiple devices through gateways?

### ISSUE THREAD

**Issue by caoyingde** [thingsboard/thingsboard#745]
I am using the gateway of TB. I refer to the document: https://thingsboard.io/docs/reference/gateway-mqtt-api/ for development, but I have encountered several problems:

1. how to connect multiple devices through the gateway, what is the JSON format?
The example of the document only gives the case of connecting a device:
Topic: v1/gateway/connect
Message: {"device"): "Device A"}

2. how can gateway devices be created automatically through MQTT instead of manually created by GUI?

Above, thank you.

**Comment by mp-loki** [comment]
Please check out this:
https://thingsboard.io/docs/iot-gateway/getting-started/#step-833-mapping-mqtt-topic-to-device-name

**Comment by caoyingde** [comment]
Found that only ordinary devices can be created, and gateway devices can not be created?

**Comment by mp-loki** [comment]
This is not supported out of box. You can create a REST API client which will 

1. login to ThingsBoard using username and password 
2. create a gateway device 
3. get device credentials 
4. repeat this for as many devices as you need

Having the credentials you can connect your gateway(s) to ThingsBoard through MQTT

**Comment by Karabiy** [comment]
for the reasons of yours, you can use the integration feature with a different combinations for those. you can have sent data from the gateway to the integration. the integration does provide no need to have an access code of the device. in case the MQTT integration being used, ThingsBoard acts as a client for the third-party MQTT broker, so that the data is being mapped to the ThingsBoard as the data converter was configured
you can refer to this link regarding the MQTT integration: https://thingsboard.io/docs/user-guide/integrations/mqtt/
