### ISSUE TITLE
[Question] How to insert data using cassandra

### ISSUE THREAD

**Issue by Vasilis-Dim** [thingsboard/thingsboard#7600]
* Generic

**Description**
I would like to add some data into devices using cassandra db. 
I tried to use insert into thingsboard.ts_kv_cf but i can't see new data into thingsboard UI. If i try to use cqlsh every data is inside thingsboard.ts_kv_cf  and can seen from console. 
Am i doing something wrong or i need to do somethings more to see the data in UI?

**Environment**
 * OS:  Ubuntu Latest
 * ThingsBoard: 2.4.1

**Comment by mykhailokornieiev** [comment]
Hi. Not sure if this request is still relevant for you, but the best practice will be to use either Save To Custom Table rule node https://thingsboard.io/docs/user-guide/rule-engine-2-0/action-nodes/#save-to-custom-table or Rest API https://thingsboard.io/docs/pe/reference/rest-api/. It's highly not recommended to edit data in database manually
I closed this ticket due to inactivity. If this question is still relevant to you, feel free to open a new ticket with full description of your request.
