### ISSUE TITLE
Thingsboard TTL

### ISSUE THREAD

**Issue by mubashirp** [thingsboard/thingsboard#7609]
I am using thingsboard cloud professional edition (prototype subscription). I have set the TTL for telemetry in root rule chain as 60 days= 60*24*60*60 = 5184000 seconds. But in dashboard, i am only able to select  previous data upto 30 days. I am confused, why i am not getting 60 days as per the configuration?
![image](https://user-images.githubusercontent.com/49026279/201622442-076bd94f-01a5-4272-87e4-8268485d9f93.png)
![image](https://user-images.githubusercontent.com/49026279/201622651-b515bd3f-6fe3-4beb-9e6f-b7c9932890b3.png)

**Comment by devaskim** [comment]
TTL and `Last` option is not synchronized. The latter list are hardcoded values.
To set your custom value enable `Advanced` option

**Comment by mubashirp** [comment]
@devaskim 
i am able to select last 60 days from advanced option. But i need to verify that by making the following change, is the TTL is being set for 60days?
![image](https://user-images.githubusercontent.com/49026279/201851329-1a8dc889-640b-4d1b-8bf7-007d5bb62d2b.png)
I have calculated 60 days in seconds and made changes in the root rule chain, as shown above. Is that the right way to set desired TTL?

**Comment by devaskim** [comment]
According to [this doc page](https://thingsboard.io/docs/user-guide/tenant-profiles/), rule node option is one of right place to set TTL.

**Comment by mubashirp** [comment]
@devaskim 
As I am using cloud subscription, i am not having system administrator access to set the TTL from tenant profile. Is the above option works?
Or is there any other method to set TTL in cloud platforms.
By default the TTL is 180 days for my current subscription.

**Comment by devaskim** [comment]
Did you read that?
```
A Tenant Administrator is able to overwrite default TTL using the “Save Timeseries” rule node configuration or using the “TTL” parameter in the post telemetry request.
```

**Comment by mubashirp** [comment]
![image](https://user-images.githubusercontent.com/49026279/201891969-38c5589e-73c2-4e31-9613-aec24ffb0544.png)
@devaskim 
That is exactly what i did, as in the above screenshot, i edited the save timeseries rule node and set TTL value as 5184000 seconds= 60 days.
Is this enough to set TTL.

**Comment by devaskim** [comment]
@mubashirp Well, as you, I only have documentation, but our case doesn't limit us in data retention period so I don't care about ttl.
Here is [my discussion](https://github.com/thingsboard/thingsboard/issues/6989) with core team about TTL. Maybe it will help you

**Comment by Abbo93** [comment]
Similar problem for us but opposite: our company wants to extend the default TTL to the maximum (5years?), but if we change the TTL from 0 to another value telemetry is not recieved anymore. Now our company is losing data on the cloud due to default TTL.

**Comment by mubashirp** [comment]
@devaskim thank you for your response.
@trikimiki @Abbo93 
As in the above screenshot, i edited the save timeseries rule node and set TTL value as 5184000 seconds= 60 days.
Is this enough to set TTL.

**Comment by Civilduino** [comment]
I have the same need as @Abbo93, to extent the TTL for at least 2 years. I am also using the Prototype Cloud version as @mubashirp. If I understand correctly the documentation, it is possible to change the default TTL in the cloud because we are Tenant Administrators and can overwrite the System Administrator default settings as @devaskim wrote.

`
A System Administrator is able to configure default TTL using the “Default Storage TTL Days” parameter in the tenant profile. A Tenant Administrator is able to overwrite default TTL using the “Save Timeseries” rule node configuration or using the “TTL” parameter in the post telemetry request.
`

Now for the [CE](https://thingsboard.io/docs/user-guide/telemetry/)

`
Data retention policy and configuration depends on the chosen storage.
Cassandra supports time-to-live(TTL) parameter for each inserted row. You may overwrite the default value in the “Save Timeseries” rule node or using “TTL” metadata field of your message. This allows you to optimize storage consumption. The maximum allowed value of TTL is 5 years. For example, you may store “raw” data for 3 month and aggregated data for 3 years.
PostgreSQL and Timescale does not support time-to-live(TTL) parameter for each inserted row. That is why, you may only configure periodic time-series data cleanup routine using ‘SQL_TTL_*’ environment variables.
`

And for the [Cloud](https://thingsboard.io/docs/paas/user-guide/telemetry/)
`
ThingsBoard Cloud stores data with configurable time-to-live (TTL) parameter. The value of the parameter is part of the Subscription plan. You may overwrite the default value in the “Save Timeseries” rule node or using “TTL” metadata field of your message. This allows you to optimize storage consumption. The maximum allowed value of TTL is 5 years. For example, you may store “raw” data for 3 month and aggregated data for 3 years.
`

and also says

`
ThingsBoard Cloud stores time-series data in the Cassandra database with replication factor of 3.
`

So yes it should be possible to change the TTL in the cloud, which is actually logical and needed in many cases.
@Abbo93 so you try writing 5 years in the rule node and you are losing data? how come?

**Comment by Abbo93** [comment]
We have set the TTL in "Save Timeseries" to 155520000 (360days * 5years) and still loosing data after 60days...

**Comment by Civilduino** [comment]
You should contact [support](https://thingsboard.io/docs/contact-us/), they answer after a couple of days and explain the situation as it is not good. Refer them to this issue. Maybe there is a bug or a limitation in the Maker subscription.

[Here](https://thingsboard.io/products/paas/subscription/) it says that the maximum time is 5 years.
I think that there is a mistake in the documentation and they need to fix it asap!

**Comment by sunyong-mwi** [comment]
In ThingsBoard configuration file, we can set the TTL using "SQL_TTL_TS_TS_KEY_VALUE_TTL" setting. What's the difference of this setting and the setting in the rule chain node?

**Comment by devaskim** [comment]
Rule chain - per tenant configuration
Configuration file - per server instance configuration

**Comment by sunyong-mwi** [comment]
@devaskim , the Rule Chain TTL configuration is 0 by default. Does this mean the data is never expired, or TTL will take the value from configuration file?

**Comment by UsmanAzam** [comment]
Rule Chain TTL configuration has higher precedence over server configuration

**Comment by sunyong-mwi** [comment]
Does that mean server configuration setting will never take effect?

**Comment by UsmanAzam** [comment]
Official documentation of Server Settings: 
System TTL value can be overwritten for a particular Tenant, or parent Customer entity by setting the server-side attribute TTL to the corresponding Tenant or parent Customer entity.

Official documentation of Rule Chain: (Timeseries Node)
Also, if Message Metadata contains TTL field, its value is used for timeseries data expiration, otherwise TTL from Node Configuration is used.

**Comment by sunyong-mwi** [comment]
I still don't get it. There is always "Save Timeseries" node in the Rule Chain. The node's TTL setting will overwrites the server configuration. So the server configuration will never take effect. Is my understanding correct?

**Comment by trikimiki** [comment]
Hi!

The priority is: Rule Node - Tenant profile - configuration file
You are correct - Rule Node's TTL overrides the previous settings.

**Comment by sunyong-mwi** [comment]
Can I say that if the Rule Node TTL is 0, Tenant profile TTL will be used, and if Tenant profile TTL is 0, configuration file TTL will be used?

**Comment by trikimiki** [comment]
You are correct, yes.

**Comment by sunyong-mwi** [comment]
Thanks for the reply. That's very clear to me now.

**Comment by smatvienko-tb** [comment]
# Cassandra Telemetry TTL Hierarchy

This document describes how the effective TTL (time-to-live) for time-series
data points is resolved when ThingsBoard persists telemetry to Cassandra.

There are three layers that contribute to the final TTL applied to a Cassandra
row, in this order:

1. **Rule node** (`TbMsgTimeseriesNode` — the "Save Timeseries" node)
2. **Tenant profile** (`DefaultTenantProfileConfiguration.defaultStorageTtlDays`)
3. **System / environment** (`cassandra.query.ts_key_value_ttl`, env var `TS_KV_TTL`)

The first two select the *requested* TTL. The system TTL acts as a *hard ceiling*
and cannot be exceeded by anything upstream.

---

## ASCII diagram

```
 ┌──────────────────────────────────────────────────────────────────────────┐
 │                          INCOMING TELEMETRY MSG                          │
 │                  (POST_TELEMETRY_REQUEST → TbMsgTimeseriesNode)          │
 └──────────────────────────────────────────────────────────────────────────┘
                                       │
                                       ▼
 ┌──────────────────────────────────────────────────────────────────────────┐
 │ LAYER 1 — Rule node: TbMsgTimeseriesNode.onMsg()                         │
 │                                                                          │
 │   ttl = msg.metaData["TTL"]                  ◄── highest priority        │
 │         ?? node.config.defaultTTL            ◄── fallback #1             │
 │   if (ttl == 0)                                                          │
 │         ttl = tenantProfileDefaultStorageTtl ◄── fallback #2 (Layer 2)   │
 │                                                                          │
 │   → saveTimeseries(... .ttl(ttl) ...)                                    │
 └──────────────────────────────────────────────────────────────────────────┘
                                       │
                                       ▼
 ┌──────────────────────────────────────────────────────────────────────────┐
 │ LAYER 2 — Tenant profile                                                 │
 │   DefaultTenantProfileConfiguration.defaultStorageTtlDays                │
 │   • Loaded on init and refreshed via ctx.addTenantProfileListener(...)   │
 │   • Converted: DAYS → SECONDS                                            │
 │   • Used ONLY when both msg metadata TTL and node defaultTTL are 0       │
 └──────────────────────────────────────────────────────────────────────────┘
                                       │
                                       ▼
 ┌──────────────────────────────────────────────────────────────────────────┐
 │ LAYER 3 — Cassandra DAO clamp: CassandraBaseTimeseriesDao.computeTtl()   │
 │                                                                          │
 │   systemTtl = ${cassandra.query.ts_key_value_ttl}  (env: TS_KV_TTL)      │
 │                                                                          │
 │   if (systemTtl > 0) {                                                   │
 │       if (ttl == 0)  ttl = systemTtl;        ◄── default when not set    │
 │       else           ttl = min(systemTtl, ttl);  ◄── HARD CEILING        │
 │   }                                                                      │
 │   // if systemTtl == 0  → no clamp; requested ttl used as-is             │
 │                                                                          │
 │                              ┌───────────────────┐                       │
 │                              │  EFFECTIVE TTL    │                       │
 │                              └───────────────────┘                       │
 └──────────────────────────────────────────────────────────────────────────┘
                                       │
                ┌──────────────────────┴──────────────────────┐
                ▼                                             ▼
 ┌────────────────────────────────┐         ┌────────────────────────────────┐
 │ Data row (ts_kv_cf)            │         │ Partition row (ts_kv_partitions│
 │ "USING TTL <effective_ttl>"    │         │  _cf) — uses computeTtl(0)     │
 │                                │         │  → systemTtl only, NEVER the   │
 │                                │         │  per-message TTL               │
 └────────────────────────────────┘         └────────────────────────────────┘
```

---
