### ISSUE TITLE
Creating and sending data to a Database other than default 'thingsboard' DB in ThingsBoard

### ISSUE THREAD

**Issue by debacs83** [thingsboard/thingsboard#7664]
**Component**

 * Generic

**Description**
When installing ThingsBoard in Linux, the default database is 'thingsboard' (postgreSQL). All the data that are send to ThingsBoard in JSON format registered in this database. Based on that I dashboard is created to display the data. 

I would also like to create a separate database with some other name of course and store the raw data (for example, payload as it is in HEX-string, not converted to their actual values etc.).  Is it possible to do that? If so, how can I do that? 

As far as I know, all the data that entered the ThingsBoard go through the Rule Chain (root). So, by default all the data comes to the ThingsBoard entered the default database (thingsboard)? Then how to divert some of them to another? 

Any helps?

Regards

**Environment**

 * OS:  Ubuntu Linux 20.04 LTS (AWS EC2 instance)
 * ThingsBoard: 3.4.1
 * Browser: Chrome, Mozilla, Edge

**Comment by rjarman** [comment]
In general, you can't, they use JPA for database transactions in the latest 3.4.0 version, which was generic though but you can't just divert some of your specific data to another DB. 
But somehow you can with a rule node because they provide all their services inside the rule node by **ctx**. So you can easily divert data by making your own node.
