### ISSUE TITLE
[Question] Device - JSON in telemetry Data

### ISSUE THREAD

**Issue by kandrianatos** [thingsboard/thingsboard#7675]
**Component**

 * UI
 * Generic

**Description**
Is it valid to store key with a JSON as value? Also is it possible to parse the JSON and display its data to a Widget in Dashboard?
![image](https://user-images.githubusercontent.com/22050314/203810689-1e1a6444-57c6-4fda-bea5-f5da54ab1253.png)

**Environment**

 * OS:  OS: Windows 11 Pro Local Installation

**Comment by liotys** [comment]
Hi @kandrianatos ,
try something like that:
![image](https://user-images.githubusercontent.com/103430329/204012575-e4a9d006-5cac-48f2-b309-ae10518ea92b.png)
It's an adaptation of #6490.

**Comment by kandrianatos** [comment]
Thanks @liotys!

**Comment by BigNavid** [comment]
Hi,

The Issue:
- Thingboard potentially treats JSON telemetry data as a string: This is a common scenario where the platform receives the JSON data as a single string value instead of recognizing it as a structured JSON object.
- Need for JSON parsing: To effectively utilize the data within Thingboard (e.g., for data visualization, analysis, or triggering rules), you need to parse the JSON string into a proper JSON object.

@liotys's Solution (Post-Data Processing):
Parsing within Thingboard: This approach suggests performing the JSON parsing within Thingboard's post-data processing rules.

- Pros: Leverages Thingboard's built-in rule engine for data transformations.
- Cons: Might introduce additional processing overhead within Thingboard.

Question:
If I'm right what's the purpose of supporting JSON in telemetry data?
