### ISSUE TITLE
Unauthorized 401 on Thingsboard PE Trial

### ISSUE THREAD

**Issue by PanGian97** [thingsboard/thingsboard#7709]
**Component**

 * Generic

**Description**
Thingsboard can't succesfully authorize me by putting username and password (tenant admin) on Swagger UI or even during api calls (trying to get JWT token ). I'm sure the credentials are right cause i can login succesfully to the platform with them. 

**Environment**

 * OS:  Windows 10 (thingsboard PE on cloud during 30 days trial)
 * ThingsBoard: PE trial
 * Browser: Mozilla

**Comment by den1jkee** [comment]
Hi,
You can copy JWT token in the security section of the profile.
Also, I've tested this issue and can't reproduce it because
![image](https://user-images.githubusercontent.com/113901187/204839142-9acbd439-dd8e-474e-96f3-50797fe89289.png)
Check your credentials and make sure about the information that you enter in a request
Best regards,
Denys.

**Comment by PanGian97** [comment]
Hi, u put the tenant login credentials right?

**Comment by den1jkee** [comment]
Yes,
My demo tenant credentials. I`ve created a demo account for 30 days and tested it.

**Comment by PanGian97** [comment]
I have no idea why it doesn't work on Thingsboard PE trial. On my
thingsboard demo it works, as well as in my paid Linux integration

**Comment by den1jkee** [comment]
Did you check your request? He must be like that below in **/api/auth/login**
`{
  "username": "example@example.com",
  "password": "<some_password>"
}`
