### ISSUE TITLE
[Bug] Catalan language displayed instead of Spanish

### ISSUE THREAD

**Issue by EliBCC** [thingsboard/thingsboard#7714]
**Describe the bug**
When Google Chrome browser language is set to español, demo.thingsboard.io is instead displayed in Catalan.

**Your Server Environment**
demo.thingsboard.io

**Your Client Environment**

* OS: Windows 10
* Browser: Chrome
* Version: 107.0.5304.122 (Official Build) (64-bit)

**Your Device**
N/A

**To Reproduce**
1. Open Chrome and set display language to 'español'
2. Relaunch the browser
3. Navigate to demo.thingsboard.io
4. See Catalan language displayed instead of Spanish

**Expected behavior**
The username field should read "nombre de usuario". Instead, it reads "nom d'usuari"

**Additional context**
The website is being accessed from Canada. This may be relevant, as the locale code for Catalan is 'es_CA', which clashes with the country code for Canada (CA).

<img width="623" alt="Snipaste_2022-11-30_11-26-18" src="https://user-images.githubusercontent.com/23089099/204891744-0272c5a7-9e3c-40c8-b5ad-e24890e1bbe1.png">
<img width="320" alt="Snipaste_2022-11-30_11-26-51" src="https://user-images.githubusercontent.com/23089099/204891759-c1822d9a-ae74-4263-b7d3-f48552fb65b5.png">

**Comment by den1jkee** [comment]
Hi
Can you show what language chrome transmits in the HEADER? By default, the language in ThingsBoard is set based on the HTTP HEADER received from the browser.
Checking service:
https://www.whatismybrowser.com/detect/what-http-headers-is-my-browser-sending

Best regards,
Denys.

**Comment by JavierNR** [comment]
Hello @den1jkee

I'm having the same issue as @EliBCC under demo.thingsboard.io.
I'm the spanish language contributor and my browser is in spanish, since both languages begins with es_ maybe thingsboard applies the first occurrence of language, and doesn't check the two cases? es_CA, es_ES

Results from whatsismybrowser:

<html>
<body>


USER-AGENT | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
-- | --



</body>
</html>
<html>
<body>


SEC-CH-UA-FULL-VERSION | "108.0.5359.98"
-- | --



</body>
</html>
<html>
<body>


ACCEPT-LANGUAGE | es,en;q=0.9,de;q=0.8
-- | --



</body>
</html>
