### ISSUE TITLE
[Question] your title here

### ISSUE THREAD

**Issue by debacs83** [thingsboard/thingsboard#7865]
**Component**

  * Generic

**Description**
On Thingsboard, devices can be registered with their respective Access Tokens (pre-prepared) with csv file or one-by-one using browser based UI. Is that can be possible with API? Something similar to sending data using HTTP(s) POST API from command line or from AWS Lambda?

**Environment**

 * OS:  Linux 20.04
 * ThingsBoard: 3.4.2
 * Browser: any (nothing specific)

**Comment by UsmanAzam** [comment]
Yes possible.

- Create an HTTP integration and copy its http endpoint url
- put that url in your lambda function so that it can pish device json 
- create a device profile and assign a rule chain to it.
- create an uplink converter for that integration where you parse that incoming json and pass it on to the rule chain
- your output from converter should be like this

{
deviceName: '',
deviceType: '',
ts: '',
      telemetry: {},
attributes: {}
}

- In the rule chain simply save the data by using "Save Timeseries" node

**Comment by debacs83** [comment]
Thank you very much for your reply.
 
But I think my explanation was not clear. Actually instead of sending 'Data' to Thingsboard by CSV file, I want send the CSV file with ACCESS TOKEN to Thingsboard to register Devices. Not Timeseries data, I want to Register devices by send CSV file through API instead of using UI.

**Comment by devaskim** [comment]
Here is [REST API endpoint for bulk provisioning](https://demo.thingsboard.io/swagger-ui/#/device-controller/processDevicesBulkImportUsingPOST)

**Comment by debacs83** [comment]
Thank you!
