### ISSUE TITLE
[Bug] v3.4.3 throws errors due to missing `assetentit0_.asset_profile_id` 

### ISSUE THREAD

**Issue by AndreMaz** [thingsboard/thingsboard#7962]
**Describe the bug**
After upgrading from 3.4.1 to 3.4.2 and then to 3.4.3 TB throws errors due to missing `assetentit0_.asset_profile_id`.

> *Note:* The `./upgrade-tb.sh` was executed during the migration to 3.4.2. For 3.4.3 only the image was updated (as per this comment https://github.com/thingsboard/thingsboard/issues/7882#issuecomment-1368912947 )

So far I detected errors in the following scenarios:

**Opening Asset Tab**
![image](https://user-images.githubusercontent.com/9802754/213125415-783efb48-aebe-44fa-b60a-9ee777a228eb.png)

**Restoring Dashboards via Version Control Tab**
![image](https://user-images.githubusercontent.com/9802754/213126645-8febfab0-4f9e-4c7a-a8e5-def7e375a56f.png)

In both cases the following error is printed in the logs
> Caused by: org.postgresql.util.PSQLException: ERROR: column assetentit0_.asset_profile_id does not exist

**Your Server Environment**
Docker deployment with ThingsBoard Version: 3.4.3

**Expected behavior**
Not to see the error.

**Additional context**
I've attached full server logs (`dashboard_restore_logs.txt` and `asset_tab_logs.txt`) for each of the errors reported above.

[dashboard_restore_logs.txt](https://github.com/thingsboard/thingsboard/files/10443944/dashboard_restore_logs.txt)
[asset_tab_logs.txt](https://github.com/thingsboard/thingsboard/files/10443945/asset_tab_logs.txt)

I guess that this issue is somehow related to https://github.com/thingsboard/thingsboard/issues/3497 and https://github.com/thingsboard/thingsboard/issues/6167

**Comment by den1jkee** [comment]
Hi,
Can you please provide  `install.log` and your `database_schema` for investigation of the problem?

Thanks.
Best regards,
Denys.

**Comment by Strauteka** [comment]
Same error if migrating from Docker thingsboard/tb-postgres:3.3.0 ->  thingsboard/tb-postgres:3.4.3 
Failing schema upgrade to 3.4.2 Error same as in linked task(/issues/7882). ` relation "old_blob_entity" does not exist`

Using env
TB_SKIP_AUDIT_LOGS_MIGRATION: true
TB_SKIP_EDGE_EVENTS_MIGRATION: true

Looks like Successful migration is:
Migration from thingsboard/tb-postgres:3.3.0 -> 3.4.1 
Starting thingsboard/tb-postgres:3.4.1 successful
Migration from thingsboard/tb-postgres:3.4.1 -> 3.4.2 
Starting thingsboard/tb-postgres:3.4.3 successful

**Comment by AndreMaz** [comment]
Hi @den1jkee 

Unfortunately I no longer have the `install.log` but here's the TB DB schema (obtained with pg_dump  `-schema-only --no-owner` params) 

[thingsboard_dump.txt](https://github.com/thingsboard/thingsboard/files/10497022/thingsboard_dump.txt)

**Comment by HardwayLinka** [comment]
Hi @den1jkee, where can i find `database_schema`.

**Comment by den1jkee** [comment]
Hi @HardwayLinka ,
You can dump it from your database with this command:
`pg_dump -U postgres -s dbname> exportFile.dmp`

Best regards,
Denys

**Comment by icebob** [comment]
I made some investigation about it because this issue blockes us in your project.

The left side shows our `asset` table in 3.4.1 - 3.4.2 - 3.4.3 upgraded database
The right side shows a newly created database with TB 3.4.3.

![image](https://user-images.githubusercontent.com/306521/216769221-f6baf087-4360-4d23-aceb-3d96b66f4e32.png)

It shows that the `asset_profile_id` column is not added, I think because its a `NOT NULL` column, but our `assets` table has records.

I saw in the [db upgrade script](https://github.com/thingsboard/thingsboard/blob/085e3c1580054531e255316e051582edc548162d/application/src/main/data/upgrade/3.4.1/schema_update_before.sql#L36) that an `update_asset_profiles` procedure created which tries to set the asset_profile_id from the `asset_profile` table but that table is empty because the upgrade script created during the upgrade.

On the other hand the `asset_profile_id` adding ALTER TABLE script is missing in the before sql script. Only the `SET_NULL` altering exists in the after sql script which will crash because the field is missing.

**Comment by lepgithub** [comment]
I'm having the exact same issue after upgrading(I was very careful, upgraded version by version only); how do I solve this issue?

**Comment by icebob** [comment]
We removed the "half-upraded" table fields manually and executed the 3.4.2 upgrade again and the second time it ran normally.

**Comment by lepgithub** [comment]
@icebob Thanks for your response. But unfortunately my postgresql skills are minimal. I tired to understand your above post, but it not that clear to me what exactly was to done to fix the issue. I would greatly appreciated if you can give me an example of how you removed the "half-upgraded" table fields. Thanks again!

**Comment by GrayCygnus** [comment]
@icebob hey there, I'd also appreciate if you clarify what you did, as I'm currently stuck in the same situation.

From what I understood, I manually removed the "asset_profile_id" from the "asset" table, and proceeded to upgrade again... but got the same error... what did I miss? what else should I delete, the indexes as well?

I also have some rows on the "asset" table, but the asset_profile one (as far as I understand) is new and being created on the upgrade... so the issue is that we "have no asset_profile" but we have assets...

I will greatly appreciate your indications :)

Thanks,
Mike

**Comment by GrayCygnus** [comment]
Update: I managed to successfully do the upgrade (at least that's what the output reads).

I ended up deleting the (2) rows I had on "asset" as those were auto-generated I believe (made a backup of them in any case). And yes the issue is that the script enforces the "not null" on that column (the asset_profile_id), but as asset_profiles are "just" being created (thus, no default one exists), enforcing that "not null" on the primary key gave the error. 

If anyone did something else, perhaps that didn't involve deleting rows, please share it for any other unfortunate soul out there 

Cheers,
Mike

**Comment by DerGue69** [comment]
I had exactly the same - always error during update process.

I remoted to DB with PG admin and ran:
[schema_update_before.sql](https://github.com/thingsboard/thingsboard/blob/085e3c1580054531e255316e051582edc548162d/application/src/main/data/upgrade/3.4.1/schema_update_before.sql#L17-L45)

my asset_profile table was missing. I deleted the 1 entry in asset table.
Then I was able to run the [schema_update_after.sql](https://github.com/thingsboard/thingsboard/blob/085e3c1580054531e255316e051582edc548162d/application/src/main/data/upgrade/3.4.1/schema_update_after.sql#L17-L21) scritp.

Then I was able to finally update thingsboard to 3.6.3 without error message.

I tried to add an aset profile - but I get a Database error in the GUI.
Then I pasted backupo from asset table into the table again >> but same >> "Database Error"

Do you know how to fix this?

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mandlg/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mandlg/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


additional_info | name | type | label | id | created_time | customer_id | tenant_id | external_id
-- | -- | -- | -- | -- | -- | -- | -- | --
null | Main_thingsboard | TbServiceQueue |   | 56ecfe00-9910-11ea-a7b2-3fcb26eb041d | 1,58981E+12 | 13814000-1dd2-11b2-8080-808080808080 | f4244df0-1548-11ea-976b-81af79ab3791 |  



</body>

</html>



![image](https://github.com/thingsboard/thingsboard/assets/96002277/f0957109-fd41-43b8-bb78-7a171684ec7a)
