### ISSUE TITLE
How to fix "creating bean with name 'entityManagerFactory' defined in class path resource" error?

### ISSUE THREAD

**Issue by Navid61** [thingsboard/thingsboard#7985]
Hi, 

I installed thingsboard v 3.4.3 on Debian 11 x64, PostgreSQL-15  and Java 11 ,when I did run below script:

sudo  /usr/share/thingsboard/bin/install/install.sh --loadDemo

I got this error:

Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
ThingsBoard installation failed!

I'm going to know how can I fix that?

**Comment by StoyanBo** [comment]
I have same error and don't know how to resolve.

**Comment by otsakir** [comment]
I had the same error and proved it was due to bad authentication credentials. I found that from the postgres log file. In my ubuntu 22.04:

# tail -f /var/log/postgresql/postgresql-12-main.log

I reviewed `SPRING_DATASOURCE_PASSWORD` in thingsboard.conf but didn't find a difference with the one i had set through psql. I ended up reseting the password to a plain, latin only with no quotes one and this fixed it.

**Comment by hemanth94** [comment]
> Thanks @otsakir. from the log `/var/log/postgresql/postgresql-12-main.log` I found the error: `postgres@thingsboard FATAL: database "thingsboard" does not exist`

I had the same issue. I resolved it by checking the logs and found out database "thingsboard" doesn't exit.
Once you create the database in pgadmin, the issue will be resolved. Thanks @23ewrdtf

**Comment by Ultrazombie** [comment]
Closed due to inactivity.
