### ISSUE TITLE
[Bug] Thingsboard map drawing radius circle

### ISSUE THREAD

**Issue by Prometheus4800** [thingsboard/thingsboard#8020]
Hi,

I'm using an OpenStreetMap and would like to have a circle around the points. I've got the long and lat working from shared attributes and I also have a radius attribute. In the advanced tab under the circle settings, I'm toggling the show circle and selecting the circle key name but nothing appears to be showing. I'm using a 700 value for the radius

**Comment by pskacel** [comment]
+1
for me it is not working on v.3.4.4PE

**Comment by argusro** [comment]
+1
Hi, I'm also not seeing the circle on CE 3.5.1
'latitude': xx.xxxx, 'longitude': xx.xxxx, 'radius': 957}

**Comment by spirosbond** [comment]
+1 Same issue here, using Thingsboard Cloud.
Any fix?

**Comment by myroslav-tb** [comment]
Hello @Adw1284, In order to draw a circle polygon on the Map widget, you need to perform the following configuration:

Before creating a Map widget, ensure that your entity being used has three telemetry data keys: latitude, longitude, and circle.
![image](https://github.com/thingsboard/thingsboard/assets/158559147/3c59af20-6b70-4d52-b985-c67bb02a36c7)

When adding the widget, you need to add all three keys to the widget's datasource.
![image](https://github.com/thingsboard/thingsboard/assets/158559147/c1386ec6-66f9-4828-b165-8daa54a6371e)

Then, in the appearance tab, you need to specify latitude and longitude in the common map settings.
![image](https://github.com/thingsboard/thingsboard/assets/158559147/d2975d76-673e-4b41-9996-2bd883e72ceb)

After that, you have to enable "Show circle", specify the circle key name and check the "Enable circle edit" checkbox
![image](https://github.com/thingsboard/thingsboard/assets/158559147/b62b91bf-23da-4e16-81ce-696b179fd1af)

As a result, a circle will be drawn on the widget
![image](https://github.com/thingsboard/thingsboard/assets/158559147/0c3a50df-ee83-4de5-b1da-2e4519d029d2)

Best regards,
Myroslav

**Comment by argusro** [comment]
Hello @myroslav-tb, does the key needs to be named circle, and does it need to be structure like this json?
In my case this value is just an integer coming from the device, could I use post-processing somehow to create this lat, long, radius structure?
This only works on OpenStreet Map or also on Trip Animation?
And lastly, which version is required, I'm on v3.6.0 CE.
Thanks

**Comment by myroslav-tb** [comment]
Hi @argusro, 
> does the key needs to be named circle, and does it need to be structure like this json?

Yes, it wouldn't work the other way.


> could I use post-processing somehow to create this lat, long, radius structure?

It is better to add a script to the rulechain that will do the transformation.

> This only works on OpenStreet Map or also on Trip Animation?

It works on both widgets.


> which version is required, I'm on v3.6.0 CE.

I tested this on 3.6.4 CE, but it should also work on 3.6.0 CE and older versions.

Best regards,
Myroslav

**Comment by myroslav-tb** [comment]
I am closing this ticket due to inactivity.
