### ISSUE TITLE
TB develop/2.0: Blank rule chain page after saving

### ISSUE THREAD

**Issue by untilbit** [thingsboard/thingsboard#806]
I have created an alarm and a clear alarm nodes and after saving the page turned blank and all nodes disappeared, also the grid does not appear.

Tutorial I was following: https://github.com/thingsboard/thingsboard.github.io/blob/9de495b8d140b373e4629ea48806bdda308a43e8/docs/user-guide/rule-engine-2-0/tutorials/create-clear-alarms.md

**Comment by vparomskiy** [comment]
This is a standard scenario that was tested allot of times. 
Is it reproducible in your instance?
Are there any errors in the browser console?

**Comment by untilbit** [comment]
**Yes. Steps to reproduce:**
- I set zoom of the browser to 90%
- Added **Message Type Switch** node and saved changes
- Tried connecting the input node to the previous node added and the blank page issue happens again.

**Yes, there are these errors and a many warnings related to translation.**

```
Translation for rulechain.root doesn't exist
angular.js:13920
Error: Coordinates not valid.
e@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:637:7900
s@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:521:20886
l/<@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:521:19205
a@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:521:20793
o/<@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:521:18975
a@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:521:20793
rt/E<@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:521:21364
i@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:521:20217
r@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:521:20517
s@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:521:20854
l/<@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:521:19205
a@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:521:20793
o/<@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:521:18975
a@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:521:20793
rt/E<@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:521:21364
i@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:521:20217
r@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:521:20517
s@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:521:20854
wt/this.$get</<@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:522:14907
a/<@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:447:2557
compile/<@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:44:24272
W/<@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:521:5650
ve@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:522:10050
p@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:522:2501
a@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:521:30350
R/<@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:521:29881
X/<@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:522:528
d@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:44:23471
compile/</<@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:44:23891
$broadcast@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:523:13780
x/T.transitionTo/T.transition<@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:44:19033
a@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:523:4586
s/<@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:523:4758
$eval@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:523:12395
$digest@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:523:10877
$evalAsync/<@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:523:12484
o@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:521:22661
ut/u.defer/n<@http://127.0.0.1:8080/static/bundle.0385ffca95dcf35dcef3.js:521:24125
 undefined
```

**Comment by vparomskiy** [comment]
This bug reproduced only when browser zoom is changed. 
We are working on the fix, but right now, as a workaround, please do not change browser default zoom

**Comment by ashvayka** [comment]
@vparomskiy is this already fixed?

**Comment by vparomskiy** [comment]
Yes, an exception is not thrown if browser zoom was changed.

**Comment by untilbit** [comment]
This bug has not been fixed, i still can reproduce with steps above.

**Comment by vparomskiy** [comment]
Please update to the latest version and clear browser cache. If the problem still reproduced, please provide additional info:

1. browser version

**Comment by untilbit** [comment]
- I have already the latest TB version and cleared cache.
- Local OS: Ubuntu 18.04
- Firefox 60.0.1

**Comment by vparomskiy** [comment]
If you are building Thingsboard from sources, then you need to clear **node_modules** directory in (./ui/node_modules) and then rebuild project (mvn clean install)
The issue was resolved a few days ago, but cached npm modules are not cleared automatically.

Please tell is it works for you, so we can close the ticket.

**Comment by volodymyr-babak** [comment]
@untilbit, Official 2.0 docker image was updated. Please re-pull 2.0 version and validate scenario. 
Thanks and sorry for inconveniences.

**Comment by untilbit** [comment]
@volodymyr-babak Now it's fixed. Thanks.

**Comment by mbari** [comment]
I have encoutered this issue today with the following errors

2019-11-12 05:24:38,056 [pool-38-thread-1] ERROR c.g.c.util.concurrent.AbstractFuture - RuntimeException while executing runnable com.google.common.util.concurrent.Futures$4@bddbb7a with executor MoreExecutors.directExecutor()
2019-11-12 06:11:07,071 [http-nio-0.0.0.0-8080-exec-1] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.http.InvalidMediaTypeException: Invalid mime type "*/*\r\nAccept-Language: zh-cn\r\nUser-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML": wildcard type is legal only in '*/*' (all mime types)] with root cause
2019-11-12 06:11:07,105 [http-nio-0.0.0.0-8080-exec-3] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.http.InvalidMediaTypeException: Invalid mime type "*/*\r\nAccept-Language: zh-cn\r\nUser-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML": wildcard type is legal only in '*/*' (all mime types)] with root cause
