### ISSUE TITLE
Not able to subscribe for the topic -->v1/devices/me/rpc/request/+

### ISSUE THREAD

**Issue by manojsai17** [thingsboard/thingsboard#808]
Hello every one,
i am able to publish to topic  v1/devices/me/telemetry... but i am not able to subscribe to topic v1/devices/me/rpc/request/+...getting response (0x80-->failed) and i am able to  subscribe the attributes response for v1/devices/me/attributes. (all are in mqtt.. 
[tblogforum.pdf](https://github.com/thingsboard/thingsboard/files/2035061/tblogforum.pdf)
).. i added the log of my code..please check it

**Comment by vparomskiy** [comment]
(0x80-->failed) -> the reason is an unexpected topic name.
Could you please verify that you are using a correct topic name.

You can also use external libraries to verify that subscription works as expected. You can find them in this tutorial:
https://thingsboard.io/docs/reference/mqtt-api/#server-side-rpc

**Comment by manojsai17** [comment]
I had taken same topic

v1/devices/me/rpc/request/+

**Comment by volodymyr-babak** [comment]
Verified with latest release and subscribe totally works fine
Used this guide to verify:
https://thingsboard.io/docs/edge/use-cases/manage-alarms-rpc-requests-ce/#connect-air-conditioner-to-edge-and-subscribe-for-rpc-commands
Please take a look at **cooler.js** and **mqtt-js.sh** scripts for details.

**Comment by OdayKabaha** [comment]
Hi @volodymyr-babak , 
I have the same problem. How did you solve the problem ? 
Thanks
