### ISSUE TITLE
Past data not visable on chart or realtime card

### ISSUE THREAD

**Issue by jensvdh15** [thingsboard/thingsboard#817]
Hi all,

I've sent data from the past to thingsboard. The latest telemetry of the device shows me that it is send.

Now I've made a chart widget and a realtime card widget of these data, but both stay empty, however the data is send.

Anyone knows what the problem is and how to solve it?

**Comment by gustavovelascoh** [comment]
I had the same issue today and figured out that when the data value is sent as string, it is plotted real-time as it arrives, but when you reload your widget/chart it is not plotted anymore. When data is sent as number, it is displayed when the widget is loaded. For example if you send {"temperature": "20.5"}` it will be plotted real-time in widget but will not be plotted when reload. You should use `{"temperature": 20.5}` instead.

**Comment by vparomskiy** [comment]
By default, time window config use **AVG** aggregation type. So all data in the selected interval are aggregated with average function.
But there is no way how to aggregate string types, so they are discarded.

There are 2 solutions:
1. Change Data aggregation function to **none** in time window configuration
2. Submit numeric values instead of string values

**Comment by gustavovelascoh** [comment]
Hi @vparomskiy, I understand your comment, but why it works for real-time data with string values (numbers as string)? I mean, If I submit data like `{"temperature": "20.5"}`, it will be added to the plot, even if aggregation type is **AVG**

**Comment by vparomskiy** [comment]
It is a side effect. With real-time widget, subscription for all required attributes is created and server sent notifications via websocket to the widget. JS knows how to aggregate this data because js is a  weakly typed language. 
But data from the _past_ interval should be aggregated on the server-side and it is not possible to aggregate strings.
