### ISSUE TITLE
[Question] Device profile alarms configurations in a device level

### ISSUE THREAD

**Issue by lstarke** [thingsboard/thingsboard#8187]
**Component**

 * Generic

**Description**
Is there a way to have the device profile alarms configurations in a device level ?

![image](https://user-images.githubusercontent.com/7483656/223738785-49a3d072-bc98-4a95-a70b-b3fa8e66f4dd.png)

Using device profiles all devices assigned to this profile will follow the alarms configurations, what I need is a specific alarm configurations for each device. 

**Environment**

 * OS:  name and version
 * ThingsBoard: Thingsboard PE Cloud
 * Browser: MS Edge

**Comment by Civilduino** [comment]
Yes, you can use the attributes of the device, for example:
<img width="691" alt="image" src="https://user-images.githubusercontent.com/27728926/223844297-93a5faae-d322-434e-8246-b656d7983d90.png">

**Comment by lstarke** [comment]
Hello @Civilduino, thank you for your comment.

Just to be clear. Inside your key filter you also did something like the image bellow ?

![image](https://user-images.githubusercontent.com/7483656/224008741-0036a49c-53d8-4906-917b-7a227f4c13e8.png)

Another question:

I created a new server attribute called `deviceName`, is there a way to fetch de device name directly from device details ?

![image](https://user-images.githubusercontent.com/7483656/224010261-88439020-9c0f-44dd-970f-58915e260d40.png)

**Comment by den1jkee** [comment]
Hi, 
Press on (x) button to expand additional settings in rule conditions.

Best regards,
Denys

**Comment by Civilduino** [comment]
As @den1jkee wrote, by clicking on (x), you can define a dynamic source instead of a constant value. In that way the filter can work with all devices with the same profile based on their own name.

![image](https://user-images.githubusercontent.com/27728926/224475350-b824fd5b-f387-471d-a2e4-7c200997e124.png)

Regarding your second question, it is possible if you pass the entityName inside the alarm details, e.g. see #3457. Not sure if there is a better way. By calling the key inside Details, you will have access to it in the Alarm filter.

Theoretically, you could pass as many keys you want inside Details and then process them in the Rule Engine, e.g. use a specific character in the string to separate them or pass them as a JSON (I haven't tried the latter though).

![image](https://user-images.githubusercontent.com/27728926/224475926-17b7e03d-5178-465d-9006-dac3fcc49fb5.png)

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
