### ISSUE TITLE
[ERROR]ThingsBoard installation failed!

### ISSUE THREAD

**Issue by Meisam-rashno** [thingsboard/thingsboard#8492]
* UI

**Description**
hi mates!
i tried to install the build version but i got this error when i ran installation script.
in thingsboard log :

`2023-05-07 15:44:14,311 [main] ERROR o.t.s.ThingsboardInstallApplication - while scanning a double-quoted scalar
 in 'reader', line 135, column 11:
        path: "${SECURITY_JAVA_CACERTS_PATH:${ ... 
              ^
found unknown escape character l(108)
 in 'reader', line 135, column 54:
     ... _JAVA_CACERTS_PATH:${java.home}\lib\security\cacerts}"`

 * OS:  Ubuntu 22
  * ThingsBoard: 3,4,4

**Comment by Meisam-rashno** [comment]
can anyone help?

**Comment by den1jkee** [comment]
Hello,
Please provide the **install.log** file, which is located at `/var/log/thingsboard/.`

Additionally, could you please provide a detailed step-by-step description of the actions you performed?

Sincerely,
Denys

**Comment by Meisam-rashno** [comment]
Thank you for your reply, it's resolved

**Comment by den1jkee** [comment]
Hi,
Please describe a little bit about the root cause of this issue and how you resolved it.
It would be great for users in the future to resolve similar issues.

Thanks.
Best regards,
Denys

**Comment by den1jkee** [comment]
Hi @An-Bin ,
Please check your thingsboard.conf file on a section of the database connection, or please provide your .conf to investigate.
`main] WARN  o.h.e.j.e.i.JdbcEnvironmentInitiator - HHH000342: Could not obtain connection to query metadata
java.lang.RuntimeException: Driver org.postgresql.Driver claims to not accept jdbcUrl, jdbc:mysql://localhost/thingsboard`

Also, which database do you using? If MySQL, so that will not work, you need to use PostgreSQL instead of MySQL.

Best regards,
Denys

**Comment by Ultrazombie** [comment]
MySQL is not supported and we use some functions that are specific to PostgreSQL

**Comment by An-Bin** [comment]
@Ultrazombie @den1jkee 
Okay, the problem has been resolved. Thank you
