### ISSUE TITLE
[Bug] Python SDK CE clear_relation endpoint 

### ISSUE THREAD

**Issue by shayMZ** [thingsboard/thingsboard#8610]
Hi,

Python SDK CE 'clear_relation' endpoint [BUG]

The clear relation api call remove device from all device group.
And because of that we couldn't see them in system, they just gone.

I expect the function to remove all the visible relation that device have.

**Comment by ashvayka** [comment]
@imbeacon please check this

**Comment by imbeacon** [comment]
Hi @shayMZ,

Are you using the latest version of the client and ThingsBoard? I cannot find this method in the latest releases of the both.

**Comment by shayMZ** [comment]
Hi @imbeacon , I'm sorry.... the function name is delete_relations

**Comment by imbeacon** [comment]
Hi @shayMZ ,

I have checked and it is expected behavior, to remove all relations for entity. 
We will think how to change this method or add a new one to remove only relations with type `COMMON`.

To achieve removing all visible relations - you can use the following workaround:
1. Get relations using methods `find_by_to` and `find_by_from` with relation_group_type - `'COMMON'`
2. Iterate over received lists and use `delete_relation` method to remove relations.
