### ISSUE TITLE
How to change value to words in thingsboard widget?

### ISSUE THREAD

**Issue by Buhaw85** [thingsboard/thingsboard#8666]
Hi im trying to use a widget to tell the state of my connectecd device on thingsboard. 

Value                     Mode
0                      Stop Mode
1                      Manual Mode
2                      Auto Mode

Is there a way to write this in the json section of the widget so that for example if the vale thats coming is 1 then the widget would display Manuel Mode and not the number 1.

This is what I have so far but as you can see it doesnt work.
![image](https://github.com/thingsboard/thingsboard/assets/130080104/2d2bf25d-6315-47e5-81b1-11c91d65e5f7)
![image](https://github.com/thingsboard/thingsboard/assets/130080104/55e63127-34a0-49af-bbef-58a52d1054ed)

Can someone help me out please?

Thanks

**Comment by Buhaw85** [comment]
As I was writting this I believe I figured out what I was doing wrong.
![image](https://github.com/thingsboard/thingsboard/assets/130080104/d2faff27-cc1d-4dac-8abc-856aea26d26e)

It should be -- and not ---.

**Comment by den1jkee** [comment]
Hi,

The == operator performs a loose equality comparison that performs type coercion if necessary to make the comparison possible.

The === operator, on the other hand, performs a strict equality comparison that does not perform type coercion and requires the operands to have the same type (as well as the same value).

So in both cases, it will be correct but requires more attention to what you are comparing.
The example below is not correct because my value is float.
```
if(value === '697.6569051919126')
{
return value = 'Stop Mode';
```
but if I write like this it will be correct:
```
if(value === 697.6569051919126)
{
return value = 'Stop Mode';
```

Best regards,
Denys
