### ISSUE TITLE
[Question] how can i make changes to my home screen 

### ISSUE THREAD

**Issue by securitylamb** [thingsboard/thingsboard#8765]
**Component**

 * UI

**Description**
Hi can i update my home screen I tried searching online but there was no resource
i want to hide these view doc links on some button if i could or could i just hide the button  
![image](https://github.com/thingsboard/thingsboard/assets/34526029/96f26413-6107-41fe-afac-4010da464025)

**Environment**

 * OS:  ubuntu
 * ThingsBoard: 3.5.1 PE latest
 * Browser: name and version

**Comment by mykhailokornieiev** [comment]
Hi
You can create your own dashboard and assign it as "Home Dashboard"
It's available to use the same widgets as in the default home screen
![image](https://github.com/thingsboard/thingsboard/assets/115699895/e64e794a-b942-415f-a0a1-b8e96a6fb08f)
You can use widgets of any type, not only Home Page widgets
Then you can set it as Home Dashboard:
1) For Tenant in Settings -> Home settings
![image](https://github.com/thingsboard/thingsboard/assets/115699895/798416fa-147d-4052-bd82-fad5baa17b52)
2) For customer user in Customer -> Manage Customer User Groups -> Customer User settings -> Home Dashboard
![image](https://github.com/thingsboard/thingsboard/assets/115699895/5e3949f0-2482-46d7-92c1-9bc6e49dd2cd)
As a result you will get a new Home Page:
![image](https://github.com/thingsboard/thingsboard/assets/115699895/4971f528-7211-46c0-87d9-3f4698e9eefc)

**Comment by securitylamb** [comment]
thanks you for such a quick  clear answer i have one further question can
we create report using rule chain of the incoming telemetry data and show
that on the dashboard

**Comment by mykhailokornieiev** [comment]
The best practice is to create separate tickets for different questions since this question is not related to the previous one. In the future, this will help other members of the community if they have a similar question, and also if someone from the community goes through the tickets, they will be able to help if they see a title with a familiar problem)
Unfortunately, I don't fully understand what you actually want.
1) If you want to generate a report through the rule chain, then as a reference you can use the default Generate Report rule chain and connect it to your rule chain
![image](https://github.com/thingsboard/thingsboard/assets/95425961/ce49e703-489a-4790-8c36-4fc46ef44425)
2) You can open the result of the report through the Files widget
https://thingsboard.io/docs/pe/user-guide/file-storage/
3) Or, if you want to first process some data (aggregate telemetry, for example), then first a rule chain is made that aggregates this data, this data is saved through the save timeseries node, then a dashboard is created in which the datasource entity is selected, in which the aggregated data is stored. And then use Scheduler -> Generate Report
https://thingsboard.io/docs/pe/user-guide/reporting/

**Comment by securitylamb** [comment]
> The best practice is to create separate tickets for different questions since this question is not related to the previous one. In the future, this will help other members of the community if they have a similar question, and also if someone from the community goes through the tickets, they will be able to help if they see a title with a familiar problem) Unfortunately, I don't fully understand what you actually want.
> 
> 1. If you want to generate a report through the rule chain, then as a reference you can use the default Generate Report rule chain and connect it to your rule chain
>    ![image](https://user-images.githubusercontent.com/95425961/256521873-ce49e703-489a-4790-8c36-4fc46ef44425.png)
> 2. You can open the result of the report through the Files widget
>    https://thingsboard.io/docs/pe/user-guide/file-storage/
> 3. Or, if you want to first process some data (aggregate telemetry, for example), then first a rule chain is made that aggregates this data, this data is saved through the save timeseries node, then a dashboard is created in which the datasource entity is selected, in which the aggregated data is stored. And then use Scheduler -> Generate Report
>    https://thingsboard.io/docs/pe/user-guide/reporting/

so i wanted to create a report of incoming telemetry data and than share it using mail but i think we cant save our telemetry data using generate report rule chain

**Comment by mykhailokornieiev** [comment]
For the behavior you want, you need:
1. It is better not to touch the Generate Report rule chain at all, since this rule chain receives settings directly from the scheduler and then generates and sends the report. If you put some other rule chain in front of it, it will not receive the necessary data for sending and generating the report.
2. If you just want to make a report of the received data, a Save Timeseries node has already been created in the default Root Rule Chain, which automatically saves all the telemetry data received in Thingsboard in the desired entity.
3. Make a dashboard on which this telemetry will be displayed and make a Scheduler Report that will make a report of this dashboard.
All this is described in the documentation that I attached above.
