### ISSUE TITLE
[Question] How to modify self.ctx.settings programmatically  ?

### ISSUE THREAD

**Issue by jource08** [thingsboard/thingsboard#8792]
**Context**: 
Building a custom widget, and will need to re-write ```self.ctx.settings``` variable programmatically.

**Background**:
I'm creating a custom chartJS bar chart with the latest chartJS library (v4).
I added a "Sort By" option on UI so user can sort the data for better experience.
![image](https://github.com/thingsboard/thingsboard/assets/43811204/6a7eb863-9917-4062-b05b-dc953a67ce28)

Reason why i add the Sort option on UI instead of JSON settings schema, because i need to update the select options dynamically based on ```dataKeys``` list.

So right now whenever the user changed the sort option, then refresh the dashboard, the selected option not saved.
I tried to utilize ```self.ctx.settings.sortBy``` by explicitly writing the value on it, but not working.
Base on my understanding so far, the ```self.ctx.settings``` variable can only modified when user accessing the widget advanced settings.

**Question**:
 1. Is it possible to update/re-write custom widget JSON schema programmatically ? If not, any alternatives?
 2. Is it possible to update/re-write self.ctx.settings programmatically ? If not, any alternatives?

**Comment by devaskim** [comment]
I don't think that overriding widget's settings programmatically will solve your case, because such settings isn't user-specific.
Try to use either localStorage/sessionStorage to per browser settings persistence, or maybe create for each user JSON server attribute called, for example, `customWidgetsSettings` which each widgets will load and update dynamically.

**Comment by jource08** [comment]
Nice idea. Thank you!
