### ISSUE TITLE
[Bug] /api/user/devices misses deviceProfileId and deviceData

### ISSUE THREAD

**Issue by albtrentadue** [thingsboard/thingsboard#8844]
When querying `/api/user/devices` API as user with Authority: CUSTOMER_USER fields deviceProfileId and deviceData are null.
There is no reason why they are null and seems a failure in getting these data.
In fact if I use the `/api/customer/{customerId}/devices` with same user and same Authority, these fields are populated normally, so there is no permission issue: the first API misses these fields and the developer is forced to issue another query.

**Server Environment**
* own setup
  * local infrastructure 
  * ThingsBoard Version 3.4.4
  * OS Name and Version Ubuntu 22.04.1 LTS

**To Reproduce**
Go to swagger-ui interface of Thingsboard, login ad a Customer Admin and use the `/api/user/devices`.
See that fields deviceProfileId and deviceData are null

**Expected behavior**
deviceProfileId and deviceData populated as in `/api/customer/{customerId}/devices`

**Screenshots**
see the attached
![API1](https://github.com/thingsboard/thingsboard/assets/1144682/cd99f1de-1180-4cf4-a3f5-7f620374dc7b)
![API2](https://github.com/thingsboard/thingsboard/assets/1144682/991b8e70-a125-4682-b6a7-af208edcf290)
![API3](https://github.com/thingsboard/thingsboard/assets/1144682/7898e24b-2148-4d3e-aced-6f0f2816662d)
![API4](https://github.com/thingsboard/thingsboard/assets/1144682/916a867f-5024-4a92-a0d1-2849cfcc1634)

**Comment by trikimiki** [comment]
I think this was done by design. This query is used only to return some "general" info.
There is another similar query that returns more info, including `deviceProfileId` and `deviceData` - try `/api/deviceInfos/all`:
![image](https://github.com/thingsboard/thingsboard/assets/41070061/d95dc467-4b61-4f4b-8998-63e3153fcbef)
![image](https://github.com/thingsboard/thingsboard/assets/41070061/90d67817-47d2-46e0-817f-13571e987bb1)
![image](https://github.com/thingsboard/thingsboard/assets/41070061/40bedf22-da0d-43e3-bb71-9cd795c3a9d0)
As with `/api/user/devices`, you can only specify the page size, so I suppose this should work with your scripts/APIs.

**Comment by albtrentadue** [comment]
Hi Mykhailo
Thank you for answer.
Could be redundant but, may you please confirm that `/api/deviceInfos/all` will anyway limit the resulting devices according to the visibility set by the authenticated user issuing the API request?

**Comment by trikimiki** [comment]
Hello Alberto,

Correct. This API call will only show devices that are owned by the current user.
Note that, if you are using Professional Edition with entity groups feature, devices from shared device groups are not displayed when using this API call.

**Comment by albtrentadue** [comment]
Clear, thanks.
