### ISSUE TITLE
[Question] How does LwM2M Device bootstrap supposed to work?

### ISSUE THREAD

**Issue by ramadhanafif** [thingsboard/thingsboard#8909]
**Component**
 * UI
 * Generic

**Description**
1. I have set up a _device entity_ with lwm2m _device profile_ that contains lwm2m bootstrap configuration.
I want to use the said _device entity_ act as both **bootstrap point and lwm2m server point.** What I mean is that any lwm2m client that tries to connects to thingsboard with matching endpoint name will go the _device profile_ for bootstrapping, and then receive a bootstrap data containing secret keys to connect to the said _device profile_. However, this method means that bootstrap key and lwm2m key are the same, which missed the point of bootstrapping.

Please check the image below for how I configure the key in bootstrap server and lwm2m server.
![image](https://github.com/thingsboard/thingsboard/assets/31378187/9cf6c26e-3a17-44e4-929a-2995b6ce7374)
![image](https://github.com/thingsboard/thingsboard/assets/31378187/129ca51d-a43e-43fc-bbf5-878b456b9138)

2. So, how does LwM2M bootstrapping intended to be used in Thingsboard?

**Environment**

 * OS:  Windows with WSL2 Docker
 * ThingsBoard: docker thingsboard/tb-postgres version 3.3 
 * Browser: Firefox 115.0

**Comment by cc-zelp** [comment]
It looks like this is still the case with ThingsBoard. 

I am unable to set, via the UI, different PSK for Bootstrap and LWM2M servers. The CoAP comms is sending the different LWM2M PSK to the device, but then the ThingsBoard server itself fails the authentication.

If Client Security Config and LWM2M Server + Bootstrap Server PSK are exactly the same (as per image above), then bootstrap works. And not otherwise.

What do you recommend in this case? As OP says, this nullifies the use of Bootstrap ...
