### ISSUE TITLE
Trendz Card widget

### ISSUE THREAD

**Issue by Juka-22** [thingsboard/thingsboard#8958]
Component:
-Trendz + Thingsboard Cloud
Environment:
-OS: Win 10 64-bit
-Browser: Firefox

Hello there...

Found this issue on a trendz widget card.

widget trendz card: 
![imagem](https://github.com/thingsboard/thingsboard/assets/79198755/7bdc30a1-6d0e-43f2-8ec4-d5ff002f5c48)
![imagem](https://github.com/thingsboard/thingsboard/assets/79198755/23537ef3-3b62-4e7f-a0b4-31a58e2fb59e)
![imagem](https://github.com/thingsboard/thingsboard/assets/79198755/13cf696d-925c-4e67-abb5-f50eac453111)

when i click on icon, this is what appears:
![imagem](https://github.com/thingsboard/thingsboard/assets/79198755/68cdd406-2ffe-4660-8ddc-d729d39d7b35)

I don't know if it's a bug or not... but how can i remove it?
![imagem](https://github.com/thingsboard/thingsboard/assets/79198755/c2457f13-bc1f-4d56-9edc-ba156871426f)

tks

**Comment by oleksandr-kupenko** [comment]
Hello Juka-22,

Thank you for bringing this to our attention. The button was added by mistake and will be removed in the next update.

At the moment, to solve the issue, we recommend not using the "Trendz Builder" bundle for creating widgets. Instead, I suggest using the "Trendz View Static" bundle. It's easy to switch – simply create a new widget and choose "Trendz View Static" instead of "Trendz Builder." The other settings will remain similar.

![image](https://github.com/thingsboard/thingsboard/assets/53411825/f53eb3a5-682b-470e-a672-4e8446ac8af5)

**Creation alternative**
Additionally, you can easily access this visualization in Trendz by clicking on the Share button located at the top right corner, then selecting "Add on dashboard" and choosing the desired dashboard.

![image](https://github.com/thingsboard/thingsboard/assets/53411825/c60bc663-a3e7-4ff3-b67c-ebaae5d20efa)
This approach also uses this more modern bundle.

This changes will result in a faster widget with the ability to quickly switch to Trendz and other technical advantages. And, of course, without any unnecessary buttons.

**Comment by Juka-22** [comment]
Hello... it's working... tks...
