### ISSUE TITLE
[Question] Generate Reports/Dashboards with targeted size

### ISSUE THREAD

**Issue by gnosticChemist** [thingsboard/thingsboard#9008]
**Component**

 * UI

**Description**
I'm trying to generate reports and lock them to A4 sheets proportion, so it can be printed without problems.
However, I can't find where to configure it, and neither found materials related to the topic. Any tips of how to approach this?

**Environment**
 * ThingsBoard: Profissional Edition v3.5.1

**Comment by elpollo12** [comment]
One way I can think is using css in the advanced settings of the dashboard. There is a box where you can add custom css and there modify the width and height

**Comment by gnosticChemist** [comment]
> One way I can think is using css in the advanced settings of the dashboard. There is a box where you can add custom css and there modify the width and height.
> 
> There is an element called tb-dashboard-page which I think is the one you should point to to change the size.

I tried multiple element, but even when the dashboard-page is on the right size the report is generated on the default dimensions (508 × 297 mm), leaving a bla

nk space on the remainder.

Here's an example: 
[report-2023-08-02_18_30_08.pdf](https://github.com/thingsboard/thingsboard/files/12245001/report-2023-08-02_18_30_08.pdf)

**Comment by DavidHartnell** [comment]
Have you had any more success with this?

**Comment by netbc** [comment]
Thingsboard does not handle pdf formatting and pagination, it just prints the screenshot of the dashboard to the pdf. We had to develop a custom Markdown/HTML Card widget using jspdf and html2canvas libraries.
https://www.npmjs.com/package/jspdf
https://www.npmjs.com/package/html2canvas

**Comment by epalchenko** [comment]
Hello @gnosticChemist,
Web Report is a headless browser that essentially takes a print screen of the browser page. The resolution of that browser is standard 1920px by 1080px.
You can open your dashboard in this way: <your_host>/dashboard/<dashboard_id> and see exactly how the web report sees the dashboard before exporting.

**Comment by rpcai** [comment]
Can this issue be re-opened? 

Feedback from our customers is that
- The reporting feature is unsuitable/not production ready. 
- There is an expectation that PDF reports should be a standard size, and that pagination should occur cleanly 

@netbc  - would you be able to share more details on your jspdf and html2canvas solution - I'm looking for a tempoary work aroundm to keep a customer happy.

**Comment by rem-electric** [comment]
I would also like to see this re-opened. It would be great to be able to use the report feature to generate customer invoices that are printer friendly.

**Comment by amber-aw** [comment]
Just getting to grips with the Reporting feature and came across this question when trying to solve my issue. I want to include a dashboard in my report that only shows a single chart. Unfortunately, the report always includes all the blank space around the chart too, so that my chart and the area around it take up almost half of my A4 page. Looking at a previous comment:
"Thingsboard does not handle pdf formatting and pagination, it just prints the screenshot of the dashboard to the pdf. We had to develop a custom Markdown/HTML Card widget using jspdf and html2canvas libraries."

I wonder if a post-process step could be added after the image is generated that allows cropping or scaling before it is added to the report?
