### ISSUE TITLE
Run dashboard over https by default

### ISSUE THREAD

**Issue by chrowe** [thingsboard/thingsboard#91]
I am running the AWS image and even after enabling https in the security group the web admin UI is not accepting traffic over https. This is becoming the default for all website and is especially important since emails/password forms are being filled out.

**Comment by ashvayka** [comment]
@chrowe We are not able to setup HTTPS on AWS image, since we need valid SSL certificate. If we will include this certificate to the AMI - it will be compromised, since AMI is publicly available. Only you, as a system administrator is able to setup HTTPS on your server. 

See [configuration guide](https://thingsboard.io/docs/user-guide/install/config/) for more details. You can specify HTTPS properties in the main configuration file.

**Comment by chrowe** [comment]
Thanks for the link to the configuration guide. Didn't find that since it didn't mentions https or ssl in the text.

I still think you should setup https by default though, just without a certificate. Even without the cert it still encrypts the data.
