### ISSUE TITLE
[Question] How can I change/remove the device name at the top of a dashboard?

### ISSUE THREAD

**Issue by jabr0ni** [thingsboard/thingsboard#9241]
**Component**

 * UI

**Description**
How can you remove/change the device name that appears between the Alias and Time window icon? Eg. with DEVICE_A:
![image](https://github.com/thingsboard/thingsboard/assets/50448490/cc032771-2313-426c-b39f-4c38b0b84c4b)

**Environment**

 * ThingsBoard: 3.5.1

**Comment by devaskim** [comment]
There is dashboard setting called _Display entities selection_

**Comment by jabr0ni** [comment]
This toggles it on and off.  Is there a way to modify what is shown there? What if I want to change it to display another device from my alias list?

**Comment by ssakharova** [comment]
Hello @jabr0ni,

This functionality has changed since version 3.5.1 and is partially unavailable. While you can still display the device used in an alias, the option to change it to display another device has been removed.

Our developers decided to streamline the user interface and remove features that were rarely used in older versions. As a result, the ability to select entities from aliases in the toolbar will no longer be available in future versions. Additionally, the 'Display entity selection' checkbox will also be removed from the dashboard settings in future versions.


Best regards,
Sofiia
