### ISSUE TITLE
[Question] Zoom to marker on click

### ISSUE THREAD

**Issue by jortega11** [thingsboard/thingsboard#9352]
**Component**

 * UI
 * Generic

**Description**
I have a map with some markers, two of them are very close to each other so I can join them as a group, but the rest are located further away from one another. I have been trying to achieve the functionality that groups of markers have when clicking on that group. I wanted to zoom to one of my markers when I click on them. How could I get this working?

**Environment**

 * OS:  W10
 * ThingsBoard: 3.6.0

**Comment by basor-dali** [comment]
Not sure if this issue is still relevant or not, but i would try using a custom action on map widget ("On marker click") and then add this logic to it.

`let currentInstance = widgetContext.mapInstance;
let selected = currentInstance.markersData.filter((sel) =>{
        return sel.entityName === entityName;
    })[0];

if (currentInstance.markers.size>0) {
    var bounds = currentInstance.bounds;

    bounds._northEast.lat=bounds._southWest.lat=selected.latitude;
    bounds._northEast.lng=bounds._southWest.lng=selected.longitude;

    currentInstance.fitBounds(bounds);
    currentInstance.map.panTo(bounds.getCenter());
}
`

Try it out and i hope that helps.

**Comment by jortega11** [comment]
It was still relevant because I could not find a solution for that, now **it is working perfectly fine**.

Thank you very much!
