### ISSUE TITLE
kafka plugin body template don't work

### ISSUE THREAD

**Issue by soupim** [thingsboard/thingsboard#95]
I used the kafka plugin to intergrate thingsboard and my app. The kafka plugin worked fine, but occasionally it delivered the wrong value. It is a problem that the body template is published as it is.
When I set the body template to {"humidity-1": $humidity-1.valueAsString}, it is usually passed as '{"humidity-1": 33}'. However, sometimes it is passed as' {"humidity-1 ": $humidity-1.valueAsString}'.

Is there a plan to fix this or is there a way to avoid it?

**Comment by setevik00** [comment]
Try to remove dash from the variable name, e.g. rename humidity-1 to humidity1 .

**Comment by soupim** [comment]
It's same result. I got result as { "humidity1":$humidity1.valueAsString}.

**Comment by setevik00** [comment]
Strange that it happens just from time to time. Here is my Kafka plugin template:
{"geoZone" : "TEMP-001", "windSpeed" : "$temperature.valueAsString"}
The only difference with your case is that I have  "$temperature.valueAsString" in double quotation marks. Hopefully that helps!

**Comment by ashvayka** [comment]
@soupim Is it possible that sometimes you are sending message from device that does not have humidity, and in this case we don't know how to map the value to the expression?

**Comment by soupim** [comment]
@ashvayka @setevik00 Thank you! I found my problem. My device sends temperature as well as humidity. Two values ​​are sent in each message. When sending temperature, the humidity value is not included. The device send humidity once every 3 seconds and temperature once every minute. This seems to have caused problems. How do I set a rule to check if telemetry contains humidity?

**Comment by setevik00** [comment]
I think you have to create two rules. First rule will check that both temperature and humidity are present and send them out via kafka plugin. Second rule will check that only temperature is present.
First rule:
typeof temperature != 'undefined' && typeof humidity != 'undefined'

Second rule
typeof temperature != 'undefined' && typeof humidity == 'undefined'

I'm not sure, but think that in second rule you have to check specifically that humidity is undefined, otherwise you will have duplicated data as both rules will apply for the same telemetry data.

**Comment by soupim** [comment]
@setevik00 Thank you!
