### ISSUE TITLE
Thingsboard's mobile flutter app doesn't work on android less than 12

### ISSUE THREAD

**Issue by ezeroldan24** [thingsboard/thingsboard#9554]
Good afternoon, it happens to me that on phones that have version Android less than 12, they do not load the widgets since version 3.6 of thingsboard.cloud. Does anyone know why this failure can happen? I have the same code as the official repository, and it still doesn't work.  Thanks a lot.

**Comment by ssakharova** [comment]
Hello @ezeroldan24,

As the community has not provided assistance on this matter over an extended period, I am closing this ticket due to inactivity.
Please re-create a new ticket in GitHub with respect to the product you are using:

- https://github.com/thingsboard/flutter_thingsboard_app/issues
- https://github.com/thingsboard/flutter_thingsboard_pe_app/issues

Please describe all the details of your case there, and then you will increase the probability that the GitHub community will be able to help you.
