### ISSUE TITLE
Thingsboard PE Cloud-Usage warning

### ISSUE THREAD

**Issue by mubashirp** [thingsboard/thingsboard#9578]
I am using a thingsboard PE Cloud subscription. In the API usage statistics, Javascript executions is almost full and showing a warning. I only have few dashboards and devices, also 2 rule chains in my subsciption. I have been using the subscription for an year, and this is the first time it is showing such a warning. I am not sure that which entity in my subscription is consuming these Javascript execution limits.Is there any method to find it, or other ways to resolve this issue. I want to resolve this before the limit is exceeded.
![image](https://github.com/thingsboard/thingsboard/assets/49026279/f59692fa-e406-43df-a2ac-1ebe961a3629)
![image](https://github.com/thingsboard/thingsboard/assets/49026279/f61ae3d0-8524-4255-aa61-ecc3bc4e5726)
@ashvayka @ashaforost @devaskim

**Comment by devaskim** [comment]
@mubashirp I am not a TB support, so don't ping me, please.

**Comment by mykhailokornieiev** [comment]
Hi @mubashirp. Please check your rule chains and integrations. If there are some script nodes (transformation or filter), generator script nodes or data converters that use JavaScript, then you will need to rebuild their logic so that it will make fewer executions.
Or, you can migrate your scripts from JavaScript to TBEL, so it will not use JavaScript executions at all
https://thingsboard.io/docs/pe/user-guide/tbel/
