### ISSUE TITLE
Alarm widget cannot show alarms of multiple devices 

### ISSUE THREAD

**Issue by civottam** [thingsboard/thingsboard#979]
Hi there,

Even I configured `entity alias` with multiple devices and use this alias in `Alarm widget`, the widget can only show one device's alarm, would you please kindly get it resolved? Thank you.

**Comment by enviroeye** [comment]
@aderbas, how did you managed to figure out you needed to create an asset 'container' for all the devices in order to see all the associated alarms. I've spent days trying to figure out why the alarm widget would only show one device's alarms when there were more than a dozen devices with active alarms.....

**Comment by clydebarrow** [comment]
I have the same problem - I am unable to get alarms for multiple devices in a table. I have tried all kinds of filters in the entity alias to no avail.

**Comment by ashvayka** [comment]
Hi @clydebarrow , @enviroeye and @civottam . Unfortunately, the current API can't allow fetching alarms from multiple devices simultaneously. We are going to evaluate how to fix this but it may introduce performance penalties. So, the only way is to use 'container' asset (CE or PE) or entity group (PE only).

**Comment by jodihonan** [comment]
I am trying to add Alarm Widgets for multiple devices based on the suggestion from @aderbas but when I apply the Entity, I get the following error:
java.lang.NullPointerException

Any assistance would be greatly appreciated

![image](https://user-images.githubusercontent.com/56988837/67542056-86955280-f72e-11e9-9961-ef4bdfec7a78.png)

**Comment by elFabo01** [comment]
I have tried using a container asset. Both, importing the assets devices via query nor as a dashboard state worked for me. I am using 21 Devices from which about 4 have alarms. I only see one device and its alarm in the widget.
Has there been any new way of doing it as of lately @ashvayka ?

**Comment by tsagadar** [comment]
I also failed to get the alerts widget to work with multiple devices - something that seems to me a very common use case. I spent hours trying out things (including proposal above) but it just does not seem to work using ThingsBoard community edition 2.4.2.1. Any help would be very appreciated.

**Comment by ltancerel** [comment]
I have same problem on thingsboard PE.
I use an alias on a group of device to display alarms for all of them but none is displayed. When using the same alias on chart display it works well.
Is there any short term plan to solve this issue ?

**Comment by Shedaim** [comment]
This does not work using entity groups. Still need to create a different device/asset related to the real ones. 
Problem with this way is that if I want to add an action on the alarm widget, that moves you to another dashboard (for extensive details for example) you cannot get the real device.

**Comment by amardhore** [comment]
I followed @aderbas instructions above and it works from me. I created an asset and made relate all devices to the asset. Checked "propagate" flag in alarm processor and I see alarms for all the devices
 --Amar

**Comment by danielarico** [comment]
@amardhore Could you explain to me how did you relate all the devices to the asset? Thanks.

**Comment by amardhore** [comment]
@danielarico create an Asset, open it and then go to the relation tab. Add existing devices to the Asset.

**Comment by adf0001** [comment]
I created an asset and the relations, it didn't work at first. But after some kind of cache cleaning, maybe at browser side, it works. A single asset entity without  dashboard state works too.

**Comment by ecmap** [comment]
Entity group list > Type:Device > Device type :)?

**Comment by RondoRonaldo** [comment]
For now, when you assign a group of devices to an alarm widget, only one of them will be processed, and the "Resolve as multiple entities" button won't work too.
So If you want to show alarms from several entities, this can be circumvented by creating an auxiliary entity (asset for the example) that will have relations to all the entities(devices for the example) with alarms and setting “propagate alarms” in the “create alarm” node to true. This way all the alarms being generated afters will be available on the asset.
Here is an example of two devices connected to an asset so you may refer to the screenshots below.
The “Create alarm“ node transforms the telemetry object into the string to be visualized easily on the dashboard “Alarm widget” and set “alarm type” to the device name, so that it won’t create a new alarm object but update the one with the same alarm type.

![image](https://user-images.githubusercontent.com/43723966/84673788-d7aebc80-af32-11ea-9333-5102a60a0b36.png)
![image](https://user-images.githubusercontent.com/43723966/84673820-dc737080-af32-11ea-9fcf-ca542293dfc8.png)
![image](https://user-images.githubusercontent.com/43723966/84673857-e39a7e80-af32-11ea-8188-32fb4d78cf15.png)
![image](https://user-images.githubusercontent.com/43723966/84673885-ed23e680-af32-11ea-81e8-f0be7f15a0e1.png)

**Comment by vortexalex** [comment]
it happens to me too. is this behavior fixed / improved in subsequent versions?
