### ISSUE TITLE
[Question] Thingsboard-PE : tenant administrator creating a tenant administrator  

### ISSUE THREAD

**Issue by shashank-r25** [thingsboard/thingsboard#9792]
Hi, 

I am working on ThingsBoard-PE Functionalities. Log in as Tenant, In Users Section - We can create Tenant Administrator and Tenant User. 
This feature lets Tenant to create another Tenant, giving him all the access to edit.

What is the use case behind this feature, How is this helpful in PE which stands out more than CE?

Thank you for guiding me through this question.

**Comment by mykhailokornieiev** [comment]
Hi. In this case, you create only another user under the same tenant, not a brand new tenant hierarchy, because it's available only on the sysadmin level. So, you can have a few tenant administrators in one tenant hierarchy. But by the fact they will work with the same entities. Also, you can set up different permissions (read, write) for each user according to their user group (tenant administrator, tenant user, or some custom one)
You can get familiar with the following documentation
https://thingsboard.io/docs/pe/user-guide/rbac/
![image](https://github.com/thingsboard/thingsboard/assets/115699895/8a95bb25-70c5-429f-86e1-afd777b7565b)
