### ISSUE TITLE
Thingsboard eks getting started help after installation!!

### ISSUE THREAD

**Issue by Rishi-NF** [thingsboard/thingsboard#9862]
**Component**

 * UI
 * Installation

**Description**
I followed all the instructions to deploy thingsboard via eks and now im following the instructions for the get started guide, i have made a test device and during the checking connectivity part, when i run the commands given on my local machine's terminal im always getting timed out, i initially thought it was because the security groups attached did not allow my ip on port 8080, i have attached the screenshots below. 

![image](https://github.com/thingsboard/thingsboard/assets/124362385/f4c7a9f1-b697-409e-b36b-00443473002d)
<img width="508" alt="Screenshot 2023-12-18 at 14 06 39" src="https://github.com/thingsboard/thingsboard/assets/124362385/6cf485b0-91f5-4551-a5d1-df5ecd2bc684">
<img width="902" alt="Screenshot 2023-12-18 at 14 10 36" src="https://github.com/thingsboard/thingsboard/assets/124362385/28a910e0-cc98-4edd-abcb-b885111cde05">

Is there a better clear cut guide for getting started that is inline with the eks deployment or can i get some details on how to fix this or best person i can talk to. 

**Environment**

 * OS:  EKS Deployment
 * ThingsBoard: Latest Version
 * Browser: Chrome

**Comment by trikimiki** [comment]
Hello!

You have deployed a load-balancer that exposes port 80 and then forwards traffic to TB port 8080. ThingsBoard does not see this load-balancer, here is why it suggests using port 8080.

Change port to 80 in your cURL command and it should work. In order to ThingsBoard to display a proper port, change Base URL and/or Connectivity endpoints/ports under Sys Admin user.
