### ISSUE TITLE
hsql to cassandra database migration issue

### ISSUE THREAD

**Issue by gopirathnamt** [thingsboard/thingsboard#989]
Moved data from ts_kv table of hsql to cassandra(ts_kc_cf) , but i checked the data on card widget on dashboard . But i cant find the data , which i migrated from hsql to cassandra .
Can u help me to solve the issue ?

**Comment by vparomskiy** [comment]
it is not enough just to move this table, you need to write migration script that will migrate all tables from the HSQLDB

**Comment by gopirathnamt** [comment]
thanks bro , i solved the issue

**Comment by mfalkvidd** [comment]
@gopirathnamt would it be possible for you to share how you performed the migration? I'd like to migrate my data from hsqldb to cassandra.

**Comment by gopirathnamt** [comment]
yes first i used a hsql db connected in java and retrive the data from database and stored in txt file .
Then i installed thingsboard with cassandra database
 then i create all the tenants manual on thingsboard .
 because we cant migrate the tenant data directly . i had issue , if i directly copy the tenant from backup hsql tenant file .
So after i create tenant manually , i push the data of other tables .
Wait i created a files and i send u the zip of that .

**Comment by gopirathnamt** [comment]
But seriesly it is a big task and i tried very hard for that , because uuid values are stored in different forms in hsql and cassandra . so i converted hsql uuid values to cassandra uuid values and i replace the same uuid values on other table values .
Ex : 
Device uuid in Hsql : 1e816efe1dea5e0ac7e4364ed79718e
Device uuid in Cassandra : 482bfd20-c6db-11e8-bf11-795f5338a446

So we need to change that values to new forms . 
Dont worry , i tried this and successfully migrate the values for two times . 
So i am here to help u

**Comment by mujahed1987** [comment]
> But seriesly it is a big task and i tried very hard for that , because uuid values are stored in different forms in hsql and cassandra . so i converted hsql uuid values to cassandra uuid values and i replace the same uuid values on other table values .
> Ex :
> Device uuid in Hsql : 1e816efe1dea5e0ac7e4364ed79718e
> Device uuid in Cassandra : 482bfd20-c6db-11e8-bf11-795f5338a446
> 
> So we need to change that values to new forms .
> Dont worry , i tried this and successfully migrate the values for two times .
> So i am here to help u

Hey
it looks that you did a big work. could you please share steps you follow to do the migration. And how did you exported the data into text file and restored them back, also if you have any scripts files specially for the uuid format conversion.

**Comment by gopirathnamt** [comment]
yes i will tell you , Even i created the .sh file to automate the most of the work

**Comment by mujahed1987** [comment]
Thank yoy very much. 🙏
I'll be waiting

**Comment by AbCthings** [comment]
ThingsBoard uses different data structures depending on the underlying database, which is also reasonable since you can range from relational to non-relational db (PostgreSQL, Cassandra, ...).

Due to this fact, I believe the most efficient way to handle data migration in a stable manner is to perform the operations at an "higher level". This means that instead of performing the migration through SQL or CQL instructions, it is better to rely on higher level features of ThingsBoard: RESTful API and MQTT communication.

You can, for example, use the API to retrieve the desired data from the "source" database and send it through MQTT (or again using API) to the "target" db. This approach is db-independent, meaning that you can migrate from relational to non-relational (or viceversa) without even notice. Furthermore using this method it is hard to broke the db, since data storage it's handled directly from the ThingsBoard service itself.

In this repository I'm trying to make all this smooth and automatic using Python: https://github.com/AbCthings/thingsboard-data-migration
I developed this to manage our instances of ThingsBoard, hope it can help. Feel free to fork if you wish to improve it.

**Comment by CooL16** [comment]
It seems the issue has been resolved
