### ISSUE TITLE
[Question] Problem making and restoring the postgres database

### ISSUE THREAD

**Issue by nomanuser** [thingsboard/thingsboard#9922]
Hi,

i'm triying to make a backup of the postgres database (version 12) with the command: `pg_dump -h "$HOST" -c "$DATABASE" --exclude-table-data='public.audit_log' > pg-backup/thingsboard_backup.sql`

and i get a .sql but when i restore it with the command: `psql -e -U username -d databaseName -f  ./thingsboard_backup.sql`

i get the following errors:
- psql:thingsboard_backup.sql:27417138: error: invalid command \N
- ERROR:  relation "alarm" already exists
- ERROR:  constraint "tb_user_email_key" of relation "tb_user" does not exist
- ERROR:  index "rule_node_debug_event_1702933200000_tenant_id_entity_id_ts_idx" does not exist

this errors only are a few of the miles and miles i get while the restore is "making"

My question is if there's a correct form of make and restore the postgres database on a new installation of thingsboard (i tried with empty database and the default database after install thingsboard.)

Thanks!!

**Comment by devaskim** [comment]
Does error happen with full db backup and empty target database?

**Comment by ashvayka** [comment]
Greetings @nomanuser . The question you are asking is actually not related to ThingsBoard, but a purely PostgreSQL question. I am not able to detect the root cause of errors in your commands, but I am also sure the following commands work fine:

```
pg_dump -U postgres -h $HOST -W -Fc $DATABASE > tb-demo.dump
pg_restore -U postgres -h $HOST -W -Fc -d $DATABASE tb-demo.dump
```

Regards

**Comment by nomanuser** [comment]
> Does error happen with full db backup and empty target database?

I tried with the database empty and the default schema that creates thingsboard, can be problem of thingsboard version? Maybe it's not the same version.

**Comment by nomanuser** [comment]
> Does error happen with full db backup and empty target database?

I tried with the database empty and the default schema that creates thingsboard, can be problem of thingsboard version? Maybe it's not the same version.

**Comment by xalt7x** [comment]
@nomanuser 
I assume you are trying to restore a dump over an existing database. If this is the case, then such errors are expected, since the built-in PostgreSQL utilities do not automatically clean up or create databases during the restore.

Also I see that you have a custom pg_dump command with a "-c" (clean option). Description from the [documentation](https://www.postgresql.org/docs/current/app-pgdump.html):

> Output commands to DROP all the dumped database objects prior to outputting the commands for creating them. This option is useful when the restore is to overwrite an existing database. If any of the objects do not exist in the destination database, ignorable error messages will be reported during restore, unless --if-exists is also specified.

In practice, it adds to the output dump SQL fle "ALTER" and "DROP" commands that seem redundant for the empty Thingsboard database. When I try restoring from the dump generated with the command below, I have errors as well.

`pg_dump -h "$HOST" -c "$DATABASE" --exclude-table-data='public.audit_log' > pg-backup/thingsboard_backup.sql`
So I suggest rewriting it, removing the "-c" option:
`pg_dump -h "$HOST" --exclude-table-data='public.audit_log' "$DATABASE" > pg-backup/thingsboard_backup.sql`

And for restore try to follow these steps:

1. Make sure that Thingsboard is stopped
`sudo systemctl stop thingsboard ; systemctl status thingsboard`
2. Drop your current Thingsboard database
`psql -h YOUR_HOST -U postgres -W -c "drop database thingsboard;"`
3. Create an empty Thingsboard database
`psql -h YOUR_HOST -U postgres -W -c "create database thingsboard;"`
4. Restore your database with psql (as you have have plain-text sql format)
`psql -h YOUR_HOST -U postgres -W -d thingsboard  -f thingsboard_backup.sql`

**Comment by Ultrazombie** [comment]
We inform you that your GitHub ticket has been inactive for some time, and we will close it. If you have any more concerns or encounter similar issues, please don't hesitate to contact us.
