### ISSUE TITLE
[Question] Thingsboard on Raspberry Pi 5 - Raspbian Bookworm 64bit

### ISSUE THREAD

**Issue by Andre-Bandarra** [thingsboard/thingsboard#9967]
**Component**
 * Installation

**Description**
I'm trying to install and run Thingsboard on the latest R Pi 5 with the recomented Raspberry pi OS
I can't seem to force to install java 11 and have to go with the recomended java 17.
This might be causing some problems.
Also when installing postgresql got some errors and had to force 
`sudo apt install --only-upgrade libpq5`
Any help on how to get thingsboard to work on the newer pi5 would be greatly appreciated.
I've had it for a few years running on an old pi2 but it's always been too slow for it

**Environment**
 * OS: Raspberry Pi OS 64but based on Debian Bookworm
 * ThingsBoard: 3.6.2
 * Browser: chromium

**Comment by xalt7x** [comment]
> I can't seem to force to install java 11 and have to go with the recomended java 17.
> This might be causing some problems.

Current Thingsboard version requires Java 11

For Debian 12 "Bookworm" based distributions there are several way to install Java 11:

1. Adoptium binaries (Temurin). You can find installation instructions on the [Adoptium website](https://adoptium.net/installation/linux/). Just replace required "temurin" version in the installation command. Whenever possible, I recommend this method to avoid OS breakdowns and to get security updates for Java.
2. Packages built for the previous release (Debian 11 "Bullseye") work as well. Generally it's not recommended (and sometimes even dangerous) practice for Debian. So proceed with caution.
Few options here:
- download and install [openjdk-11-jdk packages](https://packages.debian.org/bullseye/openjdk-11-jdk). You'll need to install packages manually and in the correct order (`openjdk-11-jre-headless`, `openjdk-11-jre`, `openjdk-11-jdk-headless`, `openjdk-11-jdk`) using the "apt" command.
- add `debian-security/ bullseye-security main` repo to your /etc/apt/sources.list.

---

> Also when installing postgresql got some errors and had to force
> `sudo apt install --only-upgrade libpq5`

Without context of the error, it's hard to say. "postgresql-15" package from the [official PostgreSQL repo](https://wiki.postgresql.org/wiki/Apt) should work fine. 

---

P.S. [Docker images](https://thingsboard.io/docs/user-guide/install/docker/) might work as an alternative to native packages.

**Comment by Andre-Bandarra** [comment]
Thanks for the help and direction. Installing Java 11 via Adoptium worked and I have Thingsboard now working on the Pi5.
A different question that I can't seem to find the answer for (maybe I'm not searching for the right terms) is:
Is there a way to export my whole thingsboard "project" or instance that I have running on the old Pi2 and import it into the 5?
I know how to export/import the dashboard but, the users/curtomers, rules, assets, devices, dashboards, system settings, etc?

Many thanks

**Comment by xalt7x** [comment]
@Andre-Bandarra 

Happy to help! 

> Is there a way to export my whole thingsboard "project" or instance that I have running on the old Pi2 and import it into the 5?

Yes.

Assuming that you have a simple non-hybrid installation, both your old and new instances use the same Thingsboard version, and your new instance doesn't yet have an important data, you can just backup and restore your PostgreSQL database:
1. On the Old Host:  
- Backup your database  
`pg_dump -h $HOST -U postgres -W -Fc -Z1 thingsboard > thingsboard.dump`
2. On the New Host:
- Stop Thingsboard service
`sudo systemctl stop thingsboard`
- Just in case, run a backup command similar to the one in the first step
- Remove your current PostgreSQL Thingsboard database
` psql -h $HOST  -U postgres -W -c "drop database thingsboard;"`
 - Create an empty thingboard database
` psql -h $HOST  -U postgres -W -c "create database thingsboard;"`
- Restore backup from the old Host
`pg_restore -h $HOST -U postgres -W -d thingsboard thingsboard.dump`
- Launch Thingsboard
`sudo systemctl start thingsboard`

If anything goes wrong on the New Host, you can just stop Thingsboard service and restore dump the same way.

**Comment by Andre-Bandarra** [comment]
@xalt7x Thanks again for the help!

> Assuming that you have a simple non-hybrid installation, both your old and new instances use the same Thingsboard version, and your new instance doesn't yet have an important data, you can just backup and restore your PostgreSQL database:

It's a very simple installation, but upon checking `sudo systemctl status thingsboard` i found that the old one is running v3.3.2 and the new one is running the latest v3.6.2. In this case would it require for sure for them to be the same? I'm guessing it should be easier to downgrade the new one to v3.3.2 since it's empty?

> * Backup your database
>   `pg_dump -h $HOST -U postgres -W -Fc -Z1 thingsboard > thingsboard.dump`

I've tried this on both old and new and I get back: 
_pg_dump: error: too many command-line arguments (first is "thingsboard")
Try "pg_dump --help" for more information._

**Comment by xalt7x** [comment]
> >       Backup your database
> >       pg_dump -h $HOST -U postgres -W -Fc -Z1 thingsboard > thingsboard.dump
> 
> I've tried this on both old and new and I get back:
>_pg_dump: error: too many command-line arguments (first is "thingsboard")_
>_Try "pg_dump --help" for more information._

This command above works if user assigns appropriate value to the `HOST` variable (local / remote hostname or IP address, e.g., `HOST=127.0.0.1`). By default, the HOST variable is not set, and this confuses `pg_dump`.  I've edited my comment with hopefully better guide.

> edit: I've also checked postgres version just in case using sudo find /usr -wholename '*/bin/postgres' and it looks like the old is using v13 and the new one v16. That might be a bigger problem?

Thingsboard v3.3.2 had some fixes/improvements to support PostgreSQL 14 and 15 (e.g. [PR 8559](https://github.com/thingsboard/thingsboard/pull/8559) , [PR 8560](https://github.com/thingsboard/thingsboard/pull/8560), therefore, I would recommend sticking with PostgreSQL v13 for Thingsboard v3.3.2

> i found that the old one is running v3.3.2 and the new one is running the latest v3.6.2. In this case would it require for sure for them to be the same? I'm guessing it should be easier to downgrade the new one to v3.3.2 since it's empty?

Well, due to [significant SQL differences between releases](https://github.com/thingsboard/thingsboard/tree/hotfix/3.6.2/application/src/main/data/upgrade), database from an old version won't work properly (if at all) with a new version.

So for your new instance I see several options:
1. Remove the new version (including [custom config](https://thingsboard.io/docs/user-guide/install/how-to-change-config/); and current database); remove postgresql-15 and install postgresql-13 ;  install an [old Thingsboard version from archive](https://github.com/thingsboard/thingsboard/releases/tag/v3.3.2) ; configure it (change config, create database) and restore dump from an old instance
2. If possible. it's recommended to upgrade version on a new machine
- Check that database work properly on an old version
- Perform an [upgrade](https://thingsboard.io/docs/user-guide/install/upgrade-instructions/#upgrading-to-333). You'll need to upgrade versions one-by-one (3.3.2 > 3.3.3 > 3.3.4 > 3.3.4.1 etc.).
- Current Thingsboard version doesn't require recent PostgreSQL versions, so presumably you can continue using PostgreSQL v13 until it reaches [end of life](https://www.postgresql.org/support/versioning/).
