### ISSUE TITLE
[Question] Could not access ThingsBoard for some time, not clear if it was a port problem or another issue

### ISSUE THREAD

**Issue by jortega11** [thingsboard/thingsboard#9976]
**Component**

 * Generic

**Description**
Last time I checked ThingsBoard (yesterday afternoon) everything was working fine, but when I checked this morning I was not able to access the IP where I have my ThingsBoard instance. We hace not done anything related to configuration, installation... in this time so it was very strange to me that it had stopped working from yesterday night until this morning.

Here are the log files, both from [yesterday](https://github.com/thingsboard/thingsboard/files/13900039/thingsboard.2024-01-10.0.log)  (when it stopped working) and [today](https://github.com/thingsboard/thingsboard/files/13900060/thingsboard.log) (when it started working again).

While looking at the log files and reading some other issues I think this may be due to some port conflict, as in #1339 or #7939.

In order to address the problem:

1.  I tried was restarting the ThingsBoard service, which did not work.
2. Restarted the Virtual Machine where my ThingsBoard is located, which (I think) did not work because when I checked after restarting it was not working.
3. Then I was checking about this port issue and the only service that was using the ports that could be problematic was some Windows service (that problably had some kind of relation with ThingsBoard?) so I do not know if some port conflict could be causing the issue.
4. Then, after some time, everything started working again, but it is not clear to me why. Here is the log file [when it started working again](https://github.com/thingsboard/thingsboard/files/13900239/thingsboard.log).

The thing is that it is working right now, but I would like to know what caused the issue and how to address/prevent it if it happens again in the future.

Thanks!

**Environment**

 * OS:  W10 Pro
 * ThingsBoard: 3.6.1

**Comment by trikimiki** [comment]
Hi!
From your logs, your ThingsBoard was stopped first, and then after ~2 minutes it started again:
```
2024-01-10 17:45:06,336 [SpringApplicationShutdownHook] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
2024-01-10 17:47:11,072 [background-preinit] INFO  o.h.validator.internal.util.Version - HV000001: Hibernate Validator 6.0.20.Final
```
The shutdown was normal, it was not caused by some issue, but rather by a normal stop/shutdown operation. Check your Windows logs, perhaps there was a reboot.
Afterwards, indeed, MQTT transport failed to bind a port. By default, it is a TCP 1883, but it might differ if you changed configuration option `MQTT_BIND_PORT`.
If you face this issue again - you can scan for open 1883 port by another application. For example, like this: https://kb.vmware.com/s/article/1003971
Usually, it is some kind of MQTT broker/prober like Mosquitto - you can check your auto-start applications and services.

**Comment by jortega11** [comment]
Yes, I checked and I think the VM where it is hosted restarted and then that caused the problem. It did not happen again so I think we can already close the issue.
Thanks!
